### ISSUE TITLE
Libellé de l'info bulle des outils de sélection

### ISSUE THREAD

**Issue by sdhem** [georchestra/cadastrapp#1]
Voir spécifications §4.2.1
Pour le point : "Sélectionne / Active / Désélectionne une parcelle par un simple clic"
Pour la ligne : "Sélectionne / Active / Désélectionne une ou plusieurs parcelles par une ligne brisée"
Pour le polygone : "Sélectionne / Active / Désélectionne une ou plusieurs parcelles à l’intérieur d’un polygone"

**Comment by laurentcornic** [comment]
modifications des libellés à valider

**Comment by sdhem** [comment]
Vu correction sur plateforme de qualif et de dev => Bug Clos
