### ISSUE TITLE
Plan de situation avec plusieurs parcelles

### ISSUE THREAD

**Issue by pigma** [georchestra/cadastrapp#100]
Si deux parcelles sont sélectionnées l'édition du plan de situation ne fonctionne pas.

![selection_deux_parcelles](https://cloud.githubusercontent.com/assets/3725336/11244766/9c9884bc-8e0f-11e5-9218-44e5f1ad5827.png)

L'édition du plan fonctionne pour chaque parcelle sélectionnée individuellement.

**Comment by MaelREBOUX** [comment]
Ici ça fonctionne :
1. sélection de 4 parcelles
2. barre d'outil > avancées > traitement des sélections > Parcelles > édition bordereaux

J'ai obtenu un PDF avec 4 pages :D
Peut-être que la PF du CRAIG est moins à jour ?

Lier à #101

**Comment by pierrejego** [comment]
Il y avait une erreur pas de plan de situation, mais pour le bordereau parcellaire ça a été corrigé sur la pf de qualif, mais pas encore déployé sur la pf du CRAIG

**Comment by MaelREBOUX** [comment]
@pigma on ferme ce ticket ?
