### ISSUE TITLE
Edition Bordereau parcellaire

### ISSUE THREAD

**Issue by pigma** [georchestra/cadastrapp#101]
L'édition du bordereau parcellaire donne le même document que l'édition du plan de situation

**Comment by MaelREBOUX** [comment]
Alors j'ai vérifié : les plans de situations ne sont pas demandés au CCTP.
En effet, un plan de situation = une carte standard réalisée par Mapfishapp.

Cet item a été mis par Gfi depuis le tt début dans les devs. Sans doute héritage d'un autre projet.

@pierrejego supprimer toute référence dans le menu "Recherches avancées"

**Comment by pierrejego** [comment]
Suppression de l'entrée dans le menu lié au commit : GFI-Informatique/addons@2fa597983bec0dac997b5507450b86371d5ad928
