### ISSUE TITLE
Supprimer les "0" dans les numéros d'adresse de parcelle

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#103]
Même idée que #93 : ça nuit à la lecture des infos et ne devrait pas apparaître.

Je propose de traiter ça dans les vues.

**Comment by MaelREBOUX** [comment]
Je ne vois pas cette modif ce matin. Normal ?

**Comment by pierrejego** [comment]
Non ce n'est pas normal, c'est que je ne les ai pas enlevé la ou tu voulais :)
Je les ai enlever au début du dlign 4 et du ccovoi.

@MaelREBOUX est-ce que tu peux me faire une copie d'écran de la ou tu les as, pour que je les supprime dans le bon champ dans la vue ?

**Comment by MaelREBOUX** [comment]
Ce sont tous les endroits où on fait apparaître les n° d'adresses :
- fenêtre de sélection de parcelles
- fiche info parcelle
- bordereau parcellaire
- relevé de propriété

**Comment by pierrejego** [comment]
Modification effectuée, et suppression des espaces devant pour Qgis. Déployé Lundi matin 

commit https://github.com/GFI-Informatique/cadastrapp/commit/2d98ebf0fa6a3d981a22376255209d25b6c1f109#diff-3205c0ded576131ea255ad2bd38b0fb2

**Comment by landryb** [comment]
Dans un résultat de recherche j'ai toujours des 000 en début de champ pour 'Adresse Cadastrale' - si je regarde dans la DB le champ dnvoiri n'est pas passé par ltrim(), le commit 2d98ebf0fa6a3d981a22376255209d25b6c1f109 n'a fait que les vues arcopole.

**Comment by pierrejego** [comment]
Oui j'avais enlever les 0 sur Arcopole et les espace sur Qgis.
Je fais le tour des champs Qgis pour enlever les 0 en début aussi

**Comment by pierrejego** [comment]
Je viens de faire les modifications, suppressions des 0 au début des champs dnvoiri et dlign4
