### ISSUE TITLE
infobulle persistante

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#105]
Quand on passe d'une parcelle A à une parcelle B, l'infobulle A devrait disparaître et la B apparaître.

![screenshot043](https://cloud.githubusercontent.com/assets/6370443/11246855/cf68b4b6-8e19-11e5-923a-6a40a2fd6859.png)

**Comment by pierrejego** [comment]
@MaelREBOUX pourrais tu vérifier le nouveau comportement et me dire si c'est bon. Merci

**Comment by MaelREBOUX** [comment]
vu : OK

**Comment by landryb** [comment]
Testé ici aussi, OK
