### ISSUE TITLE
infobulle : délai de déclenchement à raccourcir

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#106]
Je crois que le temps de latence avant envoi de la requête pour obtenir l'infobulle est de 5 s. C'est trop long : abaisser à 3 s.

**Comment by pierrejego** [comment]
Le temps est à configurer dans le GEOR_custom.js. Ce n'est pas dans le code de l'application mais dans la configuration de déploiement.

Je change le temps sur la pf de qualif, et je met à jour la doc de la conf par défaut.

**Comment by MaelREBOUX** [comment]
C'est bien mieux.

Par contre : je n'arrive plus à épingler l'infobulle.
Moi ça ne me dérange pas du tout : pas fait pour ça.
