### ISSUE TITLE
[UI] Fenêtre de sélection de parcelles : améliorer le tri

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#107]
J'ai une sélection de 12 parcelles et je voulais trier par n° de parcelles

![screenshot049](https://cloud.githubusercontent.com/assets/6370443/11268008/ecfab228-8eae-11e5-8b1c-ac6cf4f5d578.png)

Ca a fonctionné il me semble.

Dans la console FireBug :

TypeError: this.fields is undefined
ext-all.js (ligne 21, col. 320734)

**Comment by pierrejego** [comment]
Le tri fonctionne sur les autres tableaux. Ce tableau n'est pas créé de la même façon le store par defaut est celui avec le message 'Aucun résultat', puis l'utilisation d'un store JSON.

**Comment by MaelREBOUX** [comment]
Ca trie mieux on dirait mais comme ça trie sur l'ensemble de l'adresse littérale, le tri est texte, donc 10 remonte avant 1.

**Comment by MaelREBOUX** [comment]
Testé hier sur master.

Tri sur numéro plan inopérant
Tri sur contenance inopérant

**Comment by stous** [comment]
le tri fonctionne sur Contenance  et N° de plan (v1.6) mais pour N° de plan c'est un tri alpha et non pas un tri numérique
