### ISSUE TITLE
Gestion des demandes : export tables

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#108]
@pierrejego 

Tu pourrais me fournir un export CSV des tables qui gèrent les demandes d'info foncières ?

Merci d'avance.

**Comment by pierrejego** [comment]
Les tables sont purgées tous les jours sur la machine de qualif. Qu'est-ce que tu souhaites avoir comme information ?

**Comment by MaelREBOUX** [comment]
je voulais voir si les données en table étaient cohérentes avec mes saisies.
Pas grave : je fais confiance je checkerai qd ce sera déployé chez nous.
