### ISSUE TITLE
HTTP 500 sur recherche de propriétaire par nom

### ISSUE THREAD

**Issue by sdhem** [georchestra/cadastrapp#11]
La fenêtre de résultat de propriétaire ne s'affiche pas. Une erreur HTTP 500.

**Comment by laurentcornic** [comment]
Testé sur Arcopole: Affichage de la fenêtre de résultat de recherche de parcelle
Sur QGIS: erreur HTTP 500 observée

**Comment by pierrejego** [comment]
Test effectué sur les deux plateforme, Qgis et arcopole, plus d'erreur 500.
Je ferme cette anomalie, mais si vous la reproduisez merci de mettre la commune et le nom de la personne dont la parcelle est recherchée
