### ISSUE TITLE
methode getFic + compte SV_USER simple : aucune info

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#112]
J'ai un utilisateur qui a les groupes suivants :  SV_USER  EL_COM_VERN
C'est donc, chez nous, un cas super standard.

Problème : la fiche d'info ne retourne aucune information alors qu'elle devrait afficher les infos standard : code, section, etc. etc.

D'ailleurs le bordereau parcellaire demandé par le même utilisateur fait figurer ces infos.

**Comment by pierrejego** [comment]
Vu avec Mael, suppression des filtres géographiques sur les recherches de commune et de code parcelle.

Suppression de filtre geographique sur le premier onglet de la ficher d'information cadastrale

Fait déployé lundi matin

**Comment by landryb** [comment]
Il me semble qu'on en avait discuté longuement sur les recherches de communes... un utilisateur connecté avec une emprise 'bornée' ne devait voir 'que' les communes auxquelles il avait droit, et il pouvait/devait se deconnecter s'il voulait pouvoir requeter 'toutes' les communes dispos. Non ?

**Comment by pierrejego** [comment]
C'est bien ce qu'il me semblait qu'on avait dit, mais je n'ai pas de trace, et ce comportement ne semblait pas possible pour @MaelREBOUX. A priori pas de déconnexion possible chez eux.

**Comment by landryb** [comment]
Ok, c'est différent chez nous ou on veut que par défaut les utilisateurs non connectés puissent quand meme voir/consulter ce qui ne necessite aucun droit CNIL.. on vise le citoyen lambda comme ca.

**Comment by pierrejego** [comment]
ça se rejoint un peu, il n'y a plus de limitation connecté ou déconnecté pour la recherche de parcelle, juste du filtrage à partir du moment ou on a besoin d'être CNIL1 ou CNIL2

**Comment by landryb** [comment]
Je ne suis pas d'accord avec ce changement. Une personne travaillant pour une comcom sera perdue si on lui propose toutes les communes de la région lors de l'affichage de la liste des communes.

**Comment by MaelREBOUX** [comment]
>  Une personne travaillant pour une comcom sera perdue si on lui propose toutes les communes de la région lors de l'affichage de la liste des communes.

Je ne crois pas : l'auto-complétion se déclenche très vite. Ca ne m'a pas du tout gêné lors de mes tests sur ta PF. L'effet perverse avec ta demande ce sera l'impossibilité pour un utilisateur authentifié de faire une recherche ailleurs dans sa région. Il n'aura jamais l'idée de se déconnecter dans ton cas. Et **dans note cas : la désauthentification est impossible.**

> Il me semble qu'on en avait discuté longuement sur les recherches de communes... un utilisateur connecté avec une emprise 'bornée' ne devait voir 'que' les communes auxquelles il avait droit, et il pouvait/devait se deconnecter s'il voulait pouvoir requeter 'toutes' les communes dispos. Non ?

@landryb en es-tu sûr ? Ca remonte à assez loin et ma mémoire est faillible. Ce cas avait été évoqué mais **il faut balancer entre la recherche et l'accès aux données nominatives.**

Je ne pense pas que ça ait été aussi clair que ce que tu décris. **'voir les communes'** : ça veut dire quoi ? Lister les communes dans les drop-down list des formulaires ? Non : je crois que ça sous-entendait plutôt : **accéder aux données en accès restreint**.  @catmorales a le même souvenir que moi sur la question. Ce qui est cohérent car ce que tu propose ne peut pas fonctionner chez nous.
De plus : ce comportement empêche la consultation des simples infos parcelles en zone limitrophe de sa / ses commune(s) de compétence. 

@pierrejego : je comprend mieux maintenant l'absence de message retour "Vous n'avez pas accès aux données nominatives" quand on consulte une commune en-dehors de sa liste autorisée. Pour @landryb : ce ne devait pas arriver.

On s'appelle ?

**Comment by landryb** [comment]
Je laisse tomber le sujet, j'ai une PF a faire tourner et j'ai pas le temps pour des débats sans fin.

**Comment by pierrejego** [comment]
Je peux vous proposer de rajouter un paramètre dans la configuration cadastrapp.properties.

Par exemple,
modeStrict = 1 -> on filtre les communtes directement à la recherche, il faut être déconnecté pour pas avoir de filre géographique
modeStric = 0 -> pas de filtrage des communes lors de la recherche. Et toujours pas de filtre geographique en étant déconnecté

**Comment by landryb** [comment]
Discuté avec @pierrejego , ok pour le param de configuration documenté dans cadastrapp.properties avec 1 par défaut (filtre actif).
