### ISSUE TITLE
Dégriser le bouton rechercher dès qu'un champ est rempli

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#113]
Sur la recherche par id cadastral, si je copie-colle un identifiant dans le champ vide, le bouton rechercher reste grisé/inactif - il faut sortir du champ (via tab p.ex) pour activer le bouton. Sur l'onglet lot, le bouton est actif dès que le champ vide a le focus...
Au passage le tooltip pour l'onglet identifiant cadastrap est faux, on ne s'attend plus a avoir plusieurs identifiants, et on ne devrait pas mentionner le modèle utilisé (l'utilisateur n'a aucune idée de ca...) -> déplacer l'info "devrait etre séparé par virgule/point virgule" dans le tooltip de l'onglet lot ?

**Comment by landryb** [comment]
Meme comportement pour la recherche par compte proprietaire, il faut dégriser le bouton des que des infos sont rentrées dans la premiere cellule du grid

**Comment by pierrejego** [comment]
Modification effectuée

https://github.com/GFI-Informatique/addons/commit/48cd80000125bf1401bb23e440d2e5b9842c4ae8#diff-7a571e55b8ab6ef19c25dd6b9fd20485

et 
https://github.com/GFI-Informatique/addons/commit/aeb7992152cd9f9ce690f2c8195c0d1ae0ee1875#diff-7a571e55b8ab6ef19c25dd6b9fd20485

**Comment by landryb** [comment]
Le pb est a priori toujours présent pour la recherche par identifiant cadastral si on copie-colle un identifiant dans le champ, le bouton rechercher n'est pas dégrisé - j'ai l'impression que ca ne marche que si on _tape_ l'identifiant dans le champ.
