### ISSUE TITLE
[UI] Ne pas *re* charger les couches si elles sont déja présentes

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#114]
Cas d'utilisation classique trouvé par fred: je charge mapfishapp avec le contexte par défaut, j'active l'addon cadastre, ca me charge la couche WMS cadastre (cachée ou pas dans le layer tree). Je ferme l'onglet, je réouvre un nouvel onglet avec mapfishapp -> la couche cadastre est encore chargée (car stockée dans le localstorage de l'utilisateur) mais l'addon n'est pas chargé/activé. J'active de nouveau l'addon cadastre -> la couche WMS cadastre est chargée une deuxième fois, on le voit en surimpression.

**Comment by pierrejego** [comment]
Bonjour,
je viens de vérifier dans le code, dans le fichier selectFeature.js ligne 583, on vérifie si un layer du même nom existe et si oui on l'enlève avant d'ajouter le nouveau.

Ce qui devrait se passer, c'est lors de la réactivation de l'addons, la couche existante devrait être enlevé de la liste des couches et la nouvelles rajoutée.

J'enlève le preload de l'addons sur nos plateformes pour faire un test et comprendre le fonctionnement.

**Comment by pierrejego** [comment]
En résumé,
avant le chargement de la couche cadastre, je regarde dans l'ensemble des couches disponibles, si une a la même URL. Si c'est le cas, je n'ajoute pas la couche cadastre du module, et je ne la supprime pas en desactivant le module.

**Comment by pierrejego** [comment]
Modification effectuée, https://github.com/GFI-Informatique/addons/commit/5cb28ed9c73066d9ff5e1d7d39f1d4c5e8a8759d#diff-8223b00604be30566072a5470b52f7eb

**Comment by landryb** [comment]
Je viens de faire le test, et j'ai un cas ou ca ne marche pas.

Sur notre pf de qualif, charger manuellement la couche 'qgis:parcelle_bati' depuis http://georchestra.demo.craig.fr/geoserver/wms -> elle apparait dans le layertree avec le nom 'Parcelle + Bati' car c'est son titre 'officiel'.

Activer l'addon, la couche est chargée une deuxième fois, cette fois avec le titre 'geo_parcelle' (car c'est la valeur de layerNameInPanel dans GEOR_custom.js)

```
 cadastre.wms.url=http://georchestra.demo.craig.fr/geoserver/wms
 cadastre.wms.layer.name=qgis:parcelle_bati

```

Ca ne marche pas correctement, car l'url renseignée (dans openlayers) pour la layer 'préchargée manuellement' est 'http://georchestra.demo.craig.fr/geoserver/ows?SERVICE=WMS&' et non 'http://georchestra.demo.craig.fr/geoserver/wms' - donc le GetLayersBy('url') ne renvoie rien - d'ailleurs, je n'ai pas l'impression que le commit gère le cas ou une autre couche aurait été ajoutée depuis le meme service, vu qu'on teste uniquement (layers == null || layers.length == 0) et pas la valeur du layerName....

**Comment by pierrejego** [comment]
Même en faisant l'ajout de la couche par le layerstore, l'url n'est pas la même. Lors de l'ajout de la couche manuellement, on passe par une méthode DESCRIBELAYER qui renvoie l'url de cette forme ows?SERVICE=WMS&

Si je passe par le describelayer, le chargement de la couche n'est plus instantannée, il attend le retour de l'appel au geoserveur. Du coup on se retrouve avec l'outils mais pas encore forcément la couche présente.

J'ai aussi essayé en modifiant le cadastrapp.properties avec une url de la forme 
http://gd-cms-crai-001.fasgfi.fr/geoserver/ows?SERVICE=WMS& , dans ces cas la plus de soucis, la couche s'ajoute bien et on a plus de doublon avec une couche qui aurait déjà été ajoutée à la main.

Quel solution garde t'on ? Un commentaire dans le cadastrapp.properties permettant d'expliquer ce cas particulier, ou un appel supplémentaire pour avoir la description du WMS , mais avec un temps de latence à l'affichage ?.

**Comment by landryb** [comment]
Le fait d'appeler le describelayer(enfin, de passer par le layerstore) permet d'activer plus de fonctions sur la couche (si elle est visible dans le layertree..) et c'est plus 'propre' pour l'intégration dans mapfishapp. Attention aussi à ne pas faire du geoserver-specific, ici en production je fais utiliser mapproxy comme cible pour la couche WMS (qui devrait répondre a un describeLayer aussi), donc plus on reste proche du comportement de mfapp, mieux c'est a mon avis. @fvanderbiest, une opinion ?
Le cas d'un "conflit" pour moi était quand l'utilisateur avait déja chargé la meme couche cadastre en passant par le menu ajouter couche 'classique', donc passer par le layerstore me semble cohérent avec ce cas.

**Comment by MaelREBOUX** [comment]
Je crois que c'est derrière nous ?
@landryb @jusabatier

**Comment by Gaetanbrl** [comment]
Je viens de réaliser une correction pour le cas suivant : 

1 - un utilisateur importe la couche WMS "geo_parcelle" par la méthode classique (bouton "Ajouter des couches");
2 - l'utilisateur active ensuite l'addon Cadastre;
**---- -> Ajout d'un contrôle sur l'URL des couches déjà chargées
3 - la couche "parcelle" qui doit être importée avec l'addon n'est pas importée car déjà présente sous le nom "geo_parcelle";
4 - L'utilisateur ferme l'addon, la couche "geo_parcelle" n'est pas supprimée car ce n'est pas la couche ajoutée lors de l'activation de l'addon Cadastre;

Cette solution permet de ne pas avoir de sur affichage avec une couche cadastre identique déjà importée par un ajout classique. 

Le contrôle ajouté se base sur le nom de la couche du fichier cadastrapp.properties : cadastre.wfs.layer.name.
Etant le nom géoServer, toutes les requêtes appelant cette couche comporteront ce paramètre. On recherche donc ce nom dans l'URL des couches déjà importées. Donc, plus le problème avec les différents types d'URL : ows? ou wms?, toutes sont identifiées car le nom de la couche ne change pas dans la requête (ex: LAYERS=qgis%3Ageo_parcelle).
