### ISSUE TITLE
Erreur sélection par polygone

### ISSUE THREAD

**Issue by deneux** [georchestra/cadastrapp#117]
Lorsqu'on fait un double clic rapide (sans faire les 3 ou 4 pts nécessaires pour faire un polygone). Le message d'erreur suivant est renvoyé :

![capture](https://cloud.githubusercontent.com/assets/16082629/11587363/1c291f32-9a79-11e5-88b9-a30288d68b26.PNG)

**Comment by pierrejego** [comment]
Le message d'erreur vient du Handler OpenLayers sur les polygones, il est directement intégré sous la forme d'une action GeoExt, je ne trouve aucun point d'entrée me permettant de mettre une surcharge permettant d'ajouter un try, catch et de transformé l'erreur en une fenêtre contextuelle.

@deneux je ne peux donc pas corriger cette anomalie

**Comment by MaelREBOUX** [comment]
Pb openLayers / visualiseur / geOrchestra. je ferme.
