### ISSUE TITLE
Echelle graphique fausse dans Bordereau Parcellaire

### ISSUE THREAD

**Issue by deneux** [georchestra/cadastrapp#118]
L'échelle graphique est fausse dans le bordereau parcellaire .pdf. La parcelle 74 mesure environ 6 m de côté dans l'exemple.
![capture2](https://cloud.githubusercontent.com/assets/16082629/11588893/2aa45dbe-9a84-11e5-8690-ef042e5ccb62.PNG)

**Comment by jpklipfel** [comment]
En plus de l'échelle, je constate une déformation qui rend difficilement lisible les étiquettes du fond raster
![image 7](https://cloud.githubusercontent.com/assets/5012040/11682559/0f3f9954-9e66-11e5-950b-8e801dcdcb29.png)
On regroupe ces deux choses ou j'ouvre un autre ticket ?

**Comment by pierrejego** [comment]
Ah je n'avais pas encore vu ce problème de déformation. 
Je pense qu'il vaut mieux créer un autre ticket, ce n'est pas dans la même partie du code.
Sur quel PF avez vous la déformation et quel couche WMS est utilisée dans quel projection ?

**Comment by jpklipfel** [comment]
#126

**Comment by landryb** [comment]
Test fait sur http://georchestra.demo.craig.fr/cadastrapp/services/createBordereauParcellaire?parcelle=2014670067000930849&personaldata=0 l'echelle à bien l'air correcte. La déformation qu'on voyait sur #126 a bien l'air corrigée.

**Comment by jpklipfel** [comment]
OK pour moi, merci
