### ISSUE TITLE
Recherche de propriétaire par compte

### ISSUE THREAD

**Issue by sdhem** [georchestra/cadastrapp#12]
Chatelguyon / *00068 => la fenêtre résultat est la fenêtre de résultat de parcelle alors que l'on devrait avoir la fenêtre de résultat de propriétaire (nom prenom...)

**Comment by MaelREBOUX** [comment]
"bogue" toujours présent

**Comment by pierrejego** [comment]
Modification faite et commité 
https://github.com/GFI-Informatique/addons/commit/09f9c9879a0dc6875e98ee6f3ad71a02a9b9952c
