### ISSUE TITLE
[UI] Fenêtre Demande d'Information Foncière - supprimer ascenseurs horizontaux

### ISSUE THREAD

**Issue by deneux** [georchestra/cadastrapp#120]
Enlever les ascenseurs horizontaux dans la fenêtre Demande d'Information Foncière au niveau de "demande réalisée" et "Transmission des Documents". Les ascenseurs ne sont visibles qu'avec IE.

![capture3](https://cloud.githubusercontent.com/assets/16082629/11591717/4ef12eb6-9a9a-11e5-8b5d-db5333e9e03c.PNG)

**Comment by pierrejego** [comment]
Les ascenseurs ne sont pas présent sur tous les navigateurs. Je regarde pour adapter pour qu'ils disparaissent dans tous les cas

**Comment by pierrejego** [comment]
Cette fenêtre va être revu lors de la réalisation de l'évolution demandée par le puy en velay, je laisse tel quel pour l'instant, et je réaliserai la correction en même temps que l'évolution

**Comment by pierrejego** [comment]
Problème présent uniquement dans IE et qui semble connu pour ExtJS https://www.sencha.com/forum/showthread.php?296230-IE-11-problem-with-checkbox-and-scrollBar/page2
La nouvelle version de la demande d'information ne corrige pas le problème. On va essayer de modifier la structure, ou d'ajouter un style spécifique au scroll bar de cette page pour pas qu'il ne soit visible

**Comment by MaelREBOUX** [comment]
je reproduis bien sous IE11 ici.

**Comment by MaelREBOUX** [comment]
IE n'est plus supporté donc on ferme.
