### ISSUE TITLE
Unité foncière - Surface bâtie non calculée

### ISSUE THREAD

**Issue by deneux** [georchestra/cadastrapp#121]
Dans la fenêtre Unité Foncière la surface concernant le bâtie n'est pas calculée. Voir imprim écran

![capture4](https://cloud.githubusercontent.com/assets/16082629/11592110/d1c9fa3c-9a9c-11e5-881c-fe40fd53e017.PNG)

**Comment by landryb** [comment]
Test fait, a priori ok sur la parcelle/unité foncière http://georchestra.demo.craig.fr/cadastrapp/services/getInfoUniteFonciere?parcelle=2014670067000930849 - par contre je me demande si c'est normal que la surface batie soit supérieure à celles de la parcelle pour dgfip/sig:

```
{"uf":125055,"comptecommunal":"201467067¤00469","dcntpa_sum":8965,"sigcal_sum":9208.0,"sigcalb_sum":19834.0}
```

Mais j'imagine que c'est du aux étages...
