### ISSUE TITLE
La parcelle selectionnée n'est pas mise en surbrillance dans le BP généré

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#122]
Testé sur notre PF de test ou sur celle de GFI avec le modele arcopole, la parcelle n'est pas mise en surbrillance et on peut avoir des difficultés a la retrouver - même si on est centré dessus.

On la colore de la meme couleur que celle utilisée quand la FI est ouverte (selectedStyle.colorState3) ? Ca veut dire qu'il faut déplacer ce param (et opacity/strokeWidth) dans cadastrapp.properties, donc pas obligatoire...

**Comment by pierrejego** [comment]
Bonjour,
la parcelle n'est pas du tout dessinée, 
je viens de modifier le code en pensant que le problème vennait du système de coordonnée EPSG:3857 pas connu par geotools dans cette version et qui n'arrive donc pas à faire la transition en shape pour le dessiner dans l'image final, mais cela ne vient pas de là.
Je n'ai aucun polygon de dessiné sur la couche, j'ai ajouté des traces mais il n'y a aucune erreur dans les logs, je continue à chercher d'ou vient cette erreur

**Comment by pierrejego** [comment]
https://github.com/GFI-Informatique/cadastrapp/commit/e6fee69013662bf35c050a580557329f0bd3cd5a#diff-a1ae12083df166bf7d74fefbd8369027

https://github.com/GFI-Informatique/cadastrapp/commit/bf3cca0e0b0c002569c7d3843d5425e4da045f58#diff-a1ae12083df166bf7d74fefbd8369027
