### ISSUE TITLE
Informations sur les bâtiments

### ISSUE THREAD

**Issue by aureliesouvignet** [georchestra/cadastrapp#123]
Bonjour,

Je ne retrouve pas différents élements :
- l'année de construction du bâtiment  (bâtiment)
- la catégorie fiscale (batiment), 
- le champ revenu n'est pas renseigné (bâtiment)
- la taxe d'ordure (bâtiment)
- l'année d'achévement (descriptif)
  J'indique entre parenthèse, leur emplacements éventuels.

Dans la partie bâtiment, il est noté année, je pense qu'il peut induire en confusion avec l'année de construction. Est-il utile de le maintenir ?

Dans la partie mutation, la date de mutation est inscrite de la façon suivante : 15011997, ce serait bien de mettre 15/01/1997 ou 15-01-1997.

**Comment by pierrejego** [comment]
Bonjour,
dans la partie mutation, la date est déjà modifiée 
![image](https://cloud.githubusercontent.com/assets/11499415/11973819/b2b285d0-a95e-11e5-9ea5-245e5347c72f.png)

Je vous propose de remplacé le champ année, par date de construction et mettre jannat, plutôt que l'actuel pev.annee (qui effectivement n'apporte pas grand chose)

L'année d'achèvement n'est pas disponible dans la base QGIS,  Cela serait le champ jacloc de la table  local10, http://demo.3liz.com/plugin_cadastre/schema_cadastre_postgresql_autodoc.html#documentation.table.local10 
mais il est marqué comme indisponible.

Et il y avait une erreur sur le champ revenu qui s'affiche maintenant

Je vous appel pour faire un point sur les 1 autres champs, qui pour moi ne devait être présent que dans le relevé de propriété

**Comment by landryb** [comment]
@jusabatier est-ce que tout les elements mentionnés par @aureliesouvignet dans le premier commentaire du ticket sont présents maintenant ?

**Comment by jusabatier** [comment]
Il me semble que oui, par contre je n'ai pas les droits pour clore le ticket.

**Comment by landryb** [comment]
Pareil pour #125, tu peux vérifier ?
