### ISSUE TITLE
affichage de la couche parcellaire au chargement ou a l'affichage de la toolbar

### ISSUE THREAD

**Issue by aureliesouvignet** [georchestra/cadastrapp#124]
Bonjour,
On avait évoqué lors d'une conférence l'affichage de la couche geo_parcelle lorsqu'on active le module cadastrapp.
Si on le configure par défaut pour nos utilisateurs, la couche sera chargée automatiquement, même s'ils utilisent mapfishapp pour autre chose.
Est-il possible d'avoir un affichage de la couche geo_parcelle seulement lorsque l'utilisateur a cliqué sur l'icône cadastrapp (c'est à dire qu'il a la barre avec les fonctionnalités)?
Il ne me semble pas qu'on avait évoqué cette subtilité entre l'activation de l'icône et l'actionnement de celui-ci : barre des fonctionnalités.
Je vous remercie,

**Comment by pierrejego** [comment]
Bonjour,
si j'ai bien compris, oui c'est ce qui est prévu.

Le chargement de la couche (et son déchargement même si il y a une anomalie actuellement) se fait par l'activation et la désactivation du module et est visible dans la partie couche à droite on fonction de la configuration (cadastrapp.properties)

Donc l'utilisateur ne verra la couche que lorsque le module sera chargé. Un bug en cours de correction fait que la couche reste dans la liste, même après la desactivation, mais une fois celui ci corrigé le comportement devrait être le même que celui que vous souhaitez.

**Comment by aureliesouvignet** [comment]
Re, 
Si j'ai bien compris vous m'indiquez que la couche sera chargée lorsque le module est activé. 
On trouverait judicieux que la couche soit chargée seulement lorsque la pop-up (barre des fonctionnalités du cadastre) est visible.

**Comment by landryb** [comment]
Peu importe l'un ou l'autre, mais il faut que tout le monde soit d'accord sur le comportement à adopter... @MaelREBOUX ? @pigma ? @jpklipfel ?

**Comment by jpklipfel** [comment]
> On trouverait judicieux que la couche soit chargée seulement lorsque la pop-up (barre des fonctionnalités du cadastre) est visible. 

+1

**Comment by pigma** [comment]
Pas de préférence sur ce point

**Comment by MaelREBOUX** [comment]
Bonjour désolé pour le délai de réponse mais pas mal hors bureau ces derniers temps.

Je suis content de cette discussion car j'avais volontairement laissé de côté ce point car phase de développement intensive + PF dédiée de test.

Je suis d'accord avec @jpklipfel et @aureliesouvignet : il me semble logique que la couche support geo_parcelle ne soit chargée que si la barre d'outils est active et donc que l'utilisateur a réellement l'intention de faire de la consultation cadastrale.

Ici à Rennes nous disposons déjà d'un service WMTS afin de bénéficier de bonnes performances pour la consultation du plan qui est assez riche. Nous envisageons donc d'appliquer un style qui rendra transparent les objets de la couche geo_parcelle. N'est-ce pas @catmorales ?

cf image ci-dessous pour se donner une idée.
![screenshot097](https://cloud.githubusercontent.com/assets/6370443/11871791/1a03a8d6-a4d2-11e5-99d8-917d549038e6.png)

**Comment by catmorales** [comment]
oui c'est ce que nous avions pensé

**Comment by pierrejego** [comment]
Modification effectuée, la couche est ajoutée quand la barre d'outils s'ouvre et enlever quand on ferme la barre d'outils. Si une couche avec la même url existe, alors la couche de l'addons et ni ajoutée ni enlevée

**Comment by landryb** [comment]
Comportement ok pour le chargement/déchargement de la couche. Par contre #114 n'est pas encore correctement fixé.

Au passage, et c'est vraiment un détail mineur, je me serais attendu a ce que le bouton cadastrapp dans la toolbar mapfishapp soit un togglebutton qui ferme la barre d'outil quand on reclique dessus - dans l'état, on clique sur le bouton pour ouvrir la barre d'outil, et on doit cliquer sur la croix de la barre d'outil pour la fermer. Ca serait plus logique de pouvoir aussi fermer la barre d'outil en recliquand sur le bouton de la toolbar.
