### ISSUE TITLE
Partie descriptif du bâtiment

### ISSUE THREAD

**Issue by aureliesouvignet** [georchestra/cadastrapp#125]
Bonjour,

Il manque des élements dans le descriptif du bâtiment. 

Dans la partie élements de confort :
- la superficie des élements de conforts
- la présence d' eau, electrictié , gaz, vide ordure, égout, ascenseur, chauffage central

Une partie avec les élements de construction :
matériaux : mur, toit.

Enfin, il manque le détail de la taxation, il comporte :
- la val. locative 70
- la val. locative de l'année
- la base d'imposition de l'année
- les exonérations éventuelles.

**Comment by pierrejego** [comment]
Il faut que je revérifie normalement ces informations sont présentes, mais uniquement affiché si il y a des informations dans la base.
Pouvez vous me donner l'id utilisé et la plateforme pour que je puisse regarder entre la base de données et le code.
Par contre, effectivement il n'y a pas les éléments de taxation et d’exonération qui ne sont présents que dans le relevé de propriété. Il faudrait qu'on fasse un point pour voir comment les afficher si il faut bien les rajouter.

**Comment by pierrejego** [comment]
Après vérification les informations " présence d' eau, electrictié , gaz, vide ordure, égout, ascenseur, chauffage central" sont bien présentes et viennent de la base de données. Il y une erreur dans le code, qui n'affiche pas les données.

Par contre, nous n'affichons pas les éléments de matériaux, ni la taxation.

Comme pour le ticket #123, pour moi les éléments de taxation ne sont présentes que dans le relevé de propriété, mais nous pouvons en discuter.

Pour les matériaux, je rajoute les champs dmatgm    pour les murs et dmatto pour la toiture dans la vue.

**Comment by jusabatier** [comment]
> Comme pour le ticket #123, pour moi les éléments de taxation ne sont présentes que dans le relevé de propriété, mais nous pouvons en discuter.

Aurélie étant absente pour l'instant, je ne sais pas si ce point était indispensable, pour le reste ça me semble ok

**Comment by landryb** [comment]
merci!
