### ISSUE TITLE
[Plateforme de qualification gfi]pb de dimensionnement de la toolbar

### ISSUE THREAD

**Issue by catmorales** [georchestra/cadastrapp#127]
La barre d'outil cadastre qui s'ouvre par défaut est mal dimensionnée (trop grande) et non redimensionnable don difficile à utiliser

![image](https://cloud.githubusercontent.com/assets/4659829/11873816/c4770484-a4dc-11e5-85cc-8cfbb67557d0.png)

Je suis en chrome Version 38.0.2125.122 m

**Comment by pierrejego** [comment]
Bonjour,
je me rappelais bien du problème, je revoie actuellement les dimensionnements automatiques.
Je ne reproduis pas, mais le problème c'est de réussir à avoir la même version de chrome pour reproduire. Si quelqu'un reproduit sur une autre version d'un autre navigateur, je suis preneur

Pour information ma version de Chrome est la 47.0.2526.80 m

**Comment by catmorales** [comment]
Bonjour Pierre,
Merci, si c'est un problème à la marge qui n'existe que sur cette version de chrome, ce n'est pas bloquant , j'essaierai sur un chrome plus récent

**Comment by pierrejego** [comment]
Je vais quand même essayer de le corriger, dans tous les cas, je rajoute la possiblité de redimensionner la fenêtre pour ne pas être bloqué

**Comment by catmorales** [comment]
ok

**Comment by pierrejego** [comment]
J'ai ajouté un attribut boxMaxWidth qui devrait permettre de corriger le problème.
Ne pouvant pas le reproduire, @catmorales je vous laisse vérifier et fermer l'anomalie si c'est bon.
Disponible demain sur la plateforme de qualification

https://github.com/GFI-Informatique/addons/commit/224bf40904cac59d8770dfff51e1992044e2d8a0#diff-94302db2d40845274f961ee984d13d57

**Comment by catmorales** [comment]
retesté ce matin, j'ai toujours le même problème

**Comment by pierrejego** [comment]
@catmorales bonjour, est-ce que vous pouvez retester il y avait un problème sur le déploiement de la plateforme, qui n'était pas à jour côté client

**Comment by catmorales** [comment]
re -testée ce jour je n'ai plus de problème mais je viens de mettre à jour mon navigateur qui datait de la préhistoire ...

**Comment by landryb** [comment]
Je peux toujours reproduire le problème en utilisant un navigateur se basant sur le moteur webkitgtk (http://www.midori-browser.org/) sur http://georchestra.demo.craig.fr/mapfishapp/  - la pf de qualif GFI ne répond pas..

**Comment by pierrejego** [comment]
je suis sur la pf de qualif. Elle répond bien chez moi, je vais contacter l'infra pour vérifier pourquoi tu n'as pas accès.
Je vais testé ce navigateur qui m'est complètement inconnu

**Comment by pierrejego** [comment]
Je viens d'essayer Midori, je reproduis bien. Par contre, je dois rester en local, impossible de configurer mon proxy dans midori... 
Et comment tu fais pour avoir une console javascript ? Tu as installé une extension ?
