### ISSUE TITLE
[plateforme de qualification gfi] affichage Recherche des parcelles/Référence

### ISSUE THREAD

**Issue by catmorales** [georchestra/cadastrapp#128]
Petit bug dans l'affichage sur chrome, pas assez d'espace pour les premiers contrôles:

![image](https://cloud.githubusercontent.com/assets/4659829/11875745/7c5b28b0-a4e6-11e5-93b6-0476de06091c.png)

**Comment by pierrejego** [comment]
@catmorales  Je n'ai pas réussit à reproduire, mais je viens de modifié entièrement le rendu de cette fenêtre.
pouvez vous vérifié à partir de demain sur la pf de qualif, si c'est bon.

https://github.com/GFI-Informatique/addons/commit/12dae137fc33a8729b5d6c77bc0c17165821821a#diff-7a571e55b8ab6ef19c25dd6b9fd20485

Merci

**Comment by catmorales** [comment]
ok vu
