### ISSUE TITLE
Erreur 500 sur getInfoUniteFonciere

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#129]
http://georchestra.demo.craig.fr/cadastrapp/services/getInfoUniteFonciere?parcelle=2014670067000930849

```

...
org.springframework.dao.EmptyResultDataAccessException: Incorrect
 result size: expected 1, actual 0
    org.springframework.dao.support.DataAccessUtils.requiredSingleResult(DataAccessUtils.java:71)
    org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:806)
    org.springframework.jdbc.core.JdbcTemplate.queryForMap(JdbcTemplate.java:839)
    org.georchestra.cadastrapp.service.UniteFonciereController.getInfoUniteFonciere(UniteFonciereController
.java:58)
```

Vu sur cette parcelle en alsace, pas vu sur la haute loire. Les tables en BDD ont été refaites a partir de zero,et il y'a bien une unité foncière pour cette parcelle:

```
cadastrapp_qgis=# select * from cadastrapp_qgis.uf_parcelle where parcelle='2014670067000930849';
      parcelle       |   uf   |  comptecommunal
---------------------+--------+------------------
 2014670067000930849 | 125055 | 201467067Â¤00469

```

un caractère en trop/étrange dans le champ comptecommunal ?

**Comment by landryb** [comment]
Le problème n'apparait pas si l'utilisateur est deconnecté  - dans mon cas j'étais avec testadmin, qui avait accès aux infos sur le 43 uniquement et pas le 67 - mais le comportement est pareil si testadmin a accès aux infos du 67. user.search.are.filtered=1 est dans la configuration.

requete avec nouser

```
DEBUG /getInfoUniteFonciere - nouser - norole -o.s.jdbc.core.JdbcTemplate - Executing prepared SQL statement [select uf.uf, uf.comptecommunal, sum(p.dcntpa) as dcntpa_sum, sum(p.surfc) as sigcal_sum, sum(p.surfb) as sigcalb_sum from cadastrapp_qgis.parcelleDetails p, cadastrapp_qgis.uf_parcelle uf where uf.uf IN (select uf2.uf from cadastrapp_qgis.uf_parcelle uf2 where uf2.parcelle= ? )  and uf.parcelle = p.parcelle GROUP BY uf.uf, uf.comptecommunal;]
```

requete avec testadmin

```
DEBUG /getInfoUniteFonciere - testadmin - ROLE_MOD_LDAPADMIN,ROLE_SV_ADMIN,ROLE_ADMINISTRATOR,ROLE_MOD_ANALYTICS,ROLE_EL_CAD_CNIL1,ROLE_EL_DEP_33,ROLE_EL_DEP_67,ROLE_EL_DEP_43,ROLE_EL_CAD_CNIL2,ROLE_MOD_EXTRACTORAPP -o.s.jdbc.core.JdbcTemplate - Executing prepared SQL statement [select uf.uf, uf.comptecommunal, sum(p.dcntpa) as dcntpa_sum, sum(p.surfc) as sigcal_sum, sum(p.surfb) as sigcalb_sum from cadastrapp_qgis.parcelleDetails p, cadastrapp_qgis.uf_parcelle uf where uf.uf IN (select uf2.uf from cadastrapp_qgis.uf_parcelle uf2 where uf2.parcelle= ? )  and uf.parcelle = p.parcelle  AND p.cgocommune LIKE '67%' AND p.cgocommune LIKE '33%' AND p.cgocommune LIKE '43%'GROUP BY uf.uf, uf.comptecommunal;]
```

Le filtre sql sur p.cgocommune devrait etre entre parentheses, et avec des OR non ? Ou utiliser SIMILAR TO plutot qu'enchainer les LIKE...

Ca n'arriverait pas avec un vrai ORM plutot que construire les requetes a la main....

**Comment by landryb** [comment]
Le problème est aussi présent avec user.search.are.filtered=0

**Comment by landryb** [comment]
```
cadastrapp_qgis=# select uf.uf, uf.comptecommunal, sum(p.dcntpa) as dcntpa_sum, sum(p.surfc) as sigcal_sum,
 sum(p.surfb) as sigcalb_sum from cadastrapp_qgis.parcelleDetails p, cadastrapp_qgis.uf_parcelle uf where uf.uf IN (select uf2.uf from cadastrapp_qgis.uf_parcelle uf2 where uf2.parcelle='2014670067000930849' )  and uf.parcelle = p.parcelle  AND p.cgocommune LIKE '67%' AND p.cgocommune LIKE '33%'  AND p.cgocommune LIKE '43%'GROUP BY uf.uf, uf.comptecommunal;
 uf | comptecommunal | dcntpa_sum | sigcal_sum | sigcalb_sum
----+----------------+------------+------------+-------------
(0 rows)
```

requete corrigée

```
cadastrapp_qgis=# select uf.uf, uf.comptecommunal, sum(p.dcntpa) as dcntpa_sum, sum(p.surfc) as sigcal_sum,
 sum(p.surfb) as sigcalb_sum from cadastrapp_qgis.parcelleDetails p, cadastrapp_qgis.uf_parcelle uf where uf.uf IN (select uf2.uf from cadastrapp_qgis.uf_parcelle uf2 where uf2.parcelle='2014670067000930849' )  and uf.parcelle = p.parcelle  AND (p.cgocommune LIKE '67%' OR p.cgocommune LIKE '33%'
OR p.cgocommune LIKE '43%')GROUP BY uf.uf, uf.comptecommunal;
   uf   |  comptecommunal  | dcntpa_sum | sigcal_sum | sigcalb_sum
--------+------------------+------------+------------+-------------
 125055 | 201467067Â¤00469 |       8965 |       9208 |       19834
```

**Comment by pierrejego** [comment]
Je regarde, je vois bien que la requête n'est pas bonne, mais  je regarde plus en détails, je pense que l'erreur est plus général.
Pour l'utilisation d'un ORM, c'était malheureusement pas compatible avec l'utilisation de vue (même matérialisée) mais je suis d'accord avec un ORM il n'y aurait pas eut une partie des problèmes.

**Comment by pierrejego** [comment]
Ok après analyse, c'est un problème sur le filtre par département, dès qu'une personne à des droits sur plusieurs départements.
Je viens de faire des tests avec un similar to mais les temps de réponses sont beaucoup trop élevé, je reste sur ta solution avec plusieurs OR

Et c'est normal que le problème soit aussi présent avec le user.search.are.filtered=0 car, il y a l'indication du compte communal, c'est donc forcément filtré.

Par contre tu devais avec des erreurs 500 dans à peu près tous les appels de service avec ce user avec user.search.are.filtered=1

**Comment by landryb** [comment]
Ok, marche bien avec le fix.. mais pas dans tout les cas.
- requête sans être connecté -> OK:

```
select uf.uf, uf.comptecommunal, sum(p.dcntpa) as dcntpa_sum, sum(p.surfc) as sigcal_sum, sum(p.surfb) as sigcalb_sum from cadastrapp_qgis.parcelleDetails p, cadastrapp_qgis.uf_parcelle uf where uf.uf IN (select uf2.uf from cadastrapp_qgis.uf_parcelle uf2 where uf2.parcelle= ? )  and uf.parcelle = p.parcelle GROUP BY uf.uf, uf.comptecommunal;
```
- requête avec testadmin sur 3 départements dont le 67-> OK:

```
select uf.uf, uf.comptecommunal, sum(p.dcntpa) as dcntpa_sum, sum(p.surfc) as sigcal_sum, sum(p.surfb) as sigcalb_sum from cadastrapp_qgis.parcelleDetails p, cadastrapp_qgis.uf_parcelle uf where uf.uf IN (select uf2.uf from cadastrapp_qgis.uf_parcelle uf2 where uf2.parcelle= ? )  and uf.parcelle = p.parcelle  AND ( p.cgocommune LIKE '67%'  OR p.cgocommune LIKE '33%'  OR p.cgocommune LIKE '43%'  ) GROUP BY uf.uf, uf.comptecommunal;
```
- requete avec un utilisateur ayant une emprise sur la CAPEV (et donc pas de droits sur la commune 67067 requetée) -> de nouveau code 500:

```
select uf.uf, uf.comptecommunal, sum(p.dcntpa) as dcntpa_sum, sum(p.surfc) as sigcal_sum, sum(p.surfb) as sigcalb_sum from cadastrapp_qgis.parcelleDetails p, cadastrapp_qgis.uf_parcelle uf where uf.uf IN (select uf2.uf from cadastrapp_qgis.uf_parcelle uf2 where uf2.parcelle= ? )  and uf.parcelle = p.parcelle  AND p.cgocommune IN ('430241','430046','430045','430229','430197','430002','430089','430039','430190','430257','430062','430260','430157','430174','430251','430032','430152','430124','430254','430018','430061','430221','430233','430084','430078','430041','430010' ) GROUP BY uf.uf, uf.comptecommunal;
```

Il faut prévoir le cas ou les droits sont insuffisants...

**Comment by pierrejego** [comment]
Plus ajout d'une condition pour éviter les appels non nécessaire à la webapp.
https://github.com/GFI-Informatique/addons/commit/b2598e81377a3336a65dd305309c8b99c1bee048#diff-dd6012ff2d9ce5f2e16c60931337fcd0

**Comment by landryb** [comment]
Du coup, si je fais le meme test (ie user dans groupe ayant droits sur le puy, requete sur une commune du 67) je me retrouve avec... des fenetres vides, cf http://i.imgur.com/KOjhJMG.png

Ca ne va toujours pas :) Il faut qu'on revoie ce que l'option user.search.is.filtered veut dire: pour moi c'était surtout le filtrage des valeurs sur autocomplétion pour les communes - et si on est (pour des raisons X ou Y) sur une zone ou on n'a pas de droits CNIL.. ben on doit au moins avoir les informations qu'un utilisateur non connecté voit, et pas des fenetres vides.

**Comment by landryb** [comment]
En fait, le probleme est exactement le meme avec user.search.is.filtered a 0.

**Comment by pierrejego** [comment]
Hello,
Tu es dispo vers 14h ? Comme ça on fera le point sur le filtered, sur ce que moi j’ai fait et compris, et sur ce que tu veux.

—
Pierre Jégo
Tél. : +33 (0)2 96 48 25 63

De : Landry Breuil [mailto:notifications@github.com]
Envoyé : lundi 11 janvier 2016 11:17
À : GFI-Informatique/cadastrapp cadastrapp@noreply.github.com
Cc : Jego Pierre pierre.jego@gfi.fr
Objet : Re: [cadastrapp] Erreur 500 sur getInfoUniteFonciere (#129)

En fait, le probleme est exactement le meme avec user.search.is.filtered a 0.

**Comment by pierrejego** [comment]
Suite à notre conversation, je ne met de filtre géographique que sur les outils de recherches via les fenêtres par de filtre géographique sur les clics, uniquement un filtre CNIL

**Comment by pierrejego** [comment]
Le filtre géographique n'est valable que lorsque des droits CNIL sont nécessaire et sur les autocomplétions.

https://github.com/GFI-Informatique/cadastrapp/commit/aed90048ab067abed543d15d7b24313e2aa76b56

**Comment by landryb** [comment]
Ok, a priori c'est bon maintenant. Je me pose la question de la pertinence des onglets vides propriétaire/co-propriétaire dans la fiche d'info (et le bloc propriétaire dans la fenetre d'UF) quand l'information n'est pas disponible/filtrée, peut-etre qu'un message "vous n'êtes pas connectés ou cette information n'est pas incluse dans votre emprise de compétence" serait pas mal pour clarifier, mais ca on verra plus tard..

Merci!

**Comment by pierrejego** [comment]
Oui, je suis d’accord.
Le problème est de savoir ce qu’on gère comme cas. Pour l’instant la Webapp ne remonte pas l’information pour dire qu’il y a un résultat mais que vous n’avez pas les bons droits CNIL. Dans un premier temps on pourrait juste mettre une message Pas de résultat par défaut dans l’ensemble des tableaux. Je peux aussi n’afficher les onglet que si le résultat n’est pas vide (mais j’ai peur que les personnes ne s’y retrouve pas, un coup j’ai les onglets, un coup je ne les ai pas…)

C’est donc à étudier un peu avant de faire la réal. Tenez moi au courant

—
Pierre Jégo
Tél. : +33 (0)2 96 48 25 63

De : Landry Breuil [mailto:notifications@github.com]
Envoyé : mardi 12 janvier 2016 14:25
À : GFI-Informatique/cadastrapp cadastrapp@noreply.github.com
Cc : Jego Pierre pierre.jego@gfi.fr
Objet : Re: [cadastrapp] Erreur 500 sur getInfoUniteFonciere (#129)

Ok, a priori c'est bon maintenant. Je me pose la question de la pertinence des onglets vides propriétaire/co-propriétaire dans la fiche d'info (et le bloc propriétaire dans la fenetre d'UF) quand l'information n'est pas disponible/filtrée, peut-etre qu'un message "vous n'êtes pas connectés ou cette information n'est pas incluse dans votre emprise de compétence" serait pas mal pour clarifier, mais ca on verra plus tard..

Merci!
