### ISSUE TITLE
Fond de plan sur le bordereau parcellaire

### ISSUE THREAD

**Issue by jpklipfel** [georchestra/cadastrapp#130]
Les couches de l'arbre des couches mapfishapp autre que la couche parcelle ne sortent pas à l'extraction sur l'extrait du bordereau.
Est ce paramétrable ? comment faire figurer les éléments de légende dans le bordereau?

**Comment by landryb** [comment]
A l'impression, il y'a uniquement la couche de fond (baseMap.WMS.url dans cadastrapp.properties) + la couche parcellaire - c'était prévu comme ca.

**Comment by jpklipfel** [comment]
OK merci

**Comment by pierrejego** [comment]
Mettre la légende dans le bordereau parcellaire est une évolution à faire.
Pour afficher l'ensemble des couches, ce n'est pas prévu non plus, nous pensons que l'utilisation de l'impression classique via mapfishprint est à recommander

**Comment by catmorales** [comment]
> A l'impression, il y'a uniquement la couche de fond (baseMap.WMS.url dans cadastrapp.properties) + la couche parcellaire - c'était prévu comme ca.

De mon côté pas possible de voir la couche parcellaire (pf de qualif gfi) je ne vois que le fond de plan  et même en rajoutant la couche parcellaire dessus , elle ne s'affiche pas à l'impression mais il me semble qu'il y a un paramétrage à faire quelque part dans des fichiers de configuration ... pour rendre cette couche visible .
Pierre tu confirmes ?

**Comment by pierrejego** [comment]
@catmorales, effectivement il y a un soucis de configuration sur le serveur de qualification gfi. Mais je n'ai pas la main dessus avant la réunion de tout à l'heure. Je corrigerais la configuration demain matin

**Comment by MaelREBOUX** [comment]
A fermer ?
