### ISSUE TITLE
Fermer la barre d'outil cadastrapp au 2e clic sur le bouton dans la toolbar

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#131]
(extrait de https://github.com/GFI-Informatique/cadastrapp/issues/124#issuecomment-167966900)

Au passage, et c'est vraiment un détail mineur, je me serais attendu a ce que le bouton cadastrapp dans la toolbar mapfishapp soit un togglebutton qui ferme la barre d'outil quand on reclique dessus - dans l'état, on clique sur le bouton pour ouvrir la barre d'outil, et on doit cliquer sur la croix de la barre d'outil pour la fermer. Ca serait plus logique de pouvoir aussi fermer la barre d'outil en recliquant sur le bouton de la toolbar.

**Comment by omarmancourbillah** [comment]
C'est fait le bouton cadastrapp et en toggleButton
https://github.com/GFI-Informatique/addons/commit/617084d952a5f588d2ea69bcd1d9502cca3c75e5

**Comment by landryb** [comment]
Désolé mais dans https://github.com/GFI-Informatique/addons/commit/617084d952a5f588d2ea69bcd1d9502cca3c75e5 je ne vois pas ou le comportement du bouton passe en toggleButton.. et si je teste sur https://cadastrapp-qualif.asogfi.fr/mapfishapp/ ca ne fonctionne pas. Pour moi il doit faire partie du toggleGroup 'map', et rester enfoncé quand la barre d'outil est affichée.

**Comment by pierrejego** [comment]
Hello, on a modifié le comportement pour que la barre se ferme quand on reclique sur le bouton cadastrapp. Mais on ne l'a pas mis dans le toogle group. On va essayer de faire les deux en même temps, toogle groupe  + fermer quand on clique dessus, sinon quand on clique sur la selection par point, ligne ou polygone ça risque aussi de fermer la barre cadastrapp.

**Comment by landryb** [comment]
Ah, bien vu - dans ce cas il peut peut-etre etre dans un toggle group a part pour garder le visuel 'bouton enfoncé' ? dans tout les cas le 2e clic ne referme pas la toolbar sur la pf de qualif GFi, mais je ne sais pas si ca a ete redeployé..

**Comment by pierrejego** [comment]
Effectivement ce n'est pas redéployé, il ne met pas à jour avec le git pull sur l'addons. Je vais forcer la mise à jour à la main.

**Comment by pierrejego** [comment]
Je viens de corriger l'erreur de déploiement, il n'était pas bon depuis 10 jours. Tu peux rester

**Comment by landryb** [comment]
Ben.. désolé, mais ca ne marche toujours pas, et je n'ai pas non plus de résultat quand je clique sur une parcelle sur rennes, meme connecté.

**Comment by pierrejego** [comment]
C'est bon maintenant, j'avais fait des tests de reprojections avec le geoserver, et du coup la couche de parcelle était un peu en dessous de l'afrique... désolé

**Comment by landryb** [comment]
Après avoir bien bataillé avec le cache, ca marche (refermer la toolbar au 2e clic sur le bouton cadastrapp) bien sur la pf de qualif GFI. Merci!

**Comment by MaelREBOUX** [comment]
Je me permet de rouvrir ce ticket pour suivi  car ça n'a pas l'air encore parfait.
contexte : geOchestra 15.12 en test.

La désactivation de la toolbar + déchargement de la couche parcellaire applicative fonctionne 1 fois mais pas 2.

Au 2e clic j'obtiens 2 erreurs dans la console FireFox

```
main.js (ligne 92, col. 23)
TypeError: GEOR.Addons.Cadastre.addPopupOnhover is not a function
GEOR.Addons.Cadastre.addPopupOnhover(popupSetting);

main.js (ligne 103, col. 27)
TypeError: mapControls is undefined
mapControls.destroy();
```

La toolbar se ferme mais la couche des parcelles reste chargée.
