### ISSUE TITLE
Erreur Géneration BP

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#132]
Bonjour,

Sur notre instance de test, l'image de la parcelle n’apparaît pas sur le PDF du Bordereau Parcellaire.

Dans les logs de cadastrapp on retrouve cette erreur : http://pastebin.com/GPpfaLgw

**Comment by landryb** [comment]
> Sur notre instance de test, l'image de la parcelle n’apparaît pas sur le PDF du Bordereau Parcellaire.

Ca c'est le https://github.com/GFI-Informatique/cadastrapp/issues/122

**Comment by pierrejego** [comment]
Je ne reproduis pas chez moi. 
Je fais des tests pour comprendre d'ou cela vient mais je ne trouve rien. C'est la méthode getFeature de Geotools qui sort en nullpointer (d'après les traces que je vois)
Je viens de rajouter des traces en amont de l'appel, pour voir si tous les paramètres sont ok.
@jusabatier est-ce que vous pouvez récupérer la dernière version du master et mettre en debug pour que j'ai les nouvelles traces.

**Comment by jusabatier** [comment]
J'ai mis à jour avec master, et activé les logs en debug, voici ce que je retrouve lors de la génération d'un BP : 

http://pastebin.com/jV9BFsYh

**Comment by pierrejego** [comment]
Merci, malheureusement je ne vois pas les logs que j'ai rajouté. Ce qui me pose problème pour débuger.
Je fais d'autres tests de mon côté pour comprendre quand peu se produire cette erreur.

**Comment by jusabatier** [comment]
Pourtant j'ai bien fait un git pull puis recompilé l'application

**Comment by pierrejego** [comment]
Oui, je ne remet pas du tout en cause ta manip. C'est le log4j qui doit perdre les pédales, l'erreur doit se produire quasiment en même temps qu'il écrit.

**Comment by jusabatier** [comment]
En regardant à nouveau il s'avère que je n'avais pas du modifier le bon fichier pour passer les logs en DEBUG, voici un lien vers le nouveau fichier généré : 
https://cloud.lepuyenvelay.fr/index.php/s/jRdjP8OzlOe4Wq1

**Comment by pierrejego** [comment]
Merci,
est-ce que je pourrais avoir aussi le résultat de la requête http://10.1.1.142:8086/geoserver/wfs?REQUEST=GetCapabilities&version=1.0.0

**Comment by jusabatier** [comment]
Le voila : https://cloud.lepuyenvelay.fr/index.php/s/iPtV47Tq1ssQbK3

**Comment by pierrejego** [comment]
Bonjour,
on vient de faire les tests ensemble.  Et on a trouvé la raison de l'erreur.

Pour que la méthode getCapatibilities du WFS fonctionne, il faut que la couche soit activée et surtout publié. Dans le cadre du déploiement au Puy en Velay, les couches WFS ne sont pas publiées pour éviter les requêtages sur le getCapatibilitie. Pour générer l'image, ce requêtage est nécessaire.

Si la couche n'est pas publiée, l'appel WFS qui est fait avant l'appel WMS pour récupérer l'image sort en erreur, et le reste de la couche n'est pas généré.

Je vais juste rajouter un test pour éviter les nullpointer et indiquer dans les logs d'erreurs qu'il faut publié le WFS.
