### ISSUE TITLE
Parcelles - Coloration sélection courante

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#133]
Bonjour,

Lorsqu'on fait une recherche de parcelle (par id ou proprietaire), en zoomant sur la liste on constate que celles de la liste et celles sélectionnées apparaissent en bleu et jaune, mais ces couleurs de sélection sont en dessous de la couche geo_parcelle et donc invisibles.

**Comment by pierrejego** [comment]
@jusabatier est-ce que je peux avoir une copie d'écran pour être sur de comprendre ? Quel navigateur utilisez vous ?

**Comment by jusabatier** [comment]
Pour constater ce bug, en partant avec une liste de couches vides, j'ouvre une fois l'addon cadastrapp et cette première fois les parcelles listées apparaissent bien en jaune et les sélectionnées en bleu.

Ensuite si je ferme l'addon cadastrapp (suppression de la couche parcelle) et que je le réouvre, à présent si je sélectionne/liste des parcelles, la couche parcelle est ajoutée par dessus celle qui représente les selections/liste et donc la coloration des parcelles selectionnées/listées n'apparait plus car en dessous de la couche parcelles.

J'utilise le navigateur Google Chrome

**Comment by jusabatier** [comment]
Ce problème semble avoir été corrigé.
