### ISSUE TITLE
Erreur sur demande d'infos foncières

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#134]
Bonjour,

En cliquant sur le bouton "Requête" pour une demande d'Infos Foncières, je ne peut pas renseigner la partie objet de la requête.

**Comment by pierrejego** [comment]
La règle de gestion n'est pas bien implémenté dans le code. 
Pour avoir accès à la partie demande d'objet, il faut au minimum remplir le CNI dans le cas d'un particulier tiers, et le nom dans les autres cas

**Comment by jusabatier** [comment]
Même en mettant type de demandeur à Administration, il me faut toujours renseigner le CNI obligatoirement.

**Comment by omarmancourbillah** [comment]
Corrigé
Si particulier tiers, la saisie du CNI permet de remplir la partie "objet de la demande"
Si Administrateur et autre, la saisie du nom permet de remplir la partie "objet de la demande"
Le changement de type de demandeur réinitialise le formulaire.
https://github.com/GFI-Informatique/addons/commit/27524416fcefbf15f7fd43881779e43bf168130b
