### ISSUE TITLE
Probleme script sql prop_dmatgm

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#135]
https://github.com/GFI-Informatique/cadastrapp/blob/master/script/commun/tables/prop_dmatgm.sql#L10 -> typo copy/paste, devrait etre dmatto ?

Les scripts petent...

```
stderr: psql:/tmp/tmp.58qI69Zd3b/prop_dmatgm.sql:11: ERROR:  multiple primary keys for table "prop_dmatto" are not allowed
```

Il n'y a pas de tests d'intégration sur la création des tables ?

**Comment by omarmancourbillah** [comment]
c'est corrigé effectivement par erreur on crée deux clés primaires pour la table prop_matto.

**Comment by landryb** [comment]
Du coup, je pense que ca serait pas mal d'intégrer la création des tables/vues aux tests de jenkins....
