### ISSUE TITLE
Erreur lors d'impression de la demande

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#138]
Nous avons une erreur lors de l'impression d'une demmande ou de tout autre document : 

java.lang.NoClassDefFoundError: Could not initialize class javax.imageio.ImageIO
    org.apache.xmlgraphics.image.loader.impl.imageio.ImageLoaderFactoryImageIO.getSupportedMIMETypes(ImageLoaderFactoryImageIO.java:39)
    org.apache.xmlgraphics.image.loader.impl.imageio.ImageLoaderFactoryImageIO.isAvailable(ImageLoaderFactoryImageIO.java:54)
    org.apache.xmlgraphics.image.loader.spi.ImageImplRegistry.registerLoaderFactory(ImageImplRegistry.java:186)
    org.apache.xmlgraphics.image.loader.spi.ImageImplRegistry.discoverClasspathImplementations(ImageImplRegistry.java:115)
    org.apache.xmlgraphics.image.loader.spi.ImageImplRegistry.<init>(ImageImplRegistry.java:79)
    org.apache.xmlgraphics.image.loader.spi.ImageImplRegistry.<init>(ImageImplRegistry.java:88)
    org.apache.xmlgraphics.image.loader.spi.ImageImplRegistry.getDefaultInstance(ImageImplRegistry.java:97)
    org.apache.xmlgraphics.image.loader.ImageManager.<init>(ImageManager.java:63)
    org.apache.fop.apps.FopFactory.<init>(FopFactory.java:178)
    org.apache.fop.apps.FopFactory.newInstance(FopFactory.java:190)
    org.georchestra.cadastrapp.service.pdf.RequestPDFController.printPDFRequest(RequestPDFController.java:75)
    sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.lang.reflect.Method.invoke(Method.java:606)
    org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:181)
    org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:97)
    org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:200)
    org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)
    org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
    org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
    org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
    org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
    org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:251)
    org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
    org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
    org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
    org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)
    org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:293)
    org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:217)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:618)
    org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:268)
    org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

Constaté sur https://opendata.agglo-lepuyenvelay.fr/mapfishapp/

**Comment by pierrejego** [comment]
Bonjour,
ça ressemble à une problème de déploiement. Cette classe est normalement dans le rt.jar. Quel version de java est utilisé pour lancer la webapp cadastrapp ?

**Comment by jusabatier** [comment]
La version utilisée est celle de Debian Jessie par default : 

```
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-1~deb8u1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
```

Aussi je n'ai pas de "rt.jar" dans le repertoire WEB-INF/lib de l'application cadastrapp

**Comment by pierrejego** [comment]
Le rt.jar est normalement dans la jre, C'est normal que le jar ne soit pas présent dans le WEB-INF/lib de l'application.
Ta configuration semble bonne.

**Comment by jusabatier** [comment]
Oui j'ai bien le fichier : /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/rt.jar

**Comment by jusabatier** [comment]
Certains posts semblent indiquer que le JDK Oracle a corrigé le problème : http://stackoverflow.com/questions/22475739/could-not-initialize-class-javax-imageio-imageio

Cependant le post date un peu et un commentaire semble dire que ce soucis devait être réglé dans OpenJDK 7u60 mais celui qui est installé sur ma VM est un 7u79 docn normalement il ne devrait plus présenter ce problème...

C'est assez embêtant car je ne peut pas demander aux utilisateurs du service urbanisme de tester l'addon si les impressions ne fonctionnent pas.

**Comment by jusabatier** [comment]
J'ai du mal à comprendre pourquoi, mais ce matin après un redémarrage du Tomcat Mapfish, le problème semble être résolu. J'avais pourtant essayé de le redémarrer plusieurs fois hier sans que le problème disparaisse...

**Comment by pierrejego** [comment]
C'est une bonne nouvelle, même si j'aurais préféré comprendre d'ou venait l'erreur. 
J'étais en train d'installer une debian jessie pour faire le test. Je finalise pour voir si j'ai aussi l'erreur.

**Comment by jusabatier** [comment]
Et après un nouveau redémarrage elle est revenue :(

**Comment by jusabatier** [comment]
Je viens de voir quelle action a fait que ça a marché si ça peut aider : 

J'ai chargé l'addon dans MFapp, sélectionné une parcelle puis essayé d'imprimer le BP => Erreur
Ensuite en gardant ma page ouverte avec le bouton d'impression du BP visible (détail de la parcelle), j'ai redémarré le Tomcat.
Si je clique sur imprimer le BP de la page précédente, ça fonctionne. Je peux alors recharger la page ça fonctionne encore.

En revanche si je redémarre le tomcat, recharge la page MFapp puis essaye d'imprimer le BP alors j'obtiens l'erreur "NoClassDefFoundError: Could not initialize class javax.imageio.ImageIO"

**Comment by jusabatier** [comment]
Je viens de mettre a jour le java installé avec `apt-get dist-upgrade`

```
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-1~deb8u1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
```

Mais le problème reste le même.

**Comment by jusabatier** [comment]
J'ai isolé la webapp cadastrapp dans son propre tomcat (différent de celui de mapfish) et cela semble avoir résolu le problème.

Je pense donc que ce bug est causé par un conflit entre imageio de cadastrapp et de mapfish.

A voir si vous arrivez a reproduire le bug en les mettant tout les deux dans le même tomcat pour confirmer.

**Comment by pierrejego** [comment]
Voir commentaire : https://groups.google.com/forum/#!topic/georchestra-dev/M-OeAr4OXko

Il faut pour l'instant préférer utiliser deux containers différents.

Sur la VM de dev actuellement, j'ai bien mapfishapp 14.06 et cadastrapp qui tourne en même temps, dans un tomcat6 et un jdk1.7 et je ne recontre pas le problème.

**Comment by landryb** [comment]
si il faut isoler cadastrapp dans son propre tomcat, c'est.. moche. Ca serait pas mal d'avoir différentes configs ou 'ca marche/ca marche pas' pour isoler le souci. J'ai vu ce souci en prod et pas sur ma pf de qualif je crois..

**Comment by MaelREBOUX** [comment]
On est en où ?
Ici cadastrapp est bien déployé dans un tomcat séparé et je crois que c'est dorénavant dans les pré-requis.

On ferme @jusabatier @land ?

**Comment by jusabatier** [comment]
Oui ce problème est résolu, je ferme.
