### ISSUE TITLE
Autocompletion

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#139]
Lorsque j'utilise l'autocompletion pour les demmande sur une parcelle, j'ai l'autocompletion google qui passe par dessus celle de l'addon, ce qui m'empêche de selectionner la ville : 

![image](https://cloud.githubusercontent.com/assets/8310116/13218942/454f2e14-d96d-11e5-9f6a-b83ecc5a3032.png)

Est-il possible de corriger ce comportement ?

**Comment by pierrejego** [comment]
Je n'ai pas le même comportement chez moi, il faut que je comprenne d'ou ça vient. Peut être quand changeant l'id du champ pour ne pas être commune et donc que Chrome ne le prenne pas pour un champ à auto-remplir.
Il faut que je reproduise d'abord pour pouvoir trouver une solution, je te tiens au courant

**Comment by jusabatier** [comment]
Je pense que celà vient en effet de l'autocompletion Google car je suis connecté à mon compte Google sur le PC où je fais les tests. 

Il me semble que l'option `autocomplete="false"` dans la balise form en html permet de bloquer cette autocompletion, mais je ne sais pas si c'est adaptable au code utilisé pour le formulaire de cadastrapp.

**Comment by jusabatier** [comment]
Si ça peut aider, la selection de la commune dans la recherche avancée de parcelles ne pose pas de problèmes : 

![image](https://cloud.githubusercontent.com/assets/8310116/13283966/5b5c8226-daf1-11e5-876e-b290bff4867c.png)
