### ISSUE TITLE
Réinitialisation formulaire de demmande

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#140]
Lorsque je clique sur l'icone ![image](https://cloud.githubusercontent.com/assets/8310116/13219042/cc07f1c0-d96d-11e5-918d-73397b7481f7.png) et q'une seule entité est présente, je n'ai plus aucune entité présente, et donc aucun moyen de saisie d'une nouvelle (sauf fermer puis réouvrir la fenêtre).

![image](https://cloud.githubusercontent.com/assets/8310116/13219091/0d13f376-d96e-11e5-9517-a260486a2a2d.png)

![image](https://cloud.githubusercontent.com/assets/8310116/13219100/1921b806-d96e-11e5-955e-f42d1f8950ba.png)

Il serait plus adapté de réinitialiser la ligne si il n'en reste qu'une plutôt que la supprimer.

**Comment by pierrejego** [comment]
Oui effectivement :)
@Gaetanbru
