### ISSUE TITLE
Affichage infobulle

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#141]
L'infobulle sur une parcelle s'affiche même si la barre d'outil n'est pas ouverte, et donc pour un utilisateur ne voulant pas forcement utiliser le cadastre. Serait-il possible de n'afficher ces infobulles uniquement si l'utilisateur a ouvert la barre d'outil ?

**Comment by pierrejego** [comment]
Oui, c'est possible. Normalement l'ensemble des controls du module devrait être desactivé tant qu'on a pas cliqué sur l'outils
