### ISSUE TITLE
Problème ajout fond de carte

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#142]
Je viens de constater que dès qu'on charge un contexte via "Espace de travail" > "Charger une carte", si on ouvre l'addon cadastrapp, il n'ajoute plus le layer "Cadastre 2015" à la carte (layer ajouté par défaut à l'ouverture de cadastrapp).

**Comment by pierrejego** [comment]
Effectivement on voit une erreur javascript, le map.layer de l'addons ne semble plus à jour. Je regarde in doit y avoir un refresh à faire dans le code de l'addon.
