### ISSUE TITLE
Génération du document PDF

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#143]
Lorsque j'effectue une demande d'informations foncières, je clique sur "Imprimer la demande" et une barre de chargement apparaît : "Génération du document pdf". Le document est alors téléchargé sur mon PC mais la barre de chargement reste affichée.

![image](https://cloud.githubusercontent.com/assets/8310116/13282975/da84930a-daeb-11e5-9d83-c0ac8b30b299.png)

**Comment by pierrejego** [comment]
On ne reproduit pas sur notre serveur, on va essayer sur l'opendata. Y a t'il une trace d'erreur dans la console ou dans les logs mapfishapp ?

**Comment by jusabatier** [comment]
Non pas de trace d'erreur au niveau des logs de l'appli java.

J'ai juste constaté des logs (level info) dans la console javascript de chrome, mais pas des erreurs.

**Comment by jusabatier** [comment]
Je pense que c'est à cause de l'event "load" qui n'est pas géré par chrome lorsqu'un fichier est mis en attachement d'une iframe : 

http://stackoverflow.com/questions/20572734/load-event-not-firing-when-iframe-is-loaded-in-chrome

**Comment by pierrejego** [comment]
Oui c’est que Gaetan a vu, il chercher la meilleur façon de le rendre compatible pour tout navigateur.

Merci pour la recherche

—
Pierre Jégo
Tél. : +33 (0)2 96 48 25 63

De : Julien Sabatier [mailto:notifications@github.com]
Envoyé : mercredi 24 février 2016 16:54
À : GFI-Informatique/cadastrapp cadastrapp@noreply.github.com
Cc : Jego Pierre pierre.jego@gfi.fr
Objet : Re: [cadastrapp] Génération du document PDF (#143)

Je pense que c'est à cause de l'event "load" qui n'est pas géré par chrome lorsqu'un fichier est mis en attachement d'une iframe :

http://stackoverflow.com/questions/20572734/load-event-not-firing-when-iframe-is-loaded-in-chrome

**Comment by Gaetanbrl** [comment]
L'iframe qui permettait de générer le document à été remplacée par une requête Ajax. On peut récupérer l'URL de la requête retournée et ouvrir ou sauvegarder le PDF en saisissant cette URL dans une nouvelle fenêtre / onglet du navigateur. Nous travaillons maintenant sur la récupération automatique du PDF avec toujours la possibilité d'ouvrir ou sauvegarder directement.

**Comment by pierrejego** [comment]
L'erreur vient bien du onload non géré pour IE et Chrome 
http://stackoverflow.com/questions/12076494/onload-in-iframes-not-working-if-iframe-have-non-html-document-in-src-pdf-or-t

On vient de faire des modifications qui gardent le comportement actuel pour Firefox (qui marche) et supprime la fenêtre avant la fin du chargement pour les autres navigateurs.

on va aussi rajouter des GEOR.waiter dans le reste de l'application sur les requêtes pour éviter que les utilisateurs cliquent plusieurs fois en attendant une réponse qui pourrait être longue

**Comment by pierrejego** [comment]
https://github.com/GFI-Informatique/addons/commit/177f4284842b3f2453d0bd90192c82578711e79a
