### ISSUE TITLE
Anonyme / Bouton Generer les documents

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#144]
En étant non connecté (anonyme), si je vais dans "Demande Informations Foncières",

Si je sélectionne une parcelle (ou autre) et que je clique sur "Imprimer la demande", le bouton "Generer les documents" se dégrise. Si je clique dessus j'ai la barre de chargement mais aucun document n'est téléchargé et il se regrise.

Est-il possible que pour un utilisateur anonyme, ou ne faisant partie d'aucun des groupes CNIL1 ou CNIL2, ce bouton soit toujours grisé, voir même non affiché ?

Car un visiteur en voyant le comportement actuel pourrait penser à un bug.

![image](https://cloud.githubusercontent.com/assets/8310116/13313827/2e6409e6-dba1-11e5-9739-d1b112168aba.png)

**Comment by Gaetanbrl** [comment]
Bonjour,
Un utilisateur non CNIL1 ou CNIL2 peut tout de même générer un bordereau parcellaire sur une parcelle  sans données nominatives, faut-il conserver cette possibilité ?

**Comment by Gaetanbrl** [comment]
Un contrôle sur le groupe d'appartenance de l'utilisateur permet maintenant de griser / dégriser la checkBox de relevé de propriété. L'utilisateur anonyme peut donc générer uniquement le bordereau parcellaire, si il est anonyme.

**Comment by jusabatier** [comment]
Un utilisateur anonyme peut en effet imprimer un bordereau parcellaire sans les données nominatives, cependant pour cela il n'a pas besoin d'imprimer de demande et devrait donc passer par la recherche de parcelle et non par la demande d'informations.

En revanche, un anonyme doit pouvoir imprimer une demande contenant le relevé de propriété (uniquement la demande).

Donc il ne faut pas griser la checkbox de relevé de propriété, uniquement griser le bouton "Imprimer les documents ou même ne pas l'afficher aux utilisateurs anonymes si possible. Si ceux-cis souhaitent imprimer une BP, il peuvent passer par le recherche et fiche d'info de parcelle.

Deplus la modification grisant la checkbox a introduit un bug d'impression des documents : 

Uncaught TypeError: Cannot read property 'checked' of undefined

**Comment by Gaetanbrl** [comment]
Les checkbox sont donc disponibles même en anonymes et le boutons "Générer les documents" reste désactivé pour les utilisateurs anonymes.
Pour le TypeError, c'est une propriété qui était mal configurée dans le code.
