### ISSUE TITLE
Limitation Géographique

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#145]
J'ai voulu tester la limitation d'accès aux données propriétaires par commune de l'addon.

J'ai donc ajouté les liens groupe/code commune dans la table groupe_autorisation : 

![image](https://cloud.githubusercontent.com/assets/8310116/13316969/019d02f2-dbb3-11e5-9f77-dac906a06e87.png)

J'ai ensuite ajouté l'utilisateur aux groupes CADASTRE_PROP_AIGUILHE et CNIL2 puis me suis reconnecté afin que les nouveaux groupes soient pris en compte.

Cependant cet utilisateur a toujours accès aux données propriétaire des autres communes : 

![image](https://cloud.githubusercontent.com/assets/8310116/13317004/3b6b3274-dbb3-11e5-837b-b7b4ba3c96f5.png)

![image](https://cloud.githubusercontent.com/assets/8310116/13317012/457474c4-dbb3-11e5-86f8-a0db7d365523.png)

La fonction de limitation par commune ne semble donc pas fonctionner, ou alors je n'ai pas saisi comment la parametrer.

**Comment by pierrejego** [comment]
Bonjour,
je viens de refaire les tests sur nos serveurs je n'ai pas le même comportement. Le filtre fonctionne bien chez moi.

Ce que tu me montres semble bon. 
Est-ce qu'on peut refaire la manipulation ensemble par téléphone ?

**Comment by jusabatier** [comment]
Oui bien sur, appelle moi quand tu as le temps.

**Comment by pierrejego** [comment]
Après test on voit dans les logs que les users du sec-roles sont séparés par des ; et non des ,
;ROLE_PERM_CAD_CNIL2 -o.g.cadastrapp.service.CadController - user roleList : ROLE_MOD_LDAPADMIN;ROLE_SV_USER;ROLE_CADASTRE_PROP_AIGUILHE;ROLE_PERM_CAD_CNIL2

ROLE_MOD_LDAPADMIN;ROLE_SV_USER;ROLE_CADASTRE_PROP_AIGUILHE;ROLE_PERM_CAD_CNIL2
au lieu de 
ROLE_MOD_LDAPADMIN,ROLE_SV_USER,ROLE_CADASTRE_PROP_AIGUILHE,ROLE_PERM_CAD_CNIL2

Dans les versions déployé chez GFI nous avons des , mais on voit dans https://github.com/georchestra/georchestra/blob/15.12/security-proxy/src/main/java/org/georchestra/security/SecurityRequestHeaderProvider.java que c'est des ;.

Je vous propose de rendre le séparateur paramétrable via le cadastrapp.properties, mais je voudrais savoir quelle est la cible. , ou ;

**Comment by jusabatier** [comment]
Apparemment c'est le ";" qui est utilisé comme séparateur depuis 15.06

**Comment by landryb** [comment]
Oui depuis 15.06, cf https://github.com/georchestra/georchestra/issues/920. Donc par défaut avoir le ; comme séparateur, non ? @pierrejego bonne analyse du problème en tout cas :)

**Comment by jusabatier** [comment]
Je viens de redeployer avec la dernière version, et j'ai mis le separateur à ;

J'obtiens à présent une erreur 500 sur : 

https://opendata.agglo-lepuyenvelay.fr/cadastrapp/services/getInfoBulle?parcelle=2015430002000AB0638&infouf=0&_dc=1456830962353

```
cause mère

java.lang.NullPointerException
    org.georchestra.cadastrapp.service.CadController.addAuthorizationFiltering(CadController.java:155)
    org.georchestra.cadastrapp.service.InfoBulleController.getInfoBulleParcelle(InfoBulleController.java:111)
    org.georchestra.cadastrapp.service.InfoBulleController.getInfoBulle(InfoBulleController.java:52)
    sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.lang.reflect.Method.invoke(Method.java:606)
    org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:181)
    org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:97)
    org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:200)
    org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)
    org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
    org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
    org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
    org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
    org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:251)
    org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
    org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
    org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
    org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)
    org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:293)
    org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:217)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:618)
    org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:268)
    org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

```

**Comment by jusabatier** [comment]
Je pense qu'il manque un `this.roleSeparator = CadastrappPlaceHolder.getProperty("roleSeparator");` dans le constructeur de CadController afin de charger la valeur.

Edit : En effet l'ajout de cette ligne dans le constructeur corrige le problème. Je vous laisse le corriger, après ça la limitation géographique fonctionne bien.

**Comment by pierrejego** [comment]
Oui pardon, je voulais tester ce matin sur la qualification et j'ai oublié...
Je viens de faire la modification et de tester avec des , cette fois c'est bon :)

https://github.com/GFI-Informatique/cadastrapp/commit/ab31b7176b3a3a000a161d098c6c6960649fda1b

**Comment by landryb** [comment]
Peux tu passer par défaut (dans le code et dans la config) a ; plutot que , ? J'imagine que peu de personnes vont déployer sur du 14.12...
