### ISSUE TITLE
[UI] Accumulation des fenêtres / trop de fenêtres masquent la carte

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#146]
Bonjour,

Certains de nos utilisateurs se sont plains du nombre de fenêtres important qui s'ouvrait simultanément lors de l'utilisation de l'addon. Il nous a donc été demandé que lorsqu'une fenêtre s'ouvre, la précédente se ferme et que par l'intermédiaire d'un bouton, on puisse revenir en arrière à la fenêtre précédente si besoin. 

J'aurais voulu savoir si cela était faisable, ou si le cas échéant il était tout de même possible d'améliorer ce comportement ?

**Comment by landryb** [comment]
Il va falloir préciser lesquelles fenetres.. et a mon avis c'est un peu tard pour ce genre de modifications de comportement/interface. @MaelREBOUX ?

**Comment by jusabatier** [comment]
C'est notamment concernant les recherches de parcelles, affichage de la liste et affichage de la fiche d'info de la parcelle. J'aurais voulu savoir si cela était faisable, si c'est trop tard pour faire cette révision nous pourrons faire une demande de prestation.

**Comment by jusabatier** [comment]
En ajoutant très peu de code, j'ai réussi a faire fermer la fenêtre recherche avant d'afficher les résultats lorsqu'on appuie sur "Rechercher". Cela permet déjà de réduire un peu le nombre de fenêtres ouvertes.

Est-ce que cela vous parait intéressant ?  Si oui je ferais la PR, mais je voudrais savoir si personne n'y voit d’inconvénients ?

**Comment by MaelREBOUX** [comment]
C'est un peu compliqué de répondre.
Perso au début j'ai également trouvé qu'il y avait bcp de fenêtres ouvertes. Mais à l'usage, j'ai compris comment en tirer parti.
Mais je comprend que pour un usage très "guichet" ou "simple" c'est trop. Mais ce n'est pas trop quand on est en mode de recherche sur un territoire ou un ensemble de proprios.

Je suis plutôt défavorable à modifier le comportement actuel. La liste de résultats et ses onglets est en effet un des gros plus par rapport à nos outils existants. Et ça répond aux spécifications demandées.
Je note cependant ce point pour l'évaluation auprès de mes utilisateurs. Je propose donc de laisser comme ça et de réévaluer fin 2016.

**Comment by MaelREBOUX** [comment]
Nos utilisateurs ont également remonté qu'il y a trop de fenêtres et que ça masque toute la carte.
Ce qui est réellement le cas sur les écrans en 1280 x 1024. Je ne compte pas pour des écrans <.

Ma proposition ergonomique pour ne pas tout remettre en question est de mettre en place une minification des fenêtre comme le faisait Mac OS 9. A savoir double-clic sur la barre du haut de la fenêtre (ou icone image) pour ne laisser visible que cette barre avec le titre de la fenêtre.

L'utilisateur se retrouverait ainsi avec qqs barres horizontales à se balader à la place de fenêtres entières pleines de contenus dont il n'a pas besoin dans l'instant.

**Comment by jusabatier** [comment]
Cette issue peut être fermée je pense car implémentée en 1.4

**Comment by MaelREBOUX** [comment]
yes
