### ISSUE TITLE
Limitation Géographique et recherche

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#147]
J'ai constaté que pour un utilisateur sur lequel est appliqué une limitation géographique par commune, si je veux faire une recherche de parcelle (par propriétaire, référence ou adresse), alors la liste déroulante de communes ne permet d'avoir que la/les communes qui lui sont autorisées. Cependant n'importe quel utilisateur devrait pouvoir effectuer une recherche de parcelle sur toutes les communes, les limitations géographiques ne devraient affecter que l'accès aux informations nominatives.

**Comment by landryb** [comment]
Cf discussion dans https://github.com/GFI-Informatique/cadastrapp/issues/112 et user.search.are.filtered dans cadastrapp.properties.
