### ISSUE TITLE
Nom marital/naissance

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#151]
Des utilisateurs m'ont fait remarquer que la recherche de propriétaire par nom ne faisait remonter les propriétaires que par leur nom de naissance. Est-il possible d'étendre cette recherche également au nom marital ?

**Comment by pierrejego** [comment]
Oui normalement, le rechercher doit être faite sur la dénomination et non uniquement sur le nom de naissance.
Je vérifie le comportement pour voir ce qui a été modifié. 

voir #41 et #46

**Comment by pierrejego** [comment]
C'est bien le champ ddenom qui est utilisé pour faire la recherche de personne.
Par contre il y a un autre paramètre possible pour le getProprietaire, on pourrait utiliser le globalname qui correspond à une recherche un peu plus complexe, dans le dnomlp dprnlp, le dnomcp dprncp et le ddenom.
Je peux changer dans les fenêtres si vous préferez ce comportement, mais les requêtes risque d'être un tout petit peu plus longue (surtout sur les grosses communes) et il faudra revoir le tri d'affichage.

On en parle Lundi pendant la visio pour prendre une decision

**Comment by pierrejego** [comment]
Exemple de résultat, en cas d'utilisation du globalname et non du ddenom.

![image](https://cloud.githubusercontent.com/assets/11499415/13912985/cb48a582-ef42-11e5-95c7-782b90e4b6cc.png)

Il faut voir comment trier, et voir si c'est bien ça que vous voulez

**Comment by MaelREBOUX** [comment]
Si on retient cette évolution, je préconise qu'elle soit portée par une case à cocher optionnelle sur l'interface. Ainsi l'utilisateur sait qu'il étend la recherche. On peut le prévenir de l'impact sur temps de réponse dans la tooltip.

@pierrejego c'est où / quoi globalname ?

**Comment by pierrejego** [comment]
globalname c'est un paramètre qui peut être utilisé dans le service REST getProprietaire. Actuellement on utilise le paramètre ddenom.
Comme indiqué, le paramètre globalname fait une recherche sur l'ensemble des champs, dnomlp dprnlp,dnomcp dprncp et  ddenom. Il y a donc beaucoup plus de résultats reçus. Et surtout c'est un contains, donc les champs ne commence pas les caractères entrés dans la combobox

**Comment by jusabatier** [comment]
Je viens d'envoyer un screen sur la mailing list, et j'ai vérifié sur un autre propriétaire le comportement est le même.

Dans la fiche d'info, onglet bâtiment, on retrouve le nom et prénom de naissance dans "Dénomination", champ sur lequel semble actuellement porter la recherche. 

L'ajout à faire serait d'étendre l'interrogation  à  "Dénomination"+"Nom" de l'onglet bâtiment.

Le champ globalname dont tu parle me semble comporter bien plus d'attributs non ?

Ainsi il serait possible de retrouver un propriétaire par son nom marital, qui me semble-t-il est (le plus?) souvent utilisé.

**Comment by MaelREBOUX** [comment]
Bon : on a expertisé et on revient avec une GROSSE info.

Pour le millésime 2015 des fichiers Majic 3, il y a eu une évolution qui touche justement à cette notion de « nom d’usage ».
Si vous regardez dans le fichier PDF PROP_15.pdf qui décrit le fichier Majic 3 dédié aux informations sur les propriétaires, la version en date du 08/04/2015 contient en page 20 et en gras 2 nouveaux attributs :

![screenshot051](https://cloud.githubusercontent.com/assets/6370443/13949953/64434572-f028-11e5-8e50-4ef1b25e0be4.png)

 Lors de notre analyse poussée des modèles livrée en novembre 2014 nous sommes logiquement passé à côté car cette modification est intervenue en juin 2015.

En conséquence il va falloir remonter cette info à la communauté QGIS / vérifier que le plugin QGIS intègre ou pas cette évolution.
De notre côté arcOpole RM, les collègues ont prévu de regarder comment les récupérer pour le traitement de juin-juillet 2016.

Donc, nous proposons les choses suivantes :
-   Que GFi fasse le développement sur l’add-on consistant à rajouter une case à cocher qui « permute » la recherche sur le nom d’usage. Le tooltip indiquera « Rechercher dans le nom d’usage au lieu du nom standard. ».
-   Au niveau des données, GFi modifie dès maintenant les vues / la vue proprio afin de rajouter virtuellement les 2 attributs « DNOMUS » et « DPRNUS » et en remplissant ces 2 attributs avec les attributs existants « DNOMLP » et « DPRNCP »
-   Ultérieurement, une fois assurés que ces nouveaux attributs remontent nativement en base après les évolutions des moulinettes, « on » fera modifier le script créant les vues (mettre dès maintenant un ticket spécifique pour ne pas oublier).

Extrait ci-dessous du fichier Majic 3 juin 2015 : cas hyper classique de 2 personnes mariées :

```
DDENOM                        |  DQUALP |  DNOMLP |  DPRNLP         |  EXPNEE |  DNOMCP  | DPRNCP          |  DNOMUS   | DPRNUS 
THIRE/STEPHANE ANDRE          |  M      |  THIRE  |  STEPHANE ANDRE |         |          |                 |  THIRE    | STEPHANE
JEULAND/REGINE COLETTE MARIE  |  MME    |  THIRE  |  STEPHANE       |  NEE    |  JEULAND | REGINE COLETTE  |  THIRE    | REGINE
```

**Comment by MaelREBOUX** [comment]
Et pour info, dans la base RM :

![screenshot049](https://cloud.githubusercontent.com/assets/6370443/13949980/93408eca-f028-11e5-815f-57a321224759.png)

**Comment by pierrejego** [comment]
Regarder avec @landryb ce qui est le mieux à faire pour Dnomus et DPRNUS

**Comment by pierrejego** [comment]
Partie serveur de la modification, https://github.com/GFI-Informatique/addons/commit/15c8cbbbc8a9a6a17d2c1993e438cd2eb5d9ae0a

**Comment by pierrejego** [comment]
Vu avec landry, augmenter les tailles des champs dnomlp et dprnlp pour prendre en compte la nouvelle taille dnomus 60, dprnus 40

Prévoir de différencier le script en fonction de la date des données majic (prendre la valeur "années" des tables communes)

**Comment by landryb** [comment]
Le modèle QGIS sait déja gérer les champs DNOMUS/DPRNUS (cf https://github.com/3liz/QgisCadastrePlugin/search?q=dnomus) - restera a ouvrir un autre ticket pour prendre ca en compte pour l'import et le SQL faisant la requete en fonction du millésime.

Je ferme ce ticket qui concernait uniquement la case à cocher pour faire la requete sur le nom marital - et qui a été résolu.

**Comment by landryb** [comment]
Pour info, dans les fichiers majic 2016, il y'a ce changement pour PROP:

```
'Mise à blanc des champs EPXNEE, DNOMCP et DPRNCP (position 403, 3, 30 et 15 caractères).'
```

**Comment by landryb** [comment]
Tant qu'a faire je copie toute la section:

```
2.12.
Nom et prénom d’usage
La dénomination des personnes physiques est présentée sous différentes formes dans le fichier des
propriétaires :
- DDENOM (position 57, 60 caractères) : dénomination de la personne physique structurée sous la
forme : « nom/prénoms ».
- DNOMLP (position 290, 30 caractères) et PRNLP (position 320, 15 caractères) : nom et prénom
d’usage tel qu’ils étaient indiqués auparavant sur les avis de taxe foncière. Pour les hommes, le nom
et prénom d’usage correspond aux nom et prénoms patronymiques, pour les femmes il peut s’agir
soit des nom et prénoms patronymiques, soit du nom et prénom maritaux.
- DNOMUS (position 538, 60 caractères) et DPRNUS (position 598, 40 caractères) : nom et prénoms
utilisés dans les correspondances des autorités administratives adressées aux usagers, tels que
définis par la loi n° 2000-321 du 12 avril 2000 relative aux droits des citoyens dans leurs relations
avec les administrations, modifiée par la loi n° 2014-873 du 4 août 2014 pour l’égalité réelle entre les
femmes et les hommes.
Il est, par conséquent, préconisé d’utiliser soit le champ DDENOM, soit les champs DNOMUS et
DPRNUS pour la dénomination des personnes physiques.
```

Et les champs EPXNEE/DNOMCP/DPRNCP n'apparaissent plus dans le modèle..
