### ISSUE TITLE
Recherche avancée / par co-propriété

### ISSUE THREAD

**Issue by stous** [georchestra/cadastrapp#152]
Je  saisie la commune (350238), je saisie le nom (durand par exemple),  puis dans la liste déroulante je choisi le bon durand, mais la liste ne disparait pas une fois le nom sélectionné il faut cliquer ailleurs pour fermer cette liste.

**Comment by pierrejego** [comment]
Je reproduis bien, mais je ne comprend pas d'ou vient ce comportement pour l'instant. 
Les paramètres utilisées pour cette combobox semblent être les mêmes que pour les autres. 
Il y a juste l'utilsation du validor en plus, mais même en l'enlevant j'ai le même comportement.

**Comment by jusabatier** [comment]
L'erreur ici vient des validateurs des champs "cadastrappCoProprieteSearchDdenomcombo" et "cadastrappCoProprieteSearchTexfieldParcelle" qui s'appellent l'un l'autre : 

Le champ nom essaye de se valider en passant par le validateur du champ id_parcelle et id_parcelle essaye de se valider par celui de nom, ce qui provoque une boucle d'appel infini de leurs validateurs et plante le js, d'ou l'erreur : 

Uncaught RangeError: Maximum call stack size exceeded

Qu'on voit apparaitre dans la console developpeur.

Le soucis est ligne 134, 175 et 200 dans searchCoPropriete.js

**Comment by pierrejego** [comment]
Merci julien

**Comment by MaelREBOUX** [comment]
Je ne reproduis pas ou plus.
Peut-on fermer ce ticket ?

**Comment by jusabatier** [comment]
Non, le problème est toujours présent, pour le constater il suffit d'aller dans : Recherche avancée > Lots de copropriété, ensuite saisir une commune et lorsqu'on essaye de sélectionner un propriétaire dans la liste déroulante, celle-ci ne se ferme pas.

Le bug est encore présent sur une version master de l'addon compilée ce matin.

**Comment by MaelREBOUX** [comment]
ha pardon : je croyais que c'était sur les propriétaires. Je reproduis bien.

**Comment by MaelREBOUX** [comment]
ok
