### ISSUE TITLE
Ajout mentions financeurs dans le READ ME

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#154]
pour ne pas oublier...
poster les logos ici.

**Comment by jpklipfel** [comment]
![logo_cd67_pour-fond-couleur](https://cloud.githubusercontent.com/assets/5012040/13945329/ac9a6786-f00c-11e5-8acc-b21705db585b.png)

**Comment by MaelREBOUX** [comment]
![c-rm7](https://cloud.githubusercontent.com/assets/6370443/13951133/407ee162-f02f-11e5-8c70-a7b6cff7ba43.jpg)

**Comment by pierrejego** [comment]
@landryb est-ce que tu peux me donner la liste des financeurs ?
Dans le CCTP, j'ai : 
Union Européenne en Auvergne
Rennes Métropole
Aménagement du territoire et gestion des risques
Conseil Général du base-rhin. 

![image](https://cloud.githubusercontent.com/assets/11499415/14112270/5027ca6c-f5ce-11e5-9195-59343e2332bb.png)

![image](https://cloud.githubusercontent.com/assets/11499415/14112274/53ee8cda-f5ce-11e5-8eac-085af511a9f0.png)
.
J'ai bon ?

**Comment by jpklipfel** [comment]
~~Conseil Général du base-rhin.~~
Conseil Départemental du Bas-Rhin

**Comment by pierrejego** [comment]
Oups pardon :)

**Comment by landryb** [comment]
![craig_1300x1403](https://cloud.githubusercontent.com/assets/3421760/14113316/bf38b2e6-f5d2-11e5-87c5-754f776a5962.jpg)

![logo leurope-sengage feder-quadri](https://cloud.githubusercontent.com/assets/3421760/14113246/5e8bdf2c-f5d2-11e5-86a1-638b191194d3.png)

Les logos pour le FEDER ont changé avec les nouvelles region...

**Comment by pierrejego** [comment]
![image_gallery](https://cloud.githubusercontent.com/assets/11499415/14116676/41fbce6c-f5e1-11e5-8863-2b1f4cd19034.jpg)

**Comment by landryb** [comment]
@pierrejego tu peux 'retailler' un peu les logos pour éviter d'avoir d'énormes patés sur le README.md - et ajouter celui du CRAIG ? Aussi, par défaut sur github sur le repo addons on tombe sur la branche 'dev', ca devrait plutot etre la branche 'master'....

**Comment by pierrejego** [comment]
Ah pardon pour le CRAIG :) Je fais les modifications en début d'après midi.

**Comment by pierrejego** [comment]
Est-ce qu'il est possible de rajouter aussi l'agglomération du puy en velay ? Ils ont financé des évolutions  ?

**Comment by pierrejego** [comment]
vu avec @landryb demander les images du puy en velay
