### ISSUE TITLE
Nature de la parcelle ne remonte pas

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#156]
Contexte : Fiche d'info de la parcelle AM 310 à Saint Germain Laprade

Dans l'onglet subdivision fiscale, la "Nature de la culture" n'est pas renseignée,
en revanche elle apparaît dans le relevé de propriété. (c'est PIN pour cette parcelle)

**Comment by pierrejego** [comment]
Bonjour,
je n'ai pas accès à cette commune sur l'opendata de l'agglo.
Tu peux m'envoyer une capture d'écran pour que je détermine ou c'est dans le code.

Merci

**Comment by pierrejego** [comment]
Je viens de faire les modifications, j'essayais d'afficher un libellé côté client alors que j'ai uniquement le code côté serveur. 
A terme ont pourrait rajouter une table de correlation cgrnum cgrnum_lib pour afficher le libellé de la nature de le culture plutôt que le code.

**Comment by pierrejego** [comment]
@jusabatier je te laisse fermer l'issue quand tu auras pu tester

**Comment by jusabatier** [comment]
Ce qui est bizarre, c'est que sur le RP c'est bien le libelle et non le code qui est affiché. Est-il possible de garder le même affichage (libellé) car je ne sais pas si un code sera bien parlant pour les services concernés.

Sinon déjà après mise à jour, je vois bien un code numérique s'afficher dans "nature de la culture".

**Comment by pierrejego** [comment]
Tu peux m'envoyé le RP, car je vois rien du tout dans le code qui permettrait d'avoir le libellé, je ne vois pas la table de correlation entre cgrnum et cgrnum_lib

**Comment by MaelREBOUX** [comment]
@jusabatier peut-on fermer ?

**Comment by jusabatier** [comment]
Oui, je viens de tester et c'est OK
