### ISSUE TITLE
Problème changement de page sur liste des copropriétaires

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#159]
Sur la parcelle AW 106 du Puy-en-Velay, dans l'onglet "Co-propriétaires" de la fiche d'infos de la parcelle, j'ai deux pages de co-propriétaires.
Si je clique sur la flèche pour accéder à la seconde page, j'ai un message erreur 405 : 
![image](https://cloud.githubusercontent.com/assets/8310116/14280264/1820060c-fb32-11e5-8e0c-406a91713a0f.png)

En revanche tous les co-propriétaires semblent bien apparaitre sur la première page : 
![image](https://cloud.githubusercontent.com/assets/8310116/14280297/494f9fb2-fb32-11e5-9d2f-4dc996081030.png)

1 à 40 sur 40

**Comment by MaelREBOUX** [comment]
J'ai la même chose ici : la pagination ne fonctionne pas : erreur 405 method not allowed.

```
/cadastrapp/services/getCoProprietaire?parcelle=350066000AI0413
```

On dirait que les paramètres passés en POST ne sont pas acceptés.
Pourquoi ne pas avoir mis ces paramètres en GET dans l'url ?

```
start=25&limit=25
```

**Comment by MaelREBOUX** [comment]
Bogue toujours présent.

**Comment by MaelREBOUX** [comment]
Je rouvre : j'ai pas testé ;)

**Comment by MaelREBOUX** [comment]
testé et approuvé
