### ISSUE TITLE
Libellé surface DGFiP en m2 erroné dans la fenêtre de résultat de parcelle

### ISSUE THREAD

**Issue by sdhem** [georchestra/cadastrapp#16]
Dans la fenêtre des résultats de parcelle, le libellé de la colonne de dcntpa est erroné.

**Comment by laurentcornic** [comment]
Le libellé a été modifié et remplacé par "Surface DGFiP en m2"

**Comment by sdhem** [comment]
Pour l'unité des surfaces le "2" doit être un exposant.

**Comment by laurentcornic** [comment]
libellés modifiés

**Comment by sdhem** [comment]
Vérifier sur plateforme de dev=> OK=> Closed
