### ISSUE TITLE
[Demande infos] Oubli recherche par nom de naissance

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#160]
Concernant cette issue : https://github.com/GFI-Informatique/cadastrapp/issues/151

J'ai constaté ce matin lors de notre demo au service urba, que sur le formulaire "Demande informations foncières", la checkbox pour ajouter le nom marital n'était pas présente lors de la recherche d'un propriétaire : 

![image](https://cloud.githubusercontent.com/assets/8310116/14280384/cd5721cc-fb32-11e5-96a0-3906492b47a8.png)

**Comment by landryb** [comment]
A ma connaissance lorsque #151 a été corrigé (commit coté addon js https://github.com/GFI-Informatique/addons/commit/15c8cbbbc8a9a6a17d2c1993e438cd2eb5d9ae0a) , la checkbox n'a été ajoutée que dans la fenetre de recherche de propriétaire simple, pas dans la fenetre de demande d'info foncière.

**Comment by jusabatier** [comment]
Oui je sais, mais est-ce un oubli, ou était-ce volontaire ?

Logiquement on a tout autant besoin du nom marital dans ce formulaire, mais je comprends que ça pourrait encore l'encombrer un peu plus.

**Comment by MaelREBOUX** [comment]
je confirme que la demande n'a porté que sur le formulaire de recherche spécialisé proprio. Oubli collectif de reporter également sur la demande guichet afin de rester cohérent.

**Comment by pierrejego** [comment]
OK, mais ou rajouter la checkbox pour pas faire d'incompréhension avec l'édition des fichiers ?

**Comment by jusabatier** [comment]
C'est ce que je me demmandait, car il y a déjà pas mal de checkbox.

Peut-être aligner celles pour les fichiers à gauche, et celle pour le propriétaire à droite sous la combo propriétaire, ou utiliser un séparateur en tre les deux groupes.

![image](https://cloud.githubusercontent.com/assets/8310116/14420552/0277bc4c-ffcd-11e5-9e4d-61a7cd8171cf.png)

**Comment by pierrejego** [comment]
J'ai rajouté une nouvelle entrée dans la combobox "Proprio nom de naissance"
![image](https://user-images.githubusercontent.com/11499415/36078398-d2edfb16-0f75-11e8-99f3-457372a5bcf3.png)
mais ça dépasse encore.
Il faut voir pour changer le nom dans le manifest pour que ça rentre. Clé à changer cadastrapp.demandeinformation.object.type.7

**Comment by pierrejego** [comment]
Les modifications ont été faites dans ce commit 
https://github.com/georchestra/cadastrapp/commit/9eefee519f9137cd73a8c674209adb825cc797f8

**Comment by MaelREBOUX** [comment]
Au niveau IHM c'est OK : on a une entrée en plus dans le type de demande, comme convenu.

![screenshot189](https://user-images.githubusercontent.com/6370443/36197298-ae9ee342-1173-11e8-8677-e4414bff3b9a.png)

Par contre, au niveau du document de demande : **c'est pas raccord on n'a que la demande par nom d'usage du proprio**. Il faut la demande par nom de naissance.
Je suppose qu'il y a une "réduction" faite sur le compte proprio.  C'est compliqué à faire ?

![screenshot190](https://user-images.githubusercontent.com/6370443/36197361-d5676454-1173-11e8-9aa4-14c9b882d060.png)

Côté PDF obtenu, j'ai juste (et c'est normal) un PDF de 2 pages avec le BP et le RP.

**Comment by pierrejego** [comment]
Oui effectivement le nom est retranscrit en compte communal, il faudrait rajouter une nouvelle entrée dans la base pour stocker le fait qu'on utilise le nom d'usage

**Comment by MaelREBOUX** [comment]
Testé ce jour. Le document contient toujours le nom d'usage et pas le nom de naissance.

**Comment by MaelREBOUX** [comment]
On reporte dans #394
