### ISSUE TITLE
[Installation Base cadastrapp]

### ISSUE THREAD

**Issue by catmorales** [georchestra/cadastrapp#162]
Bonjour,
je suis en train de paramétrer la base cadastrapp sur notre PF de test , l'addon et la webapp sont installés mais j'ai un problème lors des recherches qui semble  relatif au paramétrage des droits dans groupe_autorisation . 
Nous n'avons pas de limitation sur l'emprise du département chez nous et donc pas de groupe EL_DEP . 
Par contre j'ai configuré:
- l'accès aux communes:`

```
INSERT INTO cadastrapp_arcopole.groupe_autorisation (idgroup, cgocommune) VALUES ('ROLE_EL_COMM_ACIGNE', '350001');
```
- et l'accès aux services de l'agglo:

```
INSERT INTO cadastrapp_arcopole.groupe_autorisation (idgroup, cgocommune) VALUES ('ROLE_EL_RM', '350001');
INSERT INTO cadastrapp_arcopole.groupe_autorisation (idgroup, cgocommune) VALUES ('ROLE_EL_RM', '350022');
INSERT INTO cadastrapp_arcopole.groupe_autorisation (idgroup, cgocommune) VALUES ('ROLE_EL_RM', '350024');
INSERT INTO cadastrapp_arcopole.groupe_autorisation (idgroup, cgocommune) VALUES ('ROLE_EL_RM', '350032');
INSERT INTO cadastrapp_arcopole.groupe_autorisation (idgroup, cgocommune) VALUES ('ROLE_EL_RM', '350039');
INSERT INTO cadastrapp_arcopole.groupe_autorisation (idgroup, cgocommune) VALUES ('ROLE_EL_RM', '350047');
```

Ma question:
Doit-on également remplir le champ ccodep pour chaque enregistrement ?

**Comment by jusabatier** [comment]
Non, dans le cas d'une limite sur commune, ccodep reste vide

**Comment by catmorales** [comment]
ok merci
