### ISSUE TITLE
Batiment ne remonte pas toujours

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#163]
Nos utilisateurs viennent de nous signaler que sur certaines parcelles baties, les batiments ne remontaient pas dans l'onglet "Batiments" de la fiche d'info.

Une parcelle où ce problème a été constaté est la AY 45 sur Le Puy-en-Velay : 

![image](https://cloud.githubusercontent.com/assets/8310116/14322093/ef2fbb9e-fc1b-11e5-8602-761ecd1f1c3b.png)

![image](https://cloud.githubusercontent.com/assets/8310116/14322114/ffa54bf6-fc1b-11e5-8ec8-b2cacc26e44d.png)

Il n'y a aucun batiments, que l'on clique sur le 01 ou le A

**Comment by jusabatier** [comment]
Je viens de tester un peu la requête qui récupère la liste des bâtiments sur cette parcelle (cf. https://github.com/GFI-Informatique/cadastrapp/blob/master/cadastrapp/src/main/java/org/georchestra/cadastrapp/service/BatimentController.java).

Tel quel, elle ne renvoie rien sur la parcelle concernée. En regardant un peu, j'ai vu que la vue **proprietebatie** créé pour cadastrapp contient un champ parcelle. Je ne voit donc pas l'utilité de la table **proprietaire_parcelle** dans la requête.

En modifiant la requête ainsi, elle fonctionne sur cette parcelle également : 

```
SELECT distinct hab.annee, pb.jannat, pb.invar, pb.descr, pb.dniv, pb.dpor, hab.ccoaff_lib, prop.comptecommunal, prop.dnupro, prop.ddenom, prop.dnomlp, prop.dprnlp, prop.epxnee, prop.dnomcp, prop.dprncp
FROM cadastrapp.proprietebatie pb, cadastrapp.proprietaire prop, cadastrapp.deschabitation hab
WHERE pb.parcelle = ? and pb.dnubat = ? and pb.comptecommunal = prop.comptecommunal and hab.invar = pb.invar ;
```

J'ai simplement enlevé les references à **proprietaire_parcelle** et cela semble résoudre le problème.

Est-ce que cela parait correcte ? Si oui, je peux faire la PR si tu veux @pierrejego

**Comment by pierrejego** [comment]
Je vais vérifier je te tiens au courant, il faut aussi que je vérifie avec le modèle Arcopole

**Comment by pierrejego** [comment]
J'ai pris en compte ta PR, ça semble bien fonctionner chez moi, mais c'est pas facile a tester sans couche de batiments :)

**Comment by jusabatier** [comment]
J'avais testé la PR sur une branche perso, et elle permettait de régler le souci.

A présent tous les bâtiments/locaux remontent correctement.
