### ISSUE TITLE
[Installation cadastrapp avec modele arcopole] divers pbs

### ISSUE THREAD

**Issue by catmorales** [georchestra/cadastrapp#164]
Suite à l'installation ce jour sur notre Plateforme de test, il nous reste 2 problèmes dont je n'arrive pas à situer la source. 
Peut être les avez vous déjà rencontrés, bien que nous soyons les seuls à utiliser  le modèle  arcopole.

1-  mauvaise géolocalisation lors du zoom sur la sélection d'une parcelle,
2 - ne trouve pas l'adresse cadastrale:
![image](https://cloud.githubusercontent.com/assets/4659829/14323502/1cc8ad04-fc21-11e5-85a2-36f4f008671f.png)

pour info:
- nos données sources sont en 3948 mais le visualiseur en 3857
- le schema "cadastrapp_arcopole" est situé dans la base cadastrapp_arcopole  (à côté de georchestra sur le même serveur postgres) et il existe des dblink vers  bdu.cadastre situé sur le serveur postgis-bdu qui contient les données sources.

**Comment by catmorales** [comment]
pour le pb 2 --> il y a un problème en base, l'adresse est vide -->à moi de voir 
reste la question 1

**Comment by landryb** [comment]
Dans geoserver, tu est sensé configurer la projection 3857 pour les données. Ie laisser 3948 pour 'nativeCRS' mais avoir 3857 pour srs, et 'forcer la reprojection'. dans le xml geoserver ca donne ici (featuretype.xml):

```
<nativeCRS class="projected">PROJCS[&quot;RGF93 / Lambert-93&quot;,
...
...
  <srs>EPSG:3857</srs>
...
 <projectionPolicy>REPROJECT_TO_DECLARED</projectionPolicy>
```

@jusabatier devrait pouvoir confirmer la mm chose, sur le puy il avait les données en CC aussi. Après, il reste peut-etre a documenter ca si ce n'est pas le cas... @pierrejego ?

**Comment by jusabatier** [comment]
Oui, j'avais constaté qu'il fallait obligatoirement passer par du 3857 via la reprojection Geoserver comme l'explique Landry.

En modifiant la projection donnée dans cadastrapp.properties, cela ne fonctionnait pas.

**Comment by catmorales** [comment]
Merci :)
Ca marche avec ce paramétrage:
![image](https://cloud.githubusercontent.com/assets/4659829/14345438/1545d82c-fcad-11e5-97b7-b2532f943c5f.png)

Par contre, mon problème d'adresse n'est pas seulement un problème en base mais je vais creuser et j'ouvrirai un autre ticket au besoin.
