### ISSUE TITLE
[modele Arcopole - recherche parcelle par adresse]

### ISSUE THREAD

**Issue by catmorales** [georchestra/cadastrapp#165]
Aucune réaction sur cette recherche chez nous (pas d'autocomplétion,, ne trouve pas les voies ...):
![image](https://cloud.githubusercontent.com/assets/4659829/14345856/a1c8c438-fcaf-11e5-9072-a270706c4152.png)

 et pas de contrôles sur la PF de qualification GFI:

![image](https://cloud.githubusercontent.com/assets/4659829/14345879/be4f7c14-fcaf-11e5-8ea3-d5ecd2d1b53d.png)

La recherche par parcelle fonctionne mais ne renvoie pas de nom de voie non plus:
![image](https://cloud.githubusercontent.com/assets/4659829/14345913/e5c4f788-fcaf-11e5-9ff0-8135ef021ccf.png)

**Comment by catmorales** [comment]
C'est à priori lié à un problème de requête et de contenu de table:
La fonction getVoie utilise pour l'affichage du nom de la voie le champ dvoie_lib de la vue matérialisée cadastrapp_arcopole.parcelle.
Ce champ utilise le champ dvoilib de la table source cadastre.dgi_nbati .
Or lors de la dernière intégration du cadastre celle-ci n'a pas été renseignée (voir pourquoi en interne) et ce n'est pas la table standard de nommage des voies .
Donc suggestion:

Il faut modifier la requête pour aller chercher le nom des voies dans la table standard dgi_voie.
On va le faire sur notre base et vous proposer la modif.

**Comment by MaelREBOUX** [comment]
Voici une voie de contournement en attendant de comprendre pourquoi ce n'est pas correct dans la base d'origine.

``` sql
SELECT
  dgi_nbati.codparc as parcelle,
  dgi_nbati.codcomm as cgocommune,
  dgi_nbati.dnupla,
  --ltrim(dgi_nbati.dnvoirie,'0') as dnvoiri,
  CONCAT(trim(both ' ' from dgi_voie.nature), ' ', trim(both ' ' from dgi_voie.libelle)) as dnvoiri,
  dgi_nbati.dindic,
  dgi_nbati.cconvo,
  ltrim(substr(dgi_nbati.codparc,7,3),'0')  as ccopre,
  ltrim(substr(dgi_nbati.codparc,10,2),'0')  ccosec,
  CAST(dgi_nbati.dcntpa AS integer)
FROM
 cadastre.dgi_nbati INNER JOIN cadastre.dgi_voie ON dgi_nbati.id_voie = dgi_voie.id_voie
```

cf https://github.com/GFI-Informatique/cadastrapp/blob/master/script/arcopole/views/arcopoleParcelle.sql#L24-L58

**Comment by catmorales** [comment]
Ne le mettez pas encore dans les dev, on va vérifier d'abord et voir pourquoi la table n'est pas renseignée

**Comment by catmorales** [comment]
Ona appliqué la solution de contournement en modifiant la vue matérialisée parcelle de la façon suivante:

```
select
            cadastre.dgi_nbati.codparc as parcelle,
            cadastre.dgi_nbati.codcomm as cgocommune,
            cadastre.dgi_nbati.dnupla,
            ltrim(dgi_nbati.dnvoirie,''0'') as dnvoiri,
            cadastre.dgi_nbati.dindic,
            SUBSTRING(trim(dgi_voie.nature,'' ''),0,4) as cconvo,
            SUBSTRING(trim(dgi_voie.libelle,'' ''),0,26) as dvoilib,
            ltrim(substr(dgi_nbati.codparc,7,3),''0'')  as ccopre,
            ltrim(substr(dgi_nbati.codparc,10,2),''0'')  ccosec,
            CAST(dgi_nbati.dcntpa AS integer)
        from cadastre.dgi_nbati INNER JOIN cadastre.dgi_voie ON cadastre.dgi_nbati.id_voie = cadastre.dgi_voie.id_voie'
```

**Comment by pierrejego** [comment]
ok tenez moi au courant.

**Comment by MaelREBOUX** [comment]
je n'ai pas encore repris l'étude de ce bogue. je le fais au plus vite.

**Comment by MaelREBOUX** [comment]
@catmorales dans ma base locale créée avec les scripts "master", la requête

```
select * from cadastrapp_arcopole.parcelle
where dvoilib = 'THEODORE BOTREL' AND cgocommune = '350047'
```

renvoie très bien les 33 parcelles rattachées à cette voie.

J'en déduis donc ça devrait être correct sans notre patch de avril. Je recommande donc de rejouer le script de création de la BD.
En profiter pour faire #171 en même temps.

**Comment by MaelREBOUX** [comment]
Je confirme qu'il n'y a plus de problème avec la mise à jour des données.
En revanche, faudra indiquer de ne pas taper le type de la voie : ça ne cherche pas dessus.

![screenshot165](https://cloud.githubusercontent.com/assets/6370443/17854563/e8bd390c-6873-11e6-8042-fddaca1728c5.png)

@catmorales merci de fermer ce ticket
