### ISSUE TITLE
Pas de nom sur RP si personne morale

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#167]
Si une parcelle appartient à une personne morale (SCI, ...) alors le nom de celle-ci n'apparait pas sur le relevé de propriété.

Par exemple sur la parcelle AV 387 au puy : 

![image](https://cloud.githubusercontent.com/assets/8310116/14422572/cfade510-ffd7-11e5-9ae3-fdf2b23ad288.png)

**Comment by pierrejego** [comment]
Je viens de vérifier, le nom utilisé dans le RP correspond à la concaténation des champs prop.ccoqua_lib et prop.ddenom.

D'après le schéma QGIS c'est bien censé être dans ddenom que l'on retrouve la dénomination de la personne physique ou morale.

ddenom  varchar 60   √        null            Dénomination de personne physique ou morale -

Je viens de faire un test avec mes données, j'ai bien le nom qui s'affiche, j'ai fait des tests avec des noms de commune et des SCI.

Peux-tu vérifié pour la parcelle AV 387 si le nom de la SCI est bien dans le champ ddenom ?

**Comment by jusabatier** [comment]
J'ai bien ddenom renseigné avec les nom de la SCI dans la BDD, celle-ci remonte dans l'onglet du propriétaire mais disparait à l'impression du RP

**Comment by pierrejego** [comment]
Je vais revérifier ce que j'ai laissé passé.

**Comment by pierrejego** [comment]
ok je pense avoir trouver, lorsque ccoqua_lib est null la concaténation des champs ne se fait pas, le retour de la concaténation renvoie null.

Je fais la modification

**Comment by jusabatier** [comment]
En effet, le problème est résolu, et idem pour https://github.com/GFI-Informatique/cadastrapp/issues/158 :)

Merci
