### ISSUE TITLE
Action sélection/désélection des parcelles sur la carto

### ISSUE THREAD

**Issue by sdhem** [georchestra/cadastrapp#17]
La sélection/désélection de la parcelle est partiellement fonctionnelle. Un fichier word plus descriptif des différentes actions et de leur résultat a été écrit.

**Comment by bounouidarhamza** [comment]
Bug Selection multiple des lignes dans la fenêtre de résultat de recherche : résolu

**Comment by sdhem** [comment]
Reste le cas 5 et 6 non fonctionnel. Gérer l'affichage de la FIUF comme celle de la FIC.

**Comment by pierrejego** [comment]
Spécification et comportement modifié
