### ISSUE TITLE
Les copropriétaires ne remontent pas lors d'une recherche

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#170]
Si on effectue une recherche par propriétaires/copropriétaires, les copropriétaires ne remontent pas.

Ceci est du à la méthode getParcellesByProprietaire de ParcelleController.java qui ne recherche les propriétaires que via la table proprietaire_parcelle, alors que dans le cas de copropriétaires, il faudrait également vérifier dans co_propriete_parcelle.

**Comment by MaelREBOUX** [comment]
+1 la recherche des lots de copropriété ne fonctionne pas.

lié à #159 ? #239 ? #178 ?

**Comment by jusabatier** [comment]
La PR ci-dessus corrige ce problème, il faut juste qu'elle soit mergée.

J'ai corrigé le problème en ajoutant un UNION entre un select sur la table propriétaire et un select sur la table copropriétaire.

Cf https://github.com/georchestra/cadastrapp/pull/172/files

Ce problème n'est pas lié à #159 

La # 239 est résolue via la PR https://github.com/georchestra/cadastrapp/pull/241 qui a été mergée, je l'avais laissée en open afin que @pierrejego puisse le constater.

Pour ce qui est des lots dans #178 , ils ont bien étés rajoutés dans la dernière version de cadastrapp et apparaissent lors de la demande de RP sur un copropriétaire.

**Comment by pierrejego** [comment]
Merge de la PR #172 effectuée

https://github.com/georchestra/cadastrapp/commit/808e36c526ec312decb83456763d503cc06e37dc
