### ISSUE TITLE
Mise à jour du cadastre -modele arcopole -  table uf_parcelle

### ISSUE THREAD

**Issue by catmorales** [georchestra/cadastrapp#171]
Nous avons eu une mise à jour du cadastre hier et j'ai donc rafraichit les vues matérialisées avec 

```
REFRESH MATERIALIZED VIEW cadastrapp_arcopole.co_propriete_parcelle;
REFRESH MATERIALIZED VIEW cadastrapp_arcopole.commune;
REFRESH MATERIALIZED VIEW cadastrapp_arcopole.descdependance;
REFRESH MATERIALIZED VIEW cadastrapp_arcopole.deschabitation;
REFRESH MATERIALIZED VIEW cadastrapp_arcopole.descproffessionnel;
REFRESH MATERIALIZED VIEW cadastrapp_arcopole.parcelle;
REFRESH MATERIALIZED VIEW cadastrapp_arcopole.parcelledetails;
REFRESH MATERIALIZED VIEW cadastrapp_arcopole.proprietaire;
REFRESH MATERIALIZED VIEW cadastrapp_arcopole.proprietaire_parcelle;
REFRESH MATERIALIZED VIEW cadastrapp_arcopole.proprietebatie;
REFRESH MATERIALIZED VIEW cadastrapp_arcopole.proprietenonbatie;
REFRESH MATERIALIZED VIEW cadastrapp_arcopole.proprietenonbatiesufexo;
REFRESH MATERIALIZED VIEW cadastrapp_arcopole.section;
REFRESH MATERIALIZED VIEW cadastrapp_arcopole.v_parcelle_surfc;

```

mais quid de la table uf_parcelle ? Il faut la supprimer et la recréer , je suppose . Ne pourrait on pas en faire une vue également ?

**Comment by catmorales** [comment]
> Ne pourrait on pas en faire une vue également ?

ce n'est pas très important dans la mesure où l'on sait qu'il faut recréer cette table mais il y a t-il d'autres tables à mettre à jour ?

**Comment by pierrejego** [comment]
Je n'ai pas encore lancer de mise à jour de données sur les serveurs de tests, je vais regarder ce qui doit être mis à jour. Je pense que les tables de références aussi doivent être mis à jour.

**Comment by landryb** [comment]
Duplicate of #243 according to @MaelREBOUX - closing
