### ISSUE TITLE
[BP] parcelle mise en surbrillance en dessous de la couche cadastre

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#173]
![surbrillance](https://cloud.githubusercontent.com/assets/3421760/15014590/294c5822-1207-11e6-9bff-67d2049fe3ff.png)

Si on selectionne une parcelle avec un bati, l'appel WFS pour récupérer la parcelle la fait bien apparaitre par dessus les autres couches sur la visionneuse, mais lors qu'on édite le BP j'ai l'impression que l'image de la parcelle est mise _en dessous_ de la couche parcellaire - et si le batiment est rendu plein, ca va cacher le contour de la parcelle.

**Comment by pierrejego** [comment]
Normalement non, la sélection de la parcelle se fait en avant dernier. Tu devrais avoir du bleu par dessus le batiment aussi.. La création de l'image côté serveur correspond à la superposition d'image. 
D'abord l'image en fond, puis par dessus la couche parcelle, puis par dessus la sélection de la parcelle, puis l'échelle et la boussole.
La méthodologie pour l'affichage et la sélection de la parcelle doit être changé. Au lieu de faire un appel WFS ramenant la feature et générant l'image avec GeoTools, il faudrait faire un appel WMS avec un SLD associé.

**Comment by landryb** [comment]
Je viens de refaire le test chez nous après maj de cadastrapp, je reproduis bien le pbm sur p.ex le puy en velay, section AC, parcelle 6.

**Comment by MaelREBOUX** [comment]
Pas ce souci là ici : la sélection graphique est bien au-dessus.
![screenshot092](https://cloud.githubusercontent.com/assets/6370443/16553520/677fc6aa-41c9-11e6-8234-1d4f07fdc2fa.png)

A ce sujet : il va falloir avoir une symbologie avec un contour plutôt qu'une surface.

**Comment by landryb** [comment]
> A ce sujet : il va falloir avoir une symbologie avec un contour plutôt qu'une surface.

Pour l'instant par cohérence avec la visionneuse, la symbologie est la meme que quand la parcelle est selectionne dans la visionneuse.. donc tu veux un style différent pour la visionneuse et l'export PDF ?

**Comment by landryb** [comment]
@MaelREBOUX des fois ca serait pas ton baseWMS le fond cadastral,ce qui expliquerait pourquoi ca marche chez toi ?

**Comment by pierrejego** [comment]
Vérifier dans imageParcelleController

https://github.com/georchestra/cadastrapp/blob/master/cadastrapp/src/main/java/org/georchestra/cadastrapp/service/ImageParcelleController.java

Il semble y avoir une inversion entre drawPlot et drawImage

drawPlot(g2, bufferGeometry, targetGeometry, (int) pdfImageHeight, (int) pdfImageWidth);
logger.debug("Add Image to final picture");
g2.drawImage(parcelleImage, 0, 0, null);

**Comment by pierrejego** [comment]
Vérifier dans imageParcelleController

https://github.com/georchestra/cadastrapp/blob/master/cadastrapp/src/main/java/org/georchestra/cadastrapp/service/ImageParcelleController.java

Il semble y avoir une inversion entre drawPlot et drawImage

Il semble y avoir une inversion entre drawPlot et drawImage

drawPlot(g2, bufferGeometry, targetGeometry, (int) pdfImageHeight, (int) pdfImageWidth);
logger.debug("Add Image to final picture");
g2.drawImage(parcelleImage, 0, 0, null);

—
Pierre Jégo
Tél. : +33 (0)2 96 48 25 63

De : Landry Breuil [mailto:notifications@github.com]
Envoyé : lundi 4 juillet 2016 11:03
À : georchestra/cadastrapp <cadastrapp@noreply.github.com>
Cc : Jego Pierre <pierre.jego@gfi.fr>; Comment <comment@noreply.github.com>
Objet : Re: [georchestra/cadastrapp] parcelle mise en surbrillance sur le BP en dessous de la couche cadastre (#173)


@MaelREBOUX<https://github.com/MaelREBOUX> des fois ca serait pas ton baseWMS le fond cadastral,ce qui expliquerait pourquoi ca marche chez toi ?

**Comment by MaelREBOUX** [comment]
oui : c'est systématiquement notre couche de fond en WMTS.

@landryb : on peut fermer ?

**Comment by landryb** [comment]
Non. Pas de commit qui corrige a ma connaissance, uniquement les 2 commentaires de @pierrejego le 4 aout.
