### ISSUE TITLE
Export PDF bordereau parcellaire

### ISSUE THREAD

**Issue by pmauduit** [georchestra/cadastrapp#177]
Rennes-métropole rencontre un problème du fait de leur plateforme "fermée" / soumise à authentification systématique: L'utilisation de l'addon fonctionne car les communications sont authentifiées quand elles passent de l'utilisateur au serveur via le navigateur de l'utilisateur, mais lors d'une impression PDF, l'image est récupérée en communication "serveur à serveur" lors de la transformation XSL/FOP, cf:

https://github.com/GFI-Informatique/cadastrapp/blob/master/cadastrapp/src/main/resources/xsl/bordereauParcellaire.xsl#L85

La transfo appelle le service suivant:
https://github.com/GFI-Informatique/cadastrapp/blob/master/cadastrapp/src/main/java/org/georchestra/cadastrapp/service/ImageParcelleController.java#L105

Qui se charge de produire l'image, mais si la plateforme est fermée, l'appel aux lignes suivantes:
https://github.com/GFI-Informatique/cadastrapp/blob/master/cadastrapp/src/main/java/org/georchestra/cadastrapp/service/ImageParcelleController.java#L118
et
https://github.com/GFI-Informatique/cadastrapp/blob/master/cadastrapp/src/main/java/org/georchestra/cadastrapp/service/ImageParcelleController.java#L251

Ne fonctionnera pas car le Security-Proxy demandera une authentification (erreur 401).

Comme solution, je voies 2 possibilités:
- Soit on duplique les parametres `cadastre.wfs.url` et `cadastre.wms.url` avec des `cadastre.internal.wfs.url` et `cadastre.internal.wms.url` qui pointeront directement sur le tomcat sans passer par le SP (cela va aussi dépendre de comment les couches sont publiées dans GeoServer, au niveau des droits).
- Soit on utilise la basic-auth avec authentification d'un compte privilégié (via des parametres supplémentaires, car vu que les deux variables sont présentées au client, il ne faudrait pas fournir un compte si les utilisateurs/mots de passe sont directement hardcodés dans les parametres)

**Comment by catmorales** [comment]
@pierrejego  peux tu nous donner ton avis sur le point cité ci-dessus car nous sommes bloqués .

**Comment by landryb** [comment]
pierre revient de congés pater la semaine prochaine... :)

**Comment by pierrejego** [comment]
Bonjour,
Effectivement je vois de quoi vous parlez. Je pensais que les appels serveurs-serveurs n’avaient pas besoin de passer par le security-proxy.
On en reparle tout à l’heure au Geocom.

—
Pierre Jégo
Tél. : +33 (0)2 96 48 25 63

De : Pierre Mauduit [mailto:notifications@github.com]
Envoyé : mardi 10 mai 2016 16:54
À : GFI-Informatique/cadastrapp cadastrapp@noreply.github.com
Objet : [GFI-Informatique/cadastrapp] Export PDF bordereau parcellaire (#177)

Rennes-métropole rencontre un problème du fait de leur plateforme "fermée" / soumise à authentification systématique: L'utilisation de l'addon fonctionne car les communications sont authentifiées quand elles passent de l'utilisateur au serveur via le navigateur de l'utilisateur, mais lors d'une impression PDF, l'image est récupérée en communication "serveur à serveur" lors de la transformation XSL/FOP, cf:

https://github.com/GFI-Informatique/cadastrapp/blob/master/cadastrapp/src/main/resources/xsl/bordereauParcellaire.xsl#L85

La transfo appelle le service suivant:
https://github.com/GFI-Informatique/cadastrapp/blob/master/cadastrapp/src/main/java/org/georchestra/cadastrapp/service/ImageParcelleController.java#L105

Qui se charge de produire l'image, mais si la plateforme est fermée, l'appel à la ligne:
https://github.com/GFI-Informatique/cadastrapp/blob/master/cadastrapp/src/main/java/org/georchestra/cadastrapp/service/ImageParcelleController.java#L118
et
https://github.com/GFI-Informatique/cadastrapp/blob/master/cadastrapp/src/main/java/org/georchestra/cadastrapp/service/ImageParcelleController.java#L251

Ne fonctionnera pas car le Security-Proxy demandera une authentification (erreur 401).

Comme solution, je voies 2 possibilités:

·         Soit on duplique les parametres cadastre.wfs.url et cadastre.wms.url avec des cadastre.internal.wfs.url et cadastre.internal.wms.url qui pointeront directement sur le tomcat sans passer par le SP.

·         Soit on utilise la basic-auth comme authentification avec un compte privilégié (via des parametres supplémentaires, car vu que les deux variables sont présentées au client, il ne faudrait pas fournir un compte privilégié si les credentials sont directement hardcodées dans les parametres)

**Comment by MaelREBOUX** [comment]
Sur nos PF tous les accès doivent être authentifiés.

si "localhost" -> génération du PDF mais pas de carte
si "portail-test.sig.rennesmetropole.fr" -> rien du tout

**Comment by pierrejego** [comment]
Je viens de rajouter des paramètres dans le cadastrapp.properties pour gérer l'authentification des appels wms et wfs lors de la création d'image. 
Je n'ai pas encore tester tous les cas. OK en http avec et sans basic authent via le security proxy, mais pas encore testé en https. Il faut mettre les certificats dans les tomcat.

**Comment by catmorales** [comment]
Bonjour Pierre,
C2C est en train de redéployer la webapp sur nos PF. Peux tu m'indiquer quelle est la conf à paramétrer dans le cadastrapp.properties, sachant que pour le moment on a mis le geoserver_privileged_user mais il me semble que nous avions convenu d'utiliser notre compte spécifique applicatif

```
...
## information about WMS and WFS service 
# Here you can configure the layer name and with field contains the parcelle Id depending if you are on Qgis or Arcopole model
cadastre.wms.url=https://portail-test.sig.rennesmetropole.fr/geoserver/wms
cadastre.wms.layer.name=ref_cad:app_cadastrapp_parcelle
# only used when wms service need authentification
# if empty no authentification is used
cadastre.wms.username=geoserver_privileged_user
cadastre.wms.password=xxxxxx

## use in the addon to check WFS fieldname to be search
cadastre.layer.idParcelle=id_parc
cadastre.format=image/png
cadastre.SRS=EPSG:3857

## used in inner call service to create image for pdf from fo file
**webapp.url.services=http://localhost:8480/cadastrapp/services/**
...
....



```

**Comment by pierrejego** [comment]
Bonjour, c'est ça on avait parler d'un compte applicatif et no du geoserver_privileged_user, il faut aussi le configurer pour le wfs. 
Et si c'est du https il faut rajouter le certificat dans les options du tomcat de cadastrapp.

**Comment by catmorales** [comment]
oui c'est ce qu'on a fait mais on a toujours une carte vide

**Comment by catmorales** [comment]
je vais déjà changer le compte utilisé car peut être est ce gênant

**Comment by catmorales** [comment]
@pmauduit et @pierrejego , je vous laisse voir ensemble car pour le coup, ça me dépasse.
Par contre, je peux essayer de mettre un fond de plan déjà pour voir si celui-ci se charge correctement dans le pdf.

**Comment by pmauduit** [comment]
@pierrejego : donc ce qu'on observe chez Rennes-metropole: A chaque demande de bordereau parcellaires, on obtient 4 requêtes différentes effectuées par GeoTools (module WFS). Celles-ci sont bien authentifiées (elles passent le SP avec une résolution des headers du SP correcte), mais on se retrouve quand même dans les fichiers temporaires avec une invite de connexion du CAS server, suivi d'une erreur au parsing.

Donc à un moment ou à un autre, il y a un problème d'authentification (récupération des schémas ?) ; pour mémoire, cela me fait penser à l'issue suivante dans georchestra (le module WFS qui ne passait pas systématiquement la basic-auth): https://github.com/georchestra/georchestra/issues/1230

**Comment by pierrejego** [comment]
@pmauduit : je vais passer sur la même version que mapfishapp avec le module gt. Je rajoute le repository camptocamp pour récupérer cette version introuvable :) Et je fais la modification.

**Comment by pmauduit** [comment]
> Je rajoute le repository camptocamp pour récupérer cette version introuvable

Quel repo c2c ? à ma connaissance dev.mapfish.org est mort il y a quelques semaines, par contre effectivement on maintient une version au niveau georchestra sur http://build.georchestra.org/maven/repository/org/geotools/gt-wfs-ng/9.2/ ; mais à mon avis tu dois pouvoir utiliser gt-wfs-ng dans la version actuellement utilisée sur cadastrapp (je pense que le code de wfs-ng et de wfs n'ont pas du beaucoup évolué dans les montées de version de gt, mais de mon point de vue, wfs-ng est vraiment mieux écrit).

**Comment by pierrejego** [comment]
Oui pardon le repo georchestra. J'ai pas trouvé la gt-wfs-ng en 10.8 sur les repo maven, du coup c'est encore plus simple d'utiliser la 9.2.

**Comment by pierrejego** [comment]
OK je viens de faire la modification, par contre je ne reproduis pas sur mes plateformes. L'impression fonctionne toujours. Je vous laisse tester sur les serveurs de Rennes.

**Comment by catmorales** [comment]
Victoire !!! ca marche à priori. Je vais continuer à tester.
Merci à vous deux !

**Comment by pierrejego** [comment]
Merci @pmauduit pour la piste, j'aurais mis très très très longtemps à trouver sinon je pense :)

**Comment by pmauduit** [comment]
;-)
