### ISSUE TITLE
Informations sur les lots dans les RP

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#178]
Nous avons eu une demande du service urbanisme qui ont besoin que l'addon remonte sur les relevés de propriétés des informations sur les lots liés à un batiment, notamment afin de savoir quelle part du bâtiment est affectée au propriétaire (valeur sur 1000).

Voici un exemple des données remontées par Editop : 

![image](https://cloud.githubusercontent.com/assets/8310116/15176215/4ee6e562-176a-11e6-9c72-056be791d583.png)

On retrouve pour chacun des lots des différents bâtiments une valeur sur 1000.

Les valeurs de ces lots sont récupérables pour chaque bâtiment via la clef local10 (il peut y en avoir plusieurs par bâtiments) dans la table lotslocaux du schema QGis.

**Comment by pierrejego** [comment]
A rajouter dans la génération. Est-ce que cette notion de lot est aussi nécessaire avec le modèle Arcopole ?

**Comment by jusabatier** [comment]
Je pense que oui, car d'un point de vue métier, c'est ce qui permet de déterminer pour chaque bâtiment les "parts" qu'il représente au sein de la parcelle afin de déterminer comment diviser les paiement entre les différents propriétaires.

**Comment by MaelREBOUX** [comment]
+1

**Comment by pierrejego** [comment]
Vu avec Julien, pour le modèle QGIS.  (Merci Julien)
Dans local10, si gpdl = 1 alors c'est des lots, le lien est fait entre la table local10 et la table lotslocaux, vi la colone local10.
 Le champ dnumql correspond à la valeur du lot (numérateur) et ddenql au dénominateur.

Reste à trouver pour Arcopole maintenant :)

**Comment by pierrejego** [comment]
Pour Arcorpole,
le codelot de dgi-nbati ne semble pas en lien direct avec le dgi_lotloc.

Pourquoi est-ce qu'il y dgi_lotloc et dgi_lot ? 

Donc dgi_nbati -> dgi_invar (id_local) ->  dgi_local (codlot) -> dgi_lotloc. 
Faire le même test avec dgi_nbati (codlot) vers dgi_lotloc pour vérifier la différence

**Comment by MaelREBOUX** [comment]
Alors, en toute logique c'est : 

dgi_nbati.codparc => dgi_invar.codparc | dgi_invar.invar => dgi_local.id_local | dgi_local.id_local => dgi_lotloc.invloc | dgi_lotloc.id_pdl => dgi_lot.id_pdl

Tester sur la parcelle  '350238000BI0694' qui a 7 copro. Certains appart ont juste des logements d'autres logement + local.

select codparc, invar from cadastre.dgi_invar
where codparc = '350238000BI0694'

=> 7 enrg

'350238000BI0694';'3502380100201'
'350238000BI0694';'3502380249481'
'350238000BI0694';'3502380249592'
'350238000BI0694';'3502380249593'
'350238000BI0694';'3502380266562'
'350238000BI0694';'3502380266563'
'350238000BI0694';'3502380325998'

**Comment by pierrejego** [comment]
Je viens de faire des modifications pour les deux modèles, mais le résultat n'est vraiment pas beau... j'arrive pas à ajuster la taille de la ligne en fonction de la donnée. du coup toutes les lignes sont décalées. 
J'ai vu la capture d'écran d'edigeo, est-ce que vous pouvez m'envoyer par mail d'autres exemples histoire que je trouve une idée pour la présentation. Pour quoi pas un tableau intermédiaire avec le numéro invar et les lots..... 
Si vous déployez et que vous ne voulez pas des lots, le plus simple c'est d'éditer le fichier relevePropriete.xsl et d'enlever 

<xsl:if test="lots/lot">
                                    <xsl:for-each select="lots/lot">
                                        Lot <xsl:value-of select="@lotId" /> - <xsl:value-of select="@numerateur" />/<xsl:value-of select="@denominateur" />
                                    /xsl:for-each
                                /xsl:if

Ligne 445

**Comment by pierrejego** [comment]
Voir pour ajouter les index liés à cette modification

**Comment by MaelREBOUX** [comment]
je pense que c'est derrière nous. @jusabatier ?
on a rajouté les indexes @pierrejego  ?

**Comment by jusabatier** [comment]
Pour moi ce point est OK, les lots remontent bien dans les RP. Reste à voir avec @pierrejego  si les INDEX nécessaires ont bien été ajoutés.

**Comment by MaelREBOUX** [comment]
@pierrejego ?

**Comment by MaelREBOUX** [comment]
je viens de tester : c'est OK également pour moi.

**Comment by MaelREBOUX** [comment]
ok pour tous : pas besoins d'index supplémentaires
