### ISSUE TITLE
[UI] Déchargement de la couche applicative des parcelles

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#179]
Nous avons avons créé une couche applicative des parcelles cadastrales qui est déclarée dans la configuration du module cadastre. Elle s'appelle (selon nos normes) **app_cadastrapp_parcelle**.

Pour le moment elle a un style avec une bordure noire mais à terme elle sera totalement transparente.

Le souci est qu'elle est chargée automatiquement à l'activation de l'add-on. Mais **elle persiste si on ferme l'add-on**. Dit autrement, elle est toujours présente dans la carte même si elle n'apparaît pas dans la TOC à droite de la carte.

Si on enregistre la carte sous la forme d'un contexte, la couche app_cadastrapp_parcelle est bien enregistrée couche couche dans la carte. Ce qui est logique.

**Comment by pierrejego** [comment]
Je viens de rester, les couches disparaissent bien sur la plateforme de qualification. Il faut qu'on fasse le test ensemble

**Comment by pierrejego** [comment]
Je pense que c'était lié à cette anomalie #184. 
Je refais un test pour vérifier

**Comment by MaelREBOUX** [comment]
ok : suite à nos essais semaine dernière c'était bien mieux. On va re-tester après redéploiement.

```
        "WMSLayer":{
            "layerNameInPanel":"Cadastre : parcelles",
            "transparent":true,
            "format": "image/png"
        },
```

Ce serait à modifier dans le fichier configuration.json mais ce fichier a l'air d'être créé à la compilation de la webapp.

**Comment by catmorales** [comment]
C'est ce qui a été fait sur test georchestra:
![image](https://cloud.githubusercontent.com/assets/4659829/15821781/371f9dba-2bf2-11e6-9f3d-e2390a23500f.png)

**Comment by MaelREBOUX** [comment]
Pour moi ce pb est derrière nous : on ferme ? @catmorales @landryb @jusabatier ?

**Comment by jusabatier** [comment]
Chez nous nous n'avions pas ce problème car la couche cadastrapp était visible dans la liste de couche.

Mais si le problème est résolu chez ceux qui veulent qu'elle soit masquée par défaut, alors oui je pense que l'issue peut être fermée.

**Comment by MaelREBOUX** [comment]
hmm : à revoir effectivement car depuis juin on fait effectivement apparaître clairement le chargement de la couche. C'est plus facile à suivre pour tt le monde.
On laisse ouvert et on met en standby.

**Comment by MaelREBOUX** [comment]
Réglé depuis longtemps visiblement.
