### ISSUE TITLE
getParcelle plusieurs parcelles avec comme séparateur un blanc ou virgule

### ISSUE THREAD

**Issue by sdhem** [georchestra/cadastrapp#18]
A partir de Soap-ui, parcelle=20146300830000A0012 20146300830000A0014&details=1
=> réponse vide alors que l'on devrait avoir le résultat de 2 parcelles

**Comment by pierrejego** [comment]
Correction done and deployed on cadastrapp.qualif.asogfi.fr

**Comment by sdhem** [comment]
Vérifier sur plateforme de dev : corrigé pour le blanc mais pas pour la virgule.
