### ISSUE TITLE
minifier JS

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#181]
Lorsqu'on charge cadastrapp, 19 fichiers js sont chargés, pour 300ko.. certes, les autres addons ne sont pas minifiés, mais ils ne sont pas aussi gros en volume de JS. Est-ce qu'on doit envisager de les minifier, au choix, tous ?

**Comment by pierrejego** [comment]
Avec plaisir maintenant que c'est plus en debug :)

**Comment by pierrejego** [comment]
Voir si il est possible d'utiliser le mode debug de mapfishapp avec les addons.

**Comment by landryb** [comment]
cf georchestra/georchestra#1420 for what's needed mfapp-side

**Comment by landryb** [comment]
Apres qqs tests avec jsbuild, on passe de 300ko a 150ko pour une version minifiée de cadastrapp.js

**Comment by landryb** [comment]
Closed by #235
