### ISSUE TITLE
[fiche info] la fermeture de la fenetre de resultats de recherche ne ferme qu'une fiche parcelle

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#182]
- ouvrir la toolbar
- selectionner 2 parcelles avec l'outil point, la fenetre 'selection de parcelles' apparait au 1er clic sur la carte
- selectionner les 2 lignes dans la fenetre 'selection de parcelles', ouvrir la fiche d'info -> 2 fenetres supplémentaires apparaissent
- fermer la fenetre 'selection de parcelle' -> elle disparait, et une des 2 fenetres de parcelle reste affichée.
- les clics suivants sur la carte ne font pas revenir la fenetre 'selection de parcelle', il faut fermer la toolbar et la reouvrir pour l'avoir de nouveau

**Comment by pierrejego** [comment]
Voir pour décaler les deux fenêtres qui s'ouvre (au lieu de l'une sur l'autre)

**Comment by pierrejego** [comment]
Voir resultParcelle.js ligne 548  ficheCadastreOuverte.close()

**Comment by MaelREBOUX** [comment]
je confirme ce bogue ici.

**Comment by MaelREBOUX** [comment]
Toujours d'actualité.

**Comment by MaelREBOUX** [comment]
ok
