### ISSUE TITLE
infobulle vide si cadastre et unité fonciere sont décochées

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#183]
Si on décoche les 2 cases, une infobulle vide est affichée au survol/attente sur une parcelle, et si on clique sur 'fiche d'info parcelle' apres en avoir selectionné une il ne se passe rien. @MaelREBOUX Y'a t'il toujours un usecase a afficher les infos foncieres _sans_ les infos cadastrales ? On fait quoi, on désactive l'infobulle/la possibilité d'avoir la fiche d'info  parcelle si les 2 sont décochées ?

**Comment by pierrejego** [comment]
Bonjour,
effectivement si au moins une des cases n'est pas coché, le bouton "Fiche d'info parcelles (s)" n'a aucune action. Je peux rajouter une message pour indiquer qu'il faut cocher l'une ou l'autre des cases ?

Pour l'infobulle, je peux faire en sorte de la deactiver quand aucune case n'est cochée.

**Comment by pierrejego** [comment]
@MaelREBOUX peux-tu nous répondre ? Est-ce qu'on peut ne garder que la case à cocher Unité Fonçière ?

**Comment by landryb** [comment]
@MaelREBOUX on en a discuté avec pierre, et si ca n'a pas de sens de demander 'que les unités foncières', on pourrait faire sauter la checkbox 'Cadastre' (qui serait du coup toujours cochée) et garder uniquement 'Unit. Fonc.' - et ca réglerait ce ticket par effet de bord...

**Comment by MaelREBOUX** [comment]
J'ai jamais compris pourquoi il y avait une case à cocher "cadastre".
On a mis en option "UF" pcq tt le monde n'a / n'avait pas cette couche au début.

**Comment by landryb** [comment]
Ok, donc on dégage la checkbox cadastre - cool :)

**Comment by MaelREBOUX** [comment]
si c'est dans master : on peut fermer @landryb ?

**Comment by landryb** [comment]
Oui, ca a été mergé dans #229
