### ISSUE TITLE
fermer/reouvrir la toolbar ne nettoie pas tout les outils -> requetes multiples pour l'infobulle

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#184]
(par erreur dans https://github.com/georchestra/georchestra/issues/1385)

Si je ferme/reouvre la toolbar, l'outil d'interrogation/selection pour l'infobulle n'a pas l'air nettoyé/supprimé. Avec la console réseau, apres avoir ouvert/fermé 5 fois la toolbar, a chaque déclenchement du timeout j'ai 6 requetes WFS et 6 requetes getInfoBulle.... je ne sais pas si c'est lié, mais si je regarde la liste des controles dans l'objet map via GeoExt.MapPanel.guess().map j'ai 5 controles 'drawFeature' et 6 controles 'generiques'. Il y'a un truc qui cloche qqpart avec un controle de selection...

**Comment by pierrejego** [comment]
Oui, je viens de le voir aussi sur la PF de Rennes métropole avec Mael et Catherine.

**Comment by landryb** [comment]
A la fermeture de la toolbar dans la console j'ai TypeError: mapControls is undefined sur main.js:103.. et .. https://github.com/georchestra/cadastrapp/blob/master/addons/cadastrapp/js/main.js#L102 .. quel est ce beau 21 codé en dur ?!? c'est quoi cette horreur ? :)

**Comment by landryb** [comment]
Il faut au moins utiliser map.getControlsBy() pour etre sur de récupérer celui que l'on a ajouté..et eviter de flinguer un controle qui aurait pu être ajouté par un autre addon, au hasard..

**Comment by pierrejego** [comment]
Effectivement qu'est-ce que ce 21.... :) je regarde ça demain

**Comment by pierrejego** [comment]
Humm, dommage, le déplacement de repo à shooté l'historique GIT. C'est vraiment dommage

**Comment by landryb** [comment]
Tu peux taper sur @Gaetanbru :) - cf https://github.com/GFI-Informatique/addons/commit/3c61a9ebfe3fe4b6a89be03f992b8374a7adf291

**Comment by pierrejego** [comment]
A oui bien jouer, on a toujours le addons dans GFI-Informatique !!!  Bon je vais sortir les orties :)
