### ISSUE TITLE
[Modèle Arcopole] Infobulle - affichage de données décalées

### ISSUE THREAD

**Issue by catmorales** [georchestra/cadastrapp#185]
Les données affichées  dans l'infobulle concernant l'année, le département, le code INSEE, le préfixe de section et la section  sont fausses. Les données sont décalées. Sans doute dues à la différence d'identifiant entre les deux modèles (pas d'année pour Arcopole)
Mauvais découpage de l'identifiant   ?
![image](https://cloud.githubusercontent.com/assets/4659829/15613356/6a0d577e-2433-11e6-8855-e8b101c0ce33.png)

**Comment by pierrejego** [comment]
Oui effectivement, l'identifiant de parcelle est différence sur le modèle Qgis et sur le modèle Arcopole. Je vérifie ce qui est fait (parsing client, ou envoie des infos erronés  côté serveur) et je corrige.

**Comment by MaelREBOUX** [comment]
Un petit up...

**Comment by catmorales** [comment]
relance car ça fait tâche ...
l'année devrait être vide (ou pas), le dépt à 35 le code insee à 0238, ....
![image](https://cloud.githubusercontent.com/assets/4659829/17058605/95a0f3c2-5021-11e6-9e32-bb65c6748f9a.png)

**Comment by catmorales** [comment]
@pjego d'ailleurs N° de plan c'est bien le N° de parcelle ?
