### ISSUE TITLE
Descriptif habitation : état d'entretien : code -> libellé

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#189]
https://github.com/MaelREBOUX/cadastrapp/blob/9a5c94f27f933715d5e555044f31446b74288b46/addons/cadastrapp/js/habitationDetails.js#L86

Ici on voit un code apparaître au lieu d'un libellé.

Exemple : "1" au lieu de "Bon état"

**Comment by landryb** [comment]
Ton lien ne marche pas mael.. j'imagine que c'est ca que tu voulais : https://github.com/georchestra/cadastrapp/blob/master/addons/cadastrapp/js/habitationDetails.js#L86

Pour le libellé, d'ou devrait il venir ?

**Comment by MaelREBOUX** [comment]
MAJIC III DESCRIPTION DU FICHIER DES PROPRIÉTÉS BÂTIES
page 24

DETENT = état d’entretien
1 bon
2 assez bon
3 passable
4 médiocre
5 mauvais

Cette information est disponible chez nous dans la table cadastre.dom_detent. Depuis qqs mois nous avons une table par domaine de valeur. Ces tables n'existent que depuis qqs mois.

@landryb ou @jusabatier  est-ce que dans le modèle QGIS ces clés codes / libellés existent dans des tables ? Il me semble que oui mais je suis pas certain.

En l'état des choses, vu que de tte façon on est sur du arcOpole modifié RM, je militerai pour faire évoluer le script de création de la BD pour rappatrier sous la forme native ou une autre toutes ces clés / valeurs.
Ton avis @pierrejego ?

**Comment by jusabatier** [comment]
Dans le modèle QGIS, il n'y a pas de table qui stocke la paire clef/valeur, seulement un commentaire sur la table : état d’entretien - 1 bon 2 assez bon 3 passable 4 médiocre 5 mauvais

cf : http://demo.3liz.com/plugin_cadastre/SchemaSpyGUI/tables/pevprincipale.html

**Comment by MaelREBOUX** [comment]
donc il faut faire un choix :
1. faire évoluer le modèle QGIS pour gérer en transparence ces paires clef/valeur. Il y a tous les codes matériaux également. Nous avons déjà toutes ces tables prêtes. Une PR peut-être rapide.
2. hardcoder

Perso je préfère l'option 1 qui me semble rigoureuse.

@pierrejego ? @landryb ?

**Comment by landryb** [comment]
1. on a déja des tables de correspondance 'statiques' dans https://github.com/georchestra/cadastrapp/tree/master/script/commun/tables. Pour l'option 1, il faudrait voir avec @mdouchin ..

**Comment by MaelREBOUX** [comment]
Excellent : je vais faire une PR pour rajouter la table **prop_detent** dans ce cas, pour commencer.

**Comment by MaelREBOUX** [comment]
@pierrejego 
En attendant la PR sur le repo QGIS Plugin (faut que je me replonge dans git...) je te propose, en mode crade :

```sql

CREATE TABLE qgis3_master.detent
(
  detent text NOT NULL,
  detent_lib text,
  CONSTRAINT detent_pkey PRIMARY KEY (detent)
);

ALTER TABLE qgis3_master.ccogrm OWNER TO qgis;


INSERT INTO qgis3_master.detent VALUES ('1','bon');
INSERT INTO qgis3_master.detent VALUES ('2','assez bon');
INSERT INTO qgis3_master.detent VALUES ('3','passable');
INSERT INTO qgis3_master.detent VALUES ('4','médiocre');
INSERT INTO qgis3_master.detent VALUES ('5','mauvais');
```

**Comment by MaelREBOUX** [comment]
Alors pour créer ce genre de table dans le plugin QGIS il faut modifier :

\scripts\plugin\commun_create_metier.sql
\scripts\plugin\commun_creation_contraintes.sql  (pas besoin dans ce cas précis)
\scripts\plugin\commun_insert_nomenclatures.sql

Trop fier de ma PR -- >https://github.com/3liz/QgisCadastrePlugin/pull/160
:p

**Comment by pierrejego** [comment]
Modifications effectuées dans cadastrapp, ajout de la table + jointure sur les requêtes
