### ISSUE TITLE
Historique parcelle : mapping des codes / valeurs de filiation

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#192]
L'attribut **parcelledetails.type_filiation** contient des codes.

Le document de référence N_BAT12.pdf de la DGFiP indique p 4 :
- D pour division
- R pour réunion
- T pour transfert

Je propose donc :
1.  la création d'une table **prop_type_filiation** pour stocker ces correspondances
2. la modification des requêtes **{modele}Parcelle.sql** pour que la vue _parcelledetails_ contiennent la valeur et pas le code

Pas urgent : mettre en enhancement.

**Comment by MaelREBOUX** [comment]
à coupler avec #189

**Comment by MaelREBOUX** [comment]
PR -->  https://github.com/3liz/QgisCadastrePlugin/pull/160

**Comment by MaelREBOUX** [comment]
En mode crade :


```sql
CREATE TABLE qgis3_master.filiation
(
  filiation text NOT NULL,
  filiation_lib text,
  CONSTRAINT filiation_pkey PRIMARY KEY (filiation)
);

ALTER TABLE qgis3_master.filiation OWNER TO qgis;


INSERT INTO qgis3_master.filiation VALUES ('D','Division');
INSERT INTO qgis3_master.filiation VALUES ('R','Réunion');
INSERT INTO qgis3_master.filiation VALUES ('T','Transfert');
```

**Comment by pierrejego** [comment]
Modifications effectuées dans cadastrapp, ajout de la table + jointure sur les requêtes
