### ISSUE TITLE
Historique parcelle : mauvais formatage des dates

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#193]
modèle QGIS : 2008-05-12
modèle arocopole : 19122009

correction qgis :
`concat(substr(jdatat,9,2),'/',substr(jdatat,6,2),'/',substr(jdatat,1,4)) as jdatat,`

correction arcopole :
`concat(substr(jdatat,1,2),'/',substr(jdatat,3,2),'/',substr(jdatat,5,4)) as jdatat,`

**Comment by MaelREBOUX** [comment]
J'arrive pas à créer une PR dédiée seulement à cette correction.

en local sur le fork de mon master j'ai créé une branche #193 
puis : `git add`
puis `git commit -m  On branch #193`
puis : `git push origin #193`

sur github j'ai créé une branche #193 : https://github.com/MaelREBOUX/cadastrapp/tree/%23193

mais quand je veux faire une PR : ça s'additionne aux 3 autres commit sur master :+1: https://github.com/georchestra/cadastrapp/compare/master...MaelREBOUX:%23193?expand=1

Qu'est-ce que j'ai loupé ?

**Comment by jusabatier** [comment]
Pour faire une PR voici les commandes utiles : 

1/ Synchronisation de la branche master avec le depot d'origine : 

Basculer sur master et definir une remote pointant sur le depot d'origine

```
git checkout master
git remote add upstream https://github.com/georchestra/cadastrapp.git
```

Mettre à jour la branche master locale avec celle definie dans upstream : 

```
git fetch upstream
git merge upstream/master
```

2/ Créer la nouvelle branche, basculer dessus et la pousser sur son dépôt github : 

```
git checkout -b patch-193
git push --set-upstream origin patch-193
```

3/ Faire les modifs à inclure à la PR

4/ Pousser les modifs sur la branche

```
git push
```

5/ Sur Github créer la PR depuis la branche précédemment créée

**Comment by MaelREBOUX** [comment]
oui j'ai eu un cours en ligne avec Landry vendredi ^_^
ok mais comment annuler mes PR en cours dans ce cas ?
Il faut que @pierrejego les refuse en fait ?

Je m'occupe de tt ça cet a-m.

**Comment by jusabatier** [comment]
Si la PR a déjà été poussée sur le Github georchestra/cadastrapp, je pense que le boutob 'Close Pull Request' doit l'annuler.

**Comment by MaelREBOUX** [comment]
ha ouais... bien vu.

**Comment by MaelREBOUX** [comment]
héhé : test sur un tout autre dossier : https://github.com/MaelREBOUX/api.gouv.fr/tree/ajout-rennes

![screenshot222](https://cloud.githubusercontent.com/assets/6370443/15821106/17f2144e-2bee-11e6-820f-6d77521fc7c3.png)

**Comment by MaelREBOUX** [comment]
Et hop une PR propre : https://github.com/georchestra/cadastrapp/pull/194

@pierrejego

**Comment by pierrejego** [comment]
Je teste demain pour vérifier avant de clore l'issue

**Comment by MaelREBOUX** [comment]
mergé : je ferme ?

**Comment by jusabatier** [comment]
Si l'issue est bien résolue, oui :)

**Comment by pierrejego** [comment]
J'ai pas encore testé :) attendez un peu

**Comment by MaelREBOUX** [comment]
Le code a bien été modifié mais ici toujours pas résolu. bizarre bizarre.
:(

**Comment by jusabatier** [comment]
De mon coté, les dates sont au format JJ/MM/AAAA dans l'onglet Batiments -> Date de mutation

Mais toujours AAAA-MM-JJ dans Historique de mutation -> Date acte

**Comment by MaelREBOUX** [comment]
ici c'est l'historique de mutation. Ouf : les données sont OK et affichage OK mais uniquement sur la PF de test. Pas en prod.

Je ferme donc ce ticket.

**Comment by jusabatier** [comment]
Bah y fallait pas le fermer si il reste des endroits où ça n'est pas bon :/

**Comment by jusabatier** [comment]
D'ailleurs après avoir testé de reconstruire la vue proposée via la PR ci-dessus, il y a de gros soucis, et elle refuse de se construire sous QGIS, et je suis étonné qu'elle ait réussi sous Arcopole car on essaye de rentrer 10 caractères (date JJ/MM/AAAA) dans un varchar(8)

**Comment by jusabatier** [comment]
En effet je viens de voir que la PR avait été revert pour QGis...

Celle ci-dessus fonctionne, mais a l'avenir il serait sympa de signaler si une PR n'est pas valide sur un des modèles avant de la clore ;)
