### ISSUE TITLE
Export CSV Ajout d'élément

### ISSUE THREAD

**Issue by pierrejego** [georchestra/cadastrapp#197]
Par rapport au CCTP, il manque des éléments dans les exports.

**Comment by pierrejego** [comment]
Missing commit https://github.com/georchestra/cadastrapp/commit/4f5fc40bfab0283ace1005164311fb95527c9b8a

**Comment by pierrejego** [comment]
Il reste encore un problème d'encodage dans le header du fichier CSV. 
Et il faut développer un service permettant d'exporter les utilisateurs à partir de la sélection de parcelles.

**Comment by MaelREBOUX** [comment]
vu : me suis permis de créer #200 pour suivre.
