### ISSUE TITLE
getCommune ne renvoie pas que des communes

### ISSUE THREAD

**Issue by sdhem** [georchestra/cadastrapp#2]
Dans la base qgis, dans la table commune, avec les communes, il existe la définition du département
qui ne possède pas de ccocom. Si je fais le test de chercher une commune avec "puy" j'ai le département qui sort. Le ccocom n'est pas vide, ce sont des blancs.

**Comment by cbesche** [comment]
Modification de la vue commune pour ne prendre en compte que les communes.
Ajout de la clause where typcom is not null

**Comment by sdhem** [comment]
Vérifier avec Soap-ui sur la plateforme de dev. => ok => Closed
