### ISSUE TITLE
Export de la liste des proprios depuis une sélection de parcelles

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#200]
cf article 3.12.3 du cahier de spécification

La méthode exportCsvProprietaire avec comme argument la liste des parcelles sélectionnées et le niveau d’export est executée.
Si la taille du fichier est inférieure à 50Mo. La fenêtre de sauvegarde s’ouvre

Description Niveau 1
Nom du fichier par défaut : parcelle_PROPRIETAIRES.csv
Colonne : epxnee | dnomlp | dprnlp | dnomcp | dprncp | adressehabitation

Description Niveau 2
Nom du fichier par défaut : parcelle_PROPRIETAIRES.csv
Colonne : epxnee | dnomlp | dprnlp | dnomcp | dprncp | adressehabitation | dldnss | jdatnss

**Comment by jusabatier** [comment]
Nous avons également une demande pour pouvoir faire un export des co-propriétaires d'une parcelle.

**Comment by pierrejego** [comment]
Il est maintenant possible d'extraire les propriétaires et copropriétaires d'une ou d'une liste de parcelle depuis la fenêtre de résultat de parcelles.

Modification effectuée avec les commits 
https://github.com/georchestra/cadastrapp/commit/9337c267732e3502a1083f60b9d691d00cca372c
et 
https://github.com/georchestra/cadastrapp/commit/1c3b1aeba3c19802443dfac3956217d3f8c2995a

Ajout de deux boutons permettant d'extraire les propriétaires et copropriétaires depuis la fenêtre de liste des parcelles.

Les champs retenu pour le niveau CNIL 1 ou le niveau CNIL2 sont pour l'instant les mêmes : 

comptecommunal;ccoqua_lib;dnomus;dprnus;dnomlp;dprnlp;ddenom;app_nom_usage;;dlign3;dling4;dling5;dling6;identitifiantsparcelles;ccodro_lib

Par rapport à la demande de Mael il manque dldnss et jdatnss, a voir ensemble si je les rajoutes pour le niveau CNIL 2.

**Comment by jusabatier** [comment]
Super ! :D

Oui autant les rajouter si possible

**Comment by pierrejego** [comment]
Ok je viens de faire le point avec Mael, je rajoute le lieu et la date de naissance lorsque l'utilisateur qui demande l'export est en CNIL2

**Comment by pierrejego** [comment]
Modification et test fait sur notre PF. @jusabatier je te laisse vérifier avant de fermer l'issue

**Comment by jusabatier** [comment]
Pour l'export de propriétaires/copropriétaire, la colonne civilité est renseignée avec null pour toutes les personnes morales, il serait mieux de le laisser à vide comme les autres champs non renseignés.

Sinon pour le reste tout me parait OK.

**Comment by pierrejego** [comment]
Ok j'avais pas fait de traitement particulier, ça doit être null dans la base. Du coup je rajouter un check, si c'est null je met vide.
