### ISSUE TITLE
Problème chargement avec Mozilla Firefox

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#202]
Pas mal de nos utilisateurs m'ont remonté un problème de fonctionnement du module.

Ceux-cis sont tous sous Mozilla Firefox et le problème est le suivant : 

Il arrive parfois que suite à la recherche d'une parcelle, il devienne impossible de faire un zoom sur la sélection, de-plus l'ouverture de la fiche d'une parcelle n'affiche rien, on voit juste les onglets mais rien en dessous.

Ce problème semble spécifique à Mozilla Firefox car je ne l'ai jamais eu sous chromium.

Ceci est assez embêtant car même en faisant un Ctrl+Shift+R le problème persiste, la dernière fois il a fallu que je vide tout le cache+cookies+données de navigation via Ctrl+Shift+Suppr pour que le problème soit résolu, ce que je ne peux pas demander à mes utilisateurs de faire. D'autant plus que ce bug semble se produire assez souvent sur leurs postes.

Est-ce que quelqu'un aurait une idée de ce qui peux causer ce comportement ? Comment résoudre ce problème ?

**Comment by MaelREBOUX** [comment]
Si tu redéploies souvent le module cadastre possible que ça engendre ça. Ici on redéploies souvent à cause des compléments en cours. Et hier j'ai dû effectivement tout purgé pour retrouver un module cadastre + mapfishapp fonctionnel.
Aucun idée de la cause.

**Comment by pierrejego** [comment]
Est-ce que tu as pu voir si il y avait une trace d'erreur javascript ? Je vais me mettre sur firefox pour faire les prochains tests pour voir si je reproduis. Mais pour l'instant, ça ne m'est jamais arrivé.
Ou alors c'est lié à #184, de quand date ta version ?

**Comment by jusabatier** [comment]
De mémoire, il y avait une erreur JS qui disait que l'attribut "bound" n'existait pas lorsqu'on essayait de recentrer sur la sélection.

**Comment by landryb** [comment]
du coup, c'est ptete la meme chose que #216 ?

**Comment by jusabatier** [comment]
En effet, c'est le même soucis que #216, mais maintenant il semble aussi affecter chromium
