### ISSUE TITLE
Erreur sur getImageBordereau

### ISSUE THREAD

**Issue by catmorales** [georchestra/cadastrapp#204]
Sur notre plateforme de production,  le  module cadastre nous donne l'erreur suivante lors de la création du BP:

```
2016-06-13 10:47:49,582 [http-8080-2] ERROR /getImageBordereau - nouser - norole -o.g.c.s.ImageParcelleController - Error while trying to init connection, please check configuration
java.net.MalformedURLException: no protocol: /geoserver/wfs?REQUEST=GetCapabilities&version=1.0.0
```

Il manque un SERVICE=WFS dans la requête

**Comment by catmorales** [comment]
on peut fermer ce ticket car le pb est résolu.
Mais je ne peux pas le faire.

**Comment by landryb** [comment]
Est-ce qu'un commit particulier a résolu ce ticket ? @pierrejego ?

**Comment by pierrejego** [comment]
Bonjour,
non j pas de commit, si je me trompe pas c'était un soucis de configuration sur l'environnement de production

**Comment by MaelREBOUX** [comment]
Résolu vendredi dernier.

@pierrejego on avait parlé de la possibilité d'ajouter des labels et de fermer les issues. Si tu pouvais le faire... Merci d'avance.

**Comment by pierrejego** [comment]
@MaelREBOUX je t'avoue que maintenant que l'on a changé de repo pour celui de georchestra, je ne sais pas trop comment faire. Dès que j'ai trouvé je te dis

**Comment by MaelREBOUX** [comment]
ok

**Comment by MaelREBOUX** [comment]
pour la mémoire : 

Le dernier commit https://github.com/georchestra/cadastrapp/commit/97a6fc2a597484e59d8fd5f17ff588dd5b580dcd 
Nous permet de définir et utiliser une authentification pour accéder aux services de données qui figurent dans le bordereau parcellaire.

Nous attirons votre attention sur la correction de la casse à la ligne 300 :
https://github.com/georchestra/cadastrapp/blob/97a6fc2a597484e59d8fd5f17ff588dd5b580dcd/cadastrapp/src/main/java/org/georchestra/cadastrapp/service/ImageParcelleController.java#L300
baseMap.WMS.url  => baseMap.wms.url

Ce changement est à répercuter dans votre fichier de configuration cadastrapp.properties
https://github.com/georchestra/cadastrapp/blob/97a6fc2a597484e59d8fd5f17ff588dd5b580dcd/cadastrapp/src/main/resources/cadastrapp.properties#L35
valeur par défaut :  baseMap.wms.url=http://osm.geobretagne.fr/service/wms?VERSION=1.1.1&Request=GetCapabilities&Service=WMS
