### ISSUE TITLE
Erreur pour la remontée d'infos

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#205]
Un utilisateur nous a signalé que l'outil n'affichait pas les infos d'une parcelle (AL 228 au Puy en Velay)

Dans le JS, on voit l'erreur suivante : 

TypeError: result[0].surfc is null => detailUniteCadastrale.js:110:58

Il semble que pour cette parcelle, la surface n'ait pas réussi à remonter du SIG, il est dommage que cela empêche l'apparition des autres infos de la parcelle.

**Comment by jusabatier** [comment]
J'ai constaté que certaines parcelles étaient présentes dans la table "parcelle" du cadastre, mais n'avaient pas d'équivalent dans la table "geo_parcelle" et donc qu'il n'est pas possible de leur associer une géometrie.

Ce cas semble ne pas être fréquent et je ne sais pas comment l'expliquer, surement une incomplétude des données fournies par la DGFiP au moment de leur export.

En tout cas je pense qu'il faudrait gérer ce cas de figure un peu mieux, par l'affichage d'une pop-up indiquant qu'aucune entité géométrique n'a pu être associé à la parcelle, mais faire en sorte que l'on puisse tout de même consulter les données disponibles (propriétaire, bati, etc...)

**Comment by catmorales** [comment]
Sans doute des parcelles présentes dans les fichiers majic et pas dans les fichiers Edigéo. C'est un cas fréquent dû au décalage entre les mises à jour du parcellaire graphique (Edigéo) et des données majic. On peut également rencontrer le contraire.
Maël l'évoque d'ailleurs pour nous dans https://github.com/georchestra/cadastrapp/issues/201
