### ISSUE TITLE
Bouton : Recherches avancées/parcelle/par adresse cadastrale

### ISSUE THREAD

**Issue by stous** [georchestra/cadastrapp#206]
Lorsque j'effectue une recherche avancée sur une parcelle par son adresse cadastrale (Recherches avancées/parcelle/par adresse cadastrale) je dois cliquer 2 fois sur le menu 'par parcelle cadastrale' pour que la boite de dialogue s'ouvre :
-  au 1er clic rien ne se passe (les menus restent dépliés) 
- au 2nd clic la fenêtre de recherche s'ouvre (les menus restent dépliés)

**Comment by landryb** [comment]
Je reproduis ce pbm sur la plateforme du puy sur n'importe lequel des items du sous-menu parcelle, et dans la console JS il y'a:

```
TypeError: GEOR.ls.get(...) is null -> searchParcelleByRef.js:93
```

L'appel vient de GEOR.Addons.Cadastre.initRechercheParcelle/parcCityCombo1<.listeners.afterrender()

Au 2e clic, nouvelle erreur dans la console:

```
TypeError: this.manager is undefined
```

Avec firefox 48 beta.

**Comment by stous** [comment]
testé et reproduit sur la visionneuse : 
- du CRAIG, 
- de GFi 
- du Puy en Velay

**Comment by landryb** [comment]
Après mise a jour ici, comportement ok - merci @jusabatier !
