### ISSUE TITLE
Dimension fenêtre : Recherches avancées/parcelle/par adresse cadastrale

### ISSUE THREAD

**Issue by stous** [georchestra/cadastrapp#207]
La dimension de la fenêtre Recherche des parcelles par adresse cadastrale ne permet que de voir et de saisir la ville, et on n'accède pas aux champs suivants : Nom de voie ou lieu-dit et n°/complément.
Ce problème se produit en utilisant "Recherches avancées/parcelle/par adresse cadastrale" et ne se produit pas si je clique sur "recherche par parcelle" et que je bascule sur l'onglet "Adresse cadastrale".

**Comment by MaelREBOUX** [comment]
Moi j'ai ça sur la recherche par proprio après avoir tout purgé. A voir si j'arrive à reproduire.

**Comment by landryb** [comment]
C'est _mieux_ maintenant après la correction de @jusabatier , par contre si via le menu on choisit 'recherche par ref cadastrale' la fenetre fait ~150px de haut, et si on switche sur l'onglet 'par adresse' la fenetre n'est pas redimensionnée en hauteur pour afficher tout les champs de l'onglet, mais au moins il y'a l'ascenseur et on peut scroller.

**Comment by jusabatier** [comment]
Ou alors il est également possible de redimensionner la fenêtre manuellement.

Peut-être voir pour fixer la taille minimum de la fenêtre afin que tout rentre, ou alors si c'est possible mettre en place un redimensionnement au changement d'onglet pour s'adapter au contenu.

A voir ce qui est possible, je n'ai pas le temps de le faire dans l’immédiat mais j'essayerais de le regarder à l'occasion.

**Comment by landryb** [comment]
Ce que je ne comprends pas, c'est qu'aucune height n'est forcée pour la fenetre de recherche de proprio et l'autolayout marche bien la-bas. C'est `layoutOnTabChange` qui est sensé faire ca, mais je n'ai pas l'impression que ca marche si aucune hauteur n'est fixée.

La, avec 150px, au moins tout les onglets passent, qu'on y arrive via le menu ou le bouton parcelle.

**Comment by pierrejego** [comment]
Hello,
... j'avais galérer plusieurs jours sur ce point, il semblait que tout était ok. Dommage, merci pour la correction

**Comment by stous** [comment]
Le problème de dimensionnement de la fenêtre de recherche se retrouve pour la recherche par propriétaire, je ne vois que la ville et je n'ai pas la possibilité de saisir un nom

**Comment by landryb** [comment]
@pierrejego : il faut probablement rajouter un attribut height qqpart

**Comment by MaelREBOUX** [comment]
On en est où sur ce ticket ?

**Comment by landryb** [comment]
A moitié fixé si tu lis les commentaires...

**Comment by MaelREBOUX** [comment]
Réglé en 1.4 avec ce commit https://github.com/georchestra/cadastrapp/commit/dfc48c12335501ecb251bd481549b48ee1e66587
