### ISSUE TITLE
Uniquement la couche 'selection' est ajoutée a la liste des couches quand l'addon est activé

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#21]
Si on déselectionne l'outil cadastre dans la liste des outils et qu'on supprime les couches specifiques au cadastre dans la liste des couches, et qu'on réactive l'addon cadastre dans le menu outils, uniquement la couche 'selection' est ajoutée a la liste des couches, pas la couche des parcelles et/ou communes.

Il faut aller a la main ajouter geo_parcelle/geo_commune/edi_comm/edi_parc depuis le menu ajouter de mapfishapp, mais les couches correspondant au modele utilisé devraient être ajoutées automatiquement à l'activation du module.

**Comment by sdhem** [comment]
Vérifier sur plateforme de qualif => OK avec firefox
Vérifier sur plateforme de dev => OK avec Firefox

**Comment by landryb** [comment]
Juste un détail.. mais c'est bien de préciser quel commit fixe un ticket (le lien peut se faire automatiquement dans le message de commit en ajoutant 'fixes #21' dans ce cas) - ainsi on s'y retrouve mieux... en l'occurence, je suppose que c'est https://github.com/GFI-Informatique/addons/commit/544b5da92a533126d87feb8897cb1593771cb15e. Je vérifierais bien sur la plateforme de qualif (j'avais un autre ticket a remonter) mais ca a l'air dans les choux actuellement (NS_ERROR_FILE_CORRUPTED sur mapfishapp.js dans firebug)
