### ISSUE TITLE
Checkbox individuelles inactives sur liste des copropriétaires

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#212]
Sur l'onglet 'Co-propriétaire' d'une parcelle (ex 2014430157000AC0371 sur notre pf de test) il y'a 67 co-propriétaires, mais il n'y a aucun moyen d'en selectionner à la main pour (je suppose) les intégrer dans le relevé de propriété a générer. Uniquement la checkbox 'globale' fonctionne (et coche toutes les autres), les checkbox individuelles sont inactives. Rien dans la console

**Comment by landryb** [comment]
En fait, je me rends compte qu'il faut cliquer sur la ligne pour 'selectionner' le co-propriétaire - dans l'onglet propriétaire, peu importe si on clique sur la ligne ou la checkbox, les 2 manières marchent pour selectionner un propriétaire. Il faut juste harmoniser le comportement...

**Comment by MaelREBOUX** [comment]
oui : on prend vite le coup sur ce truc mais c'est pas hyper logique. 
A garder de côté pour améliorer.

**Comment by MaelREBOUX** [comment]
+1 ok ici
