### ISSUE TITLE
Problème affichage fiche parcelle

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#216]
J'ai encore et toujours le même problème qui revient chez certains de mes utilisateurs (aléatoirement).

Voici un exemple de celui-ci : 

![image](https://cloud.githubusercontent.com/assets/8310116/16489336/5e5881da-3ed5-11e6-9ea0-c46a9aa953d4.png)

Donc l'utilisateur essaye d'ouvrir le fiche de la parcelle, mais rien ne s'affiche.

Cependant les données sont bien présentes dans les requêtes réseau, et ajoutées dans le DOM html.

J'ai constaté que le problème semble venir de Ext, et plus particulièrement du `<form>` sélectionné sur mon screenshot dans l'outil dev de firefox, en effet sa propriété "height" est fixée à 2px, ce qui empêche la fiche de la parcelle de s'afficher (idem pour n'importe quel autre onglet).

Ce problème est très handicapant chez nous...

Donc si quelqu'un a une idée pour le résoudre ?

Personne d'autre n'a constaté ce comportement chez certains de ses utilisateurs ?

**Comment by landryb** [comment]
Et la console dit quoi ?

**Comment by jusabatier** [comment]
Ben rien comme erreur dans la console justement c'est bien ça qui est bizarre...

Aucuns logs / warning / erreur

**Comment by MaelREBOUX** [comment]
Je n'ai pas constaté ce pb ici.

**Comment by jusabatier** [comment]
J'ai trouvé de nouveaux logs concernant ce problème, ceux-cis arrivent après avoir cliqué sur rechercher, et lors de l'utilisation de "recentrer sur la selection" : 

```
14:54:40,581 loadParcelleStore : [object Object]430157AN searchUtils.js:98:5
14:54:45,599 loadParcelleStore : [object Object]430157AP searchUtils.js:98:5
14:54:47,830 Not enough data to call the webservice  searchParcelleByRef.js:486:37
14:54:52,150 TypeError: features[0].geometry.bounds is null
```

Du coup l'affichage de la fiche de parcelle est impossible, ainsi que le recentrage sur celle-ci.

**Comment by MaelREBOUX** [comment]
Ca c'est la conséquence de #201 : cette parcelle est référencée dans la matrice foncière (majic) mais elle n'existe plus sur le plan (edigeo).

**Comment by jusabatier** [comment]
Ce problème ne vient pas que de #201 car en utilisant la navigation privée il se résoud. Il n'est pas lié à une parcelle en particulier, lorsqu'un utilisateur le rencontre elles sont toutes affectées et il est obligé de passer en navigation privée ou de vider completement cache, cookies, données de navigations via Ctrl+Shift+Suppr.

**Comment by jusabatier** [comment]
Je viens enfin de trouver d'où vient ce problème, et je pense que toutes les plateformes sont concernées : 

Ce bug survient lorsqu'un utilisateur a une résolution trop faible sur son écran, ou bien que le niveau de zoom de son navigateur est trop élevé, ce qui semble faire planter le rendu de la fenêtre de fiche d'info.

**Comment by MaelREBOUX** [comment]
OK : je le reproduit aisément ici.

**Comment by landryb** [comment]
@jusabatier : peux tu préciser 'résolution trop faible' ou 'niveau de zoom trop elevé' ? Selon toi, c'est la "place disponible sur l'écran" qui n'est pas suffisante pour afficher la fenetre ? C'est un peu empirique pour rechercher ce qui peut causer ce souci....

**Comment by jusabatier** [comment]
Je pense en effet que c'est la place disponible sur l'écran qui pose problème.

Dans le cas d'une résolution trop faible, le zoom normal ne dispose pas d'assez de place et déclenche le bug.

Dans le cas d'un utilisateur qui met son zoom à 130%, cela a le même effet qu'une résolution trop faible.

Le bug n'est pas difficile à reproduire, il suffit de zoomer à 130~150% et d'essayer d'afficher la fiche d'info d'une parcelle.

**Comment by jusabatier** [comment]
Je relance cette issue car j'ai une secrétaire de mairie qui a été opérée des yeux et qui n'y voit du coup pas très bien.

Elle utilise donc des résolutions assez faible pour pouvoir lire les écritures dans ses logiciels.

Il va donc me falloir trouver assez rapidement comment solutionner ce bug :/

Personne n'a une idée de ce qui peut provoquer ce comportement avec ExtJS ?

@landryb @pierrejego @fvanderbiest

**Comment by landryb** [comment]
Le problème principal, c'est qu'on utilise une version d'ExtJS dépréciée depuis 5+ ans.. et que du coup, bon courage pour trouver des 'spécialistes' pour cette version.

**Comment by jusabatier** [comment]
J'ai trouvé comment résoudre ce problème

Cf. https://github.com/georchestra/cadastrapp/pull/304

@pierrejego pour valider
