### ISSUE TITLE
Problème sur la recherche par nom de propriétaire

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#219]
Fenêtre de recherche d'un proprio > par nom.

SI on commence à taper, les résultats arrivent sous la forme :  NOM [espace] [pipe] [espace] DDENOM

![screenshot087](https://cloud.githubusercontent.com/assets/6370443/16519735/722b0eb0-3f8b-11e6-9e79-2373c88f0744.png)

Si on tape ensuite un espace pour commencer à taper le prénom -> la liste de suggestion disparaît

![screenshot088](https://cloud.githubusercontent.com/assets/6370443/16519745/87992872-3f8b-11e6-8cef-18b25e8af51a.png)

Le pb est contourné par la saisie d'un % à la place de l'espace

![screenshot089](https://cloud.githubusercontent.com/assets/6370443/16519769/a609695c-3f8b-11e6-8f74-1a4fa1d27a6c.png)

**Comment by jusabatier** [comment]
Ceci peut être résolu assez facilement en utilisant un str_replace sur le paramêtre, comme c'est fait pour la recherche sur le globalName : 

https://github.com/georchestra/cadastrapp/blob/master/cadastrapp/src/main/java/org/georchestra/cadastrapp/service/ProprietaireController.java#L120

https://github.com/georchestra/cadastrapp/blob/master/cadastrapp/src/main/java/org/georchestra/cadastrapp/service/ProprietaireController.java#L113

**Comment by MaelREBOUX** [comment]
Correction à faire côté webapp donc.
@jusabatier euh : tu peux t'en charger ?

**Comment by MaelREBOUX** [comment]
Extra mad !

**Comment by pierrejego** [comment]
Vérifier pourquoi ce n'était le même comportement à la base.

**Comment by MaelREBOUX** [comment]
je rentre de congés.
Nope : ça ne corrige rien du tout chez nous.
:(

**Comment by jusabatier** [comment]
Pourtant sur notre instance, le problème a été résolu avec ce patch.

As-tu bien fait un git pull puis recompilé/redéployé la webapp ?

SI c'est le cas, il faudrait voir si le souci n'est pas lié au modèle arcopole, même si ce serait étonnant vu que la modification porte sur le SQL qui est commun aux deux modèles.

**Comment by MaelREBOUX** [comment]
Je pense que Catherine a fait ce qu'il faut puisque le bouton "aide" apparaît maintenant dans la barre d'outils.

**Comment by landryb** [comment]
> Je pense que Catherine a fait ce qu'il faut puisque le bouton "aide" apparaît maintenant dans la barre d'outils.

Ca ne veut rien dire, les changements pour le bouton "aide" étaient uniquement dans la partie addon mapfishapp, les changements qu'a fait julien étaient uniquement dans la webapp java..

**Comment by MaelREBOUX** [comment]
Exact : mais je suis presque certain qu'elle fait les 2 en même temps. Elle m'a confirmé avoir redéployé le module entier le 29 juillet.
Ce qui ne fait rien à mon affaire... :(

**Comment by MaelREBOUX** [comment]
seul l'add-on a été redéployé fin juillet, pas la webapp. Attente de redéploiement sur PF test par @pmauduit pour voir.

Mais mon patch pour enlever le / dans ddenom semble produire un effet bénéfique.

**Comment by landryb** [comment]
> seul l'add-on a été redéployé fin juillet, pas la webapp. Attente de redéploiement sur PF test par @pmauduit pour voir.

Ah, ca me paraissait quand meme bien étonnant..

> Mais mon patch pour enlever le / dans ddenom semble produire un effet bénéfique.

Quel patch ? Y'a un rapport avec ce pbm ?

**Comment by MaelREBOUX** [comment]
En supprimant  le / dans ddenom je n'ai plus à saisir un % à la place de l'espace
logique : c'est un espace dans les données, plus un /

**Comment by MaelREBOUX** [comment]
réglé
