### ISSUE TITLE
Limiter la longueur du libellé de l'onglet dans la fenêtre résultat de parcelle

### ISSUE THREAD

**Issue by sdhem** [georchestra/cadastrapp#22]
Lors d'une recherche de parcelle par identifiant cadastral sur plusieurs parcelles. Toute la liste des parcelle sert comme libellé. Cela peux être très long et posé des problèmes. Il est souhaitable de limiter la longueur du libellé à un identifiant, 3 petits points pour marquer que c'est une information partielle.

**Comment by pierrejego** [comment]
Modification apporté. l'onglet a maintenant le titre "par id(s)"

**Comment by landryb** [comment]
Il serait a mon avis mieux de garder un titre 'pertinent' permettant de distinguer les recherches comme le proposait sylvie dans son premier commentaire - et surtout c'est relativement facile à faire via la fonction ellipsis() de la classe Ext.util.Format.
