### ISSUE TITLE
[UI] Recherche propriétaire : nom marital VS recherche normale

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#220]
Pour débat.

Je suis perturbé par le fait que la liste des suggestions soit la même pour la recherche sur DDENOM et la recherche sur le nom marital.

Pour moi : en mode normal / classique la liste devrait simplement montrer DDENOM.
L'affichage nom marital [pipe] DDENOM ne devrait se produire que si on fait une recherche spécifique sur le nom marital (case cochée).

Ex :  recherche normale

![screenshot090](https://cloud.githubusercontent.com/assets/6370443/16519938/ce57d6c2-3f8c-11e6-8d2c-966b70ec3ef3.png)

Recherche nom marital

![screenshot091](https://cloud.githubusercontent.com/assets/6370443/16519943/d65fe83c-3f8c-11e6-93fe-5aaf3a7a3c96.png)

**Comment by MaelREBOUX** [comment]
Remarque périmée par mise en œuvre du nom d'usage VS nom de naissance.
cf #249 

Cependant : il convient de :
- supprimer le nom + pipe pour n'avoir que la chaîne qui correspond à app_nom_usage
- changement le nom de la checkbox en "recherche sur le nom de naissance"

**Comment by jusabatier** [comment]
Ces deux points sont gérés dans la dernière PR que j'ai fait sur labranche issue-249 de sigrennesmetropole

**Comment by MaelREBOUX** [comment]
je laisse ouvert en attendant le merge

**Comment by pierrejego** [comment]
@MaelREBOUX et @jusabatier 
Vu que j'ai mergé la branche issue-249, ce point est bon non ? 
Je vois bien le changement "recherche sur le nom de naissance"

commit https://github.com/georchestra/cadastrapp/commit/335bc3a3520c2ffc56da2c21afc21df1a1458ffc

**Comment by MaelREBOUX** [comment]
non c pas bon sur ta PF de qualif : ci-dessous c'est 'JEULAND REGINE' qui devrait apparaître et pas 'TIRE REGINE' qui est son nom d'usage.

**Comment by pierrejego** [comment]
Avec les modifications faites on fait bien un recherche sur le nom de naissance mais on affiche le nom d'usage.
Dans le cas ou la case est coché, on affiche quoi  ? le nom de naissance ou le nom d'usage + le nom de naissance ? ça va faire de très grand ligne, non ?

**Comment by jusabatier** [comment]
A mon avis pour être logique : 

Si case non cochée => Nom d'usage
Si case cochée => Nom de naissance

Ainsi on affiche ce sur quoi porte la recherche.

**Comment by pierrejego** [comment]
Ok parfait, Mael vient de me dire la même chose. je fais la modification toute suite.

**Comment by MaelREBOUX** [comment]
je confirme : on est bon !
