### ISSUE TITLE
Move default options to manifest.json

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#223]
As discussed with @fvanderbiest we can move the 'default values'  from a text in README.md to the default_options value in manifest.json, instead of keeping it empty, cf https://github.com/georchestra/cadastrapp/blob/master/addons/cadastrapp/manifest.json#L27. That's how other addons do, cf https://github.com/georchestra/georchestra/blob/15.12/mapfishapp/src/main/webapp/app/addons/locateme/manifest.json#L8-L21.

To be discussed monday, then i'll do a PR.

**Comment by MaelREBOUX** [comment]
peut-on fermer ce ticket ?

**Comment by landryb** [comment]
Fermé par #225
