### ISSUE TITLE
[UF] Fenêtre unité foncière : valeurs de surface en format américain

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#226]
![screenshot105](https://cloud.githubusercontent.com/assets/6370443/16577942/3bfc7b0c-4298-11e6-92bb-7df3836b5e42.png)

Ca induit en erreur en lecture rapide : passer dans le format français : sans décimales, séparateur des milliers = espace.
#

**Comment by MaelREBOUX** [comment]
c'est la fenêtre qui apparait si on coche "Unité foncière" dans la barre d'outils

**Comment by landryb** [comment]
De ce que je comprends du code, ces valeurs sont formatées par la fonction js 'toLocaleString', cf http://www.w3schools.com/jsref/jsref_tolocalestring.asp. Il faut voir ce qui manque pour dire 'la locale, c'est francais'...

**Comment by landryb** [comment]
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Number/toLocaleString a bien plus d'infos - a priori c'est un parametrage de navigateur qui influence ca

**Comment by landryb** [comment]
Ca ne corrige pas toutes les erreurs, pour celles de la liste des parcelles dans la fenetre des details d'UF, ca passe par un Ext.util.Format.numberRenderer et je n'ai pas trouvé les bons params ici - mais j'ai rajouté qqs appels manquants a toLocaleString.

Je ne suis toujours pas sur que ce soit la vraie source du pbm, on ne devrait pas avoir a forcer le lang..

**Comment by MaelREBOUX** [comment]
embêtant.
comment faire avancer ça ?

**Comment by MaelREBOUX** [comment]
Fixé par la nouvelle unité foncière avec la PR https://github.com/georchestra/cadastrapp/pull/386
