### ISSUE TITLE
[UF] Mettre le compte propriétaire en titre de la fenêtre "unité foncière"

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#227]
Il faut mettre un titre fixe / un titre en dur pour ces 2 fenêtres : ça nuit bcp au dépannage par téléphone et cela n'a pas d'utilité.

Je propose :
- "Informations sur la parcelle " avec option sur  "+ code parcelle"
- "Unité foncière"

**Comment by jusabatier** [comment]
En effet ça serait plus clair je pense

+1

**Comment by landryb** [comment]
Tu vas être super avancé avec 10 fenetres ExtJS ayant toutes le même nom.. a mon avis, par défaut il faut un moyen de les différencier.

**Comment by MaelREBOUX** [comment]
Même avec 10 ouvertes en même temps (rare qu'un utilisateur le fasse amha) : le code de parcelle apparaît clairement.

Pour l'UF : pas possible de mettre qqch de discriminant car c'est une continuité de compte proprio autour d'une parcelle.

**Comment by MaelREBOUX** [comment]
Ticket devenu obsolète avec la nouvelle fenêtre UF. Je ferme.
