### ISSUE TITLE
[UF] Rendre la fenêtre d'info sur une unité foncière indépendante de la fenêtre d'infos parcelle

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#228]
Les utilisateurs me remontent qu'ils ont trop de fenêtres ouvertes : on ne voit plus la carte.

Une demande précise : pouvoir fermer la fiche d'info d'une parcelle sans que cela ferme la fiche unité foncière et vice-versa.

**Comment by jusabatier** [comment]
Même souci ici, en formation.

Les utilisateurs nous disent qu'il y a trop de popups ouvertes en même temps.

Pour l'instant je leur dit de monter leur résolution (certains sont encore en 800 ou 1024...)

Sinon de fermer au fur et à mesure qu'ils n'en ont plus besoin (ce qu'ils devraient faire dans l'ancien logiciel aussi).

J'avais également ajouté quelques lignes de codes pour fermer le formulaire de recherche en affichant le resultat, je ne crois pas les avoir reversé car à l'époque ça n'interessait pas.

Dans la pratique çca permet déjà d'éliminer une popup :)

**Comment by MaelREBOUX** [comment]
Ticket obsolète avec les évolutions de la v 1.6
