### ISSUE TITLE
Navigation sur les onglets dans une fenêtre de résultat trop petite par rapport au nombre d'onglet

### ISSUE THREAD

**Issue by sdhem** [georchestra/cadastrapp#23]
Créer 5 ou 6 onglets dans une fenêtre de résultat (parcelle ou propriétaire). Réduire la taille de la fenêtre et essayer d'atteindre le premier et le dernier onglet. Il manque des flèches de navigation.

**Comment by pierrejego** [comment]
Il faudrait ajouter des fleches de navigation entre les onglets
