### ISSUE TITLE
Erreur image bordereau parcellaire

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#238]
Nous avons constaté une erreur sur les parcelle : 
2016430157000AC0495, 2016430157000AW0232, 2016430157000AZ0320

L'image de la parcelle ne s'affiche pas lors de la génération du bordereau parcellaire et dans les logs j'ai cette erreur : 

> 2016-07-25 16:53:46,957 [http-nio-8484-exec-405] ERROR /getImageBordereau - nouser - norole -o.a.c.i.AbstractFaultChainInitiatorObserver - Error occurred during error handling, give up!
> org.apache.cxf.interceptor.Fault: org.geotools.data.DataSourceException: could not determine namespace bound to element prefix null (position: START_TAG seen ...gml:featureMembers><null:geo_parcelle gml:id="geo_parcelle.64462">... @1:889)

**Comment by jusabatier** [comment]
Je viens de trouver une piste qui semble avoir résolu l'erreur : 

Dans la version 2.8.3 de GeoServer, dans la configuration du service WFS : par défaut le type des SRC est sur "URN expérimentale de l'OGC", je l'ai passé sur "URL HTTP aux normes OGC" et j'ai coché "Override GML Attributes", maintenant la génération des images sur les BP semble fonctionner à nouveau.

**Comment by MaelREBOUX** [comment]
ici on a ça et pas de pb. J'en déduirait qu'on utilise GML 2
et toi ?

![screenshot164](https://cloud.githubusercontent.com/assets/6370443/17851649/5985386c-6863-11e6-80b8-49ea644697e3.png)

**Comment by jusabatier** [comment]
Je ne sais pas du tout quel GML est utilisé par défaut.

Mes connaissances sur ce genre de paramètres dans GeoServer sont très limitées.

J'ai simplement testé les différentes options possibles à ce niveau et celles citées ci-dessus ont semblé corriger le problème.

**Comment by MaelREBOUX** [comment]
Donc tu as mis le même réglage partout pour GML 2 3 et 3.2 ?

**Comment by jusabatier** [comment]
Non j'ai juste modifié GML3 pour ne pas utiliser d'URN experimental mais une URL HTTP comme c'est le cas pour le GML2.

Je n'ai pas modifié le GML3.2 : 

![image](https://cloud.githubusercontent.com/assets/8310116/17854686/af07c3b6-6874-11e6-8d80-746f04351b26.png)

**Comment by landryb** [comment]
Je viens de voir ce bug aussi:
```
org.apache.cxf.interceptor.Fault: org.geotools.data.DataSourceException: could not determine namespace bound to element prefix null (position: START_TAG seen ...embers><null:geo_parcelle_2016 gml:id="geo_parcelle_2016.2666623">... @1:794)
```
Mais mon cadastrapp est (toujours...) ancien: 1.3+201606290950

Je n'ai pas l'impression que ce soit 'constant', car j'ai des images générées correctement 'des fois' (ie des /tmp/cadastrapp/BP-*.png) 

toujours geoserver 2.8.1, je regarde ce que j'ai dans la config des URN geoserver...

**Comment by landryb** [comment]
![capture d ecran_2017-03-14_15-56-32](https://cloud.githubusercontent.com/assets/3421760/23906631/df724a94-08ce-11e7-90f2-b9024abca853.png)

J'imagine que c'est la conf par défaut - et j'ai un peu de mal a voir en quoi ca changerait quoi que ce soit pour cadastrapp, mais les voies de geoserver me sont impénétrables...

**Comment by landryb** [comment]
Et en changeant juste pour GML 3 'URL HTTP aux normes OGC' + cocher 'Override GML Attributes', ca remarche. Donc merci @jusabatier - mais ca reste complétement du vaudou pour moi :)

**Comment by landryb** [comment]
Au passage, dans mon infra 'répartie', j'ai 2 instances de cadastrapp en load balancing, donc pour une requète de generation de BP, l'image va se retrouver dans /tmp/cadastrapp/ sur le premier serveur, et le pdf renvoyé a l'utilisateur dans /tmp/cadastrapp sur le second serveur. J'espère que cadastrapp n'assume pas que les fichiers sont relus directement du meme endroit sur la meme machine, et de toute facon je doute que ce soit lié à ce bug en particulier.

**Comment by jpklipfel** [comment]
>Et en changeant juste pour GML 3 'URL HTTP aux normes OGC' + cocher 'Override GML Attributes', ca remarche. Donc merci @jusabatier - mais ca reste complétement du vaudou pour moi :)

Même chose pour moi merci pour cette solution inespérée!

**Comment by pierrejego** [comment]
@landryb, je n'ai pas testé le comportement en load balancing. Pour la partie image, c'est sur ça ne pose pas de problème.
Pour le reste au vu du code, ça ne devrait pas poser problème, j'avais peur que la partie demande d'information pose soucis, mais non génère directement les pdf à partir de la base. Donc même si ta demande arrive sur un serveur et la génération des docs sur l'autre c'est tout bon.

 Si jamais tu rencontrais des soucis tu pourrais toujours faire un point de montage et partager le /tmp/cadastrapp sur les deux serveurs.

**Comment by pierrejego** [comment]
@landryb et @jusabatier  pour cette erreur : 
org.apache.cxf.interceptor.Fault: org.geotools.data.DataSourceException: could not determine namespace bound to element prefix null (position: START_TAG seen ...embers><null:geo_parcelle_2016 gml:id="geo_parcelle_2016.2666623">... @1:794)
je l'ai eut aussi mais pas sur cadastrapp, sur un autre projet ou l'on fait de la classification.

ça se produit si tu fais une requête WFS (pour moi classify) sur un entrepôt, puis sur un autre. Le geoserver perd alors ces petits, Le fait de changer dans la liste déroulant recharge le geoserver et corrige le soucis temporairement. Chez moi ça revient dès qu'on fait deux appels WFS sur deux entrepôts différents sans repasser par le WFS globla.

Le soucis est expliqué ici : https://groups.google.com/forum/#!topic/georchestra/B3uleTC5Hq0, @fvanderbiest préconise de changer de version de geoserver.

Il y a ces issues qui en parlent. 
https://osgeo-org.atlassian.net/browse/GEOS-8017
https://osgeo-org.atlassian.net/browse/GEOS-4773
https://osgeo-org.atlassian.net/browse/GEOS-6014

Le test de changement de version est dans les tuyaux chez nous. @landryb chez toi, tu peux peut-être mettre la couche dans MapServer.

Je pense qu'on peut fermer cette issue, car elle est dépendant de la version de geoserver et non de l'applicatif.

**Comment by landryb** [comment]
Pour info, meme avec la config des commentaires précédent, le bug revient en douce..

**Comment by jpklipfel** [comment]
Chez nous aussi

**Comment by ghost** [comment]
Je suis d'accord avec vous, par contre, pour moi c'est une erreur de geoserver, pas du cadastre. Je pense que c'est pour ça que nous l'avions fermé. 

J'ai toujours ce soucis sur une autre projet, la solution de contournement est pour l'instant de changer les informations GML, valider puis les remettre. ça met à jour quelques choses que je n'ai pas encore eut le temps d'aller voir du coté de geoserver et les requêtes refonctionnent. 

La solution proposée c'est juste pour faire une sorte de refresh de geoserver (mais chez moi l'arrêt redémarage du geoserver ne fonctionne pas pour cette erreur).
De notre coté, on a cette erreur, lors qu'on fait des classifications en chaîne sur plusieurs workspaces différents.
