### ISSUE TITLE
Erreur impression documents demande d'infos copropriétaire

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#239]
J'ai une erreur avec la génération des documents de la demande d'infos, dès que la demande d'info porte sur un copropriétaire (en revanche ça fonctionne si on passe par la fiche de la parcelle) : 

Si j'essaye d'imprimer un Bordereau Parcellaire, j'ai une erreur 500 avec ce message dans mes logs

> java.lang.RuntimeException: org.apache.cxf.interceptor.Fault: Missing root object specification in trailer.

Le PDF du bordereau parcellaire semble ne pas se générer correctement, si je regarde dans le dossier tmp de mon serveur, le BP correspondant à la demande est bien créé mais il est corrompu.

L'application ne semble pas gérer le cas où la demande porte sur un co-propriétaire et non sur un propriétaire.

**Comment by omarmancourbillah** [comment]
Bonjour, Julien,

C'est probablement un souci lors de la transformation PDF, l'objet   BorderauParcellaire que l'on passe à la méthode genererPDF ne doit pas contenir les infos nécessaire à la transformation, il doit manqué un contrôle à ce niveau là.

Quel type de demande as tu utilisé pour générer l'erreur (parcellaire, co-pro...)?

Cordialement,

Mançour Billah Omar
Gfi Informatique consultant SIG/J2EE

omar.mancour-billah@gfi.frhttps://amsprd0511.outlook.com/ecp/Customize/Messaging.aspx?showhelp=false
8, square du Chêne Germain – 35510 Cesson-Sévigné
+33 (0)2 99 63 85 86
+33 (0)6 16 55 92 36

www.gfi.frhttp://www.gfi.fr/

—

Rejoignez-nous sur Facebookhttp://on.fb.me/uOp57O / Linkedinhttp://linkd.in/uI5kYG / YouTubehttp://www.youtube.com/user/GFIinformatique/featured / Google+http://bit.ly/rV2TEQ / Twitterhttp://www.twitter.com/gfiinformatique / Instagramhttp://instagram.com/gfiinformatique

---

De : Julien Sabatier notifications@github.com
Envoyé : mardi 26 juillet 2016 09:46:02
À : georchestra/cadastrapp
Objet : [georchestra/cadastrapp] Erreur impression documents demande d'infos (cas particulier) (#239)

J'ai une erreur avec la génération des documents de la demande d'infos, mais celui semble se produire sur seulement certains propriétaires (en revanche ça fonctionne si on passe par la fiche de la parcelle) :

Si j'essaye d'imprimer un Bordereau Parcellaire, j'ai une erreur 500 avec ce message dans mes logs

java.lang.RuntimeException: org.apache.cxf.interceptor.Fault: Missing root object specification in trailer.

Une idée de ce qui peut causer cette erreur ?

**Comment by jusabatier** [comment]
Je viens de corriger l'erreur via cette PR : https://github.com/georchestra/cadastrapp/pull/241

Le problème venait des co-propriétaires qui n'étaient pas gérés dans le cas d'une recherche sur un objet "Propriétaire", alors qu'ils apparaissent dans la liste déroulante.
