### ISSUE TITLE
Utiliser l'outil de selection classique sur une autre couche modifie la selection dans la liste des parcelles

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#24]
Lorsque le module cadastre est activé, on ne peut plus vraiment utiliser l'outil de requete sur une autre couche préalablement chargée, il y'a un conflit d'utilisation - j'ai fait le test sur une couches de parcelles, selectionner l'outil d'interrogation de la couche (celui dans la liste des couches, pas celui du module cadastre) et cliquer sur des parcelles va 1) et montrer la selection dans la liste en bas, 2) et modifier la selection de la liste des parcelles du module cadastre - ce qui ne devrait pas arriver.

Autant que possible, le module cadastre devrait utiliser une nouvelle instance du controle openlayers de selection des objets (OpenLayers.Control.WMSGetFeatureInfo?) et celle ci devrait etre indépendante du controle 'generique' utilisé par la visionneuse pour les autres couches. Ou le module cadastre devrait désactiver la possibilité d'interroger les autres couches s'il est activé, mais c'est peu souhaitable.

**Comment by sdhem** [comment]
Je reproduis cela sur la plateforme de qualif. J'ajoute la couche edi_comm. Lorsque j'essaie de construire une requête avec une condition spatiale sur la couche edi_comm, cela donne une sélection de parcelle non souhaitée et le résultat de la requête sur la couche edi_comm n'apparait pas dans la fenêtre 'Search' de base de geOrchestra.

**Comment by pierrejego** [comment]
Mettre le toogle bouton dans le toogle group de mapfishapp

**Comment by landryb** [comment]
Je pense que le bouton zoom de la toolbar cadastre n'a pas besoin d'etre un toggle, une fois qu'on clique dessus et que le zoom a été fait il devrait revenir dans son état normal.

Les 3 toggle bouton activant les controles graphiques openlayers (point/ligne/polygone) sont ceux qui ont besoin d'etre dans le togglegroup mapfishapp pour eviter les conflits avec les autres controles (zoom general, interrogation d'un objet dans une autre couche, etc..)

**Comment by MaelREBOUX** [comment]
suis d'accord avec @landryb pas besoin de toogle.
ce jour je crois que c'est corrigé.

**Comment by pierrejego** [comment]
Je viens de changer le toggle groupe des éléments de sélection, c'est maintenant le même que le reste de l'application.
@landryb je te laisse retester sur ta PF et fermer l'issue.

**Comment by landryb** [comment]
GFI-Informatique/addons@5b36a49890e07bd6d231a1234e796ff0fe9bbdcf
( GFI-Informatique/addons@178a1a57833c479273b8a89c74ab5641ffef6e90 n'est pas lié a ce ticket je crois)

**Comment by landryb** [comment]
Le probleme est toujours présent apres maj de l'addon, j'arrive a mettre les outils dans un état incohérent (TypeError: this.layer is undefined dans firebug).

Si je selectionne l'outil d'interrogation de mfapp sur une couche 'standard' (la couche geo_parcelle necessaire a l'addon, affichée dans la liste des couches), puis clique sur le bouton point de la toolbar cadastrapp, l'outil d'interrogation est bien désactivé. Si je reclique dessus, le bouton point de la toolbar cadastrapp n'est pas désactivé.
Sur une autre couche (non utilisée par l'addon) c'est ok.

**Comment by landryb** [comment]
Je confirme après une nouvelle maj - il y'a toujours un probleme si on veut faire une interrogation 'classique' sur la couche geo_parcelle dans le cas ou elle est présente dans le layertree.

Sinon c'est ok pour le comportement du togglegroup/bouton zoom.

**Comment by landryb** [comment]
Pb toujours présent, on ne peut pas utiliser l'outil d'interrogation classique sur la couche support si un des outils de la barre d'outil cadastre est actif - toujours un pbm de togglegroup ?

**Comment by pierrejego** [comment]
Oui, je n'ai pas réussit à corriger pour l'instant je pense qu'il faut passer par l'url en OWS pour que ça marche, c'est ce que je regardais dans le code de mapfishapp dans lequel il y a une surcharge du layer switcher. Mais j'ai pas encore très bien compris comment ça marchait, je continue à regarder comment ça marche la partie OWS.

**Comment by pierrejego** [comment]
lié à l'issue #114 
Il faut revoir la façon dont on insère la couche dans le switchlayer. Il faut utiliser le fonctionnement de mapfishapp et non juste faire un add dans le switchlayer openlayer

**Comment by pierrejego** [comment]
https://github.com/GFI-Informatique/addons/commit/3f74f9d13b198f0f1191671bea4d13376da1172c
