### ISSUE TITLE
[UF] impression fiche d'info unité foncière

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#243]
Dans le fonctionnement actuel du module cadastre, l'information sur une unité foncière vient en plus de la consultation d'une parcelle cadastrale :
1. coche "UF" dans la barre d'outils
2. clic sur une parcelle avec outil de sélection
3. double-clic sur la parcelle dans la fenêtre de sélection de parcelle

=> ouverte de la fiche d'info parcelle ET de la fiche d'info sur l'unité foncière à laquelle appartient la parcelle.

A ce stade on a une régression par rapport à notre outil actuel car on faisait apparaître sur la carte l'unité foncière en question et elle seule. Puis on ouvrait une fenêtre d'info qui pouvait être imprimée.

![screenshot138](https://cloud.githubusercontent.com/assets/6370443/17437033/90ee304c-5b1b-11e6-98fe-82aa0e358897.png)

Pour avoir une presque équivalence actuellement, il faut charger manuelle la couche des UF et faire une symbologie à la main :

![screenshot139](https://cloud.githubusercontent.com/assets/6370443/17437066/c16b478c-5b1b-11e6-9533-a84076246427.png)

Puis imprimer une carte standard mais sans **les infos sur l'UF qui ne sortent ainsi pas du "système" : elles sont uniquement affichées sur un écran, aucun copier-coller possible.**

Ma proposition d'évolution est de rajouter sur la fenêtre d'infos de l'UF un bouton "Imprimer" qui va demander à la webapp (nouveau service à créer) la création d'un équivalent au bordereau parcellaire mais pour une UF.

Il reste à gérer la question de l'affichage automatique de l'UF sur la carte : ajout d'une surcharge graphique ou chargement de la couche puis application d'un SLD filtrant sur l'UF en question ?

A vos avis.

**Comment by MaelREBOUX** [comment]
En fait, cette fonction fait partie du cahier des fonctionnalités v 1.1
- article 3.11.3 p. 68
- la méthode createPDFUf sur la webapp p. 9

En fait, la table uf_parcelle est juste une table de relation attributaire : **elle n'a pas de géométrie** !

**Comment by landryb** [comment]
Si c'est dans le CdC... @pierrejego ?

**Comment by MaelREBOUX** [comment]
et zut : doublon avec #171 : merci de fermer #171

**Comment by pierrejego** [comment]
Bonjour,
peux tu me renvoyer la documentation dont tu parles @MaelREBOUX, je viens de regarder ce que j'ai et c'est juste indiqué de s'inspirer de l'exemple, il n'y a pas du tout de notion d'impression.

**Comment by MaelREBOUX** [comment]
@pierrejego @landryb @jusabatier 

Okay @catmorales me rafraîchit la mémoire. Nous avions laissé en suspend ce point car du côté arocopole nous générons une couche des UF. Ce qui n'est pas fait par défaut par le plugin cadastre de QGIS. Nous avions découvert qu'il suffit de jouer un script supplémentaire (SQL de mémoire) pour les générer.

La question directe s'adresse donc à ceux qui opèrent du modèle QGIS : générez-vous maintenant systématiquement cette couche ?
Pour nous c'est inconditionnel des besoins des chargés d'urbanisme.

Au pire : ne pourrait-on pas mettre cette fonctionnalité (carte-image de l'UF insérée dans la fiche d'info UF) optionnelle ? Dans le cadastrapp.properties ?
Je l'active si j'ai une couche UF + j'indique laquelle -> j'aurais une image.
Je ne la gère pas -> pas d'image dans le fiche d'infos.

**Comment by jusabatier** [comment]
Pour l'impression de la geometrie : dans le modèle QGis il y a une table geo_unite_fonciere qui permet tout à fait d'avoir la géometrie correspondante et qui est déjà utilisée dans le script de création de la table uf_parcelle

**Comment by pierrejego** [comment]
Après discussion avec @MaelREBOUX.
Dans l'idée, on va se servir des couches geo UF ( geo_unite_fonciere pour Qgis et rm_uf pour Arcopole) pour l'affichage des UFs sur la carte, et continuer à se servir des couches parcelles pour récupérer les informations attributaires. (Propriétaire, contenance, liste des parcelles)

Les fenêtres existantes concernant les UF n'existeront plus.

Le fonction sera le suivant :
1 - Lorsque que l'on cochera UF, la couche UF remplacera la couche parcelle et seul l'outils point sera disponible et toutes les autres fenêtres de cadastrapp à part la barre d'outils seront fermées. 
2 - On cliquera alors directement sur la carte ce qui sélectionnera une UF (les couleurs de sélections seront les mêmes que pour les parcelles) et ouvrira une nouvelle fenêtre (dans l'idée cette fenêtre sera en HTML et non en ExtJs) 
2 - Bis, en même temps, mais de façon caché, un appel WFS vers la couche cadastre sera faite pour faire le lien avec la table UF et récupérer les informations attributaires (comme actuellement)
3 - La fenêtre contiendra ( de haut en bas ) titre, reprise de l'image visible sur la carte, information sur l'UF (Proprietaire, surface DGFIP, Surface calculée), Liste des parcelles et leur contenance DGFIP

@MaelREBOUX,  il n'y aura pas les informations de surface Bâtie.  Et actuellement nous avions aussi l'adresse et la surface SIG des parcelles, est-ce que l'on garde ces informations ?

Aux autres, est-ce que ce nouveau fonctionnement vous va ?

**Comment by pierrejego** [comment]
Si je veux pouvoir ouvrir une nouvelle page HTML depuis l'addon, il faut soit qu'on héberge la page HTML sur un serveur web (apache, ngnix), soit que je modifie un tout petit peu mapfishapp pour que les addons puissent charger des pages html https://github.com/georchestra/georchestra/blob/c3a102904add4b4f00415fa373c51d2d0367094f/mapfishapp/src/main/java/org/georchestra/mapfishapp/ws/AddonController.java#L164
pour ajouter 
```
else if (("htm".equalsIgnoreCase(ext)) || ("html".equalsIgnoreCase(ext))) {
            response.setContentType("text/html");
        }
```
Je suis plutôt pour la deuxième proposition mais ça veut dire que cette partie ne fonctionnera que si on a une nouvelle version de mapfishapp.

  @pmauduit @fvanderbiest @landryb @jusabatier vous pensez quoi de la deuxième possibilité ? Est-ce que ça vous choque qu'un addon mapfishapp puisse charger une page html ?

**Comment by fvanderbiest** [comment]
Pour ma part ça ne me choquerait pas, vu que c'est un fichier mis à disposition par l'admin, a priori considéré comme safe.

**Comment by pierrejego** [comment]
Quel rapidité de réponse !!! Bravo et merci pour la release 17.12

**Comment by landryb** [comment]
Après en avoir discuté avec @pierrejego je suis pas méga fan (qqch en moi me dit que ca pourrait amener des injections de js ? plus que maintenant ?) mais j'ai pas de vrai argument technique contre :)

Par contre sur le fond, expérimenter avec l'impression client-side :+1: :+1:

**Comment by pierrejego** [comment]
Très belle réponse de normand :) Je retiens le 👍

**Comment by MaelREBOUX** [comment]
> @MaelREBOUX, il n'y aura pas les informations de surface Bâtie. Et actuellement nous avions aussi l'adresse et la surface SIG des parcelles, est-ce que l'on garde ces informations ?

Je pense que si on avait mis la surface bâtie calculée (somme des surfaces bâties des parcelles composant l'UF) c'est qu'on nous l'avait demandé. Mais cette donnée n'existe pas actuellement dans aucun des 2 modèles de données. Il faudrait déclencher des évolutions sur ces 2 modèles pour l'avoir...
Donc pas le choix : on s'en passe pour le moment. On verra si on a des réactions.

> je me disais que plutôt que de cocher sur UF puis sur point. On pourrait directement faire un bouton UF qui serait qui permet de faire l’action sur la carte.

J'y suis favorable : un gros bouton : clic puis clique sur la carte.

> tu es sûr que ça n’intéresse personne de faire une recherche d’UF par numéro de parcelle ou par adresse ?

Si. Mais dans ce cas je pense qu'il faut donner cette possibilité depuis la fenêtre de sélection parcelle : sur-sélection puis clic sur un bouton "Afficher l'UF de la parcelle sélectionnée". Ca évite de redévelopper une interface spécifique.

> @landryb  aimerait bien rendre la partie UF optionnelle. Je peux le faire facilement avec un paramètre dans le fichier de conf.

Je crois que c'est raisonnable de le faire. Même si ici on est convaincu que ça sert à toute personne faisant du foncier et de l'ADS.

**Comment by pierrejego** [comment]
@MaelREBOUX j'enlève aussi les informations foncière de l'infoBulle, ou je les laisse si l'option foncier est activée ?
C'est bon en fait je l'ai mis en option; visible si foncier = true dans le manifest

**Comment by MaelREBOUX** [comment]
> C'est bon en fait je l'ai mis en option; visible si foncier = true dans le manifest

j'aurais pas demandé autre chose ;)

**Comment by MaelREBOUX** [comment]
Alors, 2 remarques de forme :
1. Mettre le titre "Fiche d'information foncière" en plus gros / grand
2. En pied de page il manque le nom du fournisseur du service, comme sur le BP "Rennes Métropole"
3. En pied de page indiquer également les versions du plan cadastral et des données foncières

Et une bizarrie : que ce soit en impression directe ou en PDF j'ai une bande blanche sur la droite de la carte alors que je l'ai pas sur la page HTML.

![image](https://user-images.githubusercontent.com/6370443/38098743-1d623c9e-3379-11e8-8b8d-3375dcb11624.png)

**Comment by pierrejego** [comment]
Je ne reproduis pas le blanc sur le côté, c'est étrange.

Quand tu dis augmenter le titre "Fiche d'information foncière", ici j'ai "Information sur une unité foncière" comme titre.
Tu veux que je change et que j'augmente la police ou juste que j'augmente la police ?

**Comment by MaelREBOUX** [comment]
Je n'ai pas reproduit non plus ce matin...

Synthèse des échanges / corrections de ce matin : 
- mettre une balise h1 avec CSS taille 16 bold pour la fonte
- bloc info propriétaires : aligner à gauche + mettre le compte communal sur la première ligne + faire un retrait de la liste des proprios pour décaler du titre de ligne
- bas de page : décaler avec équivalent 1 <br> de la dernière ligne de parcelles

**Comment by MaelREBOUX** [comment]
Un oubli : remplacer "Surface DGFiP" par "Contenance DGFiP".

**Comment by MaelREBOUX** [comment]
Testé et approuvé : je ferme.
