### ISSUE TITLE
Documentation - Placer le wiki comme sous module du dépôt cadastrapp

### ISSUE THREAD

**Issue by gryckelynck** [georchestra/cadastrapp#244]
Pour le suivi des évolutions de la documentation de cadastrapp gérée dans le wiki, il nous semblerait intéressant de créer un sous-module du wiki dans le dépôt cadastrapp.
Cela faciliterait selon nous le suivi et la récupération des évolutions de la documentation.
A moins qu'il existe un autre moyen qui nous échappe (visiblement il n'est pas possible de forker le wiki).
On pourrait ainsi disposer d'un arborescence de type:

```
|-- wiki
    |-- Images
        |-- les images
        |-- (...)
    |-- les fichiers .md
    |-- (...)
```

Qu'en pensez-vous?

**Comment by landryb** [comment]
Les sous-modules, c'est un cauchemard... et oui, on ne peut a priori pas 'forker' le wiki dans l'interface, mais tu peux toujours le cloner en local, et le pusher ailleurs....

**Comment by landryb** [comment]
De plus, un sous-module, ca pointe vers un commit précis du sous-dépot, donc il faut régulièrement le mettre a jour.. ce n'est pas la bonne solution a mon avis.

Si tu veux voir l'arborescence/naviguer dedans, c'est plus simple de cloner en local et d'utiliser un editeur/navigateur avec des fonctionalités d'historisation (tortoisegit, etc..)

**Comment by gryckelynck** [comment]
Merci Landry pour ces précisions.
On va essayer de trouver alors une façon plus simple de suivre les modifications sur le wiki et "synchroniser" le notre en fonction.

**Comment by landryb** [comment]
Au passage, je n'ai aucun problème pour donner les droits d'édition sur le wiki - le but, c'est que la documentation soit commune, unique, et canonique... éviter de se disperser partout et de faire chacun la sienne dans son coin :)

**Comment by MaelREBOUX** [comment]
ben si j'ai suivi la discussion sur la liste on part sur gitbook non ?

**Comment by landryb** [comment]
> ben si j'ai suivi la discussion sur la liste on part sur gitbook non ?

la discussion sur la liste, c'était pour la doc _georchestra_, pas la doc _cadastrapp_.. et je ne crois pas qu'on ait discuté/décidé de documenter cadastrapp dans la doc georchestra.

**Comment by MaelREBOUX** [comment]
ce serait logique d'avoir un peu de cohérence.
