### ISSUE TITLE
[UF] Fenetre des données foncières

### ISSUE THREAD

**Issue by stous** [georchestra/cadastrapp#245]
Je sélectionne la parcelle ZR 393 sur la commune de St Saturnin (630396), elle fait partie d'une unité foncière. J'ai coché 'unit. fonc.', j'affiche ma fiche d'info parcelles, et ma fiche d'info foncière.
Dans la fiche d'info foncière, j'ai 7 parcelles listées.
- si je clique sur 'selectionner toutes les parcelles', 
  - j'ai le message d'erreur suivant : "Impossible de retrouver la géometrie, veuillez en sélectionner au moins une.
    Si c'est déjà le cas, ceci peut être dû à une incompletude du fichier EDIGEO."
  - et visuellement l'unité foncière est affichée dans la carte.
  - les parcelles ne sont pas ajoutées à la fenêtre de sélection des  parcelles
- si je sélectionne une parcelle dans la fenêtre  unité foncière : 
  - visuellement l'unité foncière est affichée dans la carte.
  - les parcelles ne sont pas ajoutées à la fenêtre de sélection des  parcelles

**Comment by MaelREBOUX** [comment]
@stous est-ce que ce problème est tjs d'actualité ?

**Comment by landryb** [comment]
Vu que rien n'a été fait, j'imagine que oui.

**Comment by pierrejego** [comment]
Nous avons reproduit, pour le message d'erreur. Le problème vient du fait qu'il y a avait un appel WFS par feature qui mettait trop de temps à repondre. 
Cette partie est corrigée.

Par contre la partie de sélection ne fait que le zoom pour l'instant, c'était sélection dans le sens sélection graphique. On peut facilement ouvrir un nouvel onglet dans la fenêtre de selection de parcelles si besoin.

@stous c'est bien ça que tu voudrais ?

**Comment by Gaetanbrl** [comment]
Nous avons apportés les modifications suivantes lors du clic sur le bouton "Sélectionner toutes les parcelles" :  
- Ajout d'un onglet "UF sélection" dans la fenêtre de sélection (voir image).
- Le zoom n'est  plus effectué lors du clic sur le bouton "Sélectionner toutes les parcelles" mais par un clic sur "zoom liste" dans la fenêtre "sélection des parcelles".

@stous  Est-ce que cette modification convient ? 
![image](https://cloud.githubusercontent.com/assets/16317988/21761928/54bc8edc-d656-11e6-833f-952bfcfbaf4e.png)

**Comment by pierrejego** [comment]
Vu avec @landryb, le comportement semble logique

**Comment by MaelREBOUX** [comment]
OK
