### ISSUE TITLE
[Amélioration] Perte de la table request_user_information lors d'une mise à jour

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#248]
Lors d'une mise à jour des données cadastrales, on rejoue tout le script.
Notamment parce qu'il faut créer la table uf_parcelle (cf https://github.com/georchestra/cadastrapp/issues/243#issuecomment-238895512)

Ceci intervient 3x par an chez nous.

Un problème : le script commence par supprimer toutes les tables.
Or, la table **request_user_information** est censée contenir en permanence les dernière demandes de documents fonciers.
En fait, c'est comme la table groupe_autorisation qui n'est pas non plus droppée dans commun/dropTablesAndViews.sql

Je vois 2 pistes de résolution.
**Soit le script d'intégration teste la présence de données dans la table et gère ce cas**. Ex : renommage de la table, création de la nouvelle table et insertion des enregistrements.
**Soit on imagine carrément un script dédié à la mise à jour des données** en plus du présent script de création qui est plutôt fait pour être jouer lors d'une installation / ré-installation. Le pb ici est qu'il faut veiller au grain pour suivre les évolution dans le modèle de données et répercuter dans les requêtes d'installation et éventuellement dans les requêtes de mise à jour.

A vos remarques.

**Comment by landryb** [comment]
Si on utilisait un ORM comme hibernate, on pourrait gérer les versions de structures de tables/vues.. la en l'occurence, si la structure change, il faut penser a la migration des données existantes, ce que personne ne fait proprement, donc on jette tout et on recrée les vues à chaque changement. Et le problème sera présent tant que vous voudrez faire des modifications aux modèles des vues..

En ce qui concerne les tables dédiées a cadastrapp (request_user_information, groupe_autorisation) elles ne devraient être crées que si non existantes (CREATE IF NOT EXISTS) et pas supprimées par les scripts... a condition que l'on fige leur structure ad vitam aeternam.

**Comment by pierrejego** [comment]
Oui, les scripts de création et suppression sont à adapter à chaque intégration.  Il ne faut par forcement dropper toutes les tables.
Et surtout cette partie est gérée par un ORM, du coup hibernate fait un validate avant de démarré. Voir 
https://github.com/georchestra/cadastrapp/blob/master/cadastrapp/src/main/webapp/WEB-INF/beans.xml ligne 118, la stratégie peut être changé à cette endroit.

Il faut enlever le delete du drop pour vos instances, je le laisse pour les tests

**Comment by pierrejego** [comment]
Erreur de message de commit pas de référence à la 248 ici mais à la 249

**Comment by MaelREBOUX** [comment]
Réglé par https://github.com/georchestra/cadastrapp/commit/2e2d2e0ba03d7d321b9d92fc24cb4eed202b3179

La suppression des tables existantes est en commentaire.
