### ISSUE TITLE
[Général] Prise en compte des attributs dnomus et dprnus

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#249]
Ici à Rennes les 2 attributs sont disponibles en base depuis cette semaine et évolution vers le modèle 2015-3 de arcOpole.

En cohérence, **les attributs EPXNEE, DNOMCP et DPRNCP (position 403, 3, 30 et 15 caractères) ont été mis à blanc. La conséquence directe est que ces infos risquent de ne plus apparaître dans les interfaces, le bordereau parcellaire et le relevé de propriété.**

Lié à #151 

Rappel

```
2.12.
Nom et prénom d’usage
La dénomination des personnes physiques est présentée sous différentes formes dans le fichier des
propriétaires :
- DDENOM (position 57, 60 caractères) : dénomination de la personne physique structurée sous la
forme : « nom/prénoms ».
- DNOMLP (position 290, 30 caractères) et PRNLP (position 320, 15 caractères) : nom et prénom
d’usage tel qu’ils étaient indiqués auparavant sur les avis de taxe foncière. Pour les hommes, le nom
et prénom d’usage correspond aux nom et prénoms patronymiques, pour les femmes il peut s’agir
soit des nom et prénoms patronymiques, soit du nom et prénom maritaux.
- DNOMUS (position 538, 60 caractères) et DPRNUS (position 598, 40 caractères) : nom et prénoms
utilisés dans les correspondances des autorités administratives adressées aux usagers, tels que
définis par la loi n° 2000-321 du 12 avril 2000 relative aux droits des citoyens dans leurs relations
avec les administrations, modifiée par la loi n° 2014-873 du 4 août 2014 pour l’égalité réelle entre les
femmes et les hommes.
Il est, par conséquent, préconisé d’utiliser soit le champ DDENOM, soit les champs DNOMUS et
DPRNUS pour la dénomination des personnes physiques.
```

Il convient donc rapidement de patcher les éléments suivants pour prendre en compte les modifications en base :
- au niveau des scripts :
  - cadastrapp\cadastrapp\script\arcopole\views\arcopoleProprietaire.sql
  - cadastrapp\cadastrapp\script\qgis\views\qgisProprietaire.sql
- au niveau de la webapp :
  - cadastrapp\cadastrapp\src\main\java\org\georchestra\cadastrapp\service\BatimentController.java
  - cadastrapp\cadastrapp\src\main\java\org\georchestra\cadastrapp\service\CoProprietaireController.java
- au niveau de l'add-on :
  - cadastrapp\addons\cadastrapp\js\detailUniteCadastrale.js

Sans fouiller davantage je n'ai pas vu d'autre endroit mais à vérifier.

**Comment by jusabatier** [comment]
Je pense qu'il pourrait être intéressant quitte à modifier la webapp sur ce point de mettre en place un affichage correcte des noms de propriétaire, a savoir qu'il présente le nom d'usage et si il est nécessaire le nom d'origine.

En revanche je ne sais pas trop comment mettre ça en place correctement car les champs EPXNEE/DNOMCP/DPRNCP qui ont étés supprimés étaient bien plus utiles que DDENOM/DNOMLP/DPRNLP.

Au moins avec la combinaison EPXNEE/DNOMCP/DPRNCP/DNOMUS/DPRNUS on arrivait à avoir un affichage correct permettant de retrouver la personne lors d'une recherche...

Je ne trouve pas cohérent d'utiliser DDENOM qui est un champ déjà formatté et reprenant les infos d'autres champs mais visiblement il va falloir y passer si je comprends bien ?

**Comment by MaelREBOUX** [comment]
Un recap pcq pour ceux qui n'ont pas les données...

AVANT

```
DDENOM                        |  DQUALP |  DNOMLP |  DPRNLP         |  EXPNEE |  DNOMCP  | DPRNCP          |  DNOMUS   | DPRNUS 
THIRE/STEPHANE ANDRE          |  M      |  THIRE  |  STEPHANE ANDRE |         |          |                 |  THIRE    | STEPHANE
JEULAND/REGINE COLETTE MARIE  |  MME    |  THIRE  |  STEPHANE       |  NEE    |  JEULAND | REGINE COLETTE  |  THIRE    | REGINE
```

MAINTENANT (v 2015)

```
DDENOM                        |  DQUALP |  DNOMLP |  DPRNLP         |  EXPNEE |  DNOMCP  |  DPRNCP  |  DNOMUS   |  DPRNUS 
THIRE/STEPHANE ANDRE          |  M      |  THIRE  |  STEPHANE ANDRE |         |          |          |  THIRE    |  STEPHANE
JEULAND/REGINE COLETTE MARIE  |  MME    |  THIRE  |  STEPHANE       |         |          |          |  THIRE    |  REGINE
```

La lecture de la réglementation nous dit qu'il faut privilégier le nom d'usage dans nos relations avec l'administré(e). Moi je suis effectivement pour privilégier le nom d'usage et faire apparaître le nom de naissance uniquement sur le relevé de propriété.

Dans l'exemple ci-dessus il faudrait donc :
- remonter "**THIRE REGINE**" dans les interfaces et sur le bordereau parcellaire (CONCAT DNOMUS + DPRNUS)
- si on clic sur l'option "recherche par nom de naissance" (à la place de "marital") -> on remonte "**JEULAND REGINE COLETTE**" (DDENOM)
- sur le relevé de propriété, en haut :
  - bloc de gauche : "**THIRE REGINE**" (CONCAT DNOMUS + DPRNUS)
  - bloc de droite : dans une ligne sous la date et lie de naissance, rajouter "**JEULAND REGINE COLETTE**" (DDENOM)

**Comment by MaelREBOUX** [comment]
Une très bonne remarque de @jusabatier 
Dans le cas d'une personne autre que physique, il n'y a que l'attribut ddenom de renseigné, les autres attributs sont vides.

``` sql
select gtoper, dformjur, ddenom, dqualp, DNOMLP , DPRNLP, EPXNEE, DNOMCP, DPRNCP--, DNOMUS, DPRNUS
from cadastrapp_arcopole.proprietaire
where dformjur = 'ASS'
LIMIT 25
```

ça veut qu'il va falloir tester chaque ligne pour choisir entre ddenom et concat(dnomus, dprnus) ?! 
Ça milite pour simplifier et gérer ça dans la construction de la vue ? dans un nouvel attribut ?

**Comment by MaelREBOUX** [comment]
work in progress : https://github.com/sigrennesmetropole/cadastrapp/commits/issue-249

**Comment by MaelREBOUX** [comment]
Etat d'avancement
- <strike>au niveau des scripts :</strike>
  - <strike>cadastrapp\cadastrapp\script\arcopole\views\arcopoleProprietaire.sql</strike>
  - <strike>cadastrapp\cadastrapp\script\qgis\views\qgisProprietaire.sql</strike>
- au niveau de la webapp :
  - cadastrapp\cadastrapp\src\main\java\org\georchestra\cadastrapp\service\BatimentController.java
  - cadastrapp\cadastrapp\src\main\java\org\georchestra\cadastrapp\service\CoProprietaireController.java
  - cadastrapp\cadastrapp\src\main\java\org\georchestra\cadastrapp\model\pdf\BordereauParcellaire.java + service
  - cadastrapp\cadastrapp\src\main\java\org\georchestra\cadastrapp\model\pdf\CompteCommunal.java + service
  - cadastrapp\cadastrapp\src\main\java\org\georchestra\cadastrapp\model\pdf\RelevePropriete.java + service
- au niveau de l'add-on :
  - cadastrapp\addons\cadastrapp\js\detailUniteCadastrale.js

**Comment by MaelREBOUX** [comment]
Etat d'avancement
- <strike>au niveau des scripts :</strike>
  - <strike>cadastrapp\script\arcopole\views\arcopoleProprietaire.sql</strike>
  - <strike>cadastrapp\script\qgis\views\qgisProprietaire.sql</strike>
- au niveau de la webapp :
  - les services
  - <strike>cadastrapp\src\main\java\org\georchestra\cadastrapp\service\BatimentController.java</strike>
  - <strike>cadastrapp\src\main\java\org\georchestra\cadastrapp\service\CoProprietaireController.java</strike>
  -  <strike>cadastrapp/src/main/java/org/georchestra/cadastrapp/service/InfoBulleController.java</strike>
  - <strike>cadastrapp/src/main/java/org/georchestra/cadastrapp/service/ProprietaireController.java</strike>
  - <strike>cadastrapp/src/main/java/org/georchestra/cadastrapp/service/UniteCadastraleController.java</strike>
  - les PDF
  - <strike>cadastrapp/src/main/java/org/georchestra/cadastrapp/service/pdf/BordereauParcellaireHelper.java</strike>
  - <strike>cadastrapp\src\main\java\org\georchestra\cadastrapp\model\pdf\BordereauParcellaire.java </strike>
  - cadastrapp\cadastrapp\src\main\java\org\georchestra\cadastrapp\model\pdf\CompteCommunal.java
  - cadastrapp\cadastrapp\src\main\java\org\georchestra\cadastrapp\model\pdf\RelevePropriete.java
  - <strike>cadastrapp\cadastrapp\src\main\java\org\georchestra\cadastrapp\model\pdf\ReleveProprieteHelper.java</strike>
- au niveau de l'add-on :
  - <strike>addons/cadastrapp/js/componentUtils.js</strike>
  - <strike>addons\cadastrapp\js\detailUniteCadastrale.js</strike>
  - <strike>addons/cadastrapp/js/detailUniteFonciere.js</strike>
  - <strike>addons/cadastrapp/js/infoBulle.js</strike>
  - <strike>addons/cadastrapp/js/resultProprietaire.js</strike>
  - <strike>addons/cadastrapp/js/searchCoPropriete.js</strike>
  - <strike>addons/cadastrapp/js/searchParcelleByOwner.js</strike>
  - <strike>addons/cadastrapp/manifest.json</strike>

https://github.com/sigrennesmetropole/cadastrapp/commit/2de7b6c2380d9a7cc0d283eed45bbd358009519c
et
https://github.com/sigrennesmetropole/cadastrapp/commit/df45bde01f767c53edc8d4a244645b1768bc9a3d

**Comment by MaelREBOUX** [comment]
@jusabatier il faut faire apparaître le nom de naissance dans la 3e case de chaque ligne de propriétaire dans le relevé de propriété. Sous la date et le lieu de naissance.

J'ai regardé les commits mais comme je ne sais pas du tout comment sont généré les PDF, j'ai du mal à voir si ça existe déjà ou pas.

**Comment by jusabatier** [comment]
Il n’apparaît pas actuellement, je rajouterais ça demain matin.
- Ajout de app_nom_naissance dans la 3e colonne des infos propriétaire d'un RP

**Comment by jusabatier** [comment]
Dans le cas d'un relevé minimal, la troisième colonne n'apparaît pas.

Faut-il alors déplacer le nom de naissance ailleurs ou bien il n’apparaît pas non-plus ?

**Comment by MaelREBOUX** [comment]
Il ne doit pas apparaître non plus.
La CNIL considère nom naissance + date naissance comme des infos sensibles.

**Comment by MaelREBOUX** [comment]
Etat d'avancement
- <strike>au niveau des scripts :</strike>
  - <strike>cadastrapp\script\arcopole\views\arcopoleProprietaire.sql</strike>
  - <strike>cadastrapp\script\qgis\views\qgisProprietaire.sql</strike>
- au niveau de la webapp :
  - les services
  - <strike>cadastrapp\src\main\java\org\georchestra\cadastrapp\service\BatimentController.java</strike>
  - <strike>cadastrapp\src\main\java\org\georchestra\cadastrapp\service\CoProprietaireController.java</strike>
  -  <strike>cadastrapp/src/main/java/org/georchestra/cadastrapp/service/InfoBulleController.java</strike>
  - <strike>cadastrapp/src/main/java/org/georchestra/cadastrapp/service/ProprietaireController.java</strike>
  - <strike>cadastrapp/src/main/java/org/georchestra/cadastrapp/service/UniteCadastraleController.java</strike>
  - les PDF
  - <strike>cadastrapp/src/main/java/org/georchestra/cadastrapp/service/pdf/BordereauParcellaireHelper.java</strike>
  - <strike>cadastrapp\src\main\java\org\georchestra\cadastrapp\model\pdf\BordereauParcellaire.java </strike>
  - <strike>cadastrapp\cadastrapp\src\main\java\org\georchestra\cadastrapp\model\pdf\RelevePropriete.java</strike>
  - <strike>cadastrapp\cadastrapp\src\main\java\org\georchestra\cadastrapp\model\pdf\ReleveProprieteHelper.java</strike>
- au niveau de l'add-on :
  - <strike>addons/cadastrapp/js/componentUtils.js</strike>
  - <strike>addons\cadastrapp\js\detailUniteCadastrale.js</strike>
  - <strike>addons/cadastrapp/js/detailUniteFonciere.js</strike>
  - <strike>addons/cadastrapp/js/infoBulle.js</strike>
  - <strike>addons/cadastrapp/js/resultProprietaire.js</strike>
  - <strike>addons/cadastrapp/js/searchCoPropriete.js</strike>
  - <strike>addons/cadastrapp/js/searchParcelleByOwner.js</strike>
  - <strike>addons/cadastrapp/manifest.json</strike>

https://github.com/sigrennesmetropole/cadastrapp/commit/9fccb5fd0fbc6b78031e17c9d6a2f0d285c78175

Bé on peut PR sur master alors !

**Comment by MaelREBOUX** [comment]
PR #255 prête !

**Comment by pierrejego** [comment]
Whoua la PR, il va me falloir un peu de temps pour la  tester, surtout sans les données. Est-ce que Julien tu as testé cette PR sur ton repo ?

**Comment by jusabatier** [comment]
Oui, j'ai créé une instance de test en local, avec nos données QGis tout fonctionne.

En revanche je n'ai pas pu tester avec le modèle Arcopole, voir avec @MaelREBOUX  si il l'a fait.

**Comment by catmorales** [comment]
Bonjour, 
Pour info, Maël reviendra vendredi et de mon côté je découvre un peu toutes les modifications réalisées en août ...

**Comment by MaelREBOUX** [comment]
@pierrejego : pas vraiment de raison que ça ne fonctionne pas pour nous pour arcOpole. Au final cela simplifie les requêtes car on tape l'un ou l'autre des 2 nouveaux attributs.

Si @jusabatier a testé chez lui la recherche + BP + RP : je vois pas pourquoi ça coincerait. Mais un oubli peut tjs arriver et j'avoue que le code de la webapp et quoi se passé où m'échappe en grande partie actuellement.

Mais je trouve aussi que c'est une belle PR :dancers:

**Comment by pierrejego** [comment]
@MaelREBOUX comment est-ce que je peux rajouter les nouveaux champs avec la base que vous m'aviez donnée, je voudrais tester avec de valider la PR

**Comment by MaelREBOUX** [comment]
tu les auras si tu rejoue le script de création de la base cadatrapp qui contient ces modifs cf la PR.

**Comment by pierrejego** [comment]
Ok , j'ai pu tester sur les deux modèles avec les données de la région Rennaise.

**Comment by MaelREBOUX** [comment]
Je rouvre car ce n'est pas bon sur arcopole. J'ai commenté une PR il y a 2 j mais je ne retrouve pas.
La liste de suggestion ne montre pas le bon attribut. Dans le cas présent c'est "JEULAND REGINE" qui devrait être affiché. "THIRE REGINE" étant son nom d'usage.

**Comment by pierrejego** [comment]
Fermé avec le commit https://github.com/georchestra/cadastrapp/commit/a06de896c932bd122233e597b1d7c61b995caf19

**Comment by MaelREBOUX** [comment]
je confirme : on est bon : youpla la boum !
