### ISSUE TITLE
Ne pas mettre de parametres a la racine de GEOR.custom

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#25]
Dans le README.md de https://github.com/GFI-Informatique/addons/tree/dev/cadastrapp je vois qu'il y'a 2 sections, une concernant l'intégration de l'addon dans la visionneuse, a rajouter dans l'array ADDONS, puis 5 structures a priori spécifiques a l'addon.

D'une part, par convention toutes les variables dans GEOR.custom sont en majuscules, et je pense que ces réglages spécifiques a cadastrapp mériteraient d'etre rassemblés dans un namespace distinct.

Ie

```
    CADASTRAPP: {
        "wmsLayer": {
            ....
        }, 
        "WFSLayerSetting": {
            ....
        }, 
        ....
     }
```

Et les variables seraient ainsi accédées via GEOR.custom.CADASTRAPP.wmsLayer - ainsi, pas de pollution de namespace.

Evidemment, a comparer avec la manière de configurer les autres addons tiers de mapfishapp... p.ex l'addon sol met ses parametres dans l'objet JS a ajouter au tableau ADDONS - c'est peut-etre préférable.

**Comment by landryb** [comment]
Cf https://github.com/georchestra/addons/tree/master/sol pour l'addon sol

**Comment by fvanderbiest** [comment]
Landry me demande mon avis, donc je le donne ici.

Je confirme qu'il faut mettre toute la config de l'addon dans ses options, et non en dehors.

Cf par exemple https://github.com/georchestra/georchestra/blob/14.12/mapfishapp/src/main/webapp/app/addons/streetview/README.md avec `initial_window_size` et `api_key`

**Comment by pierrejego** [comment]
OK, merci pour les liens d'exemple.
Pn essaye donc de tout mettre dans la partie options de l'addon. Nous avions eut un soucis technique pour le faire lors de la création de l'addon, un problème d'accès par Id je crois, je refais une passe dessus, et j'y ajoute aussi l'url de la webapp.
