### ISSUE TITLE
Problème zoom après chargement de contexte

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#251]
Lorsqu'on charge un nouveau contexte depuis mapfishapp après avoir ouvert une première fois l'addon cadastrapp, il devient alors impossible d'utiliser les boutons "Zoom sélection" ou "Zoom liste" de la fenêtre de résultat de recherche.

Ceci est du au fait que la fonction zoom dépend des features de la couche WFS créée par l'addon et ajoutées à la carte, cependant le fait de "Charger" un contexte retire toutes les couches de la carte, y compris celles de l'addon (WMS+WFS).

J'ai une solution pour réinsérer la couche WFS lors de la réouverture de l'addon (clic sur l'icone), mais cela force une action supplémentaire de l'utilisateur et lui fait perdre toute recherche en cours.

Une bonne solution je pense serait de créér un event lancé par Mapfishapp lors du nettoyage de la layerList et sur lequel les addons utilisant une couche WMS/WFS pourraient se brancher afin de les réinsérer si besoin. Ou bien de modifier ce nettoyage afin qu'il n'impacte pas les couches non visibles de la layerList.

@MaelREBOUX  m'a dit que le même problème se présentait pour leur module urbanisme

**Comment by landryb** [comment]
Si j'ai bien compris, le probleme se pose si tu : 
- ouvres cadastrapp
- charge un autre contexte

A partir de la, les zooms ne marchent plus, et il faut fermer/reouvrir cadastrapp ?

Pour moi, si tu charges un autre contexte, tu 'sors' déja de cadastrapp... donc je ne m'attend plus a ce que cadastrapp marche, l'addon devrait même limite se fermer.. sinon on revient a un problème évoqué par le passé, ou cadastrapp 'devrait' vérifier que ses couches support sont présentes avant chaque requete, et les rajouter si besoin. C'est un cauchemard a gérer en termes de cycle de vie des couches...

@fvanderbiest y'a t'il un moyen de se 'brancher' sur un eventuel event mfapp lors du nettoyage de la layerList/chargement du contexte ?

@jusabatier on ne va pas 'modifier le nettoyage pour qu'il n'impacte pas les couches non visibles de la layerList'. A mon avis quand on charge un contexte, on vire _toutes_ les couches de manière unilatérale.

**Comment by jusabatier** [comment]
Chez nous un changement de contexte ne signifie pas forcement qu'on veut sortir de cadastrapp : 

Nous avons divisé les couches d'urbanisme en 4 contextes, du coup un utilisateur peut vouloir changer de contexte (=perdre le zoom sur la parcelle) sans avoir à refaire toute la recherche 
=> pouvoir simplement re-cliquer sur zoomer et ainsi consulter la nouvelle donnée sur la parcelle concernée

Pour moi la solution d'un event sur lequel les addons pourraient se brancher me semble être la meilleure solution et cela pourrait servir je pense à d'autres addons utilisant leur propre couche. A voir si c'est techniquement faisable.

**Comment by pierrejego** [comment]
Dans ton cas Julien  si je me trompe pas c'est surtout qu'on perd la sélection (et la couche aussi) 
Par contre ce que je ne comprends pas c'est que si tu cliques, tu auras les mêmes données d'affichées, l'addon ne gère qu'une seule couche WFS, du coup c'est juste le fond qui va changer non ?

**Comment by jusabatier** [comment]
Le problème est que lors d'un chargement de contexte, il y a un RaZ des couches dans MFapp, du coup la couche WFS utilisée par l'addon pour obtenir les coordonnées sur lesquelles zoomer n'existe plus...

Et donc après un chargement de contexte, il devient impossible de zoomer sur une parcelle.

**Comment by fvanderbiest** [comment]
> @fvanderbiest y'a t'il un moyen de se 'brancher' sur un eventuel event mfapp lors du nettoyage de la layerList/chargement du contexte ?

https://github.com/georchestra/georchestra/blob/15.12/mapfishapp/src/main/webapp/app/js/GEOR_wmc.js#L30-L44

**Comment by landryb** [comment]
Ah, magique. yapluka (tm) implémenter les bouts de glue.

**Comment by MaelREBOUX** [comment]
Je confirme avoir reproduit le comportement. Il faut que cadastrapp surveille l'état de la TOC et veille à ce que la couche app_cadastrapp_parcelles soit présente en permanence.

**Comment by jusabatier** [comment]
cf https://github.com/georchestra/cadastrapp/issues/321

**Comment by jusabatier** [comment]
Corrigé avec https://github.com/georchestra/cadastrapp/pull/326

Uniquement disponible avec Georchestra 16.12
