### ISSUE TITLE
MATERIALIZED VIEW partout + dropAll

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#252]
Issue pour préparer une PR pour alignement du modèle QGIS sur arcopole : MATERIALIZED VIEW au lieu d'une simple vue.
La vue matérialisée à plus de performances grâce aux indexes (cf @jusabatier).

@landryb : une remarque ?

**Comment by landryb** [comment]
Ah, je ne savais pas que les vues étaient déja matérialisées dans le modèle arcopole (et ca, depuis 7e78b5d) .. de toute facon, je fais déja pareil dans les playbooks de déploiement ansible (cf https://github.com/georchestra/ansible/blob/master/roles/postgresql/tasks/cadastrapp.yml#L105) donc je suis :+1: - du coup les vues matérialisées deviennent une dépendance obligatoire, et par conséquence postgresql 9.3 aussi. @pierrejego ?

**Comment by MaelREBOUX** [comment]
on est en 9.4 ici. 9.3 mini +1 pour moi

**Comment by MaelREBOUX** [comment]
PR 253 corrigée et prête à être mergée : https://github.com/georchestra/cadastrapp/pull/253

**Comment by landryb** [comment]
Merged
