### ISSUE TITLE
[Infobulle] Trou de sécurité accès aux données nominatives pour un utilisateur non autorisé

### ISSUE THREAD

**Issue by catmorales** [georchestra/cadastrapp#256]
Un bug  que je viens d'identifier. 
Voici le test:
- je me connecte à la plateforme en tant qu'utilisateur de la commune d'acigné, de niveau cnil2 donc habilité à regarder les données nominatives de la commune d'acigné et seulement celles là; j'active le module cadastre, je fais quelques interrogations de parcelles sur ma commune, j'active l'affichage de l'info-bulle avec les unités foncières --> OK
- je me déplace dans la carte sur une autre commune, ici cesson-sévigné, je n'arrive pas à interroger les données , c'est normal car je n'ai pas les droits --> OK
- mais l'info-bulle s'affiche avec l'information du compte communal (donnée nominative)  --> NOK
  ![image](https://cloud.githubusercontent.com/assets/4659829/18206885/04fba050-7129-11e6-91bc-f9b845b275e0.png)

**Comment by landryb** [comment]
Est-ce que c'est avec user.search.are.filtered=1/0/peu importe la valeur ? si je comprends bien, c'est **uniquement** l'information '_compte communal pour l'unité foncière_' qui fuite ?

**Comment by MaelREBOUX** [comment]
> si je comprends bien, c'est uniquement l'information 'compte communal pour l'unité foncière' qui fuite ?

oui

**Comment by pierrejego** [comment]
Ajout du filtre côté serveur fait avec le commit  https://github.com/georchestra/cadastrapp/commit/3e67dc273f0c4b5d72181eb98e427bb47ab44fb4

**Comment by MaelREBOUX** [comment]
Je rouvre : pas bon ici ça génère une erreur 500.
Si on active "UF" sur la barre d'outils : on a une erreur 500 sur une commune sur laquelle on n'a pas d'accès aux DN.

Le contenu renvoyé est : 
`Infobulle : Error occured when trying to get information from server, please check server logs`

**Comment by MaelREBOUX** [comment]
```sql
select uf.comptecommunal, sum(p.dcntpa) as dcntpa_sum, sum(p.surfc) as sigcal_sum from cadastrapp_arcopole.parcelleDetails p, cadastrapp_arcopole.proprietaire_parcelle proparc, cadastrapp_arcopole.uf_parcelle uf  
where proparc.parcelle = '350047000AS0350'
 and proparc.comptecommunal = uf.comptecommunal 
 and p.parcelle=uf.parcelle
 AND p.cgocommune IN ('350238' )  GROUP BY uf.comptecommunal ;
```

renvoie bien 0 enregistrement

**Comment by MaelREBOUX** [comment]
@pierrejego a reçun un log pour tracer.

**Comment by MaelREBOUX** [comment]
J'ai retesté ce matin à cause des diff entre PF de test et PF de prod.

Comportement idem : erreur 500 sur les 2 PF.

**Comment by MaelREBOUX** [comment]
Le bogue original est corrigé donc je fermet créé un nouveau ticket pour l'erreur 500.

**Comment by landryb** [comment]
moved to #287
