### ISSUE TITLE
[RP] Propriété non baties ne remontent pas

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#257]
J'ai constaté une erreur ce matin en essayant de depanner un utilisateur qui cherchait le proprietaire sur une de nos parcelles, lorsqu'on imprime un relevé de propriété.

On voit le cadre des propriétés baties apparaitre mais vide alors qu'il n'y en a aucune pour ce compte communal.

Mais plus grave la partie correspondant aux propriétés non baties n'apparait pas du tout, alors que ce compte communal en possède 3.
Il semblerait donc qu'on ait un souci au niveau de la remontée des propriétés non baties dans les RP.

Aussi si j'avais fait pas mal de test pour remonter plus d'infos dans les RP (cf https://github.com/georchestra/cadastrapp/pull/176) qu'il faudrait d'ailleur valider...

Je n'avais testé que la partie batie, et je pense que la partie non-batie necessiterait également que l'on se penche dessus pour la tester.

Le fait de ne pas pouvoir garantir à nos utilisateurs de pouvoir générer des RP valides va vite devenir un problème bloquant chez nous.

**Comment by MaelREBOUX** [comment]
Des utilisateurs nous ont remonté la même chose.
Je n'ai pas eu le temps en août de regarder dans les données. Ce que tu dis me semble confirmer que le problème est du côté applicatif.

**Comment by pierrejego** [comment]
@jusabatier je ne reproduis pas les mêmes erreurs qu'avec Arcopole, est-ce que tu pourrais m'envoyer un jeu de données avec une parcelle qui pose problème ?
J'ai besoin d'analyser la différence entre les données QGis et la vue créée

**Comment by pierrejego** [comment]
Je pense avoir trouvé l'erreur, les propriétés non baties qui n'ont pas d'id dans la table sufexo.

Il faut changer la requête du releve de propriété en remplacant le where par un left join

Je fais les tests avant de commiter

**Comment by pierrejego** [comment]
Ok sur les cas que j'avais trouvé, maintenant les RP ont a bien le même nombre de propriété non-baties dans les deux RP générés par les deux modèles.

**Comment by MaelREBOUX** [comment]
A lier à #254  ?

**Comment by MaelREBOUX** [comment]
normalement c'est ok -> on ferme
