### ISSUE TITLE
FireFox : suppression des préférences de sites et zoom sur sélection

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#259]
Pour information je rencontrais un problème récurrent et embêtant sur mon profil FF sur mon poste : impossible de zoomer sur une parcelle sélection dans la liste des parcelles.
Une erreur javascript accompagnait ce bogue.
J'ai débloqué une utilisatrice sur ce même pb.

La solution : supprimer les préférences de site. La purge des cookies et du cache ne suffisant pas.

**Comment by landryb** [comment]
Supprimer les préférences de site revient a vider le localstorage...

**Comment by landryb** [comment]
Ie (from https://support.mozilla.org/en-US/kb/block-websites-storing-site-preferences)  aller sur la page de mapfishapp, clic droit, view page info, onglet 'permissions', 'maintain offline storage' -> block. Mais c'est un peu dommage car ca pete tout ce qui dépend du localstorage dans mfapp...

**Comment by MaelREBOUX** [comment]
> Supprimer les préférences de site revient a vider le localstorage...

je ne savais que ça produisait ça. Ceci explique donc cela. Merci @landryb 
Ca fait partie pour nous des choses compliquées à faire passer aux utilisateurs : cache, localstorage. Pour le moment on n'aborde pas ça.

**Comment by jusabatier** [comment]
J'ai constaté plusieurs fois le même problème, la dernière fois c'était hier et ça empêchait l'affichage de la liste de résultats d'une recherche.

**Comment by MaelREBOUX** [comment]
et pas d'équivalent sur IE ou Chrome ?
Ici non mais le panel de personnes est encore restreint mais ça va augmenter vite (presque 100 utilisateurs interne en 1 semaine)

**Comment by jusabatier** [comment]
La majorité de nos utilisateurs sont sous Mozilla Firefox, personnellement je n'ai jamais eu ce souci sous chrome, mais j'ai souvent eu a faire ce type de dépannage sur le poste d'utilisateurs.

**Comment by MaelREBOUX** [comment]
suite dans #319
