### ISSUE TITLE
[infobulle] ne fonctionne pas avec IE 11

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#260]
Pb remonté par 1 utilisateur et vérifié sur 2 postes.
Sous IE 11 : l'infbulle ne s'affiche pas.

@jusabatier : tu pourrais confirmer chez toi STP ?

**Comment by jusabatier** [comment]
Je viens d'installer la dernière version d'IE 11 et je ne constate pas ce problème, ici l'infobulle s'affiche bien.

PS : IE c'est mal

**Comment by MaelREBOUX** [comment]
IE 11.0.9600.18426 et toi ?

**Comment by jusabatier** [comment]
IE 11.0.9600.17843

**Comment by MaelREBOUX** [comment]
On vient officiellement de dire qu'on ne supportait plus IE mais uniquement FireFox, Chrome et Edge.
Je souhaite donc fermer ce ticket.

OK tout le monde ?

**Comment by landryb** [comment]
Die IE.
