### ISSUE TITLE
[RP] Revenu cadastral et revenus imposables incorrects

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#261]
J'ai pu constater que les informations de revenu cadastral remontées sur les RP ne sont pas correctes : 

Par exemple pour la parcelle AA194 sur Chaspuzac : 
- Sur l'addon on a un revenu cadastral de 273, alors qu'en interrogeant via QGis ou Editop, on a 686
- La taxe OM ne remonte pas

On est en train de déployer dans nos différentes communes le cadastre 2016 via cet addon et les utilisateurs s'affolent un peu de voir de telles erreurs...

**Comment by MaelREBOUX** [comment]
idem ici : nos bêta testeurs nous ont fait des remontées cet été mais j'en attendais d'autres depuis la mise à jour des données intervenues fin août.
Et ça commence depuis hier : les valeurs sur le revenu imposable n'ont pas l'air correctes.

J'ai soumis hier à @pierrejego des cas. On va pouvoir creuser la semaine prochaine et regarder plus près.

**Comment by jusabatier** [comment]
Après quelques recherche, je pense avoir trouvé la logique pour calculer le revenu cadastral : 

http://forum-entraide-surendettement.fr/index.php?topic=10780.0

En gros il faut prendre la "Valeur locative de la pev, en valeur de l’année" (pev.dvlpera) puis diviser cette valeur par 2 pour obtenir le revenu cadastral.

A approfondir car je ne suis pas sur d'avoir saisi exactement ce à quoi correspond une pev, et il semble que dans certains cas il puisse y en avoir plusieurs par local.

**Comment by MaelREBOUX** [comment]
Une pev = partie d'évaluation. Ca sert à calculer les impôts locaux foncier : ce pourquoi le cadastre existe.

Ici on va demander à la DGFiP des RP de référence. On vous encourage à en faire autant. Comme ça on devrait pouvoir comparer sur des parcelles / propriétaires repères.
Mais il faut bien choisir car on a 8 mois de décalage entre le Majic et ce que peut produire la DGFiP.

**Comment by MaelREBOUX** [comment]
En attente du merge de la PR

**Comment by MaelREBOUX** [comment]
@jusabatier @pierrejego   on en a rediscuté ici et on peut pas laisser une valeur différente à cause de l'arrondi postgreSQL inférieur en base.

Donc, ligne 68 : mettre  `ROUND(CAST(dvlpera AS FLOAT)/2) as revcad,`

cf commit https://github.com/georchestra/cadastrapp/commit/45a4e1129577f49d0b0dea6b71fdc07ac00a362d et https://github.com/georchestra/cadastrapp/commit/04360bc0f6e28d55dee88c050b33da54a465a301

**Comment by MaelREBOUX** [comment]
En ce qui concerne les 3 revenus imposables des propriétés bâties on a trouvé.

Pour arcOpole, il faut dans la table dgi_taxpev prendre les attributs **bipevla** pour la commune, **bipevla_dep** pour le départemetn et **bipevla_reg** pour la région. Actuellement ce sont les attributs vlbaia\* qui sont utilisés sauf qu'ils stockent la valeur 70... cf supra.

Pour qgis on dirait que c'est la même chose : prendre **co_bipevla dep__bipevla et reg__bipevla** à la place de ceux utilisés actuellement.

**Comment by jusabatier** [comment]
Je pence que c'est bien les valeurs **vlbaia** qu'il faut prendre, en effet celles ci correspondent à la part de VL imposée sur  l'année comme l'indique le a de la fin.
Les attributs bipevla correspondent eux à la base d'imposition.

Pour ce qui est des revenus imposables, ils doivent correspondre à la somme des parts de VL imposée de toutes les propriétés baties du compte communal. Les champs à utiliser pour QGis sont : 

Commune : **co_vlbaia** _(Commune - Part de VL imposée (valeur de l’année))_
Departement : **de_vlbaia** _(Département - Part de VL imposée (valeur de l’année))_
Groupement de commune : **gp_vlbaia** _(Groupement de commune - Part de VL imposée (valeur de l’année))_

Pour ce qui est de la part de la region, je ne suis pas sur que ce soit encore d'actualité : 

Région (**avant 2012**) - Part de VL imposée (valeur de l’année)

**Comment by MaelREBOUX** [comment]
Voici ce qu'on a en base arcopole chez nous dans la table dgi_taxpev

![screenshot257](https://cloud.githubusercontent.com/assets/6370443/19181426/4f4c3246-8c6d-11e6-8ddd-9cf0965d9104.png)

Comme tu le vois, si tu regardes le RP en PDF issu de visuDGFiP hier, il prend les chiffres les plus bas. Soit 1755 (1773 pour 2016) et non pas 3545 comme tu le dis ci-dessus.

Tu peux mettre une capture d'écran de la table qgis STP ?

**Comment by jusabatier** [comment]
Conformément à la formule que j'ai donné hier : 

Revenu cadastral = VL de l'année / 2

Donc pareil pour l'exoneration j'ai l'impression : 

3545/2 = 1772.5

En fait on a tout les deux raison, je pense que les champs bipevla sont le revenu cadastral exonéré tandis que vlbaia sont la valeur locative.

**Comment by MaelREBOUX** [comment]
## extrait de la documentation Majic

![screenshot258](https://cloud.githubusercontent.com/assets/6370443/19181647/ccf19c30-8c6e-11e6-9ebe-3a79f32a0bae.png)

## Extrait de la documentation arcopole

![screenshot259](https://cloud.githubusercontent.com/assets/6370443/19181661/ea8ee6e4-8c6e-11e6-8425-8ec566e1635f.png)

## Extrait de la documentation QGIS

![screenshot260](https://cloud.githubusercontent.com/assets/6370443/19181854/1781082a-8c70-11e6-9021-8c2040f3a70c.png)

Si tu regardes un RP DGFiP ce sont les valeurs **bipevla...** qui appraissent. Soit les valeurs "Base d’imposition de la PEV(valeur de l’année)" et pas les valeurs **vlabia** "Part de VL imposée (valeur de l’année)".
Tu es ok avec ça ?

**Comment by jusabatier** [comment]
Oui, je voulais juste faire remarquer que les deux sont liées

**Comment by jusabatier** [comment]
Et à mon avis, il est plus simple de diviser par deux les vlbaia dans le RPHelper (1 seule modif)

Que de modifier encore les vues, modèles, fichiers js, helpers, etc...

**Comment by MaelREBOUX** [comment]
On ne veut pas commencer à faire des calculs dans les vues cadastrapp. 
De plus, on ne peut pas savoir si ces valeurs sont différentes pour certaines parcelles sur lesquelles il y a auraient des exonérations plus fortes. Cela arrive. D'où l'importance de ne pas recalculer. Les moulinettes vont lire le fichier Majic et mettent en base. Il faut s'y tenir.

**Les valeurs existent en tables il faut aller les chercher.**

**Comment by MaelREBOUX** [comment]
work in porgress : https://github.com/sigrennesmetropole/cadastrapp/commits/patch-revenus-imposables

**Comment by jusabatier** [comment]
Pourquoi autant de modifications sur _script/qgis/views/qgisProprieteBatie.sql_ ?

Aussi, je ne suis pas sur que ton patch s'appuie sur master car il modifie le calcul de revcad (ajout du round+cast float), ce qui est déjà fait dans master.

cf https://github.com/sigrennesmetropole/cadastrapp/commit/5eeb75398fc7d49c12b75128ca6abcb9a1cf4e43

**Comment by MaelREBOUX** [comment]
je me suis aperçu qu'il y avait des différences dans l'ordre des attributs entre Qgis et arcopole. J'ai tenté de remettre ça dans l'ordre. Plus facile pour comparer entre les 2 modèles.
Je suis bien reparti de master pourtant. Bizarre pour le revcad. Mais bon : au merge ça devrait pas poser de pb.

**Comment by jusabatier** [comment]
Dernière question, dans le modèle QGis on a également un attribut gp_bipevla qui correspond à "Groupement de commune - Base d’imposition de la pev(valeur de l’année)".

Il ressort également sur les RP QGis. Est-il également disponible sur le modèle arcopole ? Si oui, ne serait-il pas intéressant de le faire apparaître également ?

Enfin qu'en est-il de la taxation région qui apparaît comme inutilisée depuis 2012 sur le modèle de données QGis ? "Région (avant 2012) - Base d’imposition de la pev(valeur de l’année)"

cf http://demo.3liz.com/plugin_cadastre/SchemaSpyGUI/tables/pevtaxation.html

A mettre en parallèle avec "TSE (à partir de 2012) - Base d’imposition de la pev(valeur de l’année)", je ne sais pas si il y a un lien.

**Comment by jusabatier** [comment]
Pour le revenu cadastral, je viens de voir une difference entre le resultat QGis et l'addon : 

Dans l'addon : 446
Dans QGis : 447

Est-on sur que la methode utilisée pour arrondir la valeur est la bonne (ROUND) car QGis semble faire un arrondi superieur (CEIL).

**Comment by MaelREBOUX** [comment]
Extrait des données MAJIC PROP BATI

```
3500470470261655              00      AS0350  A0100010010740 005850010 0453RUE THEODORE ALBERT           X
3500470470261655              10   0AR0070819122009      C 1P 000 MA000000733               0P              196601    01011985                     0
3500470470261655           00121   HA6 120   000172000000733000003545                                P 009                                              000000733     1+ 005+ 005+ 000
3500470470261655           00136   000000733 000003545 000001773 000000733 000003545 000001773 000000733 000003545 000001773 000000733 000003545 000001773 000001773 000000000
3500470470261655           00140 H GA00002006CV00003203GR00006402  00000000OO O O O00010101035070104000101031000007240201966101
```

**Comment by MaelREBOUX** [comment]
Une correction sur arcopole https://github.com/georchestra/cadastrapp/commit/ddb4744f337314e1321a09f553ccdce5ff80c70e

Maintenant : il faut vérifier les totaux et on pourra fermer.

**Comment by MaelREBOUX** [comment]
Alors, chez moi 

### pour les **propriétés bâties**
- total revenu imposable / revenu cadastral : ok
- commune : 
  - total revenu imposable : ok
  - total revenu exonéré : sans doute ok  (exonération à zéro)
- département : sans doute ok  (exonération à zéro)
- groupement de commune : 
  - **total revenu imposable : k0 : valeur double**  à vérifier après redéploiement ici de https://github.com/georchestra/cadastrapp/commit/ddb4744f337314e1321a09f553ccdce5ff80c70e
  - total revenu exonéré : sans doute ok  (exonération à zéro)

### pour les **propriétés non bâties**
- total revenu imposable / revenu cadastral : ok
- commune : 
  - total revenu imposable : ok
  - **total revenu exonéré : ko  (valeur à zéro)**
- département :
  - total revenu imposable : ok ??
  - **total revenu exonéré : ko  (valeur à zéro)**
- groupement de commune : 
  - total revenu imposable : ok
  - total revenu exonéré : ok

@pierrejego : je voudrais bien un RP venant de la version QGIS pour comparer.

De ton côté @jusabatier  ?

**Comment by jusabatier** [comment]
De mon coté, tout est bon.

Pour les propriétés baties, les exonerations et revenus imposables sont tous OK.

Pour les non baties aussi.

**Comment by MaelREBOUX** [comment]
c'est bien fait par calcul par le XSL ?

**Comment by jusabatier** [comment]
Le XSL c'est juste pour faire du rendu PDF (comme le HTML pour des sites web), il ne fait pas de traitements.

L'info de base est dans les vues Postgis et les traitements sont faits dans le RPHelper.

Mais vu que pour moi tout fonctionne, je pencherais plus pour un soucis avec les vues arcopoles.

Si le problème venait des traitements ou rendu, j'aurais les mêmes soucis sur mes RP.

**Comment by MaelREBOUX** [comment]
En attente de @pierrejego pour maj PF de qualif pour test.

**Comment by pierrejego** [comment]
La mise à jour de la qualif se fait automatiquement 3 fois par jour, 12h30, 16h30 et 22h. Je pense que vos modifications sont déjà déployé.

**Comment by MaelREBOUX** [comment]
C'est identique entre qgis et arcopole - > ok -> on ferme !
