### ISSUE TITLE
[RP] traitement des valeurs avec des centimes d'euro

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#268]
Les exonérations de taxes sont exprimées en centimes d'euros. Exemple : attribut **drcsuba (revenu cadastral revalorisé en valeur du 01/01 de l'année)**.

On ne peut pas laisser sur le relevé de propriété une valeur en centimes.

Pb : changer ça dans la **vue proprietenonbatie** se fait de cette manière `CAST (suf.drcsuba AS REAL)/100 as drcsuba` (division par 100). Sauf que l'attribut drcsuba est déclaré en entier.

Il faudrait donc changer le type de entier à réel + changer le code java qui le nécessite.

Sinon : déporter le passage de centimes en euros dans RPHelper.java

A votre avis @pierrejego @jusabatier ?

**Comment by MaelREBOUX** [comment]
@pierrejego pour test / trace :  id_suf =
'3500010000A0002'
'350196000YI0029aj'

**Comment by jusabatier** [comment]
J'ai essayé dans l'aprem de générer un RP avec propriétées baties et non baties,

pour le bati il n'y a pas de decimal, mais par contre dans le non bati les decimales apparaissent.

Par exemple sur la parcelle où j'ai testé on a un revenu imposable/cadastral de 0.39

**Comment by MaelREBOUX** [comment]
Peut-on clore ce ticket ?

**Comment by MaelREBOUX** [comment]
@jusabatier : on attend ton retour. Pour @pierrejego et moi c'est ok.

**Comment by jusabatier** [comment]
Ok pour moi aussi
