### ISSUE TITLE
Pas d'affichage du sous-groupe dans le RP pour les parcelles agricoles

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#269]
J'ai eu le retour d'un utilisateur du CRPF comme quoi le champ groupe/sous-groupe pour une parcelle agricole dans le relevé de propriété ne remontait que le groupe (code type de parcelle ?) et pas le sous-groupe, et l'intitulé de colonne est 'GR/SS GR' mais le contenu est p.ex '01/' sans valeur après le /. En regardant dans le schéma, la valeur est sensée venir du champ dsgrpf de la vue proprietenonbatie, et dans la base j'ai ~19000 enregistrements ou cgrnum et dsgrpf sont vides, et 4703216. Je doute que ce soit un coup de malchance et que l'utilisateur soit tombé sur les seules parcelles ayant juste une valeur pour cgrnum et rien pour dsgrpf (aucun enregistrement dans la base avec ce cas), donc je me demande s'il manque pas un bout de plomberie. A debugger, mais est-ce que vous voyez la meme chose sur arcopole (@maelReboux?) et au puy (@jusabatier?)

**Comment by jusabatier** [comment]
Je confirme ce que tu dis.

J'ai testé sur une parcelle avec du non bati et sur le RP QGis on a bien GR / SS GR
par contre via l'addon le SS GR ne remonte pas 

exemple : 
- QGIS : 02/PA
- Addon : Prés/

**Comment by landryb** [comment]
Donc ca veut aussi dire qu'il faudrait traduire le code 02 en libellé 'compréhensible' ?

**Comment by jusabatier** [comment]
Le 02 (GROUPE) est déjà traduit en "Prés".

Il suffit juste de faire remonter le SS GROUPE qui doit déjà être dans un format lisible dans la vue car on avait fait la modif pour l'afficher dans la fiche d'info parcellaire de l'addon (nature de culture).

**Comment by pierrejego** [comment]
Le sous groupe est déjà dans la base et prévu dans le RP, il manquait juste le select du dsgrpf.
 Je viens de le faire sur la branche 257-propnonbat.

**Comment by pierrejego** [comment]
Erreur de message de commit, je ne voulais pas la fermer.

J'ai une remarque sur les valeurs pour le modèle Qgis, Le groupe et sous-groupe ont très souvent la même valeur, alors que dans le modèle Arcopole il est vide dans ce cas là.

Est-ce qu'on laisse afficher Eaux/Eaux ?

Les cas les plus faciles a voir pour le sous groupe, c'est pour le groupe Bois, on voit bien les différentes végétations en sous groupe.

@landryb un avis ?

**Comment by landryb** [comment]
> Les cas les plus faciles a voir pour le sous groupe, c'est pour le groupe Bois, on voit bien les différentes végétations en sous groupe.

L'erreur m'avait été reportée par qqn du CRPF qui utilise beaucoup cette info..

Je pense qu'il faut afficher ce qui vient de la BDD, peut importe la valeur. On est jamais a l'abri d'un changement dans la sémantique des données MAJIC, et les impots peuvent trés bien subitement décider d'ajouter des détails/sous-groupes. Et l'intitulé de la colonne est bien GR/SS-GR donc il faut afficher 2 valeurs a mon avis.

**Comment by pierrejego** [comment]
Ok c'est ce qui a été fait avec mon commit du coup.  Si c'est bon pour tout le monde on peut fermer cette issue

**Comment by landryb** [comment]
ok pour moi

**Comment by MaelREBOUX** [comment]
ok ici en test.
