### ISSUE TITLE
code insee sur 6 chiffres ?

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#27]
Dans https://github.com/GFI-Informatique/cadastrapp/blob/master/script/user/groupeAutorisation.sql je vois la table de correspondance entre code insee et role ldap georchestra, mais pourquoi utiliser 6 chiffres ? Meme si pour le cadastre c'est souvent 2 chiffres pour le departement + le code direction (0 dans tout les cas pour nous) et les 3 chiffres de la commune, de manière générale un vrai code insee est sur 5 chiffres...

**Comment by landryb** [comment]
Apres discussion, c'est bien sur 6 chiffres avec le 3e comme code direction, mais alors il ne faut pas l'appeller 'code insee'...

**Comment by pierrejego** [comment]
en cherchant, http://www.insee.fr/fr/methodes/nomenclatures/cog/documentation.asp?page=telechargement/2015/doc/doc_variables.htm#dep

Pour l'insee, le code insee de la commune = DEP(Code département)+ COM (Code commune)

• COM - Code commune
Code de la commune sur 3 positions. Quand il est précédé du code DEP, il forme le code Insee de la commune.

Il n'existe pas de vocabulaire pour définir le code DEP+AR+COM.
Par abus de langage, on peut voir des codes insee sur 5 , 6 ou 8 chiffres. On parle alors de différents format de code insee.

Ces champs sont décrits dans le Code Géographique Officiel.

Qu'est-ce que je choisi comme nom pour le nouveau "code insee" pour la commune. 
-> communeId
-> cityid
-> cgocom (Code Géographique Officiel Commune)

Ou alors une autre proposition ?
