### ISSUE TITLE
Erreur lors de l'ajout du layer cadastrapp

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#270]
Apres avoir mis a jour l'addon, lorsque j'ouvre l'addon, ma couche cadastre WMS ne se charge plus.

Suite à ce commit : https://github.com/georchestra/cadastrapp/commit/08c39de6e67d5a6aa43bdfa205b8785f4a45cf61

Dans la console JS, j'ai : 

> cadastrapp.js:76 Uncaught TypeError: Cannot read property 'indexOf' of null(anonymous function) @ cadastrapp.js:76Ext.apply.each @ ext-base.js:21GEOR.Addons.Cadastre.addWMSLayer @ cadastrapp.js:76window.Ext.Window.listeners.show @ cadastrapp.js:118h.Event.fire @ ext-all.js:21h.Observable.fireEvent @ ext-all.js:21Ext.Window.Ext.extend.afterShow @ ext-all.js:21Ext.Window.Ext.extend.show @ ext-all.js:21GEOR.Addons.Cadastrapp.Ext.extend._onCheckchange @ cadastrapp.js:126Ext.Button.Ext.extend.onClick @ ext-all.js:21I @ ext-all.js:21

**Comment by jusabatier** [comment]
Autre soucis, sur le poste d'un utilisateur grid[0] ne semble pas toujours defini...

Ca serait bien de s'assurer du fonctionnement d'un code avant de le merger à l'avenir

**Comment by pierrejego** [comment]
Bonjour,
j'ai bien fait les tests avant de merger, je n'ai pas d'erreur chez moi. Tout fonctionne bien, si elle est pas déjà chargé elle se charge, si elle est déjà chargé elle ne se charge pas.

Tu est dans quel conf chez toi ?

 Tu peux passer en mode debug pour voir ou c'est exactement dans le code ?  le mode minifié c'est pas facile à lire.

**Comment by jusabatier** [comment]
Je viens d'avoir l'erreur chez moi après avoir chargé un contexte : 
Uncaught TypeError: Cannot read property 'indexOf' of null(anonymous function)

Et Chez un utilisateur, c'est grid[0] qui n'était pas défini : https://github.com/georchestra/cadastrapp/blob/08c39de6e67d5a6aa43bdfa205b8785f4a45cf61/addons/cadastrapp/js/selectFeature.js#L585

La procedure exacte suivie est : 

Charger l'URL : /mapfishapp/?wmc=/mapfishapp/context/default.wmc
Charger un autre contexte
Essayer d'ouvrir l'addon cadastre pour charger la couche.

Pour un aperçu de ce WMC : http://opendata.agglo-lepuyenvelay.fr/mapfishapp/context/default.wmc

**Comment by pierrejego** [comment]
Ok on va refaire la manip et trouver une correction

**Comment by jusabatier** [comment]
D'accord, merci de me confirmer si vous arrivez à reproduire.

**Comment by pierrejego** [comment]
Oui on arrive à reproduire, c'est lié au fait que toutes les couches n'ont pas forcément de grid. On vient de rajouter un control. On finit de retester un peu tous les cas possibles et on push

**Comment by pierrejego** [comment]
C'est corrigé on a essayé de tester plein de cas pour vérifier qu'il n'y avait pas d'effet de bord, mais on sait jamais @jusabatier je te laisse vérifié sur ton cas et fermer l'issue.

**Comment by MaelREBOUX** [comment]
en attente retour @jusabatier pour test avant de clore

**Comment by jusabatier** [comment]
Testé avec mon cas et ça fonctionne correctement. Merci pour la correction.
