### ISSUE TITLE
[RP] Elements restants à corriger sur RP

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#271]
Suite aux différentes PR pour corriger les RP, les éléments qu'il reste à voir sont : 

Bati :
- <strike>Tx Om => Faire remonter le libelle correspondant</strike>  -> #281 
- <strike> Coef => Déterminer à quoi ça correspond et le faire remonter</strike>

Non Bati :
- <strike>FP / DP => A faire remonter </strike> -> #282
-<strike> ref lot => Voir si ça remonte correctement car pour ma part toujours vide (cas particulier ?) </strike> #288

**Comment by MaelREBOUX** [comment]
OK avec ça. Je rajoute :
- <strike>vérifier les totaux</strike> -> #261 
- <strike>certains RP sont parfois vides</strike> : #254 
- <strike>année de rattachement fiscal (colonne M, la première)</strike> :#311
- <strike>vérifier valeurs GC sur prop bâties</strike> -> corrigé avec https://github.com/georchestra/cadastrapp/commit/ddb4744f337314e1321a09f553ccdce5ff80c70e
- nommage idlocal -> idsuf

**Comment by MaelREBOUX** [comment]
A traiter en bugfixes
- <strike>vérifier les totaux -> #261<strike>
- <strike>vérifier valeurs GC sur prop bâties</strike> -> corrigé avec https://github.com/georchestra/cadastrapp/commit/ddb4744f337314e1321a09f553ccdce5ff80c70e

A passer en enhancement -> release stable :
- année de rattachement fiscal (colonne M, la première)
- nommage idlocal -> idsuf
- homogénéiser les codes SQL des scripts bases -> #276 
- bâti : 
  - Tx Om => Faire remonter le libelle correspondant -> #281
  - Coef => Déterminer à quoi ça correspond et le faire remonter -> @pierrejego demande à @stous 
- non bâti :
  - FP / DP => A faire remonter -> #282
  - ref lot => supprimer ? #288 
- mise en forme du RP simple généré lors d'une demande d'infos foncières (petit pb alignement) #284

Bug geOrchestra 16.12 avec urldecode du Security Proxy  : #254

**Comment by pierrejego** [comment]
Bonjour,
pour moi il ne reste que le renommage idlocal -> idsuf dans l'application, mais je pense que c'est lié à #276 

Pour moi cette issue peut être fermé, l'ensemble des actions ont été faite entre la v1.3 et la v1.4

**Comment by MaelREBOUX** [comment]
On ferme.
