### ISSUE TITLE
[documentation][RP] Faire une doc complète

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#279]
Faire une doc complète / un mode d'emploi sur le contenu du relevé de propriété.

Faire image avec pastilles numérotées sur les infos + explication en-dessous.

**Comment by MaelREBOUX** [comment]
On fait ça dans le wiki ?

**Comment by landryb** [comment]
Oui, dans le wiki .. vu que tout est déja la, et que c'est sensé être la source canonique de doc..

**Comment by MaelREBOUX** [comment]
Voici la doc visuDGFiP 2017

voir p. 9

[MU_VisDGI_CAD.pdf](https://github.com/georchestra/cadastrapp/files/3573428/MU_VisDGI_CAD.pdf)

**Comment by pierrejego** [comment]
Bon support effectivement pour faire notre doc

**Comment by MaelREBOUX** [comment]
Il y a eu une petite avancée quand même au printemps :  https://github.com/georchestra/cadastrapp/tree/documentation
+ http://docs.georchestra.org/cadastrapp/

En lien avec le portage sur MapStore

**Comment by MaelREBOUX** [comment]
Script de build de la doc cadastrapp en multi version ok

https://github.com/MaelREBOUX/georchestra_documentation/tree/master/cadastrapp

à déployer...

**Comment by MaelREBOUX** [comment]
Merci à @stous pour son travail sur la doc utilisateur.

- [ ] J'attaque la relecture + révision comme convenu ce matin.
- [ ] on arbitre ce qui sera à arbitrer
- [ ] Puis je bascule tout ça dans master.
- [ ] Puis je met en place le build auto sur le serveur georchestra

**Comment by MaelREBOUX** [comment]
Fait !
