### ISSUE TITLE
[RP] division par zéro -> NaN

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#280]
Sur certains RP on voit NaN apparaître, sans doute provoqué par une division par zéro.

Ex : RP 350066+00430

**Comment by jusabatier** [comment]
Ce n'est pas du à une division par zero mais à l'utilisation de format-number sur une chaine non numérique (espace) dans le XSL.

Ceci est très simple à régler : 

Il suffit d'ajouter l'attribut "NaN" dans le decimal-format "euro" définit au début du fichier cadastrapp/src/main/resources/xsl/relevePropriete.xsl (WEB-INF/classes/xsl/relevePropriete.xsl dans la webapp).

`<xsl:decimal-format name="euro" decimal-separator="," grouping-separator=" "  NaN=" "/>`

Merci de me confirmer si ça fonctionne (tu peux le remplacer directement dans le XSL de la webapp deployée pour tester).

**Comment by MaelREBOUX** [comment]
C'est dans fraction RC Exo qu'il faut mettre ça.

ligne 875 ?
https://github.com/georchestra/cadastrapp/blob/55f3b5077cb3e1a47ad75bb8b6feb574445e405b/cadastrapp/src/main/resources/xsl/relevePropriete.xsl#L875

**Comment by jusabatier** [comment]
Non ligne 6 : 

https://github.com/georchestra/cadastrapp/blob/55f3b5077cb3e1a47ad75bb8b6feb574445e405b/cadastrapp/src/main/resources/xsl/relevePropriete.xsl#L6

tu rajoute NaN=" " dans la balise.

Elle definit un format d'affichage pour les euros.

**Comment by MaelREBOUX** [comment]
ça marche pas. Il faut redémarrer la webapp ?

**Comment by MaelREBOUX** [comment]
oui : il faut redémarrer.  ça donne ça :  
![screenshot293](https://cloud.githubusercontent.com/assets/6370443/19594173/3eef4e02-9784-11e6-85bf-049f60381418.png)

![screenshot294](https://cloud.githubusercontent.com/assets/6370443/19594218/707bf9e8-9784-11e6-81eb-0ddf67a42b68.png)

On valide ou pas ? @jusabatier

**Comment by jusabatier** [comment]
A voir si ça convient, sinon il y a une autre methode qui permet de ne rien afficher du tout.

Je l'ai déjà utilisée pour enlever des NaN que j'avais sur mes RP : 

https://github.com/georchestra/cadastrapp/blob/55f3b5077cb3e1a47ad75bb8b6feb574445e405b/cadastrapp/src/main/resources/xsl/relevePropriete.xsl#L500

En gros on rajoute un test pour voir si la valeur est numerique avant de l'afficher.

Il serait peut être plus cohérent d'utiliser cette méthode qui permet de ne pas afficher le "€" et qui est déjà mise en place sur certains cas que j'avais identifié.

**Comment by MaelREBOUX** [comment]
allez hop : fait avec https://github.com/georchestra/cadastrapp/commit/269499e06232b652832f353bae809ac794d56694
