### ISSUE TITLE
[RP] Remonter info(s) sur la taxe ordure ménagère

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#281]
Extrait de la doc DGFiP 

p 8 

> Zone OM de l'article 10
> Valeurs possibles « P » (taux plein) et taux réduits « RA » à « RD »; si la zone est au taux plein, la lettre « P » est cadrée à gauche

p 11

> - BATEOM = base d’imposition de la PEV prise en compte pour la taxe d’enlèvement des ordures
>   ménagères (TEOM) ;
> - BAOMEC = base d’imposition écrêtée de la PEV, c’est-à-dire non prise en compte pour la taxe
>   d’enlèvement des ordures ménagères.

On est d'accord qu'on veut remonter une valeur P / RA / RB / RC / RD ?

**Comment by MaelREBOUX** [comment]
Dans arcOpole, l'info est dans **dgi_local.gtauom**
Dans QGIS, l'info est dans **local10.gtauom**

Faut donc modifier les 2 vues proprietebatie.

**Comment by MaelREBOUX** [comment]
COEFF = coefficient de réduction qui s'applique à la TEOM.

Je ne trouve rien qui semble correspondre à ça dans les données :(

**Comment by pierrejego** [comment]
Ok actuellement dans le modèle Arcopole on remonte dgi_taxpev.bateom et pevtaxation.bateom dans le modèle QGIS.

local10.gtauom correspond à la zone de ramassage des ordures ménagères - P RA RB RC RD ou blanc

la ou pevtaxation.bateom correspond à la BASE ORDURES MENAGERES

Je change donc pour prendre gtauom pour les deux modèles

**Comment by pierrejego** [comment]
Est-ce que je change le titre TX OM de la colonne et est-ce que j'enlève la colonne Coeff à côté ?

**Comment by pierrejego** [comment]
Première modification effectuée avec ce commit : https://github.com/georchestra/cadastrapp/commit/b83491fa1dd45911911c4c27616a90a5987b66f8

Attention modification de la vue, suppression de deux champs et ajout d'un nouveau

**Comment by pierrejego** [comment]
J'enlève le champ COEFF

**Comment by MaelREBOUX** [comment]
pour mémo : page 8 de BATI_16.PDF

2.1.2.6. Zone OM
Valeurs possibles « P » (taux plein) et taux réduits « RA » à « RD »; si la zone est au taux plein, la lettre
« P » est cadrée à gauche.
