### ISSUE TITLE
[RP] FP / DP

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#282]
D'après la notice DGFiP :
- 0 = FP = domaine privé qui figure au plan
- 1 = DP = domaine privé ou public qui ne figure pas au plan

Dans arcopole, l'info se trouve dans **dgi_nabti.gparnf**.
Dans qgis,  l'info se trouve dans **parcelle.gparnf**.

Il faut donc modifier les 2 vues proprietenonbatie.

**Comment by pierrejego** [comment]
Je prépare l'ajout du FP/DP dans la partie non batie.
Pour l'instant ce champ est dans la vue parcelledetails, mais jamais utilisé.
Je vais donc le supprimer de la vue parcelledetails, pour le mettre dans la vue la vue proprietenonbatie, et le récupérer ensuite pour générer le RP.
Dans le RP, comment est-ce qu'on l'affiche ? Je met DP pour 1 et FP pour 0 ou je garde 1 et 0 sachant que le nom de la colonne est FP/DP ?

**Comment by pierrejego** [comment]
Par contre je viens de vérifier dans la base et dans les docs, j'ai un doute. Actuellement en base on récupère déjà nbati.gparnf pour Arcopole, mais gpafpd pour Qgis.

Dans la doc QGIS, parcelle.gparnf correspond à "Indicateur de parcelle non figurée au plan - 1 = figurée, 0 = non figurée" alors que parcelle.gpafpd "Domanialité, représentation au plan" mais à priori il est indisponible, et vide dans la base que j'ai.

Ou est-ce que tu as trouvé tes infos @MaelREBOUX ?

**Comment by pierrejego** [comment]
Ok j'ai mal lu, je remplace par gparnf

**Comment by pierrejego** [comment]
@jusabatier et @MaelREBOUX  Est-ce que je met DP pour 1 et FP pour 0 ou je garde 1 et 0 sachant que le nom de la colonne est FP/DP ? J'ai regarder sur les exemples que tu m'as donné Mael, on voit 1 et 0 mais pas DP ou FP.

**Comment by MaelREBOUX** [comment]
oui : on garde 1 ou 0 et on renverra à la notice (à faire...)

**Comment by pierrejego** [comment]
Ok merci, je laisse comme ça.

**Comment by MaelREBOUX** [comment]
Pour mémo : page 15 du fichier NBAT_16.PDF

70 70 1 X GPARNF Indicateur de parcelle non figurée au plan 1 = figurée, 0 = non
figurée
