### ISSUE TITLE
[RP simple] petit problème mise en forme

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#284]
Petit problème d'alignement sur le RP simple généré par la demande d'infos foncières 

![screenshot320](https://cloud.githubusercontent.com/assets/6370443/19718219/ab88beb6-9b64-11e6-8534-89770055e3dc.png)

**Comment by pierrejego** [comment]
Ok je viens de faire des tests de modifications, pour résoudre ce problème de décalage. @jusabatier avait modifier les tableaux en déclarant toutes les colonnes au début. Mais il n'y a plus de notion de header et donc plus de report des intitulés de colonne sur chaque page.
Ce que je fais essayer de faire, c'est de déclarer toutes les colonnes et d'utiliser les number-columns-spanned pour déclarer les headers.
