### ISSUE TITLE
[RP] [BP] Date : mois en anglais

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#285]
A plusieurs endroits on fait apparaître une date littérale de génération des documents : bordereau parcellaire, relevé de propriété.

Sur ces documents le mois apparaît en anglais : "October" à la place de "Octobre", par exemple.

**Comment by pierrejego** [comment]
@MaelREBOUX  Est-ce que tu peux me détailler les endroits ou tu vois les dates en anglais, je viens de regénérer toute une série de document, mais je n'ai pas une seul date en Anglais.
D'ailleurs la seul référence d'une date que j'ai, c'est la date de création du document dans le BP qui est bien en français chez moi.

![image](https://cloud.githubusercontent.com/assets/11499415/22056093/a6fd8656-dd5e-11e6-9df2-da9f53da6025.png)

**Comment by landryb** [comment]
c'est dépendant de la locale, cf #116 et #226

**Comment by MaelREBOUX** [comment]
Vu : en cours de check chez nous.
