### ISSUE TITLE
[BP] Améliorer la qualité de la carte

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#286]
Actuellement la qualité de l’image produite dans un bordereau parcellaire est de médiocre qualité.
Les images actuelles semblent faire 550 x 550 px max pour une résolution de 72 dpi. 

Comment augmenter la qualité ?

**Comment by landryb** [comment]
Après discussion, on va proposer dans la future fenetre de parametres utilisateurs de choisir entre 72 et 200 (et que la valeur soit dans le localstorage comme le contexte/style), ou vous voulez que ce soit 'basse resolution'/'haute résolution' et que les valeurs soient paramétrables par l'admin ?

**Comment by pierrejego** [comment]
Comme je le disais dans un mail @MaelREBOUX , j’ai modifié la génération, ce qui améliore la qualité de l’image, l’image est maintenant toujours de la même taille. Un carré de 550px par 550px et la parcelle centrée (centroîd de la parcelle au milieur de l'image).
 Par contre, la notion de DPI n’est pas dans la norme OGC, et a été implémentée différemment sur les geoserver, mapserver et autres serveurs cartographique. 
(paramètre MAP_RESOLUTION pour mapserver, DPI pour QGISSERVER et FORMAT_OPTIONS pour geoserver). 

 Du coup, si je ne connais pas le type de serveur qui héberge la couche avant, je ne peux pas ajouter la commande de DPI. 
J'ai quand même fait des tests sur les geoservers et le fond de plan fournit par geobretagne.  Avec et sans DPI à 200 et personnellement je trouve ça même plus beau sans avoir mis d'information de DPI.
La couche du geobretagne ne prend pas en compte le changement de DPI, la couche en fond est toujours de la même qualité.

Il faut qu'on en reparle ensemble, mais modifier le DPI, sans être maître de l'origine du fond de plan et de la couche, ne me semble finalement pas une bonne solution. On risque de faire du spécifique en dehors de la norme OGC.

Vous en pensez quoi ? @MaelREBOUX @jusabatier @landryb

**Comment by pierrejego** [comment]
C'est bon en fait, j'ai trouvé un autre moyen de prendre en compte les DPI.
Je prends en compte dans le PDF le DPI souhaité, et je modifie la taille en pixel des images demandées côté serveur cartographique.
Plus besoin de demander un niveau de DPI particulier, juste une bounding box, et une taille en pixel plus ou moins grande.
ça plus la sélection par SLD et c'est bon niveau qualité

**Comment by MaelREBOUX** [comment]
C'est BIEN  mieux !!

Amélioration de la qualité : OK ++

Toute la place disponible / forme de la carte : OK
**MAIS** il faut rajouter un peu de marge à droite de la carte. La marge qui est G H et B de la carte par rapport au bord de la page A4 est OK. Rapporter la même distance par rapport au bloc de texte de droite. 

Blocage du zoom max dans le fichier conf : OK (testé au 1/1500 = valeur 15 puis au 1/1000 = valeur 10)
Adaptation du zoom pour les grandes parcelles : OK

@pierrejego comme vu par tel : jeter un coup d'œil rapide pour voir comment obtenir des échelles graphiques bien rondes. Genre 0-160 mètres plutôt que 1-159 mètres. Sinon on garde ça sous le coude pour une vraie évolution.

Un truc oublié depuis longtemps : flèche Nord en noir et pas en blanc. Possible @pierrejego ?

**Comment by MaelREBOUX** [comment]
Top ! RAS Plus rien à ajouter. Je ferme.
