### ISSUE TITLE
[Infobulle] erreur 500 si UF demandée et interrogation hors commune autorisée

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#287]
Si on active "UF" sur la barre d'outils : on a une erreur 500 sur une commune sur laquelle on n'a pas d'accès aux DN.

Le contenu renvoyé est :
Infobulle : Error occured when trying to get information from server, please check server logs

``` sql
select uf.comptecommunal, sum(p.dcntpa) as dcntpa_sum, sum(p.surfc) as sigcal_sum from cadastrapp_arcopole.parcelleDetails p, cadastrapp_arcopole.proprietaire_parcelle proparc, cadastrapp_arcopole.uf_parcelle uf  
where proparc.parcelle = '350047000AS0350'
 and proparc.comptecommunal = uf.comptecommunal 
 and p.parcelle=uf.parcelle
 AND p.cgocommune IN ('350238' )  GROUP BY uf.comptecommunal ;
```

renvoie bien 0 enregistrement

**Comment by MaelREBOUX** [comment]
J'ai retesté ce matin à cause des diff entre PF de test et PF de prod.

Comportement idem : erreur 500 sur les 2 PF.

Et confirmé aussi sur PF Le Puy par @jusabatier

**Comment by pierrejego** [comment]
ok je ne comprenais pas pourquoi je n'arrivais pas à reproduire, mais en fait c'est un cas particulier. la parcelle 350047000AS0350 n'est dans EDIGEO. Du coup, il n'y a pas d'entrée en base permettant de calculer la surface. 

Dans les autres cas, c'est à dire la plus part du temps ça fonctionne bien ? ou vous avez tout le temps l'erreur 500 ?

**Comment by MaelREBOUX** [comment]
ha ben ça ça sera résolu avec #201 alors ?

**Comment by jusabatier** [comment]
Euh il me semble bien que ça le faisait tout le temps du moment qu'on est sur une autre commune que celle qui est assignée au compte utilisateur.

**Comment by MaelREBOUX** [comment]
si si : AS350 parcelle tout à fait normale. ça le fait quand tu vas hors de ta commune autorisée.

**Comment by jusabatier** [comment]
> org.springframework.dao.EmptyResultDataAccessException: Incorrect result size: expected 1, actual 0
>   org.springframework.dao.support.DataAccessUtils.requiredSingleResult(DataAccessUtils.java:71)
>   org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:806)
>   org.springframework.jdbc.core.JdbcTemplate.queryForMap(JdbcTemplate.java:839)
>   org.georchestra.cadastrapp.service.InfoBulleController.getInfoBulleUniteFonciere(InfoBulleController.java:168)
>   org.georchestra.cadastrapp.service.InfoBulleController.getInfoBulle(InfoBulleController.java:57)

**Comment by pierrejego** [comment]
... du coup je ne comprends pas pourquoi je ne le reproduis pas sur mes serveurs. J'aimerai reproduire pour être sur de la correction...

Et pour la parcelle, j'ai ce message si je veux zoomer dessus. Donc si elle est normal, le message ne l'est pas si ?

![image](https://cloud.githubusercontent.com/assets/11499415/19925126/fea2ae6a-a0ee-11e6-84c5-d1f8737e5e0e.png)

**Comment by MaelREBOUX** [comment]
A relire, si on traite #201 on règlera ce problème ?

**Comment by jusabatier** [comment]
Ce message s'affiche normalement lorsqu'on essaye de faire un zoom (resultat de recherche) et que  soit aucune parcelle n'est sélectionnée, soit la parcelle sélectionnée est uniquement présente dans le fichier MAJIC, et ne dispose pas de correspondance EDIGEO (pas vectorisée).

Actuellement, ce message avait été ajouté afin que les parcelles non vectorisées puissent être retrouvées via le formulaire de recherche et que l'on puisse consulter leur fiche foncière sans avoir des messages incompréhensibles en essayant de zoomer dessus.

Le problème traité par #201 est l'opposé, il s'agit de pouvoir retrouver une parcelle vectorisée mais n'ayant pas de correspondance dans les fichiers MAJIC, afin d'a minima pouvoir zoomer dessus et la localiser. Eventuellement en tirer un plan via l'impression MFapp.

En tout cas, cela ne me semble pas lié au souci évoqué par cette issue.

Ici le problème vient de la requete de l'infobulle qui est faite lorsqu'on est en dehors des communes autorisées pour son profil.

Pour corriger cette erreur il faut aller voir dans le fichier : 
https://github.com/georchestra/cadastrapp/blob/master/cadastrapp/src/main/java/org/georchestra/cadastrapp/service/InfoBulleController.java#L168

Cf les logs que j'ai posté ci-dessus. Le résultat est récupéré dans un queryForMap, or cette fonction necessite de recupérer au moins un résultat, ce qui n'est pas le cas quand on est hors de son perimetre de compétence.

Visiblement on a donc affaire à un problème au niveau de la requête SQL, probablement le filtre géographique qui n'est pas correctement ajouté et fait qu'aucun resultat correspondant n'est retrouvé.

**Comment by landryb** [comment]
Sur une maj en 1.7 je viens d'avoir une NPE précisément pour cette erreur, le bug existe toujours (j'imagine qu'il est revenu suite a 0c67a2556 ?).

On ne gère pas le cas d'une demande d'UF sur un zone non autorisée, donc on affiche la carte dans la popup/nouvel onglet, mais le  `GET cadastrapp/services/getInfoUniteFonciere?parcelle=<parcelleid>` renvoie un code 500 et les infos textuelles ne sont pas affichées :/

```
java.lang.RuntimeException: org.apache.cxf.interceptor.Fault: Incorrect result size: expected 1, actual 0
	org.apache.cxf.interceptor.AbstractFaultChainInitiatorObserver.onMessage(AbstractFaultChainInitiatorObserver.java:116)
	org.apache.cxf.phase.PhaseInterceptorChain.wrapExceptionAsFault(PhaseInterceptorChain.java:365)
	org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:323)
	org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:251)
	org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)
	org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:293)
	org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:217)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:268)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
```

**Comment by pierrejego** [comment]
Ok, a prendre en compte dans la 1.8
Je vais essayer de trouver un cas dans mes données pour reproduire d'ici demain

**Comment by landryb** [comment]
Il n'y a pas de "cas" a trouver, il suffit juste de faire un demande d'UF dans une commune ou on n'a pas les droits :)

**Comment by MaelREBOUX** [comment]
ou simplement de vouloir consulter l'info-bulle

**Comment by pierrejego** [comment]
Ok on a reproduit correction en cours

**Comment by MaelREBOUX** [comment]
Cool : hâte de tester

**Comment by MaelREBOUX** [comment]
Bon : enfin pu tester. Pas facile à cause de la gestion des comptes.

pour l'UF : on n'a plus d'erreur 500 sur la page UF mais une page avec juste une carte et pas d'autre information. 

![capture_061](https://user-images.githubusercontent.com/6370443/58417982-c58f8100-8086-11e9-9df6-f223562cde68.png)

Perso : **si on pouvait mettre un message** genre "Aucune information n'est affichée car vous ne disposez pas d'un accès aux données foncières pour cette commune." : ce serait un peu mieux pour l'utilisateur.

Pour l'infobulle : 
Le positif : la requête aboutit et on récolte un JSON en réponse, sans DN.
Le négatif : pas d'infobulle. Je veux dire : L'infobulle ne se construit pas et ne s'affiche pas.  *Est-ce que c'est ce qu'on veut ?*

**Comment by landryb** [comment]
non, il faut un message clair a l'utilisateur, en l'état il ne comprendra rien.

**Comment by Gaetanbrl** [comment]
On peut afficher une fenêtre affichant que l'utilisateur ne dispose pas des droits suffisants dans ces deux cas ?

**Comment by MaelREBOUX** [comment]
Je propose :

* pour la page UF : on rajoute ce message dans le cadre sous la carte : "Aucune information n'est affichée car vous ne disposez pas d'un accès aux données foncières pour cette commune."

* pour l'infobulle : on laisse en l'état : à savoir : pas d'infobulle en-dehors des communes autorisées.

**Comment by landryb** [comment]
pas d'infobulle => l'utilisateur va cliquer 125 fois, et appeler.

**Comment by MaelREBOUX** [comment]
C'est pas faux : donc on affiche les qqs infos renvoyées par la webapp.

Je crois qu'il n'y a que la référence cadastrale d'ailleurs.

**Comment by Gaetanbrl** [comment]
Si j'ai bien compris, on affiche un message pour la page d'UF sous la carte contenant : 

> "Aucune information n'est affichée car vous ne disposez pas d'un accès aux données foncières pour cette commune."

Et pour l'infobulle on affichera l'infobulle contenant le peu d'information renvoyé actuellement. Cela vous convient ?

**Comment by Gaetanbrl** [comment]
@MaelREBOUX  @landryb  On aurait alors ces informations dans l'infobulle : 
![image](https://user-images.githubusercontent.com/16317988/58547833-63f72000-8208-11e9-8a0b-b9a3b06d18e1.png)

**Comment by landryb** [comment]
mais l'utilisateur ne va toujours pas comprendre pourquoi il a des infos d'UF sur certaines communes et pas d'autres.. je pense qu'il faut etre plus clair :)

pourquoi vouloir gérer différemment les 2 cas ? "Aucune information n'est affichée car vous ne disposez pas d'un accès aux données foncières pour cette commune." me va bien pour la fiche UF, on pourrait avoir l'équivalent "raccourci" pour l'infobulle.

**Comment by Gaetanbrl** [comment]
Ce message "raccourci" peut convenir ? 

![image](https://user-images.githubusercontent.com/16317988/58548957-bd604e80-820a-11e9-9f2b-f78b4ee269cb.png)

**Comment by landryb** [comment]
oui nickel ;)

**Comment by MaelREBOUX** [comment]
Je vous suis. Même si pour l'infobulle j'aurais préféré ne rien afficher de plus.

Car si on n'affiche rien de spécial : l'utilisateur ne sait pas qu'il n'a pas accès à d'autres infos.
Et ça me va très bien.

**Comment by landryb** [comment]
Si tu n'affiche rien, pour moi l'utilisateur va te demander pourquoi il a accès aux UF a certains endroits et pas a d'autres...

**Comment by pierrejego** [comment]
Modification faite, nouveau comportement a valider

**Comment by MaelREBOUX** [comment]
Bon je viens de m'arracher les cheveux à tente de tester en ça en test.

Mais cette PF vient de changer d'infrastructure. Je n'ai aucune info sur la version qui y est déployée.
Donc je sens que ça va repousser de 10 j :(

Chez moi pas d'infobulle en-dehors de la commune autorisée.

Et sur la commune autorisé MAIS sans le rôle APPLI_CAD je vois :

![image](https://user-images.githubusercontent.com/6370443/59509936-b85df900-8eb2-11e9-916e-adc90c2762f4.png)



Pour l'UF : tout est vide maintenant. Pas normal.

![image](https://user-images.githubusercontent.com/6370443/59509164-92cff000-8eb0-11e9-9e5e-b76ce579248c.png)

**Comment by MaelREBOUX** [comment]
OK. Grâce à @Gaetanbrl  je sais que notre serveur de test n'a pas la dernière version du code.
A revoir.

**Comment by MaelREBOUX** [comment]
Infobulle OK : plus d'erreur 500 mais si on pouvait virer le "undefined" ce serait mieux.

![capture_145](https://user-images.githubusercontent.com/6370443/60712916-4e1bff80-9f18-11e9-9918-10cc5ea327d0.png)


![capture_144](https://user-images.githubusercontent.com/6370443/60712925-52481d00-9f18-11e9-9758-e2811af4ea18.png)


je constate que je n'ai plus la surcouche graphique qui montre l'unité foncière. mais comme on vient de changer des réglages je préfère vérifier à 2 fois avant d'ouvrir une issue ici.

**Comment by Gaetanbrl** [comment]
> je constate que je n'ai plus la surcouche graphique qui montre l'unité foncière

Dans la fenêtre d'information sur une unité foncière ?

**Comment by Gaetanbrl** [comment]
> Infobulle OK : plus d'erreur 500 mais si on pouvait virer le "undefined" ce serait mieux.

A ce sujet, je viens de faire un commit https://github.com/jdev-org/cadastrapp/commit/ac006ad7621edee3de71be2c8e5ac187e4a5cd39, j'attend ton retour sur la surcouche graphique de l'UF pour une PR.

**Comment by MaelREBOUX** [comment]
>> je constate que je n'ai plus la surcouche graphique qui montre l'unité foncière

> Dans la fenêtre d'information sur une unité foncière ?

Même dans mapfishapp. Mais comme je te dis : j'ai un doute sur notre config sur test. Sauf si tu l'as constaté aussi de ton côté. C'est le cas ?

**Comment by Gaetanbrl** [comment]
Si ca peut permettre de comparer et d'identifier un boug ou une configuration voici ce que j'ai de mon côté.

- Au clique dans Mapfishapp j'ai bien la surcouche qui me permet de voir la sélection :

![image](https://user-images.githubusercontent.com/16317988/60892341-4e413580-a25f-11e9-93be-2c208d3d3156.png)

- Lorsque je demande l'UF j'ai bien l'entité de dessinée :

![image](https://user-images.githubusercontent.com/16317988/60892506-86e10f00-a25f-11e9-96f0-d05ff97cbb05.png)

Est-ce bien la surcouche graphique en question ?

**Comment by Gaetanbrl** [comment]
Ok vu avec @MaelREBOUX . La surcouche n'est pas visible de leur côté. Testé et validé de notre côté.

PR à réaliser pour le patch au sujet du "undefined".

**Comment by MaelREBOUX** [comment]
Super. Réglé avec https://github.com/georchestra/cadastrapp/commit/741ef947c9d07cbef533612513ce25414d93f21b

![capture_155](https://user-images.githubusercontent.com/6370443/60983273-f5929b00-a339-11e9-839a-b241ef8a7853.png)

Je vais donc compléter la note de version demain matin et @pierrejego pourra faire la release avant vendredi.

Ouf !
