### ISSUE TITLE
[RP] supprimer ref lot dans les propriétés non bâties ?

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#288]
Il est probable qu'il y a eu une confusion avec les lots d'une propriété bâtie car cette colonne est vide sur les RP.

On propose donc de supprimer cette colonne. **Qui est contre ?**

**Comment by pierrejego** [comment]
Après vérification dans le CCTP, c'est une demande du Puy En Velay.

**Comment by pierrejego** [comment]
@jusabatier je ne sais pas si tu as pu en discuter avec Aurélie.

Voilà les informations que j'ai pu trouver ; 

2.1.2.4. Indicateur d’appartenance à une PDL
Le top GPDL peut prendre les valeurs :
- 0 : la parcelle n’appartient pas à une PDL ;
- 1 : la parcelle est référence de PDL (identifie une PDL) ;
- 2 : la parcelle est composante de PDL mais ne l’identifie pas.
Remarque : PDL = Propriété Divisée en Lots, regroupe les notions de copropriétés, de biens
non délimités, de propriétés en transparence fiscale ainsi que tous les cas où un état
descriptif de division est établi.
2.1.2.5. Identifiant de PDL
Cette zone est servie pour les parcelles d’indicateur GPDL égal à 2, c’est-à-dire pour les
parcelles composantes d’une PDL. Elle contient les références cadastrales de la parcelle qui
identifie la PDL, et partant les lots s’y rapportant.
C’est la parcelle de référence de PDL.

Dans le model QGIS, il y a deux colonnes dans la table suf : 

dnupdl et pdl

Dans les données que j'ai, je n'ai qu'une seule entrée ou ces champs ne sont pas vides. Le dnupdl est à 001 et pdl est la clé primaire de la table pdl qui contient un numéro de lot. C'est peut être ce lot qui nous intéresse. 
Pour être sur il faudrait des données avec un dnupl égal à 002 pour vérifier si il y a bien plusieurs lots.

Il y a aussi le champ dnulot dans la table suff  mais c'est le lot pour les BND (je crois bien non délimité) je ne pense pas que cela corresponde.

**Comment by jusabatier** [comment]
J'en ai parlé à Aurélie, elle non plus n'a pas su me dire à quoi ça correspond.

J'ai regardé dans notre BDD, je n'ai aucun enregistrement avec un dnupdl à '002'.

La table pdl ne contient pas de numero de lot mais un champ lot de type caractere qui pour moi et toujours à 1.

A mon avis, le champ à utiliser est bien dnulot, il ne correspond pas seulement à des BND (Bien Non Délimités), il est juste indiqué en commentaire qu'un BND commence par '00A'.

**Comment by pierrejego** [comment]
Ok je vais mettre la valeur du champ dnulot.

**Comment by pierrejego** [comment]
Le releve de propriete prend déjà le champ dnulot, je viens d'essayer sur une propriété non batie la valeur apparaît bien, par contre il y a peu de cas ou cette valeur apparaît. Tester avec une parcelle 350352000AT0033
