### ISSUE TITLE
[fiche info] mauvais comportement du tri des copros à cause de la pagination

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#289]
Dans l'onglet co-propriétaires, dans les cas où le nombre d’enregistrements retournées est supérieure à 25, la pagination des résultats se met en route.

 Si on clique sur l'une des colonnes visibles pour trier cela trie sur les enregistrements de la page en cours et non pas sur l'ensemble des enregistrements.
Cela est dû à une limitation ExtJs 3.4. 

Un contournement est de supprimer la pagination.

A vos commentaires.

**Comment by landryb** [comment]
supprimer la pagination, si t'as 2000 enregistrements... je suis pas certain que ce soit une bonne idée.

**Comment by pierrejego** [comment]
Pour détailler un peu, la limitation ne vient pas de ExtJs 3.4. 
C'est tout à fait possible de le faire, mais uniquement en mettant en place un remoteSort. A chaque fois qu'on clique ça renvoie un requête côté server et refiltre en nous laissant sur la page courant. (A cause des paramètres limit et start)

Ce qui pose problème c'est les paramètres d'appels côtés serveur, il faut lui envoyer l'ordre du sort.
Or ce paramètres ne peut pas être facilement intégrer sans laisser un risque d'injection SQL. On ne peut pas faire de ? pour la partie ASC ou DESC.

Et il faut que le nom de la column grid extjs correspond au nom de la column dans la requête et la c'est un vrai casse tête car la column adresse c'est un concaténation de dlign3 4 5 et 6

C'est donc plus côté serveur que cela pose de gros problème.

Je vois d'ailleurs dans le code existant qu'il y a un risque d'injection avec les paramètres start et limit. Je change ça toute suite.

**Comment by landryb** [comment]
> Ce qui pose problème c'est les paramètres d'appels côtés serveur, il faut lui envoyer l'ordre du sort.
> Or ce paramètres ne peut pas être facilement intégrer sans laisser un risque d'injection SQL.

Je ne vois pas de soucis avec un queryparam du GET sort=asc ou sort=desc, et coté serveur en fonction de la valeur du param sort ajouter `ORDER ASC` our `ORDER DESC` sans faire `ORDER ? ` avec la valeur du param...

**Comment by pierrejego** [comment]
Oui c'est vrai on pourrait faire un case.
Reste le problème des noms de colonnes du coup.

**Comment by MaelREBOUX** [comment]
Ca va être possible ou pas du coup ?

**Comment by pierrejego** [comment]
Non je n'ai pas de moyen de le faire à cause du nom des colonnes pour l'adresse.

**Comment by pierrejego** [comment]
En fait si je peux, si je modifie directement la complétion côté serveur au lieu de le faire côté client. Au lieu d'envoyer dlign + dlign..... et de les concaténer côté client, il suffit que j'envoie adresse directement

**Comment by pierrejego** [comment]
Et bien non, un order by ne marche pas sur un alias, il faudra modifier la structure de la base pour avoir un champ adresse dans la vue plutôt que dlign3, 4 5 et 6.

**Comment by MaelREBOUX** [comment]
J'enlève le milestone mais je rouvre pour trace.

pr contre : on a une régression -> #437
