### ISSUE TITLE
WhiteSpace in libcom Qgis

### ISSUE THREAD

**Issue by pierrejego** [georchestra/cadastrapp#29]
La table commune QGIS contient des espaces en fin de libellé de communes. Il faudrait soit les enlever dans la vue, soit proposer un script de nettoyage pour QGIS (de préférence la deuxième solution).
Le champ est bien en varying(30) il n'y a donc pas besoin de ces espaces supplémentaires.

**Comment by cbesche** [comment]
Modifier dans la vue pour le moment - Attention il y a de déjà un upper dans le script pour passer en  majuscule . 
si script il faudrait envisager d'ajouter  directement une colonne avec un libelle formaté pour l'appli
