### ISSUE TITLE
[RP] propriétés bâties : mise en forme %age exonération

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#290]
![screenshot321](https://cloud.githubusercontent.com/assets/6370443/19723133/387f9c4e-9b7a-11e6-819c-bcb3c6a76afe.png)

ici on devrait afficher 100 % et pas 1000.

On a oublié une division par 100 dans la vue Proprietebatie.sql j'ai l'impression ?

@jusabatier tu as la même chose de ton côté ?

**Comment by jusabatier** [comment]
Avec le modèle QGis c'est OK : 

![image](https://cloud.githubusercontent.com/assets/8310116/19725264/e43eefbc-9b84-11e6-833c-796530501afb.png)

Surement un soucis dans le script de création de la vue Arcopole.

**Comment by pierrejego** [comment]
Je peux faire la correction maintenant si tu veux ?

**Comment by MaelREBOUX** [comment]
ok : on fait comme ça.

**Comment by pierrejego** [comment]
Vérifié sur la qualif

**Comment by MaelREBOUX** [comment]
En attente vérification chez nous.

**Comment by MaelREBOUX** [comment]
Testé et approuvé !
