### ISSUE TITLE
Limitation du nb de parcelles pour l'export CSV

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#292]
Je viens de constater que la fonction "Exporter sélection" est très limitée : elle ne fonctionne plus à partir d'un certain nombre de parcelles sélectionnées.

Je pense que ce problème vient du fait que le service est appelé en passant la liste de parcelles en GET, ce qui pose problème si on en selectionne trop car la taille d'une URL est limitée.

Il faudrait donc appeler ce service via POST afin de corriger ce souci.

**Comment by MaelREBOUX** [comment]
Un indice sur la volumétrie limite ?

**Comment by jusabatier** [comment]
A partir du moment où on dépasse la limite de caractère d'une URL dans l'appel au service
