### ISSUE TITLE
[RP] propriétés bâties : problème totaux si présence exonération

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#293]
Le RP produit par VisuDGFiP

![screenshot324](https://cloud.githubusercontent.com/assets/6370443/19727197/bebfb08c-9b8e-11e6-9c8a-6ec003c1cc38.png)

Le RP produit par cadastrapp

![screenshot325](https://cloud.githubusercontent.com/assets/6370443/19727209/c5ed0530-9b8e-11e6-9b63-4a1fb45a58ba.png)

Les millésimes sont différents ce qui explique les légère différences de valeurs.

Les problèmes :
- le revenu imposable total est la somme de la colonne revenu cadastral -> qui est ici faux car la parcelle 118 apapraît 2 fois au lieu de une
- le revenu communal est également faux

Quoi d'autre ?

@pierrejego il faudrait que tu regardes sur ta PF de test qui utilise les données QGIS pour voir si ça produit la même chose.

**Comment by pierrejego** [comment]
Pour repérer les cas ou l'erreur se produisait voila une requête.
select invar, Count(invar) from cadastrapp_qgis.proprietebatie Group by invar ORDER BY COUNT(invar) DESC;

J'ai fait la modification des revenus imposables. En vérifiant dans les deux modèles.

Il me reste à voir pourquoi l'exonération du département ne s'affiche pas, je ne vois pas d'erreur dans les logs, la table est bien rempli, c'est le bon paramètre qui est appelé et le bon affiché dans le xsl.

**Comment by pierrejego** [comment]
Cela fonctionne pour Qgis mais pas pour Arcopole, l'erreur doit venir de la vue

**Comment by pierrejego** [comment]
Ok j'ai trouvé, il y a un espace à gauche dans la colonne ccolloc pour la vue arcopole, je rajoute un trim dans la création de la vue pour corriger

**Comment by MaelREBOUX** [comment]
En attente vérification chez nous.

(désolé : pas pu te donner infos pour les totaux...)

**Comment by MaelREBOUX** [comment]
Testé et approuvé !
