### ISSUE TITLE
[webapp] bean java pour purger automatiquement les fichiers générés ?

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#294]
La webapp produit plusieurs types de fichiers :
- bordereaux parcellaires en PDF
- relevés de propriétés en PDF
- exports de parcelle en CSV
- exports de proprios en CSV

Tous ces fichiers sont créés dans un répertoire défini en plusieurs endroits : https://github.com/georchestra/cadastrapp/search?utf8=%E2%9C%93&q=tempFolder&type=Code

Actuellement aucun processus n'est mis en place pour purger automatiquement ces fichiers.
Plutôt que de mettre en place un job cron sur l'OS, peut-on confier cette tâche de nettoyage / purge à un bean côté Java ?

Exemple avec extractorapp : https://github.com/georchestra/cadastrapp/blob/master/cadastrapp/src/main/webapp/WEB-INF/beans.xml

A vos commentaires.

**Comment by MaelREBOUX** [comment]
Pour info : en régime de croisière on estime ici le volume entre 700 et 1100 Mo par jour de documents générés.

**Comment by MaelREBOUX** [comment]
Je viens de voir que [la doc sur le wiki ](https://github.com/georchestra/cadastrapp/wiki/Guide-Administrateur) indique ceci :

> Les fichiers générés par l'application sont déposés dans le répertoire 'tempFolder' paramétré dans le fichier cadastrapp.properties. Ces fichiers sont supprimés à chaque redémarrage de la JVM. Ces fichiers peuvent aussi être purgés à la main, ou par un script que vous pouvez créer.

**Comment by landryb** [comment]
ici le volume de fichiers temporaires est bien plus faible, mais oui il peut grimper facilement, donc avoir un job qui supprime les fichiers > 24h serait pas mal. Certes on peut le faire via cron, mais il faut le documenter, et ne pas oublier de le déployer.... donc +1 pour l'avoir dans l'usine à gaz java.

**Comment by pierrejego** [comment]
Je vais mettre en place un Job Quartz de suppression de tous les fichiers de plus de x heures d'un répertoire donné. Ce qui implique que le répertoire temporaire va devoir être spécifique à Cadastrapp, ou alors il faut qu'on modifie les noms de fichiers temporaires pour avoir un discriminant commun à toute l'application.

Vous préférez quoi ?
1- Discriminant dans le nom de tous les fichiers, par exemple préfixer tous les fichiers par cadastrapp 
2- Suppression de l'ensemble des fichiers du répertoire temporaire

**Comment by pierrejego** [comment]
La solution 2 est implémentée grâce à ce commit, 
https://github.com/georchestra/cadastrapp/commit/8681dde7a3868eac7eaeed325f75d3a7327e139f

Attention deux paramètres supplémentaires sont nécessaire dans le cadastrapp.properties

la modification est simple à faire si on choisit finalement la solution 1

**Comment by landryb** [comment]
Perso, j'utilise /tmp/cadastrapp et je m'assure qu'il appartient a l'utilisateur tomcat, donc supprimer tout les fichiers dans ce répertoire datant de + de 24h me va bien.

**Comment by pierrejego** [comment]
Ok, donc c'est bon avec ce que j'ai fait.  

Quelqu'un d'autre a un avis ?

Le paramétrage permet de mettre à jour le CRON de lancement de la purge, ainsi que le nombre d'heure que doit avoir le fichier pour être purgé. Seul les fichiers sont supprimés.

**Comment by jusabatier** [comment]
Il serait intéressant que l'appli verifie au démarrage si le dossier /tmp/cadastrapp existe et le créé sinon pour ensuite pouvoir l'utiliser sans soucis pour stocker ses fichiers temporaires (un peu comme les dossiers de log des app georchestra).

**Comment by pierrejego** [comment]
Au démarrage l'application vérifie si le répertoire définit dans la variable tempFolder du fichier cadastrapp.properties existe, sinon l'application essaye de le créer.

Si il n'existe pas et n'arrive pas à le créer cela bloque le démarrage de l'application.
Voila le code déja existant : 
https://github.com/georchestra/cadastrapp/blob/master/cadastrapp/src/main/java/org/georchestra/cadastrapp/servlet/InitFolderServlet.java

Je vais rajouter un deuxième contrôle dans la servlet  pour faire un test d'écriture, je croyais que c'était fait, mais ce n'est pas le cas.

Donc soit on met dans la doc que la variable tempFolder doit correspondre à un répertoire dédié au cadastre, par exemple /tmp/cadastrapp comme l'a fait @landryb .

Soit je peux créer un sous-répertoire cadastrapp dans le tempFolder lors de l'initialisation de l'application. 

A vos avis !!!
