### ISSUE TITLE
[documentation] Manque les prérequis

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#295]
Je ne vois les prérequis (ex : versions postreSQL) nul part.

Créer une entrée / page spécifique sur le wiki.

**Comment by landryb** [comment]
https://github.com/georchestra/cadastrapp/blob/master/script/README.md, qui est référencé par https://github.com/georchestra/cadastrapp/wiki/Guide-Administrateur#installation ?

**Comment by MaelREBOUX** [comment]
ok mais pour le coup c'est noyé. Est-ce que OK pour faire un chapitre "Requirements" en haut du READ ME pour synthétiser ?

**Comment by landryb** [comment]
C'est le meilleur moyen de perdre tout le monde. Ou on met rien dans le README, et on renvoie vers le wiki, ou on vire la partie 'installation' du wiki et on met tout dans le README, mais il faut arrêter de mettre des trucs a gauche a droite au petit bonheur la chance...

**Comment by MaelREBOUX** [comment]
Je voulais juste dire que un https://github.com/georchestra/cadastrapp/wiki/Guide-Administrateur#Prerequis je trouverais ça sympa.

Et non je souhaite pas voir ça dans le ReadMe

**Comment by MaelREBOUX** [comment]
A mettre :
- version geOrchestra
- version postgreSQL
- recommandations genre isoler dans un tomcat à part

Voir ensuite qui référence quoi entre le wiki et la doc qui sera sur gitbook ou readthedoc.

**Comment by MaelREBOUX** [comment]
Je viens de rajouter les prérequis. Merci de réagir si j'ai mis une bêtise.

https://github.com/georchestra/cadastrapp/wiki/Guide-Administrateur#pr%C3%A9requis

**Comment by MaelREBOUX** [comment]
ping @alebras ou @catmorales  :  pourriez-vous jeter un coup d'œil aux sections Installation et Configuration ?

On a besoin d'un regard externe SVP.

**Comment by MaelREBOUX** [comment]
Vu.
