### ISSUE TITLE
styles complets sld PCI vecteur

### ISSUE THREAD

**Issue by jpklipfel** [georchestra/cadastrapp#297]
Bonjour,

Je ne sais pas si cela peut être utile mais j'ai travaillé sur les sld du pci

Un aperçu ici
https://www.cigalsace.org/mapfishapp/map/c08039c3c39b8d09d1e5ce2602517cd7

Les éléments ici
https://github.com/cigalsace/processes/tree/master/sld/pci

**Comment by pierrejego** [comment]
Merci, je suis sur que ça donnera des idées à d'autres.

**Comment by MaelREBOUX** [comment]
On dirait que tu as réussi à bien positionner les symboles de mitoyenneté. On s'est cassé les dents dessus. Faut que je regarde de plus près.

Faut de vous donner un accès : une capture d'écran : 

![screenshot329](https://cloud.githubusercontent.com/assets/6370443/19933926/4568e262-a115-11e6-942f-82a066da5959.png)
![screenshot330](https://cloud.githubusercontent.com/assets/6370443/19933931/4a88cc12-a115-11e6-91ff-0154751618e7.png)
![screenshot331](https://cloud.githubusercontent.com/assets/6370443/19933933/4ca010fa-a115-11e6-912e-5ae7262dbd98.png)
![screenshot333](https://cloud.githubusercontent.com/assets/6370443/19934000/8a4d712c-a115-11e6-9496-5157637b5392.png)

**Comment by landryb** [comment]
A ajouter dans https://github.com/georchestra/cadastrapp/tree/master/geoserver-workspace/pci/styles avec de la doc/des screenshots pour montrer ce que les différents SLD donnent ?

**Comment by jpklipfel** [comment]
Quelle organisation alors ? un dossier par type de style (sample_qgis_style, sample_rennes_style ...) ou un seul style à maintenir dans /styles ? mais alors là je ne sais pas ce qui vaut le mieux entre mes styles parcelles section bat ou ceux déjà en place.
A priori nous n'avons pas de spécificités particulières sur les représentations

![stylepci1](https://cloud.githubusercontent.com/assets/5012040/20055112/f987fb0c-a4df-11e6-88a4-2e267ff84f84.png)

![stylepci2](https://cloud.githubusercontent.com/assets/5012040/20055115/fc4cfa18-a4df-11e6-8661-08265b278616.png)

![stylepci3](https://cloud.githubusercontent.com/assets/5012040/20055118/feeb9e96-a4df-11e6-80c9-01b599fa2d82.png)

![stylepci4](https://cloud.githubusercontent.com/assets/5012040/20055124/02f75d18-a4e0-11e6-9c0e-f8971df10948.png)

**Comment by landryb** [comment]
C'est prévu pour etre un exemple a copier-coller dans le datadir de geoserver, et je doute que ce dernier supporte des sous-repertoies... peut-etre ORG_pci_parcelle_style, ORG_pci_section_style.... ?

**Comment by jpklipfel** [comment]
Ou alors chacun propose son datadir dans https://github.com/georchestra/cadastrapp/tree/master/geoserver-workspace sous la forme ORG_pci avec copies écran dans le readme?

**Comment by landryb** [comment]
peu importe, dans tout les cas le principal c'est qu'il y'ait les captures d'ecran pour qu'on puisse 'faire son marché dedans', et copier uniquement les styles qui nous interessent.. pour faire des tests en live, je pense que tout les styles (de toutes les 'provenances') seront copiés, du coup je pensais que ce serait plus simple qu'ils soient tous au meme niveau, plutot que devoir faire X copier/coller..

**Comment by jpklipfel** [comment]
Donc il y aurait deux possibilités

1/

Je colle mes styles dans https://github.com/georchestra/cadastrapp/tree/master/geoserver-workspace/pci/styles

sous la forme 

CIGAL_geo_batiment.sld
...


à voir où mettre le répertoire des svg et la doc + screen shot

Avantage ne démultiplie pas les copier/coller pour faire son marché dans les styles

2/

Je colle mon datadir dans https://github.com/georchestra/cadastrapp/tree/master/geoserver-workspace/pci_CIGAL

à voir où mettre le répertoire des svg et la doc + screen shot

Avantage le datadir est déjà prêt avec layer et layer group

D'autres avis?
@MaelREBOUX tu tranches?

De plus, je serais tenté d’anonymiser les acronymes des organismes dans les noms de fichiers 

Par exemple 

b_geo_batiment.sld (si solution 1)

ou

https://github.com/georchestra/cadastrapp/tree/master/geoserver-workspace/pci_b/styles (si solution 2)

**Comment by MaelREBOUX** [comment]
je devais le faire depuis qqs temps : tous nos styles ici :  https://github.com/sigrennesmetropole/geoserver_sld
Notre style cadastre est là : https://github.com/sigrennesmetropole/geoserver_sld/tree/master/ref_cad

Je penche pour rajouter un répertoire rennes_pci avec un renvoi vers mes styles dans le README.
il faut garder tt dans un répertoire homogène. Ca va être illisible et pas réutilisable facilement si on préfixe chaque fichier par "organisme_"
ok ?

**Comment by landryb** [comment]
> De plus, je serais tenté d’anonymiser les acronymes des organismes dans les noms de fichiers

Pourquoi anonymiser ? Jveux dire, ca apporte quoi ?


> Je penche pour rajouter un répertoire rennes_pci avec un renvoi vers mes styles dans le README.

Un renvoi... vers un autre repo ? Pas persuadé que ce soit la bonne idée d'éparpiller le tout sur X repos (enfin c'est déja le cas sur ce ticket..). Ou alors y'a juste un README et les screenshots...

**Comment by jpklipfel** [comment]
>Pourquoi anonymiser ? Jveux dire, ca apporte quoi ?

Les styles que nous avons mis en place sont un travail de conversion des styles du module qgis vers geoserver. Il n'y a pas spécialement de particularisme lié à notre organisme. Du coup je me disais que ce serait intéressant que d'autre les reprennent et les améliorent (on peut dire dans le readme que la première mouture est proposé par l'organisme). Si on les attache à un organisme cela freinerait peut être une réappropriation. Un peu dans l'idée à ce que pci_a pci_b pci_c proposent des alternatives comme par exemple un fond bright, faded ou grey
Mais bon après c'est juste une proposition

>Un renvoi... vers un autre repo ? Pas persuadé que ce soit la bonne idée d'éparpiller le tout sur X repos

D'accord avec ça, je serais plus pour regrouper dans un repo les styles proposés et le readme ou le wiki détaille les possibilités

>enfin c'est déja le cas sur ce ticket..)

?

**Comment by landryb** [comment]
> Les styles que nous avons mis en place sont un travail de conversion des styles du module qgis vers geoserver.

Ah, d'accord, j'avais pas noté ca, mea culpa. Oui dans ce cas, c'est ptete mieux de les mettre explicitement comme 'style provenant de ceux du plugin qgis' plutot que 'style cigal', tout en gardant l'info 'parternité de la conversion' qqpart ?



> > enfin c'est déja le cas sur ce ticket..)
> 
> ?

je veux juste dire que sur ce ticket, on renvoie deja vers 3 repos proposant des styles...  :)

**Comment by jpklipfel** [comment]
https://github.com/georchestra/cadastrapp/pull/307

**Comment by MaelREBOUX** [comment]
Du coup, si je veux proposer notre style : je le met où ?

/geoserver-workspace/rm_arcopole/  ?

@jpklipfel tu as un répertoire 'svg' à la racine du data-dir de ton GeoServer ??

**Comment by jpklipfel** [comment]
>#307

Ce devrait être bon par rapport à la réorganisation proposée
@landryb ok pour toi le renommage en pci_basic ?

**Comment by MaelREBOUX** [comment]
https://github.com/georchestra/cadastrapp/pull/307 merged !

Doit-on fermer ce ticket ?

**Comment by landryb** [comment]
> @landryb ok pour toi le renommage en pci_basic ?

oui, ou pci_cadastre_gouv, le style que j'avais fait s'inspire directement du style sur cadastre.gouv.fr... sauf qu'il est basique, effectivement :)


> Doit-on fermer ce ticket ?

Sauf si tu veux en profiter pour faire ta PR..

**Comment by MaelREBOUX** [comment]
pas le temps là et pour que ce soit propre il faut que je monte un workspace vierge sur mon geoserver local car on a d'autres couches dans notre workspace en production.

donc je laisse ouvert pour pas oublier...

**Comment by jusabatier** [comment]
Je viens d'essayer de mettre en place le style "pci_qgis", tout s'est bien passé hotmis que les SVG ne semble pas vouloir s'afficher correctement.

Exemple avec la couche geo_symblim :

![image](https://cloud.githubusercontent.com/assets/8310116/21845106/9a7d082e-d7f1-11e6-8fec-c27ecb06afeb.png)

J'ai mis tous les svg dans le datadir sous styles/symbols/pci et modifié le SLD en conséquent : 

`<sld:OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:type="simple" xlink:href="file://./symbols/pci/symblim_44.svg"/>`

Quelqu'un a-t-il une idée de ce qui peut provoquer ce souci ?

@jpklipfel @landryb @MaelREBOUX

**Comment by jpklipfel** [comment]
Que disent les log?

On avait un pb un peu similaire un moment résolu par
https://github.com/georchestra/georchestra/pull/1410

**Comment by jusabatier** [comment]
Je viens de tester en utilisant l'URL de la PF : https://opendata.agglo-lepuyenvelay.fr/geoserver/styles/symbols/pci/symblim_44.svg

Et là ça marche, c'est que GS ne doit pas aimer les SVG en local...

**Comment by MaelREBOUX** [comment]
Nous notre "stratégie" est de tout mettre en ligne sur www et de mettre des url résolvables. Au moins c'est unique partout et plus facile à maintenir.

**Comment by jpklipfel** [comment]
@jusabatier 
Tu n'as pas rencontré de problème pour l'impression du bordereau parcellaire avec ce style et Mapfishapp? le pdf me retourne un fond vide

**Comment by jusabatier** [comment]
Non, pas de problèmes, il est en prod sur notre instance : https://opendata.agglo-lepuyenvelay.fr/mapfishapp/

En revanche, il me semble que j'avais modifié certains des styles sld pour mieux coller à nos besoins.

Il faut bien penser à valider les styles avant de les enregistrer car il me semble que certains présentaient des erreurs mineures.

Dans tous les cas je te conseille de verifier les logs de ton Geoserver car il y signalerait toute erreur de rendu du style.

**Comment by MaelREBOUX** [comment]
J'ai pas eu de dispo pour sortir proprement notre style arcopole ++. 
En plus on vient de changer des trucs la semaine dernière.

Donc je laisse ouvert mais je change de milestone.

**Comment by MaelREBOUX** [comment]
Comme nous allons abandonner le modèle arcOpole RM nous allons recâbler notre fond de carte vers le modèle QGIS entre janvier et mars 2019.

**Comment by MaelREBOUX** [comment]
5 ans...  https://github.com/georchestra/cadastrapp/pull/562

**Comment by landryb** [comment]
better late than never ;)
