### ISSUE TITLE
[fiche info parcelle] affichage incorrect windows 10 Surface 4

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#298]
Une utilisatrice nous a contacté pour le problème suivant : la fiche d'infos parcelle n'affiche rien dans aucun onglet. Que ce soit sous Chrome ou FireFox (tous 2 à jour) : même comportement.
J'ai vérifié : tout se passe correctement : les requêtes passent, les réponses arrivent, pas d'erreur dans la console. J'ai fait passer en plein écran : ça ne change rien.

Aucun pb chez ses collègues. LA seule différence : elle utilise une tablette MS Surface 4 dockée avec un moniteur externe. Mais le pb persiste avec l'écran intégré de la tablette.

A part trouver qqn qui a une configuration identique, je ne vois pas quel diagnostic poser.

![screenshot341](https://cloud.githubusercontent.com/assets/6370443/20000788/93833e56-a279-11e6-846e-df20eb897d59.png)

**Comment by jusabatier** [comment]
Je pense que c'est lié à un problème que j'avais déjà fait remonter : si la resolution est trop basse ou le niveau de zoom de la page trop gros, il y a un bug d'affichage de la fiche d'info des parcelles.

Cf. https://github.com/georchestra/cadastrapp/issues/216

**Comment by MaelREBOUX** [comment]
J'y ai pensé mais je ne crois pas (sans certitude). Regarde la capture d'écran : il y a autant de hauteur en pixels que sur l'écran de @catmorales.
J'ai vérifié le zoom également : c'était bien à 100 % sur les 2 navigateurs.

**Comment by jusabatier** [comment]
Je n'arrive pas à juger d'un nombre de pixel à l’œil nu ;)

Pour essayer de confirmer mon hypothèse, tu peux essayer de baisser le zoom en passant à 80 voir 60% sur la tablette où ça bug et fermer réouvrir la fenêtre.

**Comment by MaelREBOUX** [comment]
Je viens de faire tester à la personne :

> Bonjour,
> Bingo ! Ça marche ! Merci !
> Cordialement,

Je ferme alors.

**Comment by MaelREBOUX** [comment]
En fait ça amène une autre question : où dans le wiki on rassemble ces "bogues" connus ?

**Comment by jusabatier** [comment]
Normalement ceci devrait être réglé via https://github.com/georchestra/cadastrapp/pull/304

Tu peux fermer cette issue je pense.

Il vaudrait mieux en créer une nouvelle spécialement pour cette nouvelle problematique (liste bogues connus).
