### ISSUE TITLE
Faire la release v 1.3

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#299]
Pierre : moi je suis OK.
Comment procède-t'on ?

**Comment by landryb** [comment]
Il y'a déja une 1.2, donc 1.3 ?

**Comment by MaelREBOUX** [comment]
oui vu mais je crois que pour Pierre c'était bien une v1.2. Moi après... ce qui m'importe c'est que ce soit tracé et suivi.

**Comment by MaelREBOUX** [comment]
Pierre va réaliser la release de la version 1.3 cet a-m. Elle sera nommée « Cadastrapp-v1.3 ».
J'ai fait les dernières modifs sur le Read Me et le wiki en conséquence. Merci de relire et de donner votre Go.

https://github.com/georchestra/cadastrapp/blob/master/README.md
https://github.com/georchestra/cadastrapp/wiki/Releases

**Comment by landryb** [comment]
Ca me parait bien dans la formulation, en général dans les release notes on peut linker vers les tickets corrigés (comme tu as listés les corrections), ca permet d'atteindre facilement les discussions/commentaires/détails.

**Comment by landryb** [comment]
https://github.com/georchestra/georchestra/blob/master/RELEASE_NOTES.md#version-1512 pour exemple :)

**Comment by MaelREBOUX** [comment]
OK : je note pour la prochaine fois. J'ai voulu être synthétique ce coup-ci car en gros on a touché au 3/4 du RP...
Quitte à faire des issues maîtresses qui renvoient vers d'autres tickets.

**Comment by MaelREBOUX** [comment]
https://github.com/georchestra/cadastrapp/tree/Cadastrapp-v1.3

**Comment by MaelREBOUX** [comment]
Maintenance faire comm' sur la liste de diffusion geOr
