### ISSUE TITLE
Une reconnection rapide engendre une erreur "Adresse introuvable"

### ISSUE THREAD

**Issue by sdhem** [georchestra/cadastrapp#3]
On se connecte  sur la plateforme de dev via le bouton "Connexion". La connection est réussie. On se déconnecte. La déconnection est réussie. On essaie de se reconnecter avec le bouton "Connexion". Une fenêtre de connexion réussie apparait puis l'erreur Adresse introuvable

**Comment by pierrejego** [comment]
L'erreur se produit lorsqu'on utiliser l'adresse IP et non l'url pour se connecter à l'application. Cette anomalie n'est pas lié au développement de l'addon cadastrapp, mais à la façon dont Georchestra a été installé.
