### ISSUE TITLE
Conflit de la couche cadastrapp avec l'impression mapfishapp

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#300]
Il semblerait que le chargement de la couche de l'addons génère un bug de l'outil d'impression de Mapfishapp : 

https://github.com/georchestra/georchestra/issues/1532

Il serait intéressant de déterminer ce qui provoque ce comportement et de le corriger.

D'autres addons chargent leurs couches sans pour autant provoquer ce genre de comportement (outils de mesure, dessin, OSM 2 georchestra).

**Comment by pierrejego** [comment]
Je ne reproduis pas pour l'instant, mais je l'ai déjà vu ce bug. Je vais essayer de garder l'erreur Js la prochaine fois pour comprendre ce qui ne va pas dans le chargement de la couche.

**Comment by pierrejego** [comment]
Toujours pas d'erreur javascript, je suis passé plusieurs fois en pas à pas dans le GeoExt/Plugins/PrintExtent.js tout se fait de la même façon merci ou sans le plugin cadastre. Mais surtout le plus rageant c'est dès que je suis en pas à pas je ne reproduis plus.... ça doit être un problème de chargement ou déchargement de control je pense plus qu'un problème de layer.

Comme tu l'indiques le cadre s'affiche bien, mais impossible de faire une action dessus.

**Comment by jusabatier** [comment]
Ca ne m'étonnerais pas que ce soit un problème lié au chargement des addons, car actuellement c'est fait à l'arrache, ce qui semble provoquer différents effets de bords.

Par exemple sur notre instance l'ordre de chargement des icones des addons dans la barre d'outils change à chaque chargement de la page.

**Comment by MaelREBOUX** [comment]
Voir si c'est à lier avec #319 et/ou un comportement général de Mapfishapp sur le chargement des add-ons et/ou le chargement des layers.

**Comment by jusabatier** [comment]
https://github.com/georchestra/cadastrapp/blob/master/addons/cadastrapp/js/selectFeature.js#L81

**Comment by Gaetanbrl** [comment]
Pour les archives - Commit daté du 16 avril 2016 comportant déjà la méthode [setZIndex](https://github.com/georchestra/cadastrapp/blob/c6385ad144a7e0e2b42a564ef4da3a1eff9989c9/addons/cadastrapp/js/selectFeature.js#L81)(). 
Ce n'est pas lié à une modification récente, je ne sais pas dans quel contexte cette fonction a été utilisée. 
A regarder si c'est toujours d'actualité voir si ce n'est pas bloquant.

Le [graphicZIndex ](https://github.com/Gaetanbru/cadastrapp/blob/c6385ad144a7e0e2b42a564ef4da3a1eff9989c9/addons/cadastrapp/js/selectFeature.js#L24): 1000 est surement du même type...

**Comment by MaelREBOUX** [comment]
@jusabatier  est-ce que ce bogue est toujours présent ?
geOr 15.12 ?
geOr 16.12 ?
geOr 17.12 ?
cadastrapp 1.5 ?

**Comment by jusabatier** [comment]
Le bug existe toujours en 17.12 et dernière version de cadastrapp.

Si j'actualise MFapp après avoir ouvert l'addon, je ne peux pas déplacer le cadre d'impression à la première ouverture de l'outil impression.

**Comment by MaelREBOUX** [comment]
Okay. On vient de refaire des tests avec @pierrejego Quand cadastrapp est actif on ne peux effectivement pas bouger le cadre de l'impression.
si on purge le cache local et qu'on refait une impression c'est OK mais si on se re-sert de cadastrapp c'est à nouveau bloqué.

On temporise et on voit si après le merge de la PR #405 ça change qqch.

**Comment by pierrejego** [comment]
ça semble corrigé, en tout cas je ne reproduis pas, mais ça n'arrivait pas à chaque fois chez moi non plus...

**Comment by MaelREBOUX** [comment]
Besoins de tester maintenant poke @jusabatier

**Comment by jusabatier** [comment]
Je suis en train de redeployer l'integralité de ma stack cadastre pour prendre en compte toutes les MaJ (QGis + Cadastrapp) donc je ne pense pas que ce sera testé aujourd'hui mais plutôt lundi.

**Comment by jusabatier** [comment]
Je n'arrive plus à reproduire non plus sous 1.7, donc je pense qu'on peut fermer l'issue.
