### ISSUE TITLE
[Amelioration] Surbrillance batiment consulté

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#301]
Lors d'une formation, un de nos utilisateurs nous a fait remarquer que lors de la consultation des bâtiments d'une parcelle, dans le cas où celle-ci en compte plusieurs, il est impossible de savoir quel bâtiment on est en train de consulter sur le plan.

Il pourrait être intéressant de mettre en surbrillance le bâtiment en cours de consultation sur la carte.

**Comment by pierrejego** [comment]
C'est une bonne idée, pour l'instant on a que les parcelles, mais c'est vrai qu'on a les informations des batiments, il faudrait ajouter un deuxième flux WFS pour mettre en surbrillance les batiments au survol du batiment dans le fenêtre.

**Comment by MaelREBOUX** [comment]
C'est juste pas possible : dans la base cadastrale il n'y a aucun lien attributaire entre un bâtiment (A B C...) et un polygone de la couche bâtiment.

A moins que tu ne parles du cas où un bâtiment a l'exacte emprise de la parcelle cadastrale qui la supporte ?

**Comment by jusabatier** [comment]
Pour moi cette issue ne devrait pas être fermée : 

On arrive bien pour une parcelle à lister les bâtiments, et on dispose d'une couche geo_batiments.

Logiquement il est donc possible de lier le bâtiment sélectionné dans la fiche de la parcelle à sa representation dans geo_batiment et à le mettre en surbrillance.

Merci de réouvrir l'issue car pour moi elle n'est pas résolue.

**Comment by MaelREBOUX** [comment]
Non : il n'y a pas de lien attributaire entre un bâtiment A dans les fichiers Majic et un polygone dans la couche bâtiments.
Il y a fort longtemps la DGFiP a géré ce lien mais cela n'a pas été maintenu. C'est une vrai demande de tous les agents qui font de l'urbanisme mais tant que la DGFiP ne gère pas ce lien, on ne peut pas l'inventer.

**Comment by MaelREBOUX** [comment]
A fermer ?

**Comment by jusabatier** [comment]
L'issue peut être fermée, même si le besoin reste présent.

Il faudra juste penser à y revenir si jamais la situation change concernant ce lien entre bati majic et edigeo.
