### ISSUE TITLE
Positionnement des fenêtres

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#302]
Lors d'une formation, plusieurs utilisateurs nous ont fait remarquer qu'il serait plus pratique que les fenêtre (recherche, resultat, ...) s'ouvrent sur la gauche de la carte au lieu de le faire en plein milieu.

Cela permettrait de garder visible la zone de travail/intérêt qui est souvent située au centre de la map.

**Comment by pierrejego** [comment]
J'avoue n'avoir jamais essayé en ExtJs, mais ça doit pas être bien compliqué. ça serait pour toutes les fenêtres ? 
J'aime bien avoir la recherche au milieu, et la première fenêtre avec la liste des possibilités au milieu. Pour le résultat détaillé on peut le mettre à gauche.

Quelqu'un d'autre à un avis ?

**Comment by jusabatier** [comment]
Oui, les plus importantes a placer sur la gauche sont les listes de résultats parcelles/propriétaires je pense.

Pour la fiche d'info, je pense qu'elle peut rester au milieu.

Ca se fait avec les attribut x/y de l’élément Window il me semble.

**Comment by jusabatier** [comment]
Après quelques test, je propose : 

- Liste de resultats (parcelle/proprio) => bottom-left
- Fiche d'info parcelle => top-right
- Recherche => middle-right

Qu'en pensez-vous ?

Je propose cet agencement car on a des utilisateurs qui se plaignaient de ne plus voir leur parcelle en ouvrant les fenêtres, donc ainsi on pourrait garder la zone du milieu visible autant que possible.

**Comment by pierrejego** [comment]
On peut le faire rapidement si vous voulez, juste besoin de savoir si tout le monde est OK. Nous ça nous paraît bien comme proposition. 
@landryb @MaelREBOUX un avis ?

**Comment by Gaetanbrl** [comment]
Ce type de positionnement conviendrait-il ? 
(Image prise sur un écran format 1280 x 918).
![image](https://cloud.githubusercontent.com/assets/16317988/21811855/6f3024e4-d751-11e6-8cc8-f99f682dc45f.png)

**Comment by Gaetanbrl** [comment]
Nouvelle proposition @jusabatier. la vue est un peu surchargée mais elle permet de voir le rendu avec une majorité de fenêtres.
Ecran de capture : 1280 x 918.

![image](https://cloud.githubusercontent.com/assets/16317988/21886976/467ea778-d8be-11e6-8e64-5e948ee9a640.png)

**Comment by MaelREBOUX** [comment]
Ma contre proposition qui me semble plus dans le fil chronologique d'une recherche

![screenshot473](https://cloud.githubusercontent.com/assets/6370443/21990529/732ffade-dc0f-11e6-8865-5f703084ef92.png)

et je vous confirme qu'on a pas mal d'utilisateur avec de très petites hauteurs d'écran et en 16/10

**Comment by jusabatier** [comment]
@pierrejego : Ok pour moi, avec ça le parcelle restera visible sauf en cas d'affichage d'une UF.

@MaelREBOUX : Pas bon pour nous car le but premier était de garder visible la zone centrale et donc la parcelle. Mais sinon c'est sur que ta proposition est plus logique chronologiquement...

**Comment by Gaetanbrl** [comment]
Merci pour vos retours, quelle solution je conserve du coup ? Qui tranche ?
Je trouve personnellement la proposition de julien plus clair en dégageant l'espace central, si toutes les fenêtres ne sont pas ouvertes bien entendu. 
Sur des petits écrans je ne sais pas si la taille des fenêtres permettra de trouver une solution viable pour tous.

**Comment by MaelREBOUX** [comment]
![image](https://cloud.githubusercontent.com/assets/6370443/22508937/56ad9fd6-e88c-11e6-8656-fb5976136fcf.png)

**Comment by MaelREBOUX** [comment]
![image](https://cloud.githubusercontent.com/assets/6370443/22508985/7ed439b6-e88c-11e6-91b6-abad7712933c.png)

**Comment by MaelREBOUX** [comment]
ce qui a été retenu après un point tel 

![image](https://cloud.githubusercontent.com/assets/6370443/22509231/6c070a42-e88d-11e6-9e41-0d295d7c5eba.png)

**Comment by MaelREBOUX** [comment]
Vu : ok.

Ci-dessous rendu en 1440x900 qui nous pose des soucis et en 1280x1024

![position_1440x900](https://cloud.githubusercontent.com/assets/6370443/25891788/94b3a216-3572-11e7-97aa-6e18997ea63b.png)

![position_1280x1024](https://cloud.githubusercontent.com/assets/6370443/25891792/97ce77fa-3572-11e7-8de9-be4c81b5e1a5.png)
