### ISSUE TITLE
Possibilité d'imprimer un extrait de propriété

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#303]
Actuellement on ne peut imprimer qu'un relevé de propriété qui va concerner toutes les parcelles lié au compte communal pour lequel il est demandé.

Beaucoup d'utilisateurs nous ont fait remarquer qu'il était important pour eux de pouvoir n'imprimer qu'un extrait de ce relevé concernant uniquement la parcelle qui les intéresse.

Par exemple, si on veut uniquement les infos d'une seule parcelle, il n'est pas pratique de générer un RP de 18 pages contenant toutes les propriétés du compte communal.

**Comment by pierrejego** [comment]
On s'était posé la question à l'origine,  comme le code est fait ça n'est pas très compliqué à générer, par contre il faudrait savoir comment positionner le bouton d'impression dans l'IHM.

ça intéresse d'autres personnes que le Puy en Velay ?

**Comment by jusabatier** [comment]
Pour moi il y a une logique toute simple : 

- Fiche de parcelle : 

Ajout d'un bouton Extrait de Propriété à coté de l'actuel

- Dans les demandes d'info foncières : 

Si sélection de parcelle, alors impression de l'extrait correspondant à la parcelle
Si sélection de propriétaire, impression du RP lié au(x) CC

**Comment by pierrejego** [comment]
Je suis pour faire le merge de la PR, est-ce que cette nouvelle possibilité intéresse bien tout le monde ?

**Comment by landryb** [comment]
Oui, ca parait plus souple...

**Comment by pierrejego** [comment]
Juste une question car je pense que j'ai raté une étape.

 Il s'agit bien de générer le RP d'un compte communal donnée mais d'en limiter la liste de parcelle à l'id de parcelle donnée ou alors c'est de générer un RP de la parcelle sans compte communal fournit à l'origine ?

**Comment by jusabatier** [comment]
Le but était de générer un RP à partir du CC (comme avant), mais de limiter le résultat à la parcelle consultée.

En revanche, pour les demandes foncières, si l'objet de la demande est une parcelle, il serait intéressant de générer les RP de tous les propriétaires de celle-ci (limité à cette parcelle). Je ne sais plus comment c'était géré avant mais ça devait surement déjà être ce comportement en générant pour toutes les parcelles du CC.

**Comment by pierrejego** [comment]
OK du coup c'est bon. Merci pour l'explication

**Comment by jusabatier** [comment]
Je ferme l'issue vu que ça a été mergé
