### ISSUE TITLE
Les préfixes de section ne sont pas pris en compte

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#308]
![screenshot415](https://cloud.githubusercontent.com/assets/6370443/21186536/4b971502-c215-11e6-9fbc-7a54e3cf99c7.png)

C'est une régression du coup, sûrement produite par le travail réalisé pour la version 1.4.
Je met que ça concerne les 2 modèles tant qu'on a pas écarté / diagnostiquer ça pour QGIS.

**Comment by landryb** [comment]
Tu peux expliquer un peu mieux ce que tu veux dire par 'prefixe de section' ? la je vois AL sur ta capture, ou est le souci ?

**Comment by MaelREBOUX** [comment]
Une des parcelles est 073AL0104, l'autre est AL0104.
Résultat de 2 communes qui ont fusionnées. L'ancien code INSEE de la commune absorbée a été mis en préfixe de section.

C'est ce qui a été retenu dans le cadre des fusions de communes en cours ou à venir.
Donc si qqn a ça chez lui, il faut vérifier si vous avez ça côté QGIS.

PS : la liste des sections dans la fenêtre de recherche cadastrale est correcte.

**Comment by jusabatier** [comment]
Une explication ici : http://georezo.net/blog/parcellair/2011/03/14/crige-paca-journee-technique-cadastre-suite/

Est-ce que cela fonctionnait avant ? Car il me semble que la recherche n'a jamais porté sur le préfixe de section, uniquement sur commune/section/numéro.

Le problème serait le même sous QGis vu que les id parcellaire sont identiques.

Cela ne me semble pas être un bug mais plutôt une évolution.

Du coup ces complément parcellaires devraient ils simplement apparaitre dans les infos du resultat de recherche, ou aussi être inclus dans le formulaire de recherche selon vous ?

**Comment by MaelREBOUX** [comment]
oui : c'était bon "avant" : mais avec la fatigue de fin d'année plus sûr de rien...

**Comment by pierrejego** [comment]
Bonjour,

Si j'ai bien compris les explications (merci pour le lien Julien)  il faut avoir le ccopre concaténé avec le ccosec, si il existe, je viens de vérifier sur la plateforme de test  j'ai bien les infos.  

La plateforme de test tourne sur le master avec la dernière version de la base que vous m'aviez donné.  
Est-ce que le champ ccopre est bien renseigné dans ta base de données ?

![image](https://cloud.githubusercontent.com/assets/11499415/21586219/9dbcb284-d0ce-11e6-9130-634de42e9155.png)

**Comment by pierrejego** [comment]
Ok j'ai compris, ce n'est pas la fenêtre de recherche qui pose problème mais le résultat de la recherche. Il manque la parcelle 73AB dans la liste de résultat

**Comment by pierrejego** [comment]
En fait c'est dans le résultat de la requête, si on fait une recherche sur AL 104 on a aussi le 73AL 104.

**Comment by pierrejego** [comment]
Je viens de vérifier dans le code, voila l'explication.

La recherche précédente lance l'appel de service suviant: getParcelle?cgocommune=350206&dnupla=134&ccopre=&ccosec=AB

le ccopre étant vide, le service faire une requête en base sans ccopre
select distinct p.parcelle, p.cgocommune, p.dnvoiri, p.dindic, p.cconvo, p.dnupla, p.dvoilib, p.ccopre, p.ccosec, p.dcntpa from cadastrapp_arcopole.parcelle p where cgocommune = ?  and ccosec = ?  and dnupla = ? 

Ce qui renvoie les deux parcelles, avec et sans prefixe

J'ai revérifié il n'y a pas de changement de comportement sur cette partie depuis le début, maintenant reste à savoir comment modifier le comportement actuel.

Le ccopre étant vide en base je ne vois pas de moyen de traiter ça simplement sans faire une grosse verrue (si ccopre empty dans la requête du service  alors ajouter ccopre is null dans la requête de la base de donnée)

**Comment by jusabatier** [comment]
Je pense que le plus gros problème n'est pas que deux parcelles soient remontées dans le cas où ccopre n'est pas renseigné, mais plutôt que le préfixe ne soit pas affiché dans la liste des résultats car on ne peut pas différencier les deux parcelles.

De plus dans la vue parcelle de cadastrapp, ccopre n'est pas NULL mais '', donc il suffit juste de mettre ccopre = '' si le paramètre n'est pas fourni.

**Comment by pierrejego** [comment]
+1 pour ajouter le ccopre dans la fenêtre de resultat, ça me paraît une bonne solution.

Par contre pour le null ou le "" plutôt c'est bien ce que je voulais dire, ça fait faire un cas particulier (une sorte de verrue) car dans tous les autres cas, si le paramètre reçu est vide on ne le met pas dans la requête SQL.

**Comment by MaelREBOUX** [comment]
Donc oui : on concatène ccopre + section. Comme ça on touche à moins de choses.
Pb : il faut modifier le bordereau parcellaire car là ça n'apparaît. Le RP est bon par contre.

Faut-il modifier les vues ??

![screenshot457](https://cloud.githubusercontent.com/assets/6370443/21773477/9068ecb2-d68f-11e6-87ee-6735cae3e72c.png)

![screenshot458](https://cloud.githubusercontent.com/assets/6370443/21773483/9387a578-d68f-11e6-972e-4139dd3c2fb3.png)

**Comment by MaelREBOUX** [comment]
/!\ on n'est pas bon sur le préfixe : il est impérativement long de 3 caractères car c'est le suffixe du code INSEE de la commune qui a été fusionnée et qui n'existe plus en tant que tel. Donc ici ce devrait être "073", le code INSEE de l'ancienne commune "Châtillon-sur-Seiche" disparue en 1993 :  http://www.insee.fr/fr/metadonnees/cog/commune/COM35073-chatillon-sur-seiche

**Je signale que tout ça vaut pour toutes les prochaines fusions de communes donc c'est super important.**

**Comment by pierrejego** [comment]
Anomalie dans la demande d'information.  La requête ne prend que le ccosec et pas le ccopre,
l'affichage dans la demande est bon, par contre la recherche n'est pas bonne

**Comment by pierrejego** [comment]
Avec ce commit on remet tous les 0 du ccopre avant le ccosec, ce qui n'est pas géré dans la demande d'information https://github.com/georchestra/cadastrapp/commit/fb758c57f07bc58cfb8bde768ba7363b3ded627c 
uniquement visible sur Arcopole. 

Dans Qgis il n'y a pas de 0 mais des espaces en base, donc l'anomalie n'était visible que si un ccopre était renseigné.

@MaelREBOUX tu es sur de vouloir les 0 devant le ccopre, ils n'apparaissent pas dans le modèle Qgis, je me demande donc si c'est vraiment nécessaire ?

**Comment by MaelREBOUX** [comment]
Je reformule : 
- si la section est "classique" -> pas de ccopre -> "AL"
- si la section provient d'une ancienne commune -> il y a un ccopre -> "073AL"

Le ccopre ce sont les 3 derniers chiffres de l'ancien code INSEE de la commune fusionnée. Ex : '35073'

L'image ci-dessous : c'est pas bon : il ne devrait pas y avoir "000" devant le code de section car ce sont des sections "classiques".

![screenshot474](https://cloud.githubusercontent.com/assets/6370443/21991164/c9117386-dc11-11e6-8005-8732258a0078.png)

Vous suivez ?
