### ISSUE TITLE
Nécessité de purge régulière du navigateur

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#319]
Suite de #259 

On doit très régulièrement / irrégulièrement (c'est selon le point de vue) indiquer à nos utilisateurs comment vider : cache, cookies, données de sites hors connexion et préférences de site.

En tout cas : ça va bloquer sur tous les postes à un moment ou un autre. Amha en fonction de l'intensité d'utilisation de cadastrapp.
On pense ici qu'il y a vraiment un truc en lien avec cadastrapp. Mais comment en être certain ? Et quoi ?

Les symptômes :
- plus de listes des communes dans les fenêtres (réseau hors de cause)
- plus de listes sections
- si on arrive à faire une recherche par référence, la fenêtre des résultats ne s'ouvre pas

Et rien dans la console.

**Comment by pierrejego** [comment]
On va faire des tests sur firefox pour voir si on trouve quelque chose

**Comment by jusabatier** [comment]
Même chose chez nous, de temps en temps je dois faire la manip sur le poste de certains utilisateurs mais je n'ai jamais réussi à déterminer d'où provient le souci

**Comment by pierrejego** [comment]
En faisant des tests sous firefox, j'ai détecté une erreur dans la fermeture et ouverture du module cadastre et en plus l'utilisation d'une variable globale pour l'utilisation du layer.
Ces erreurs engendraient une erreur javascript peut être à l'origine du blocage et surtout une mauvaise utilisation du layer lors du rechargement.

Voir commit
https://github.com/georchestra/cadastrapp/commit/c1c8c6b19a0cac8306969de9e74442f7058a1d92

**Comment by MaelREBOUX** [comment]
A réévaluer après déploiement de la version 1.5 alors.
Pcq ça touche tous nos utilisateurs à des fréquences très différentes. C'est LE gros point galère chez nous.

**Comment by MaelREBOUX** [comment]
Voir si c'est un comportement général de Mapfishapp sur le chargement des add-ons et/ou le chargement des layers par les add-ons + complications si on recharge des cartes modèles.

**Comment by MaelREBOUX** [comment]
Pour suivi : beaucoup moins de sollicitations depuis la mise en route de la version 1.4 en juin.

Mais impossible de dire si c'est cette version qui améliore et/ou les utilisateurs qui savent purger leur cache / cookies tout seuls.

**Comment by jusabatier** [comment]
Si chez nous, il arrive encore de temps à autre que des utilisateurs appellent pour ce problème.

**Comment by MaelREBOUX** [comment]
Je n'ai pas dit que ça a disparu loin de là : je disais juste que moins de sollicitation directe.
J'ai fait un dépannage pas plus tard que hier.

Le pb est tjs présent.

**Comment by MaelREBOUX** [comment]
@jusabatier est-ce que tu pense qu'on peut fermer ce ticket ? Ici je n'ai plus de pb depusi la v1.6 ou 1.7

**Comment by jusabatier** [comment]
Je pense que oui, ça fait longtemps que je n'ai pas eu ce souci moi aussi.
