### ISSUE TITLE
[AddOn.003.00] Menu de cadastrapp - Items

### ISSUE THREAD

**Issue by catmorales** [georchestra/cadastrapp#32]
- Le libellé _Fonctions avancées_ doit être renommé _Recherches avancées_
- L'import des listes csv (à notre avis) ne devrait pas se trouver sous l'item _traitement sélection_ mais plutôt sous un nouvel item _Parcelle/Par lot_.

**Comment by pierrejego** [comment]
Le troisième onglet permet déjà d'y insérer une liste de parcelle ID avec différent type de séparateur (espace, point virgule et virgule)
Je vous propose de supprimer la partie permettant de faire l'import par fichier csv.

**Comment by MaelREBOUX** [comment]
lié à #45

**Comment by MaelREBOUX** [comment]
Version anglaise : corriger : "Advanced search" -> "Advanced searches"  (au pluriel).

Et les items de la barre d'outils sont en anglais sur la PF du CRAIG et en FR sur la PF de GFI.

Supprimer label "enhancement" pour le coup.
