### ISSUE TITLE
Paramétrer un zoom max sur la carte

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#320]
Après qqs mois d'usage il y a un comportement à corriger dans le cas des petites parcelles.

Il faut introduire un paramètre **Zoom max** sur la carte. Pour moi il devrait être par défaut au 1/1066 max. Je dis max car dans le cas où une parcelle est très grande il faut bien évidemment que le zoom de la carte soit inférieur (donc échelle supérieure).
Ca va de paire avec une envie chez nous d'empêcher l'affichage du cadastre au max au 1/500. On a détecté des mauvais usages du cadastre (qui est complètement déformé par endroit : c'est le PCI...) qu'on pourrait border en mettant une limite d'affichage zoom min.

On retrouve également ce besoin sur les bordereaux parcellaires. Dans le cas des petites parcelles / micro-parcelles il arrive que le bordereau se mettent au 1/250 voire au 1/133 et affiche du blanc.

**Comment by jusabatier** [comment]
Suite a notre conversation téléphonique, un point sur le comportement attendu pour le zoom sur la carte et la génération du Bordereau Parcellaire : 

- Utilisation de la méthode pour centrer sur la parcelle et obtenir le zoom optimal
- On garde le même centre
- On recule d'un niveau de zoom pour obtenir un aperçu des parcelles alentours
- Si le zoom résultant est plus important que 1/1066 (ex : 1/533, 1/267, ...), alors on met 1/1066 comme zoom

Ceci serait un gros plus pour les BP car pas mal d'utilisateurs souhaitent avoir un aperçu des alentours de la parcelle.

**Comment by pierrejego** [comment]
J'ai regarder côté serveur, je ne peux pas utiliser le scale avec geotools. Par contre, il y a avait déja une notion de buffer. 
Ce que je vous propose c'est de faire un buffer sur la parcelle, en prenant en compte son périmètre.

Si inférieur à 100 mètres, faire un buffer de 0,4 * le périmètre de la parcelle
Si entre 100 et 2000 mètres, faire un buffer de 0,2 * périmètre de la parcelle
Si supérieur à 2000 mètres, faire un buffer de 0,1 * périmètre de la parcelle.

Si vous avez d'autres algos, je suis preneur. Les valeurs que j'ai mis là sont juste issue de tests.

**Comment by jusabatier** [comment]
Est-il possible d'avoir un aperçu du résultat avec ces valeurs ?

**Comment by pierrejego** [comment]
Oui bien sur

Une parcelle toute petite : 

![image](https://cloud.githubusercontent.com/assets/11499415/22650075/cc7ce3c6-ec7d-11e6-8c12-478cafa880c8.png)


Une parcelle de plus de 100 mètres
![image](https://cloud.githubusercontent.com/assets/11499415/22649994/a3cd45b0-ec7d-11e6-82d5-2a0d5bd2b84b.png)

Une parcelle de plus de 2000 mètres

![image](https://cloud.githubusercontent.com/assets/11499415/22650142/24512c6a-ec7e-11e6-9999-7755c79dbcc3.png)

**Comment by jusabatier** [comment]
Une idée d'algo : 

Vu que les echelles doublent à chaque niveau de zoom, il suffit de doubler la zone a afficher (bounds).

maxX += (maxX-minX)/2
minX -= (maxX-minX)/2

maxY += (maxY-minY)/2
minY -= (maxY-minY)/2

Reste le problème des echelles < 566...

**Comment by pierrejego** [comment]
Je viens d'essayer, mais je n'arrive pas à le mettre en place. Le fonctionnement actuel de la création d'image  utilise un buffer pour agrandir la géométrie de la parcelle, et je n'arrive pas à mettre en corrélation le maxX et minX ou maxY ou minY avec un unité de buffer. 
Je vais essayer d'appeler le WMS avec un SLD pour la sélection de la parcelle et du coup plus besoin de geometry ni de buffer.

**Comment by MaelREBOUX** [comment]
Pour moi c'est réglé dans le visualiseur :

avant -> 1/133
![320_avant](https://cloud.githubusercontent.com/assets/6370443/25892930/4075da30-3576-11e7-9a5b-07d44de904e8.png)

après -> 1/533
![320_apres](https://cloud.githubusercontent.com/assets/6370443/25892932/42a8576a-3576-11e7-8637-d0a142e9111c.png)

Donc je scinde en 2 issues :
- 1 (cette issue) pour la carte qui est réglé en v 1.4
- 1 nouvelle issue pour le BP mis en milestone v 1.5 -> #335

**Comment by MaelREBOUX** [comment]
Donc, en toute logique, je ferme cette issue.
Belle amélioration.
