### ISSUE TITLE
Amelioration de la gestion des couches de l'addon

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#321]
Je viens récement de faire une PR sur georchestra qui sera disponible dans la version 16.12 : 

https://github.com/georchestra/georchestra/pull/1639

Celle-ci ajoute des events "aftercontextcleared" (supprimer toutes les couches) et "aftercontextrestore" (charger un contexte).

Ceux-cis ont pour but de signaler aux addons ayant leur propre couche qu'un raz des couches de la map a été fait et donc qu'il doit recharger les siennes.

Il serait interessant lorsque la 16.12 sera releasé d'utiliser ces events pour recharger les couches WMS/WFS de l'addon en cas de nettoyage des couches ou chargement d'un contexte.

**Comment by pierrejego** [comment]
Ok, effectivement ça semble intéressant, il faudra essayer de voir comment on peut gérer à la fois avec ces nouveaux events et sans pour rester compatible avec les anciennes versions de georchestra.

**Comment by MaelREBOUX** [comment]
ok

![321_reload_context](https://cloud.githubusercontent.com/assets/6370443/25892385/887d3da2-3574-11e7-95be-5650d38d1239.png)
