### ISSUE TITLE
Minimiser les fenêtres de cadastrapp

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#322]
Les utilisateurs se "plaignent" du trop de fenêtres qui masquent la carte.
En plus de l'optimisation du placement des fenêtres (cf #302), il serait intéressant de savoir si on peut minimiser une fenêtre à sa seule barre de titre, à l'instar du Finder de Mac OS 8 et 9.

Un bouton " - " serait rajouté à gauche de la croix de fermeture de chaque fenêtre.
1er clic  : minification
2e clic : ré-affichage du contenu de la fenêtre

**Comment by landryb** [comment]
Je pense que c'est possible en mettant la propriété `collapsible` à `true` (cf http://docs.sencha.com/extjs/3.4.0/#!/api/Ext.Window), elle est par défaut à `false`.

**Comment by Gaetanbrl** [comment]
En effet le paramètre collapsible est existant sur toutes les fenêtres. 
En jouant un peu avec le css, il est également possible d'avoir un bouton plus sympa. 

![image](https://cloud.githubusercontent.com/assets/16317988/22542005/037dfc72-e92a-11e6-9864-b3df1333393d.png)
![image](https://cloud.githubusercontent.com/assets/16317988/22542010/074a4e28-e92a-11e6-855b-9af5e2859ab9.png)

**Comment by MaelREBOUX** [comment]
\o/

![collapse_off](https://cloud.githubusercontent.com/assets/6370443/25891978/33b4b85a-3573-11e7-8f66-49990f898f4d.png)

![collapse_on](https://cloud.githubusercontent.com/assets/6370443/25891980/35fc8282-3573-11e7-9725-196ef2f9a987.png)

**Comment by MaelREBOUX** [comment]
![collapse_exemple](https://cloud.githubusercontent.com/assets/6370443/25892195/e51e36c0-3573-11e7-9c5c-e57cff105366.png)
