### ISSUE TITLE
"Nous ne pouvons restaurer un contexte enregistré avec Chrome 36 ou 37"

### ISSUE THREAD

**Issue by catmorales** [georchestra/cadastrapp#327]
Un problème apparu  récemment revient régulièrement chez nos utilisateurs:

"Lorsque j'ouvre l'outil Cadastrap, une fenêtre apparait avec le message suivant: "Nous ne pouvons restaurer un contexte enregistré avec Chrome 36 ou 37"
Ensuite l'outil fonctionne mais aucune donnée n'est disponible (le numéro de parcelle, l'adresse... n'apparaissent pas)."

Seul un rechargement de l'addon permet de sortir de ce plantage.
L'avez vous déjà rencontré , y a t-il une résolution en cours sur ce problème ?

**Comment by landryb** [comment]
Il faut probablement vider le localstorage qui stocke le dernier contexte vu....

**Comment by pierrejego** [comment]
Non je n'ai jamais rencontré ce problème, y a t'il des logs dans la partie console javascript ?

**Comment by catmorales** [comment]
Ce problème est récurrent malheureusement et n'est résolu que par un redémarrage du tomcat-cadastre.
Il m'a été signalé à nouveau et résolu  par un redémarrage du service (:( pas terrible en prod avec la quantité d'utilisateurs).
Dans les logs du tomcat hébergeant cadastrapp je n'ai pas trouvé d'erreur correspondante à l'heure du problème.
Pas eu le temps de vérifier les logs de la console - je le ferai dès que le problème se renouvellera.

**Comment by MaelREBOUX** [comment]
@catmorales on pense que ce n'est pas lié à cadastrapp mais à un comportement général du chargement des contextes.

Peut-on fermer du coup ?

**Comment by catmorales** [comment]
ok
