### ISSUE TITLE
Problème sur RP de copropriétaires multiples

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#329]
Une utilisatrice nous a signalé un souci sur la generation de Relevés de Propriétés lorsqu'elle selectionne plusieurs copropriétaires à la fois.

Au niveau de la requête , on a par exemple : 

> /cadastrapp/services/createRelevePropriete?compteCommunal=201643157%C2%A400956%2C201643157%C2%A401774%2C201643157%C2%A400812%2C201643157%C2%A401953%2C201643157B02651%2C201643157B03277%2C201643157B03278&parcelleId=2016430157000AW0106

Pour moi, il est impératif de changer cet appel en POST, au moins pour la liste de comptes communaux, sinon on risque éventuellement de dépasser la limite de taille d'une URL.

Deplus, il semble y avoir un souci à la génération du document car dès qu'on a plus d'un copropriétaire de sélectionné, le RP renvoyé est complètement vide.

Pour le POST est-ce que c'est faisable @pierrejego  ?

Ensuite pour le bug du RP vide ça demande peut-être plus d'investigation.

**Comment by pierrejego** [comment]
Bonjour,
@jusabatier, pour moi le nombre de paramètres ne pose pas problème pour cette appel, on est encore loin de la limite du GET. plus d'info sur la limite de caracatère d'une URL dans cet article https://boutell.com/newfaq/misc/urllength.html
Changer pour tous les appels de services et tous les services me prendrait beaucoup de temps. Et je ne pense pas que le problème vienne de là.

Pour la partie génération de doc, est-ce que tu as des logs serveurs ? ça m'aiderait le temps que j'arrive à reproduire.

**Comment by pierrejego** [comment]
@jusabatier merci pour les logs. C'est bon je reproduis avec mes données, j'ai trouvé plusieurs cas.

**Comment by pierrejego** [comment]
Après analyse le problème vient de la façon dont ExtJs transforme les valeurs du formulaire. 
https://github.com/georchestra/cadastrapp/blob/master/addons/cadastrapp/js/printRelevePropriete.js -> ligne 65, le form.getValues transforme l'objet de type array en string avec les valeurs séparées par une virgule.
J'adapte le côté serveur pour spliter les valeurs.
