### ISSUE TITLE
Pb à la restauration des vues matérialisées

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/cadastrapp#330]
On a un problème lors de l'installation sur une base `cadastrapp` pour laquelle on n'a pas accès au super utilisateur `postgres`:
```
pg_restore: creating MATERIALIZED VIEW DATA "cadastrapp_qgis.co_propriete_parcelle"
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 3645; 0 22169 MATERIALIZED VIEW DATA co_propriete_parcelle cadastrapp
pg_restore: [archiver (db)] could not execute query: ERROR:  password is required
DETAIL:  Non-superuser cannot connect if the server does not request a password.
HINT:  Target server's authentication method must be changed.
    Command was: REFRESH MATERIALIZED VIEW co_propriete_parcelle;
```

**Comment by pierrejego** [comment]
Bonjour,
je n'ai pas encore fait de dump de la partie vue matérialisée, les dumps que j'ai sur le serveur de qualification concerne uniquement les tables. J'ai un autre script pour refaire les vues matérialisées (uniquement si besoin ) qui se base d'ailleurs sur ce script -> https://github.com/georchestra/cadastrapp/blob/master/script/qgis/createDBUsingQgisModel.sh et qui ne reprend que la partie Drop et Create views.

Je ne suis pas sur que Postgresql sache faire des dumps et restore de vue materialisée correctement. L'application ne fait que de la lecture sur ces vues, du coup le risque de corruption est très basse.

Dans ton cas particulier, est-il possible que le dump ai été fait avec un autre user que celui avec lequel tu fais le restore ?

Je vais essayer de faire un dump avec les vues materialisées et un restore pour voir le comportement sur le serveur de qualification. Je te tiens au courant

**Comment by pierrejego** [comment]
Pour info, je viens d'essayer de faire un dump via pgadmin pour faire un test rapide, et pgadmin ne propose même pas le dump des vues materialisées. Je vais essayer en ligne de commande

**Comment by MaelREBOUX** [comment]
Je ferme car les vues matérialisées ne sont jamais droppées. Ce qui est droppé ce sont les tables normales.
Il faut ensuite rejouer les requêtes qui vont créer les vues matérialisées.
Et ensuite les éventuelles vues qui s'appuierait sur des vues matérialisées.
