### ISSUE TITLE
[BP] Paramétrer un zoom max sur le bordereau parcellaire

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#335]
Suite de #320 

L'impression d'un BP pour de petites parcelles peut produire chez nous une carte blanche car on bloque l'affichage du service cadastre en-dessous du 1/500. De plus, montrer le cadastre en-dessous du 1/066 est déjà une aberration.

Se reporter aux propositions d'algo faites en #320.

**Comment by pierrejego** [comment]
Modification effectuée dans ce commit
https://github.com/georchestra/cadastrapp/commit/60481a1bf886816eceb0179f2100e32201690682

Il faut maintenant mettre l'échelle minimum souhaité dans le fichier cadastrapp.properties
