### ISSUE TITLE
Pb mise en forme formulaire recherche proprio

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#336]
v 1.3

![screenshot665](https://cloud.githubusercontent.com/assets/6370443/25944763/bf359d00-3644-11e7-9a8f-49ef6685c1ad.png)

v 1.4

![screenshot666](https://cloud.githubusercontent.com/assets/6370443/25944778/d4d57d42-3644-11e7-9021-37a4f31507ad.png)

La longueur de la liste proprio est trop courte.

Possible de modifier ça pour la 1.4 rapidement ?

**Comment by pierrejego** [comment]
Mais ou sont passé les champs Ville, Commune et Nom et/ou Prénom ?
Je vérifie dans l'historique

**Comment by jusabatier** [comment]
Corrigé dans la PR ci dessus, le souci venait du layout "fit", l'attribut "fieldLabel" est uniquement utilisé par un layout "form".

**Comment by MaelREBOUX** [comment]
OK : à tester demain main ici après déploiement add-on.

**Comment by MaelREBOUX** [comment]
Réglé. je ferme.
