### ISSUE TITLE
[RP] les numéros de parcelles à 4 chiffres s'affichent en ###

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#338]
Tout est dans la capture d'écran 

![screenshot671](https://cloud.githubusercontent.com/assets/6370443/26411858/416bd20a-40a7-11e7-8e4e-e203c92a4b6f.png)

Bogue présent en v 1.3 et v 1.4.

**Comment by jusabatier** [comment]
Est-ce que ce bug concerne uniquement tes propriétés non baties ?

Si c'est le cas, le souci vient peut-être de ton script SQL : https://github.com/georchestra/cadastrapp/blob/master/script/arcopole/views/arcopoleProprieteNonBatie.sql#L43

Il faudrait eventuellement mettre : 
> to_char(nbati.dnupla,''9999'')

**Comment by MaelREBOUX** [comment]
Merci Julien.

Ca corrige effectivement bien ce bogue : https://github.com/georchestra/cadastrapp/commit/ac9055b088e42ddd567f3082a2ad559900171ff0

Donc rien à faire côté QGIS ? Tu confirmes ?

**Comment by jusabatier** [comment]
Je confirme que coté QGis on a pas ce souci.

**Comment by MaelREBOUX** [comment]
OK. Je ferme.
