### ISSUE TITLE
[RP] Différence prop bâtie / non bâtie : n° de parcelle

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#339]
Un "0" zéro précède la numérotation pour les propriété bâties alors que c'est un vrai chiffre pour les propriétés non bâties.

![screenshot715](https://user-images.githubusercontent.com/6370443/27483213-c2784380-5824-11e7-9c40-074bd19cfb8d.png)

Il faut homogénéiser.

@jusabatier : tu constates la même chose ?

**Comment by jusabatier** [comment]
Non, de mon coté j'ai uniquement le nombre de chiffres nécessaire pour propriété baties ou non baties.

**Comment by jusabatier** [comment]
Le problème vient surement de là : 

https://github.com/georchestra/cadastrapp/blob/master/script/arcopole/views/arcopoleProprieteBatie.sql#L51

Le substr recupère 4 caractères. Il faudrait je pense l'encapsuler dans un ltrim : 

ltrim(substr(invar.codparc,12,4), ''0'') as dnupla,

**Comment by MaelREBOUX** [comment]
OK : à améliorer donc. Je laisse ouvert.
