### ISSUE TITLE
[AddOn.004.02] Recherche parcelle par référence

### ISSUE THREAD

**Issue by catmorales** [georchestra/cadastrapp#34]
La fenêtre affichant la liste des parcelles ne se redimensionne pas si on agrandit verticalement la fenêtre.

**Comment by pigma** [comment]
En cas de sélection multiple la taille de la fenêtre "Sélection des parcelles" peut dépasser la taille écran

![pb_taille_fenetre_selection_parcelles](https://cloud.githubusercontent.com/assets/3725336/9255303/ad1f25ca-41e8-11e5-9ef5-871257248a97.png)

**Comment by pierrejego** [comment]
Test fait avec Landry pas scrollabe à l'intialisation. Essayer de mettre une taille max

**Comment by MaelREBOUX** [comment]
@pigma attention : on parle de cette fenêtre ici :
![screenshot105](https://cloud.githubusercontent.com/assets/6370443/10429572/d81e5dc8-70f9-11e5-918e-e7289c927de8.png)

**Comment by pierrejego** [comment]
@MaelREBOUX ton commentaire correspond au #48 non ?

**Comment by landryb** [comment]
Petit point sur ce ticket: on parle bien de la taille de la fenetre de resultat de recherche listant les parcelles. Dans l'immédiat sa taille est _fixe_ a 200px de haut et s'il y'a 'beaucoup' de resultats de recherche une scrollbar apparait - et on peut redimensionner la fenetre.

Le comportement désiré (qui sera une amélioration future, car pierre n'a pas trouvé comment tordre le bras dans le dos a ExtJS pour l'implémenter, et je compatis) sera d'avoir une taille _maximale_ (disons 500px) jusqu'a laquelle la fenetre s'auto-dimensionnera en fonction du nombre de résultats de recherche (donc sans scrollbar), et s'il y'en a "trop" alors la taille est bornée à 500px et il y'a une scrollbar.

@catmorales si tu peux corriger le nom du ticket pour correspondre a l'anomalie ? merci :)

**Comment by MaelREBOUX** [comment]
ok avec le comportement désiré.
on va évauler ça avec les retours de vrais utilisateurs mais ça va revenir comme demande.

@landryb le pb de taille existe effectivement pour les 2 fenêtres.

**Comment by MaelREBOUX** [comment]
doublon avec #48 je crois. On ferme ce ticket ?
