### ISSUE TITLE
Activer le copier/coller dans la fiche d'info

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#341]
Il est possible d'activer le copier/coller dans les fiches d'infos avec cette methode : 

https://ahlearns.wordpress.com/2011/10/27/ext-js-make-grid-text-selectable/

Je viens de le tester et ça fonctionne :  https://opendata.agglo-lepuyenvelay.fr/mapfishapp/

En revanche je pense qu'il peut être interessant d'ouvrir une discussion pour faire remonter cette fonctionalité non pas au niveau de cadastrapp ("on one grid"), mais de mapfishapp via la redefinition du template Grid (2ème methode de l'article) car cela permettrait d'en profiter également lors de l'interrogation des couches autres que le cadastre.

**Comment by landryb** [comment]
Oh, classe ca... @fvanderbiest une opinion sur la faisabilité de faire ca dans mfapp ?

**Comment by fvanderbiest** [comment]
Faut tester si ça ne casse rien ...

**Comment by MaelREBOUX** [comment]
C'est TOP !  Je veux ça.

Du coup faut organiser une session croisée de tests sur TOUS les add-ons ?

**Comment by landryb** [comment]
A été mergé dans mfapp, donc techniquement on peut fermer ce bug la.

**Comment by MaelREBOUX** [comment]
Merci pour le suivi.
