### ISSUE TITLE
[export] L'export de la liste des parcelle sans etre connecté ne fonctionne plus (master)

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#343]
Je viens d'avoir un utilisateur qui m'appelle après avoir effectué une recherche comportant une vingtaine de parcelles.

Malheureusement celui-ci n'avait pas pensé à se connecter avant de faire sa recherche.

Du coup on a essayé d'utiliser la fonction exporter selection qui est censée fournir un csv de la liste des parcelles, afin d'utiliser la recherche par id de parcelle, ainsi il n'aurait pas eu à ressaisir toutes ses parcelles.

Mais nous sommes tombés sur une regression : 

En mode visiteur, il est impossible de réaliser un export des parcelles sélectionnées.
Nous avons essayé via le bouton "Exporter sélection" => Aucune réaction ni message dans la console
Via "Recherche avancée > Traitement sélection > Parcelles > Export Liste.csv" => idem

Il me parait assez important / urgent de corriger cette régression.

**Comment by ghost** [comment]
OK, je vais regarder, ça va me prendre un peu de temps, je remonte un environnement de dev sur la dernière version du georchestra.

**Comment by landryb** [comment]
Jepeux confirmer cette régression avec master quand l'utilisateur n'est pas connecté - le js fait un POST sur `/exportParcellesAsCSV` avec la liste des parcelles présentes dans la sélection, et il se fait tej par la webapp qui répond 204/No Content. Dans le log:
```
INFO  /exportParcellesAsCSV - nouser - norole -o.g.c.providers.PreRequestFilter - Incoming request
DEBUG /exportParcellesAsCSV - nouser - norole -o.g.c.providers.PreRequestFilter - Parameter list : {}
DEBUG /exportParcellesAsCSV - nouser - norole -o.g.cadastrapp.service.CadController -  Check user CNIL Level 
DEBUG /exportParcellesAsCSV - nouser - norole -o.g.cadastrapp.service.CadController -  Get user roles informations : null
DEBUG /exportParcellesAsCSV - nouser - norole -o.g.cadastrapp.service.CadController -  Check user CNIL Level : 0
INFO  /exportParcellesAsCSV - nouser - norole -o.g.c.service.ParcelleController - User does not have rights to see thoses informations
INFO  /exportParcellesAsCSV - nouser - norole -o.g.c.providers.PreReponseFilter - Sending response
```

Au passage, quand on est pas connecté, il me parait peu logique d'avoir 'Propriétaires' et 'Co-propriétaires' dans le sous-menu 'exporter selection'.....

**Comment by landryb** [comment]
Et c'est probablement une regression due a 1c3b1aeba3c19802443dfac3956217d3f8c2995a et e05e6ac3d8c0e3452512136ee65d4854353e92e1 / #292 - je creuse.

**Comment by landryb** [comment]
Et donc la cause probable est ici, dans /exportParcellesAsCSV on vérifie le niveau CNIL:
https://github.com/georchestra/cadastrapp/blob/master/cadastrapp/src/main/java/org/georchestra/cadastrapp/service/ParcelleController.java#L567

Autant pour les propriétaires/copropriétaires ca se tient, mais pour la liste des parcelles je ne pense pas.

Au passage, j'ai vu les items 'propriétaires/copropriétaires' dans le sous-menu export selection en étant non connecté, alors qu'il y'a bien du code js pour avoir un comportement différent - ie faire un bouton simple pour exporter juste les parcelles quand on est non connecté vs un menu avec les 3 choix quand on est connecté. 

`GEOR.Addons.Cadastre.isCNIL2()` me renvoie `true` alors que cas/le header me dit que je ne suis pas connecté.. il doit y'avoir un autre bug probablement indépendant.

**Comment by landryb** [comment]
> GEOR.Addons.Cadastre.isCNIL2() me renvoie true alors que cas/le header me dit que je ne suis pas connecté.. il doit y'avoir un autre bug probablement indépendant.

Pour ca, probablement un pbm de cache navigateur, `GEOR.config.ROLES` n'avait pas été reset correctement, donc j'avais encore CNIL2 dedans (je me suis déconnecté et j'ai fait précédent..)

**Comment by landryb** [comment]
@jusabatier @MaelREBOUX @pierrejego je ne voudrais pas faire d'erreur avec ca, mais il me semble qu'il n'y a aucune raison de conditionner l'export CSV d'une liste de parcelles au fait d'etre connecté, a plus forte raison si l'interface utilisateur n'affiche que ce bouton si l'utilisateur est non connecté - donc je pense que c'est juste un oubli/copier-coller malencontreux qui fait qu'on ce retrouve avec ce check de cnillevel dans le cas des parcelles - si ca vous va, je fais sauter ce check.

**Comment by MaelREBOUX** [comment]
L'export CSV contient les attributs : 
- Identifiant de parcelle
- Commune
- dnvoiri
- dindic
- cconvo
- dvoilib
- ccopre
- ccosec
- N° de plan
- Contenance DGFiP en m²

Donc aucune donnée à caractère personnel.
Je confirme qu'il n'y aucun besoin de contrôler les groupes CNIL sur cette fonction d'export.

Par contre : je note l'hétérogénéité du nom des attributs. Pas top ça. Je vois que ça se passe ligne 569.
@landryb je fais un commentaire pour que tu change ça mais du coup @pierrejego il va se passer quoi au réimport du fichier ?
Mieux vaut faire une issue séparée non ?

**Comment by landryb** [comment]
> il va se passer quoi au réimport du fichier ?

Je ne suis pas certain que ce fichier CSV soit prévu pour être 'réimportable', pour moi le seul import d'un CSV qu'on peut faire contient une liste d'id de parcelle uniquement, cf https://github.com/georchestra/cadastrapp/blob/master/cadastrapp/src/main/java/org/georchestra/cadastrapp/service/ParcelleController.java#L381 - et pareil pour un CSV avec une liste de compte communaux. 

Donc pour moi, l'entete des CSV importe peu... pourvu qu'il soit "harmonieux" et ne mixe pas des labels et des codes.

Il y'aurait que celui la a fixer: https://github.com/georchestra/cadastrapp/blob/master/cadastrapp/src/main/java/org/georchestra/cadastrapp/service/ParcelleController.java#L569

Les entetes pour les exports de proprietaire et copropriétaire sont a priori corrects - https://github.com/georchestra/cadastrapp/blob/master/cadastrapp/src/main/java/org/georchestra/cadastrapp/service/ProprietaireController.java#L331 est en commentaire/a la bonne version juste en dessous.

**Comment by landryb** [comment]
Celui de ProprietaireController.java contient 'Dénominiation', un i en trop :)

**Comment by landryb** [comment]
Et pareil pour celui de CoProprietaireController.java en fait - ces 2 entetes finissent par `ccodro_lib` qui serait donc aussi a corriger.
```
cadastrapp/src/main/java/org/georchestra/cadastrapp/service/CoProprietaireController.java:                      String  entete = "Compte communal;Civilité;Nom;Prénom;Nom d'usage;Prénom d'usage;Dénominiation;Nom d'usage;Adresse ligne 3;Adresse ligne 4;Adresse ligne 5;Adresse ligne 6;Identitifiants de parcelles;ccodro_lib";
cadastrapp/src/main/java/org/georchestra/cadastrapp/service/ProprietaireController.java:                        String  entete = "Compte communal;Civilité;Nom;Prénom;Nom d'usage;Prénom d'usage;Dénominiation;Nom d'usage;Adresse ligne 3;Adresse ligne 4;Adresse ligne 5;Adresse ligne 6;Identitifiants de parcelles;ccodro_lib";

```

**Comment by landryb** [comment]
Après vérification avec @pierrejego , on peut corriger les entetes directement, ils ne sont pas réutilisés à l'import.

**Comment by MaelREBOUX** [comment]
OK. Pour tracer j'ai ouvert un nouveau ticket -> #356

**Comment by landryb** [comment]
Fixed by #353
