### ISSUE TITLE
[documentation] doc sur purge à compléter

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#345]
hum : depuis la version 1.4 je crois que ceci est obsolète non ?
https://github.com/georchestra/cadastrapp/wiki/Guide-Administrateur#purge

> Les fichiers générés par l'application sont déposés dans le répertoire 'tempFolder' paramétré dans le fichier cadastrapp.properties. Ces fichiers sont supprimés à chaque redémarrage de la JVM. Ces fichiers peuvent aussi être purgés à la main, ou par un script que vous pouvez créer.

Et la note de version 1.4 indique :

> Création d'un job Quartz de suppression de tous les fichiers temporaires (donc essentiellement les fichiers des bordereaux et des relevés de propriété) par #294. Veiller à supprimer les tâches cron système que vous auriez mis en place.

Confirmation @pierrejego ?

**Comment by pierrejego** [comment]
La première explication reste vraie, on peut toujours purgé manuellement, on a juste rajouter un ordonnanceur pour purger régulièrement.
Je vais mettre à jour cette partie de la doc

**Comment by MaelREBOUX** [comment]
@pierrejego : on en est où sur ce ticket ?  Fait / pas fait ? On ferme ?

**Comment by pierrejego** [comment]
Non pas encore fait :)

**Comment by MaelREBOUX** [comment]
OK. Je laisse le tag alors ;)

**Comment by MaelREBOUX** [comment]
Merci.
