### ISSUE TITLE
[model] Bug script de création et d'alimentation de la base de données si port différent de 5432.

### ISSUE THREAD

**Issue by spelhate** [georchestra/cadastrapp#346]
les scripts ne fonctionnent pas si la base cadastrapp et la base qgis tournent sur des instances dont le port est différent de 5432.

**Comment by spelhate** [comment]
Je peux proposer une PR.

**Comment by landryb** [comment]
Closed by #351

**Comment by MaelREBOUX** [comment]
Sauf que la PR n'a porté que sur la partie QGIS.
Il faudrait logiquement reporté sur la partie arcOpole.

**Comment by landryb** [comment]
> Il faudrait logiquement reporté sur la partie arcOpole.

Certes, et c'est trivial, tu t'en charges ?

**Comment by MaelREBOUX** [comment]
Je vais essayer pour la v 1.5...

**Comment by pierrejego** [comment]
J'ai fait la modification et le test pour l'intégration des fichiers Majic 2017. Attention à bien mettre à jour vos scripts de lancement.  Voir commit précédent
