### ISSUE TITLE
[model] intégration de données Majic 2017

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#348]
J'ouvre les hostilités.

On a mouliné les fichiers EDIGEO et Majic v 2017. Le tout avec une version arcOpole 2016.1.
Aucun pb au moulinage.
Aucun pb au chargement dans notre postgis de test.

Je lance un test de création des tables et vues cadastrapp. Vlan : erreur de type numeric sur la vue proprietebatie.

La cause : **des valeurs vides dans l'attribut DVLPERA de la table dgi_pev.**

L'étude du fichier BATI Majic III m'a permis (si je me suis pas gourré) de bien retrouver ces valeurs vides.

Si qqn voulait bien corroborer l'existence et la persistence de ces valeurs vides côté QGIS, ce serait sympa. Merci.

**Comment by landryb** [comment]
J'ai reçu les fichiers cette semaine donc je vais les traiter dans les jours/semaines qui viennent, mais dans les fichiers DESCRIPT rien ne dit pour 'mise à jour 2017' que l'attribut DVLPERA peut avoir des valeurs vides, donc ce n'est pas un changement par rapport a l'an dernier.

**Comment by MaelREBOUX** [comment]
> rien ne dit pour 'mise à jour 2017' que l'attribut DVLPERA peut avoir des valeurs vides, donc ce n'est pas un changement par rapport a l'an dernier.

Euh : c'est justement un changement tu veux dire ?

Il se trouve que j'ai sous la main depuis vendredi un CD-Rom visuDGFiP. Ce qui m'inquiète c'est que je ne retrouve pas les mêmes valeurs entre visuDGFiP et les données Majic III pour le même local. Je suis très inquiet.

**Comment by MaelREBOUX** [comment]
Ce matin j'ai appelé la personne qui distribue les CD VisuDGFiP. On a regardé ensemble 2 locaux test.
Il a consulté son application et moi visuDGFiP : les valeurs sont bien les mêmes.

**Conclusion : pour les locaux commerciaux révisés, les anciennes valeurs locatives PEV continuent d'apparaître dans visuDGFiP mais elles ont bel et bien été retirées des fichiers Majic III. La DGFiP diffuse donc 2 produits pas équivalents.**

On regarde quand même dans le fichier brut non dégroupé fourni par le Conseil Départemental pour vérifier si on a bien les mêmes lignes pour ces 2 locaux.

**Comment by MaelREBOUX** [comment]
Ça sent la branche spécifique...

Je vais relancer en faisant un coalesce pour autoriser des valeurs vides. On n'a pas vraiment le choix...

**Comment by MaelREBOUX** [comment]
A priori tout passe :
- les recherches
- les bordereaux parcellaires avec / sans DN
- les RP sur un proprio qui a une maison d'habitation
- les RP sur un proprio qui a un local commercial : que sur la parcelle consultée
- les RP sur un proprio qui a un local commercial : sur la totalité des biens

ouf !

Bon j'ai détecté un autre pb mais c'est autre chose (les valeurs locatives sont erronées).

**Comment by MaelREBOUX** [comment]
Je viens de faire un test d'intégration avec le plugin QGIS v 1.4.1 sous QGIS 2.18.2 et ça s'est bien passé.
Les valeurs sont bonnes sur les RP produits par le plugin.

**Comment by MaelREBOUX** [comment]
En revanche : la moulinette 2016.1 de arcOpole ne s'est en pas sortie. Il y a un décalage dans les colonnes et donc les valeurs.

**Comment by MaelREBOUX** [comment]
Beau commit sur le plugin QGIS : https://github.com/3liz/QgisCadastrePlugin/commit/f059205ec627529734fd660243eb748d36fe8f07

En attente de la nouvelle version de l'outil arcOpole.

**Comment by MaelREBOUX** [comment]
Nouvelle version arcOpole disponible depuis ce matin. On mouline.

Appel à tester uen version bêta côté QGIS : https://github.com/3liz/QgisCadastrePlugin/issues/109#issuecomment-327504961

Je viens de le tester. L'import s'est bien déroulé. Je ne vois aucune différence sur le RP. Pas regardé la base.

**Comment by mdouchin** [comment]
2ème commit avec des corrections mineures suite à mon premier commit : 3liz/QgisCadastrePlugin@095c5205eb1fe5347d83e586dc19582b48dfe131
A ce stade la structure doit être ok, cad qu'on a bien dans la bdd les données issues des fichiers. A noter que dans le plugin, un choix avait été fait de ne pas supprimer les anciens champs.

Au sujet des relevés et des calculs, il va falloir regarder comment les calculs doivent être fait. 
https://www.impots.gouv.fr/portail/files/media/1_metier/1_particulier/EV/5_patrimoine_logement/590_revision_valeurs_locatives/calcul_cotisation_taxe_fonciere.pdf

Un sujet en cours sur [forumsig](http://www.forumsig.org/showthread.php/44478-Plugin-Cadastre-Nous-aider-%C3%A0-tester-les-donn%C3%A9es-MAJIC-2017)

**Comment by smevel** [comment]
@landryb tu vas adapter ton [script d'import](https://github.com/landryb/QgisCadastrePlugin/tree/import_cli) ?

Des difficultés de notre côté sur un département pour l'EDIGEO.

**Comment by landryb** [comment]
> @landryb tu vas adapter ton script d'import ?

C'est dans les tuyaux, techniquement c'est pas 'mon script' mais une adaptation du plugin...

**Comment by landryb** [comment]
J'ai mergé les commits de @mdouchin dans ma branche (cf https://github.com/landryb/QgisCadastrePlugin/commits/import_cli) et j'ai a priori pu importer edigeo/majic sur une commune du cantal dans une base postgis. Avec la v1.4.1 du plugin cadastre de QGIS, j'ai pu me connecter et charger les données depuis la ladite base, générer des RP/BP, donc pour moi c'est en bonne voie.

Evidemment, la prochaine étape c'est de tester sur X départements...

**Comment by landryb** [comment]
Pas de soucis majeurs pour importer 4 départements en ~11h avec le script d'import.

Je n'ai pas encore testé de créer les vues matérialisées de cadastrapp à partir des données 2017, c'est la prochaine étape.

**Comment by MaelREBOUX** [comment]
Ici les collègues ont fini de mouliner et d'adapter les données en base PostGIS. Je fais un test d'import Cadastrapp d'ici vendredi.

**Comment by landryb** [comment]
Coté qgis, j'avais déja des valeurs 'vides' pour `pev.dvlpera` (qui est de type `integer`) en 2016, j'en ai toujours en 2017, mais elles sont a 0 et non 'nulles':
```
qadastre=> select count(*) from qad2016.pev where dvlpera is null;
0
qadastre=> select count(*) from qad2016.pev where dvlpera = 0;
543
qadastre=> select count(*) from qad2017.pev where dvlpera is null;
0
qadastre=> select count(*) from qad2017.pev where dvlpera = 0;
469
```
Donc je ne pense pas qu'on ait de souci dans le modèle QGIS comme tu as eu dans Arcopole lors du calcul du champ `revcad` - ce qui n'empeche pas de faire le changement dans les 2 scripts tant qu'il ne pète rien.

**Comment by landryb** [comment]
Une fois mergé la pr #348, aucun autre/nouveau pb pour créer les vues matérialisées sur 4 depts entiers avec le modèle QGIS. Wait and see..

**Comment by MaelREBOUX** [comment]
Je viens de faire une intégration avec des nouvelles données arcOpole avec succès (branche issue-348).
J'ai regardé dans les tables et je retrouve les valeurs attendues en revcad.

Il faut maintenant maj sur le serveur de test pour voir la suite et la tronche des RP.

**Comment by MaelREBOUX** [comment]
Problème : Dans l'article 50, 2 attributs ont disparu.

**DNUDES : Numéro d’ordre de descriptifs
VSURZT : Surface réelle totale**

qgis : table pevprofessionnelle
arcopole : table dgi_pprof

La doc de arcOpole fait tjs mention de ces 2 attributs mais ils ont bien disparu en base.
La [doc de Qgis ](http://htmlpreview.github.io/?https://github.com/3liz/QgisCadastrePlugin/blob/master/doc/modele_donnees/postgresql_autodoc/index.html) fait encore mention de dnudes mais les 2 attributs  ont bien disparu en base. -> @mdouchin 

Contrairement à mon dernier message : cela plante l'intégration. Je propose une modification rapide pour que cadastrapp fonctionne avec ces 2 attributs à vide ; en attendant d'intégrer les nouveautés.

**Comment by landryb** [comment]
> cela plante l'intégration

Il faut que tu sois plus précis. Pas de pbm ici, juste les valeurs sont nulles pour toutes les entrées.
```
qadastre=> select dnudes from qad2017.pevprofessionnelle where dnudes is not null;
 dnudes 
--------
(0 rows)
```

Un rapport d'erreur sans message ne sert a rien :)

**Comment by MaelREBOUX** [comment]
Je viens de pousser un contournement : on crée 2 attributs vides.
https://github.com/georchestra/cadastrapp/commit/b6c23cb4add21a4744de41c0a8156659ceee4b50

![image](https://user-images.githubusercontent.com/6370443/30694932-73b7f2ec-9ed6-11e7-9e3a-52864cb7749a.png)

**Comment by MaelREBOUX** [comment]
@landryb : la base QGIS contient encore ces 2 attributs or elle ne devrait pas : ils n'existent plus. Il faut l'anticiper.
Je m'attèle à remonter en base les nouvelles données.

**Comment by landryb** [comment]
> cela plante l'intégration

tu n'as toujours pas expliqué en quoi ca 'plantait l'intégration'. Ta capture d'écran montre une valeur vide/erronée, mais ca veut dire que les vues ont été créees correctement (meme si les valeurs sont erronées, ce qui est un pbm différent)

**Comment by MaelREBOUX** [comment]
> cela plante l'intégration

En toute évidence ça remontait une erreur SQL qui disait que l'attribut 'dnudes' n'existait pas.

**Comment by landryb** [comment]
ok, mais donc l'erreur n'arrive que sur le modele arcopole (ce qui n'empeche pas que les 2 doivent etre corrigés, qgis en préventif)

**Comment by MaelREBOUX** [comment]
Voilà le début des nouveaux attributs pour **descproffessionnel**
https://github.com/georchestra/cadastrapp/commits/issue-348

J'en ai profité pour homogénéiser des datatype entre arcopole et qgis...
Et je teste également pour QGIS.

**Comment by MaelREBOUX** [comment]
Pour suivi 

**article 50 : descriptif de la partie professionnelle**
- [ ] tables nomenclatures des locaux professionnels
  - [ ] type
  - [ ] sous-type
- [X] gestion dnudes et vsurzt en attendant suppression [[commit](https://github.com/georchestra/cadastrapp/commit/b6c23cb4add21a4744de41c0a8156659ceee4b50)]
- [X] 6 nouveaux attributs : remontée en base [[commit](https://github.com/georchestra/cadastrapp/commit/583212e98b556f3fc0a0f73a61c149403854cdc3)]
- [ ] 6 nouveaux attributs : modification code Java et javascript pour afficher dans cadastrapp dans fiche détails locaux commerciaux

**article 21 : descriptif de PEV**
- [ ] 7 nouveaux attributs : remontée en base
A ce stade je ne crois pas qu'il soit nécessaire de faire des modifications pour les locaux d'habitation.

**Relevé de propriété**
- [ ] propriété bâtie : modifier pour que apparaisse 1 ligne par taxeur (comm / group comm / dpt)

**Comment by pierrejego** [comment]
Pour suivi 

**article 50 : descriptif de la partie professionnelle**
- [X] tables nomenclatures des locaux professionnels
  - [X] type
  - [X] sous-type 
- [X] gestion dnudes et vsurzt en attendant suppression [[commit](https://github.com/georchestra/cadastrapp/commit/b6c23cb4add21a4744de41c0a8156659ceee4b50)]
- [X] 6 nouveaux attributs : remontée en base [[commit](https://github.com/georchestra/cadastrapp/commit/583212e98b556f3fc0a0f73a61c149403854cdc3)]
- [X] 6 nouveaux attributs : modification code Java et javascript pour afficher dans cadastrapp dans fiche détails locaux commerciaux

**article 21 : descriptif de PEV**
- [X] 7 nouveaux attributs : remontée en base
A ce stade je ne crois pas qu'il soit nécessaire de faire des modifications pour les locaux d'habitation.

**Relevé de propriété**
- [x] propriété bâtie : modifier pour que apparaisse 1 ligne par taxeur (comm / group comm / dpt)

**Comment by pierrejego** [comment]
Pour la remontée des informations en base (Article 21) j'ai un soucis de type et de valeur.

DCFLOC,CCORTAR, DTAURV et DCMLOC sont des entiers dans Qgis et des chaines de caractères dans Arcopole.
J'ai voulu faire un cast en entier pour arcopole, mais il y a des valeurs vides (un espace)

J'ai vérifié dans le fichier de descriptif des nouveaux champs ils sont déclarés de NAT 9. Est-ce quelqu'un sait ou je peux trouver la correspondance de ce numéro ?

![image](https://user-images.githubusercontent.com/11499415/32719598-395a6bde-c861-11e7-96fe-dfc4512ef6a0.png)

C'est le quatrième champ.

J'aurais tendance à supprimer les espaces et caster en integer. Vous en pensez quoi ?

**Comment by MaelREBOUX** [comment]
Revue faite ce matin. Un dernier truc à corriger sur le RP et la release de la v1.5 est en vue. J'amorce la release note.

**Comment by landryb** [comment]
> Revue faite ce matin. Un dernier truc à corriger sur le RP et la release de la v1.5 est en vue. J'amorce la release note.

Tu comptes vraiment faire une 1.5 sans fixer #356 et #357 alors que les PR sont triviales et en attente ?

**Comment by pierrejego** [comment]
la #356 n'est pas encore faite et il faut que je teste la #357 mais si j'arrive à le faire dans la journée, je l'embarque dans la 1.5. 
Autrement ça sera pour la 1.6 qui est prévue en Janvier

**Comment by MaelREBOUX** [comment]
A relire : https://github.com/georchestra/cadastrapp/wiki/Releases#v-15-novembre-2017

**Comment by pierrejego** [comment]
J'ai ajouté la #356 et la #357 dans la release note

**Comment by MaelREBOUX** [comment]
vu : je ferai de la comm semaine prochaine.
