### ISSUE TITLE
validation erronée du champ ddenom sur la recherche de copropriétaire

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#354]
Dans la fenetre de recherche de copropriétaire, le champ nom/prénom est marqué comme 'en erreur' avec moins de 12 caractères (cf https://github.com/georchestra/cadastrapp/blob/master/addons/cadastrapp/js/searchCoPropriete.js#L122), alors que c'est un nom d'usage/ddenom, pas un comptecommunal (sur lequel devrait porter la verification de longueur)

De plus, le tooltip d'aide n'a pas de traduction pour la clef `cadastrapp.search.copropriete.ddenom.control` - je ne suis pas certain qu'il devrait y'avoir une validation sur ce champ, étant donné qu'il n'y en a pas sur la recherche de propriétaire par nom (cf https://github.com/georchestra/cadastrapp/blob/master/addons/cadastrapp/js/searchParcelleByOwner.js#L232) donc je ferais sauter minlength/minlenghttext de la definition dans searchCoPropriete.js.

**Comment by MaelREBOUX** [comment]
En erreur console ou il y a un message que voit l'utilisateur ?

Et pour les tooltip il y en a qqs uns qui sont à reprendre  -> #355

**Comment by landryb** [comment]
Le contenu du champ est souligné en rouge quand il n'y a pas 12 chars.

**Comment by ghost** [comment]
Effectivement ça ne sert plus à rien sur un ddenom.
Je propose d'utiliser la variable déjà existante dans la conf , ça permettra de quand même limité les requêtes faites au serveur.

> ## Min char number that is required to make a search in database
> ## in link with the min char in combox need before calling webapp
> minNbCharForSearch=3

https://github.com/georchestra/cadastrapp/blob/master/cadastrapp/src/main/resources/cadastrapp.properties

**Comment by landryb** [comment]
Ca me va !

**Comment by MaelREBOUX** [comment]
On peut fermer ce ticket ? @landryb @pierrejego  ?

**Comment by pierrejego** [comment]
En faisant la modification je vois qu'il y a quelques choses de pas cohérent. 

On a pas fixé de minlength pour les ids de parcelles et pour les comptescommunaux côté client ( Qui ne sont d'ailleurs pas les mêmes entre Qgis et Arcopole. ). C'est en dur alors qu'on a l'information (au moins pour la parcelle côté serveur). 
Je rajouterai bien un nouvelle entrée dans le fichier properties et une nouvelle variable côté client pour tout uniformiser. (Pour la longueur du comptecommunal)

**Comment by MaelREBOUX** [comment]
Je vois l'idée. Comportement non bloquant jusqu'à présent.

**Comment by pierrejego** [comment]
Corrigé avec ce commit https://github.com/georchestra/cadastrapp/commit/50a937cb6dd93c10ccdaa129f6760b53916dcb04#diff-142927dd03b2550fc49ba99057109a53
