### ISSUE TITLE
[export] Harmoniser les noms des colonnes des CSV

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#356]
Cela concerne 
- l'export CSV de la liste des parcelles
- l'export CSV de la liste des propriétaires

Pour les parcelles : https://github.com/georchestra/cadastrapp/blob/master/cadastrapp/src/main/java/org/georchestra/cadastrapp/service/ParcelleController.java#L569

**Comment by landryb** [comment]
@MaelREBOUX si tu peux valider les labels.. et je merge.

**Comment by landryb** [comment]
Au passage, je serais tenté de virer les fioritures (lettres accentuées, symbole degré) - dans un éditeur de texte, ils apparaissent comme des '?' et pareil a l'import dans soffice, meme en specifiant UTF8 pour le charset.

**Comment by landryb** [comment]
Hm, en fait c'est probablement toujours du a mon tomcat de dev qui detecte pas correctement le charset/LANG du systeme..

**Comment by MaelREBOUX** [comment]
Alors  je propose

**pour l'export de la liste des parcelle**
- parcelle
- commune
- voie_adr
- voie_adr_cplmt
- voie_type
- voie_nom
- section_prefixe
- section
- parcelle_num
- contenance

**pour l'export de la liste des proprios, dans l'ordre actuel des attributs**
proprio_id
- civilite
- nom_usage
- prenom_usage
- nom_naissance
- prenom_naissance
- denomination_naissance
- denomination_usage
- adresse_ligne3
- adresse_ligne4
- adresse_ligne5
- adresse_ligne6
- parcelles
- droit_reel_libelle
- lieu_naissance
- date_naissance

Sauf que tant qu'à y être, s'il y a moyen de modifier l'ordre des attributs, ce serait plus logique et plus lisible de réorganiser ce qui a trait aux noms :
- proprio_id
- droit_reel_libelle
- denomination_usage
- parcelles
- civilite
- nom_usage
- prenom_usage
- denomination_naissance
- nom_naissance
- prenom_naissance
- adresse_ligne3
- adresse_ligne4
- adresse_ligne5
- adresse_ligne6
- lieu_naissance
- date_naissance

@jusabatier ton avis ?

**Comment by jusabatier** [comment]
Aucun soucis pour la réorganisation des champs qui me parait logique en effet.

**Comment by landryb** [comment]
@MaelREBOUX tu es libre de faire les changements que tu veux sur ma PR.

**Comment by ghost** [comment]
très bonne idée cette uniformisation
