### ISSUE TITLE
Bugs sur sections/parcelles communes fusionnées

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#357]
Meme après #308, il me reste des incohérences - et je ne sais pas si c'est dans la structure de la base ou des vues.

La commune 430255 a été fusionnée dans 430090 - si je liste les sections j'ai bon:
```
GET /cadastrapp/services/getSection?cgocommune=430090

[{"cgocommune":"430090","ccopre":"","ccosec":"A"},{"cgocommune":"430090","ccopre":"","ccosec":"B"},{"cgocommune":"430090","ccopre":"","ccosec":"C"},{"cgocommune":"430090","ccopre":"","ccosec":"D"},{"cgocommune":"430090","ccopre":"255","ccosec":"A"},{"cgocommune":"430090","ccopre":"255","ccosec":"AB"},{"cgocommune":"430090","ccopre":"255","ccosec":"B"},{"cgocommune":"430090","ccopre":"255","ccosec":"C"}]
```

Si dans l'interface de recherche j'essaie de lister les parcelles de la section A du prefix 255 -> RIEN, car le découpage de `ccopre/ccosec` est faux:
```
GET /cadastrapp/services//getDnuplaList?cgocommune=430090&ccopre=25&ccosec=5A
```
et pareil pour la section B ou C. Evidemment, pas de souci avec la section D de la commune originale (ccopre vide, ccosec=D)

étrangement, pour la section AB ca marche:
```
GET /cadastrapp/services//getDnuplaList?cgocommune=430090&ccopre=255&ccosec=AB
[{"dnupla":"1"},{"dnupla":"10"},{"dnupla":"100"},{"dnupla":"103"},{"dnupla":"104"},{"dnupla":"107"},{"dnupla":"108"},{"dnupla":"109"},{"dnupla":"11"},{"dnupla":"110"},{"dnupla":"111"},{"dnupla":"113"},{"dnupla":"114"},{"dnupla":"116"},{"dnupla":"117"},{"dnupla":"118"},{"dnupla":"119"},{"dnupla":"12"},{"dnupla":"120"},{"dnupla":"121"},{"dnupla":"122"},{"dnupla":"123"},{"dnupla":"124"},{"dnupla":"126"},{"dnupla":"127"},{"dnupla":"128"},{"dnupla":"13"},{"dnupla":"135"},{"dnupla":"136"},{"dnupla":"137"},{"dnupla":"138"},{"dnupla":"14"},{"dnupla":"143"},{"dnupla":"144"},{"dnupla":"145"},{"dnupla":"146"},{"dnupla":"147"},{"dnupla":"148"},{"dnupla":"149"},{"dnupla":"15"},{"dnupla":"150"},{"dnupla":"151"},{"dnupla":"152"},{"dnupla":"153"},{"dnupla":"154"},{"dnupla":"155"},{"dnupla":"156"},{"dnupla":"157"},{"dnupla":"16"},{"dnupla":"17"},{"dnupla":"18"},{"dnupla":"19"},{"dnupla":"2"},{"dnupla":"20"},{"dnupla":"21"},{"dnupla":"22"},{"dnupla":"23"},{"dnupla":"24"},{"dnupla":"26"},{"dnupla":"27"},{"dnupla":"28"},{"dnupla":"29"},{"dnupla":"3"},{"dnupla":"30"},{"dnupla":"31"},{"dnupla":"32"},{"dnupla":"33"},{"dnupla":"34"},{"dnupla":"35"},{"dnupla":"36"},{"dnupla":"37"},{"dnupla":"38"},{"dnupla":"39"},{"dnupla":"4"},{"dnupla":"40"},{"dnupla":"41"},{"dnupla":"42"},{"dnupla":"44"},{"dnupla":"45"},{"dnupla":"46"},{"dnupla":"47"},{"dnupla":"48"},{"dnupla":"49"},{"dnupla":"5"},{"dnupla":"50"},{"dnupla":"51"},{"dnupla":"52"},{"dnupla":"53"},{"dnupla":"54"},{"dnupla":"55"},{"dnupla":"56"},{"dnupla":"57"},{"dnupla":"59"},{"dnupla":"6"},{"dnupla":"60"},{"dnupla":"61"},{"dnupla":"63"},{"dnupla":"64"},{"dnupla":"65"},{"dnupla":"67"},{"dnupla":"69"},{"dnupla":"7"},{"dnupla":"70"},{"dnupla":"71"},{"dnupla":"72"},{"dnupla":"73"},{"dnupla":"74"},{"dnupla":"75"},{"dnupla":"76"},{"dnupla":"77"},{"dnupla":"78"},{"dnupla":"79"},{"dnupla":"8"},{"dnupla":"80"},{"dnupla":"81"},{"dnupla":"82"},{"dnupla":"83"},{"dnupla":"84"},{"dnupla":"85"},{"dnupla":"86"},{"dnupla":"87"},{"dnupla":"88"},{"dnupla":"89"},{"dnupla":"9"},{"dnupla":"91"},{"dnupla":"94"},{"dnupla":"95"},{"dnupla":"96"},{"dnupla":"97"},{"dnupla":"98"},{"dnupla":"99"}]
```

Je ne sais pas si c'est un pbm de JS ou de base.. a mon avis de JS, car si je query a la main cadastrapp/services/getDnuplaList?cgocommune=430090&ccopre=255&ccosec=A j'ai bien les bonnes données. A voir s'il n'y a pas d'autres gags du genre a d'autres endroits..

**Comment by landryb** [comment]
2 endroits suspects: https://github.com/georchestra/cadastrapp/blob/master/addons/cadastrapp/js/searchUtils.js#L100 et https://github.com/georchestra/cadastrapp/blob/master/addons/cadastrapp/js/searchParcelleByRef.js#L478

**Comment by landryb** [comment]
Les données en base sont correctes, donc c'est bien un pbm de parsing de string dans le js. c'est juste **horrible**.

**Comment by landryb** [comment]
Je ne sais pas comment sont les données en base dans arcopole (@maelreboux?) mais dans le modèle QGIS, ccosec n'est pas préfixé par des 0 a gauche, donc ca marche quand la section est sur 2 lettres, mais quand sectionId=255A (https://github.com/georchestra/cadastrapp/blob/master/addons/cadastrapp/js/searchUtils.js#L101), on se retrouve avec prefix=25 et section=5A.

Je suis partagé entre toucher le modèle/vues pour ajouter des 0 a gauche (ie 0A, 0B, AB..) ou pour faire une heuristique regardant si les 3 premiers caractères forment un chiffre, et dans ce cas les considérer comme un préfixe et considérer le reste comme la section (avec chiffre potentiel si 0 dans le modele arcopole?) - ou faire ce choix sur la longueur de sectionId (ie si > 2, c'est préfix+section, sinon uniquement section ?)

**Comment by landryb** [comment]
De ce que je vois du sql, ccopre fait 3 chars, et ccosec en fait 2, et:

* dans arcopole les 0 sont supprimés de ccosec:
```
ltrim(substr(invar.codparc,10,2), ''0'') ccosec
```
* pas dans qgis, on vire juste des espaces:
```
ltrim(l.ccosec) as ccosec,
```
* pour ccopre dans arcopole on vire 000 si on les trouve (?)
```
regexp_replace(substr(codparc,7,3), ''0{3}'', '''') as ccopre,
```
* et dans qgis on vire juste des espaces comme ccosec:
```
ltrim(ccopre),
```

Donc si je récapitule, il ne peut pas y avoir de 0 devant ccosec, et ccopre est soit vide soit contient 3 caractères, donc le bon algo pour parser consiste a vérifier la taille, et initialiser en fonction dans les 2 cas.

**Comment by landryb** [comment]
Je ne trouve aussi pas logique de faire une recherche sur la parcelle 1 de la section A, et d'avoir 2 résultats avec les parcelles 1 des sections A et 255A...

**Comment by MaelREBOUX** [comment]
On a 1 commune avec des préfixes.

Le JSON /cadastrapp/services/getSection?

```
    "cgocommune": "350206",
    "ccopre": "073",
    "ccosec": "AC"
```

En base tout est propre et nettoyé : pas de zéro devant comme demandé dans #308 
```
'350206';'AM';''
'350206';'AC';'073'
'350206';'AD';'073'
```

**Comment by landryb** [comment]
Oui, mais est-ce que cette commune a des sections avec une seule lettre ? c'est dans ce cas que ça plante...

**Comment by MaelREBOUX** [comment]
Pas sur cette commune si chez nous mais ça existe forcément. Et ça va se multiplier avec les fusions.

**Comment by landryb** [comment]
@jusabatier est-ce que le fix te parait logique ?
