### ISSUE TITLE
[AddOn.004.09] Recherche par référence

### ISSUE THREAD

**Issue by catmorales** [georchestra/cadastrapp#36]
- l'autocomplétion du champ commune est OK mais le tri du résultat doit êtr efait sur le nom de la commune et non pas sur le code insee (plus pratique),
- pas d'accents sur le nom des communes ex: Pac **é**
- Pour les  champs section et parcelle l'autocomplétion fonctionne uniquement si champ commune bien renseigné. Il manque des contrôles entre les différentes zones de saisies (pas possible de renseigner section si commune non renseignée, ....)

**Comment by pierrejego** [comment]
Des contrôles ont été rajouté avec la correction de l'issue #35, les champs sections et parcelles ne peuvent être sélection que lorsque la commune est sélectionnée.

Nous ne disposons pas des accents dans la base de données, nous ne pouvons donc pas les afficher.

Il faut rajouter un order by dans la requête du getCommune

**Comment by landryb** [comment]
Quand tu dis que les accents ne sont pas dans la BDD, c'est pour le modèle arcopole uniquement ? Ca devait pas venir des communes du geofla ?

**Comment by pierrejego** [comment]
Non c'est bien pour les deux modèles, 
pour Arcopole on prend les données dans dgi_comm ou les valeurs sont en majuscule non accentuée
et pareil pour Qgis dans la table commune.
On ne prend pas de données de GeoFla, on prend uniquement les données contenues dans les bases que vous nous avez fourni pour pouvoir faire les jointures sur les parcelles.
