### ISSUE TITLE
[RP] Propriété bâtie : Revenu cadastral != revenu imposable

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#361]
Bonjour,

J'ai ce matin une secretaire de mairie qui m'appelle car elle a un souci avec les relevés de propriété des parcelles de sa commune : 

Elle voulait connaitre le revenu imposable de chacun des biens de la commune (dans le but de calculer une TOM).
Or sur les relevés de propriété, seul le revenu cadastral est détaillé à chaque ligne, le revenu imposable n'apparait que sous forme d'un total.
Elle m'a aussi fait remarquer que dans la ligne de récap, le revenu imposable indiqué à gauche est en fait un revenu cadastral (somme des revenus cadastraux des propriétés).

Donc pour recapituler, plusieurs besoins remontés : 

- Voir apparaitre le detail des revenus imposables par ligne
Cela ne me parait pas très simple, car on en a 3 différents (Commune, Departement et GC).

- Corriger le libellé "Revenu imposable" à gauche du recap en "Revenu cadastral"

Ce besoin est-il justifié ? Avez-vous déjà eu ce genre de problèmes avec vos utilisateurs ?

**Comment by MaelREBOUX** [comment]
Je note à l'instant que pour la partie propriété bâtie du RP, VisuDGFiP 2017 met, pour l'évaluation du local, "RC COM IMPOSABLE" là où QGIS et Cadastrapp indiquent "Revenu cadastral".

A corriger donc. Et vérifier les valeurs.

De toute façon, si c'est un local commercial révisé (majic 2017) les chiffres qu'on sort sont pas les bons...

**Comment by jusabatier** [comment]
Autant pour moi, il y avait un souci avec la moulinette QGIS de 2016 : 

Celle-ci provoquait un décalage en BDD des champs et donc la valeur remontée en revenu cadastrale était erronée.
En repassant avec la moulinette 2017 du plugin le problème et résolu et le revenu cadastral est bien identique au revenu imposable.

C'est donc une fausse alerte, il faut juste noter de bien utiliser la moulinette 2017 du plugin (a recupérer sur github car pas encore de release officielle) sinon les revenus cadastraux sont faussés.

**Comment by MaelREBOUX** [comment]
OK.
Mais je rouvre car on a un pb dans l'intitulé quand même.

**Comment by MaelREBOUX** [comment]
Je confirme l'évolution. Avant dans VisuDGFiP ça s'appelait "revenu cadastral" et maintenant ça s'appelle "RC COM IMPOSABLE".

**Comment by jusabatier** [comment]
RC COM IMPOSABLE = Revenu Cadastral Commune Imposable

Pour moi il n'y a pas de problème, c'est bien le revenu cadastral qui apparait à gauche.

Celui de la commune apparait egalement dans le recap (imposable et exo) au même titre que departement et GC.

Désolé d'avoir induit en erreur.

**Comment by MaelREBOUX** [comment]
@jusabatier vu notre discussion du jour sur les évolutions Majic 2017 je pense que cette issue est caduque.
Si tu es d'accord tu fermes ?
