### ISSUE TITLE
[demande] Gel de mapfishapp sur demande vide

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#362]
Si on remplit uniquement les infos du demandeur et pas l'objet de la demande, il est quand même possible de cliquer sur le bouton "Imprimer la demande".
L'interface ci-dessous apparaît et reste indéfiniment. Seul un F5 débloque mapfishapp.

![image](https://user-images.githubusercontent.com/6370443/30634581-e1374bd4-9def-11e7-8867-ac36832ab7f1.png)

**Comment by MaelREBOUX** [comment]
Toujours présent.

**Comment by Gaetanbrl** [comment]
En effet, il reste affiché sans fin.
Autrement, si le la fenêtre de chargement n'apparaît pas, le bouton "Imprimer la demande" reste cliquable.
Le bouton 'Imprimer la demande' doit-il être uniquement dégrisé à la sélection d'une valeur dans la liste "Objet de la demande" ?
Merci pour ces précisions.

**Comment by MaelREBOUX** [comment]
Oui : c'est ça : il faut formuler au moins 1 demande pour activer ce bouton.

**Comment by Gaetanbrl** [comment]
Il semble qu'il existent plusieurs moyens d'afficher le bouton "Imprimer la demande" sans que les informations sont complètes.
Egalement, il est possible de mettre des informations "vides" avec uniquement des espaces. Cette possibilité doit-elle être corrigée également ?

**Comment by MaelREBOUX** [comment]
Ben...
Dans l'absolu c'est pas propre oui. Générer une demande vide c'est pas "normal".

Si c'est pas trop de temps pour toi d'améliorer ça : c'est bon à prendre mais l'urgent est surtout de ne pas planter l'appli.

**Comment by Gaetanbrl** [comment]
Une première correction vient d'être proposée. Elle permettra de débloquer la saisie et débloquer ce comportement bloquant dans un premier temps.

**Comment by MaelREBOUX** [comment]
testé et approuvé
