### ISSUE TITLE
[RP] manque numéro d'adresse

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#365]
![screenshot879](https://user-images.githubusercontent.com/6370443/31136168-aaee66f2-a867-11e7-897f-caf013544d1a.png)

Concerne les propriétés bâties et non bâties.
Constaté à Rennes et Le Puy.

**Comment by pierrejego** [comment]
A tester pour vérifier si c'est toujours le cas

**Comment by MaelREBOUX** [comment]
Vérifié : on a bien le numéro d'adresse : donc RAS à fermer pour moi.

**Comment by MaelREBOUX** [comment]
@jusabatier tu l'as ?

**Comment by jusabatier** [comment]
Ok pour moi aussi, je vois bien les numeros d'adresse sur mes RP

**Comment by MaelREBOUX** [comment]
alors je ferme.
