### ISSUE TITLE
[RP] Manque des parcelles sur le RP en pdf

### ISSUE THREAD

**Issue by jpklipfel** [georchestra/cadastrapp#366]
Bonjour,
On constate que des parcelles disparaissent dans la liste des propriétaires
![image 7](https://user-images.githubusercontent.com/5012040/31267785-cb586d5c-aa79-11e7-89fb-1f645ba31bbb.png)
Selon que l'on fasse "voir les parcelles"
![image 6](https://user-images.githubusercontent.com/5012040/31267577-f1ca6b1c-aa78-11e7-86f5-2094636a8938.png)
ou "relevé de propriétés"
![image 8](https://user-images.githubusercontent.com/5012040/31267848-10da4ff8-aa7a-11e7-8988-594e34d8c1de.png)
Des parcelles disparaissent dans l'export pdf

Est ce que vous auriez une piste?
(nous sommes encore en 1.3)

**Comment by ghost** [comment]
Jamais rencontré ce problème, mais ce sont deux services différents qui récupèrent les données pour l'ihm ou qui génère le PDF.
C'est pour un type de propriétaire particulier ?

**Comment by jpklipfel** [comment]
Le test était sur des propriétaires commune de ou département de

**Comment by ghost** [comment]
@jpklipfel je ne comprends pas ta phrase ? Peux-tu développer un peu plus ?

**Comment by jpklipfel** [comment]
@Pedroo22 je n'ai pas compris ta question non plus ;)
Je voulais dire que l'on retrouve cette erreur sur le RP PDF du département du Bas-Rhin sur la commune d'Obernai ou sur le RP PDF de la commune de Lichtenberg sur la commune de Lichtenberg
C'est plus clair?

**Comment by ghost** [comment]
Oui beaucoup plus, merci. Donc ça ce produit, pour tous les cas que tu testes.  Ce n'est donc pas un type de propriétaire atypique. 

Dans ton exemple, c'est la parcelle de la section 15 qui disparaît, est ce que les autres parcelles sont aussi dans la commune 670348 ?
Je n'ai jamais rencontré ce soucis, mais je me dis que c'est peut lié à un regroupement de commune. Est-ce que sur cette section il y a une propriété batie, ou c'est du non batie ? ça me permet d'orienter un peu les recherches.

Le mieux serait de lister plusieurs cas pour essayer de trouver le point commun.

**Comment by jpklipfel** [comment]
>Dans ton exemple, c'est la parcelle de la section 15 qui disparaît, est ce que les autres parcelles sont aussi dans la commune 670348 ?

Oui

Nous ne sommes pas dans le cas d'un regroupement de commune. 

Les parcelles qui disparaissent (car il y en a plein!) ce sont des parcelles où les colonnes Classe, Coll, Nat Exo et An Ret sont vides. En général il y a un bâtiment dessus mais pas toujours

**Comment by jpklipfel** [comment]
Les sous groupes S ne remontent pas

**Comment by ghost** [comment]
OK, je vois ça vient peut être du regroupement du calcul des Exonérations lors de la création du RP

**Comment by jpklipfel** [comment]
Est ce c'est corrigé dans la version 1.4?

**Comment by jpklipfel** [comment]
Nous sommes les seuls à rencontrer ce pb?

**Comment by ghost** [comment]
Je n'ai pas rencontré ce cas, @MaelREBOUX , @jusabatier vous avez déjà eut ce cas ?
J'ai revérifié le code de cette partie, je ne pense pas que cela vienne du cacul de l'exonération, il n'y a eut que très peu de changement dans cette partie entre la 1.3 et la 1.4, mais ça vaut toujours le coup de passer en 1.4. Il y a eut quelques amélioration du RP.
https://github.com/georchestra/cadastrapp/wiki/Releases

**Comment by MaelREBOUX** [comment]
Bjr Jean-Pascal.

Qqs questions :
1. La "disparition" concerne-t-elle des propriétés bâties et/ou non bâties ?
2. T'est-il possible de tester la version 1.4 de cadastrapp pour voir si ce bogue perdure ?
3. "Les sous groupes S ne remontent pas" : c'est-à-dire ? (Pr tenter de trouver un cas identique)

**Comment by jpklipfel** [comment]
1. Que des propriétés non bâties on dirait (2ème partie du RP)
2. Pas dans l'immédiat (par contre je peux voir pour fournir un mini dump anonymisé s'il existe une plateforme de test en 1.4)
3. C'est sur le RP de l'autre outil qui nous sert de comparaison
![image 1](https://user-images.githubusercontent.com/5012040/31618823-44025cc4-b293-11e7-905a-7f3647b0aa96.png)

**Comment by pierrejego** [comment]
J'ai fait des tests sur la version 1.4 et la future 1.5. Mais je ne reproduis pas, j'ai bien le même nombre de propriétés non batie dasn mes RP que de parcelle dans l'addons.
Je ne vois aucune modification dans le code qui aurait pu changer ce comportement. Je sèche, par contre je peux prendre un dump anonymisé et tester sur une 1.4. Il faudra retrouver le cas en question.

**Comment by jpklipfel** [comment]
On va bientôt passer sur du 1.4 on vous dira ce que cela donne

**Comment by pierrejego** [comment]
C'est noté, n'hésitez pas à revenir vers moi si besoin maintenant que j'ai des environnements disponible sous la main.

**Comment by MaelREBOUX** [comment]
@jpklipfel on vient de sortir la version 1.5 avec Majic 2017. Il serait bon que vous migriez sur cette version et nous rapporter si vous rencontrez encore ce problème.

**Comment by jpklipfel** [comment]
Oui on suivra ça avec @pmauduit

**Comment by jpklipfel** [comment]
>@jpklipfel on vient de sortir la version 1.5 avec Majic 2017. Il serait bon que vous migriez sur cette version et nous rapporter si vous rencontrez encore ce problème.

Testé avec succès sur la nouvelle version, merci à tous!
