### ISSUE TITLE
[AddOn] Recherche des parcelles - Affichage du résultat

### ISSUE THREAD

**Issue by catmorales** [georchestra/cadastrapp#37]
Le résultat de la recherche de parcelle est une liste de parcelles.
![image](https://cloud.githubusercontent.com/assets/4659829/9173745/6c2b6600-3f7c-11e5-9b2f-91b8baa7a448.png)
- Lors de l'affichage de cette liste, les parcelles sélectionnées sont en jaune mais  il n'y a pas dans la carte de recentrage sur ces parcelles donc on ne les voie pas toujours.
- Lors du clic sur une parcelle de la liste, il y a zoom sur l'ensemble des parcelles  et passage en bleu de la parcelle sélectionnée, puis la fiche d'information de la parcelle s'ouvre.
  Erreur http 500
  ![image](https://cloud.githubusercontent.com/assets/4659829/9174078/469adb94-3f7e-11e5-9f31-0365fbd3676c.png)

Nous suggérons des adaptations de l'ergonomie (à discuter ensemble):
- centrage automatique sur l'ensemble des parcelles listées lors de l'ouverture de la liste des parcelles (fenêtre  sélection de parcelles)
- ajout  d'un bouton de zoom sur chaque parcelle
  - soit en face de chaque ligne dans la fenêtre sélection de parcelles
  - soit à côté du bordereau parcellaire dans la fenêtre d'info de la parcelle.

**Comment by pierrejego** [comment]
Les erreurs 500 n'apparaissaient que sur le modèle Arcopole et ont été corrigé ce matin.

Pour le recentrage automatique et lors d'un clique sur une parcelle, j'attends votre retour

**Comment by MaelREBOUX** [comment]
lier à #50

**Comment by MaelREBOUX** [comment]
/!\ ne pas tenir compte de la description du comportement des interactions qui n'est plus à jour (plus d'interactions).
1. rajouter dans la fenêtre de sélection de parcelles un bouton "Zoom sur la sélection courante" au même niveau que le bouton "fermer" mais aligné à gauche
2. rajouter dans la fenêtre de sélection de parcelles un bouton "Zoom sur la liste" au même niveau que le bouton "fermer" mais aligné à gauche
3. comportement des onglets de la fenêtre de sélection de parcelle
   Si on change d'onglets (pas fonctionnel ce jour) il convient de sélectionner / colorer / mettre en surbrillance les parcelles sélectionnées dans l'onglet courant  => à arbitrer avec ticket ? sur le comportement des onglets.
4. ouverture de la fiche d'info par double-clic (et pas simple clic) sur la liste des parcelles
5. le simple clic entraîne une sélection de la ligne. Sert aux fonctions de sélection dans la liste.
6. rajouter un bouton "Enlever de la liste" (en bas de la fenêtre aligné à gauche, à côté des boutons Zoom sur..." qui permet de supprimer une entrée de la liste de sélection des parcelles
7. rajouter un bouton "Exporter la liste" -> correspond à l'item de menu Traitement de la sélection > Parcelles > Export liste CSV
8. rajouter en bas un bouton "Ouvrir la fiche d'infos" pour rester cohérent

**Comment by MaelREBOUX** [comment]
lié à #61

**Comment by catmorales** [comment]
Une maquette simple de ce que l'on a décrit ci-dessus donnerait quelque chose comme ce qui est illustré ci-dessous.
J'ai rajouté un _(s)_ à enlever parcelles si  l'on maintient la possibilité de sélectionner plusieurs parcelles à la fois (touche shift) (et donc de les supprimer de la liste) mais dans ce cas quel serait le comportement de l'ouverture de la fiche d'info en cas de sélection multiple: ouverture de plusieurs fiches d'infos ?

![image](https://cloud.githubusercontent.com/assets/4659829/10069273/594a1b06-62ab-11e5-98d8-1fe829bca066.png)

_Note:_ ce matin, testé sur plateforme de qualification, je n'ai plus du tout de zoom automatique sur les parcelles mais c'est peut être en cours de correction...

**Comment by landryb** [comment]
On veut bien permettre la selection multiple d'items dans la liste résultant de la selection, pour:
- pouvoir zoomer sur un ensemble de parcelles
- supprimer cet ensemble de la selection
- ouvrir la fiche d'info pour toutes ces parcelles (comportement actuel quand on selectionne plusieurs via une geometrie)

le bouton 'zoom liste' correspond a "zoomer sur l'ensemble du resultat de recherche"

**Comment by catmorales** [comment]
OK, donc en toute logique on doit rajouter un (s) dans le bouton à Fiche d'info parcelle(s) ;)

**Comment by pierrejego** [comment]
Modification effecutée, disponible sur la machine https://cadastrapp-qualif.asogfi.fr/mapfishapp/
