### ISSUE TITLE
Erreur de build v1.5

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#370]
J'ai tenté un build de la v1.5 : 
`mvn clean install`

Mais celui-ci echoue visiblement à cause de validations Javadoc : 

```
22 errors
93 warnings
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Addons Cadastre pour georchestra ................... SUCCESS [  1.434 s]
[INFO] Cadastrapp webapp .................................. FAILURE [ 17.219 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.059 s
[INFO] Finished at: 2017-11-20T10:11:19+01:00
[INFO] Final Memory: 25M/275M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.3:javadoc (build-javadocs) on project cadastrapp: An error has occurred in JavaDocs report generation:
[ERROR] Exit code: 1 - /home/jusabatier/Workspace/cadastrapp_v1.5/cadastrapp/src/main/java/org/georchestra/cadastrapp/repository/RequestRepository.java:25: warning: no description for @param
[ERROR] * @param cni
[ERROR] ^
[ERROR] /home/jusabatier/Workspace/cadastrapp_v1.5/cadastrapp/src/main/java/org/georchestra/cadastrapp/repository/RequestRepository.java:26: error: unknown tag: InformationRequest
[ERROR] * @return List<InformationRequest>
...
```

**Comment by pierrejego** [comment]
Bonjour,
oui j'ai eut la même erreur, tu dois builder ça vient de l'utilisation de java8 à la place de java7 pour builder.
 
J'ai prévu de refaire la javadoc dans la version 1.6 (qui commence Jeudi) pour qu'elle soit compatible avec java 1.8
En attendant il faut builder en java 1.7

**Comment by pmauduit** [comment]
Il y a une option à passer à maven / Javac afin de désactiver les vérifications sur la Javadoc, ca doit etre l'option `-Xdoclint:none`.

**Comment by jusabatier** [comment]
Je viens de tester avec : 
`mvn clean install -Xdoclint:none`

Et ça ne marche pas non plus : 
```
[ERROR] No plugin found for prefix 'doclint' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/jusabatier/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
org.apache.maven.plugin.prefix.NoPluginFoundForPrefixException: No plugin found for prefix 'doclint' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/jusabatier/.m2/repository), central (https://repo.maven.apache.org/maven2)]
	at org.apache.maven.plugin.prefix.internal.DefaultPluginPrefixResolver.resolve(DefaultPluginPrefixResolver.java:95)
	at org.apache.maven.lifecycle.internal.MojoDescriptorCreator.findPluginForPrefix(MojoDescriptorCreator.java:265)
	at org.apache.maven.lifecycle.internal.MojoDescriptorCreator.getMojoDescriptor(MojoDescriptorCreator.java:219)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleTaskSegmentCalculator.calculateTaskSegments(DefaultLifecycleTaskSegmentCalculator.java:104)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleTaskSegmentCalculator.calculateTaskSegments(DefaultLifecycleTaskSegmentCalculator.java:83)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:89)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

J'avoue qu'il aurait été bien pratique de pouvoir désactiver cette verif.

Aussi si les releases sont figées, ne serait-il pas judicieu de fournir en plus des sources une archive contenant le war+zip addon ?

**Comment by jusabatier** [comment]
L'option à passer est : `-Dmaven.javadoc.skip=true`

**Comment by pmauduit** [comment]
Bizarre, sans avoir à passer aucune option, j'ai pu builder la branche master actuelle (je suis en Java 8 OpenJDK) ; pour revenir à la stacktrace précédente, cela est du au fait que Maven intercepte l'option avant la JVM, apparemment il faut la passer au niveau du pom.xml:

```
<properties>
    <additionalparam>-Xdoclint:none</additionalparam>
</properties>
```

**Comment by MaelREBOUX** [comment]
Hum : je perçois un comportement différent selon qu'on est en Java 8 Oracle ou Java 8 OpenJDK ?

Du coup j'ai l'impression que même la doc geOrchestra n'indique aucun prérequis sur la version de Java. Est-ce un pb ?

> Aussi si les releases sont figées, ne serait-il pas judicieu de fournir en plus des sources une archive contenant le war+zip addon ?

Bonne question.

**Comment by pierrejego** [comment]
> Aussi si les releases sont figées, ne serait-il pas judicieu de fournir en plus des sources une archive contenant le war+zip addon ?

Est-ce que vous savez si il y a un nexus georchestra quelque part ? ça serait la meilleur place pour les mettre je pense.
On doit peut être pouvoir déposer ça là https://packages.georchestra.org/maven/repository, mais je n'ai pas les droits.  @pmauduit et @fvanderbiest  c'est un nexus ? il est possible d'avoir un droit d'accès dans un sous-répertoire (org.georchestra.cadastrapp) pour déposer les releases ?

**Comment by pmauduit** [comment]
> Est-ce que vous savez si il y a un nexus georchestra quelque part ? ça serait la meilleur place pour les mettre je pense.

Ce n'est pas un nexus, mais un dépot de jars sourcés apres un build maven (ceci pour notamment répondre aux problématiques de dépendances qui n'existent pas ou plus sur les dépots officiels, et aussi permettre un téléchargement "fiable", étant donné que - comme souvent - dans les dépots java lié aux logiciels en geospatial, beaucoup de dépendances sont hébergées sur des dépots tiers sur lesquels nous n'avions pas forcément la main, qui disparaissaient pendant quelques jours puis réapparaissaient, passaient en SSL avec une redirection depuis http qui faisait planter le téléchargement depuis maven), si tu as les fichiers quelquepart, on peut les mettre dessus.

**Comment by jusabatier** [comment]
Problème toujours présent sur master, donc en 1.6

**Comment by pierrejego** [comment]
Oui je n'ai pas encore touché à la javadoc, ça va venir bientôt

**Comment by MaelREBOUX** [comment]
@pierrejego est-ce que ce ticket concerne également la v 1.6 ? Faut-il changer le milestone ?

**Comment by jusabatier** [comment]
L'erreur de compilation est toujours présente en v1.6

Il est necessaire de passer l'option `-Dmaven.javadoc.skip=true`
