### ISSUE TITLE
Liste des lots et locaux d'un batiment - PDF et CSV

### ISSUE THREAD

**Issue by pierrejego** [georchestra/cadastrapp#371]
Cette évolution permettra d'export la liste des lots et locaux d'un bâtiment ( en cas de copropriété)

L'export sera généré après que l'utilisateur soit passé par une fenêtre modal, permettant de choisir
le type d'export (CSV ou PDF) ainsi que le bâtiment souhaité (si plusieurs bâtiments présent sur la parcelle)

**Comment by pierrejego** [comment]
Link to PR #377 

Il y a encore deux poins a voir.

1 - le tri de par numéro de lot par ordre numérique et non alphabétique
2 - une optimisation de la récupération des propriétaires pour chaque lot, qui ne pose pas de problème avec moins d'une dizaine de lots, mais qui peut prendre jusqu'a 30 secondes quand on a une centaine de lots

**Comment by pierrejego** [comment]
Note pour plus tard
dans arcopole id_local = invar mais dans Qgis id_local = codedep+invar
Voir comment optimiser ça pour enlever le champ id_local.

**Comment by MaelREBOUX** [comment]
Testé sur master hier.

Quand on veut consulter les lots directement depuis la fiche info parcelle, UI déroutante pour le choix du bâtiment : ne sert à rien car il faut d’abord sélectionner le bâtiment dans la fiche info parcelle. La liste ne sert donc à rien.

![screenshot182](https://user-images.githubusercontent.com/6370443/36200102-dc34b6bc-117b-11e8-82d8-09a302b1059f.png)

Cette liste sert en revanche quand on veut faire l'export des lots depuis la fenêtre de sélection de parcelles.

![screenshot183](https://user-images.githubusercontent.com/6370443/36200125-ef1a3e96-117b-11e8-8a08-9242761bea62.png)

=> **Possible de masquer la liste quand on demande la génération depuis la fiche infos parcelle ?**

**Comment by MaelREBOUX** [comment]
Concernant le PDF généré.

Sur la fenêtre intermédiaire : **mettre PDF en premier et par défaut.**

Données semblent OK d’après ce que j’ai pu vérifier par rapport à VisuDGFiP. Pas été tester les requêtes en base.

Tantièmes OK

**Tri alpha et pas numérique sur les numéros de lots.** Embêtant ça.

Concernant l'export CSV : RAS : ça me convient (c'est bien du point-virgule ?).

**Comment by MaelREBOUX** [comment]
- [X] choix PDF en premier : ok
- [X] pas de liste quand ouverture depuis onglet locaux : ok
- [x] tantièmes
- [ ] Tri alpha et pas numérique sur les numéros de lots
- [x] export CSV : point-virgule
- [x] export CSV : pb dans le nom de l'attribut "local_commerciale"  -> "local_commercial"

**Comment by MaelREBOUX** [comment]
On reporte l'histoire du tri -> #393

A tester avant de fermer.

**Comment by MaelREBOUX** [comment]
Testé et approuvé.
