### ISSUE TITLE
Export RP en CSV

### ISSUE THREAD

**Issue by pierrejego** [georchestra/cadastrapp#378]
Il est demandé le développement d’un nouvelle fonction permettant à l’utilisateur de pouvoir demander le téléchargement de 3 fichiers CSV correspondants aux 3 blocs d’information du relevé de propriété :
propriétaires
propriétés bâties
propriétés non bâties

Ces 3 fichiers seront générés côté serveur et encapsulé dans un ZIP pour effectuer 1 seul téléchargement.

La commande permettant cet export sera rajoutée dans le traitement des sélections de la recherche avancée.

**Comment by pierrejego** [comment]
@MaelREBOUX et @jusabatier  

J'ai commencé les exports, mais comme je le disais à Catherine, est-ce qu'il faut rajouter deux fichiers pour la partie imposition ?
Et est-ce que dans l'export, il faut garder les valeurs d'imposition par C,GC,TSE etc ainsi que les exonérations ?  Et si oui, est-ce que je rajoute des colonnes pour chacun, ou est-ce que je duplique les lignes comme dans le RP ?

Deuxième question, j'ai commencé à utiliser la lib openCSV. Elle est sous licence apache2, c'est bien compatible avec geOrchestra ?  http://opencsv.sourceforge.net/license.html

**Comment by landryb** [comment]
C'est pas plus simple d'avoir une api par fonction, et un menu déroulant permettant d'exporter qu'un seul des fichiers, plutot que de les bundler ensemble dans une fonction/zip ? je pense au cas ou la base est grosse, si tu fais 5 requetes 'lourdes' à la suite puis tu zippe le tout avant d'y renvoyer, ca va prendre plus de temps (vu de l'utilisateur) que 5 requetes distinctes, potentiellement faisables en parallèle...

**Comment by pierrejego** [comment]
Non c'est pas plus simple, la je vais reprendre le même objet que pour générer le PDF du RP. Je vais juste faire des csv et un zip au lieu du PDF. ça devrait prendre presque le même temps que le RP actuelle (mais je crois que chez toi c'est long ....)

**Comment by MaelREBOUX** [comment]
Point tel fait avec @pierrejego ce matin.

Les attributs des bases d'impositions seront mis dans des colonnes distinctes pour éviter de multiplier les linges par 3.

Il faut régler la question de compatibilité de licence également.

**Comment by MaelREBOUX** [comment]
Testé sur master hier.
Données OK d’après ce que j’en vois.

Séparateur virgule alors qu’on point-virgule pour export lots, parcelles, proprios -> **point-virgule pour homogénéiser ?**

**Comment by MaelREBOUX** [comment]
Point-virgule OK. Je ferme.
