### ISSUE TITLE
[AddOn ] Affichage des info bulles

### ISSUE THREAD

**Issue by catmorales** [georchestra/cadastrapp#38]
![image](https://cloud.githubusercontent.com/assets/4659829/9174462/30547262-3f80-11e5-95c9-484f66db97d8.png)
Les noms associés au boutons ne nous semblent pas explicites et n'indiquent pas qu'il s'agit de l'activation des info-bulles. Il manque les info-bulles sur ces deux boutons

**Comment by pierrejego** [comment]
Même issue que la #33 
Un tooltip a été ajouté pour améliorer la compréhension, et les labels des checkbox sont modifiables dans le manifest.json 
cadastrapp.cadastre
et
cadastrapp.foncier

Les textes explicatifs sont eut modifiable aussi dans le manifest.json
clés cadastrapp.menu.tooltips.foncier et cadastrapp.menu.tooltips.cadastre

Pour rappel, ces boutons servent  afficher soit les informations foncières soit les informations cadastrales, soit les deux. Différentes fenêtres s'ouvrent lorsque vous avez sélectionné une parcelle, et les information de l'infobulle lorsque vous survolez une parcelle sont différentes.
