### ISSUE TITLE
[model] Index manquant sur le code proprio sur la table proprietaire

### ISSUE THREAD

**Issue by spelhate** [georchestra/cadastrapp#381]
Il manque un index sur la table proprietaire pour le champ comptecommunal. Avec la création de cet index, l'affichage des propriétaires passe de 10 secondes à quelques millisecondes pour 4 départements.
https://github.com/georchestra/cadastrapp/blob/f72c2171a71f1032192712ccad302bff41daee8f/script/commun/index.sql#L12

**Comment by landryb** [comment]
Hmmm tu m'interesses :) a lier avec #376 ?

**Comment by MaelREBOUX** [comment]
Je confirme :

![screenshot155](https://user-images.githubusercontent.com/6370443/35798036-e565f460-0a61-11e8-848c-fe1ef0902992.png)

**Comment by landryb** [comment]
Effectivement, ca blaste..

```
cadastrapp=> create index idxproprietairecomptecommunal on cad2017aura.proprietaire(comptecommunal);
CREATE INDEX
cadastrapp=> \di+ cad2017aura.idxproprietairecomptecommunal 
                                           List of relations
   Schema    |             Name              | Type  |   Owner    |    Table     |  Size  | Description 
-------------+-------------------------------+-------+------------+--------------+--------+-------------
 cad2017aura | idxproprietairecomptecommunal | index | cadastrapp | proprietaire | 261 MB | 
(1 row)
```

Pour un appel getFic?onglet=1 (les proprios donc) je passe de ~13s a 300ms. Merci @spelhate :)

**Comment by landryb** [comment]
Si tu en as encore des comme ca, je prends :)

**Comment by spelhate** [comment]
De nada @landryb.

**Comment by spelhate** [comment]
J'en ai un autre qui améliore nettement les perfs du service getBatiment. mais c'est moins spectaculaire que pour les proprios  : champ parcelle de la table proprietebatie ;-)

**Comment by landryb** [comment]
Et cette fois un getBatiment ici passe de 5s à .. oh, 20ms :)

```
cadastrapp=> create index idxproprietebatieparcelle on cad2017aura.proprietebatie(parcelle);
CREATE INDEX
cadastrapp=> \di+ idxproprietebatieparcelle 
No matching relations found.
cadastrapp=> \di+ cad2017aura.idxproprietebatieparcelle 
                                          List of relations
   Schema    |           Name            | Type  |   Owner    |     Table      |  Size  | Description 
-------------+---------------------------+-------+------------+----------------+--------+-------------
 cad2017aura | idxproprietebatieparcelle | index | cadastrapp | proprietebatie | 322 MB | 
```

**Comment by landryb** [comment]
Mais ce dernier  avait déja été rajouté recemment, cf 6b0dcbe8ad04674dab0932788618fa94e04c10cf

**Comment by landryb** [comment]
Il manquerait aussi des index sur `uf_parcelle`, cf #376

**Comment by pierrejego** [comment]
Merci à tous les deux, je dois regarder la uf bientôt pour refaire l'IHM et l'impression, je regarderai les indexes en même temps
