### ISSUE TITLE
IE  GEOR.Addons.Cadastrapp namespace should be definied

### ISSUE THREAD

**Issue by jpklipfel** [georchestra/cadastrapp#387]
Message d'erreur à l'ouverture de Mapfishapp
>GEOR.Addons.Cadastrapp namespace should be definied

(sous Internet Explorer 11)

>Cela signifie qu'il y a une erreur de syntaxe dans le code JS de cadastrapp.
Cela peut etre un ; manquant ou une virgule en trop dans un objet...
A priori dans https://raw.githubusercontent.com/georchestra/cadastrapp/master/addons/cadastrapp/js/main.js

**Comment by pierrejego** [comment]
Bonjour,
Est-ce que je peux avoir un peu plus d'information sur l'erreur ?  Je ne la reproduis pas chez moi.
Est-ce que c'est uniquement sur IE 11 ?

Vous êtes sur le master, mais en mode debugjs ? C'est une installation sur un poste de développement ou sur une pf de production ?

Pour information, le master n'est pas la dernière version stable, mais la dernière version en cours de développement.

**Comment by jpklipfel** [comment]
>Est-ce que c'est uniquement sur IE 11 ?

De mon côté oui (testé sous FF et Chrome)

C'est une installation sur un poste de développement

Pour le mode debugjs je ne sais pas répondre

**Comment by pierrejego** [comment]
Je n'ai pas d'IE 11 pour tester, je n'ai pas de soucis avec EDGE.
Est-ce qu'il y a beaucoup d'IE 11 dans votre parc informatique ?

Est-ce que vous avez un problème avec les autres addons de mapfishapp aussi ou seulement avec celui là ?

**Comment by jpklipfel** [comment]
>Est-ce qu'il y a beaucoup d'IE 11 dans votre parc informatique ?

oui

>Est-ce que vous avez un problème avec les autres addons de mapfishapp aussi ou seulement avec celui là ?

Le message d'erreur mentionne bien cadastrapp

**Comment by landryb** [comment]
Pareil avec d'autres versions de IE, on commence a avoir des remontées d'utilisateurs dans les mairies avec ce soucis (ou j'imagine c'est du windows xp avec de l'IE7 ou équivalent). Evidemment on leur dit de passer sur un vrai navigateur, mais c'est pas la solution idéale... avoir au moins les IE 'récents' supportés serait un plus :)

**Comment by MaelREBOUX** [comment]
Bonjour,

Pour moi c'est un problème global à geOrchestra. Je milite pour que l'on rajoute un test de version de navigateur dans le header. Je vois pas comment faire autrement.

Si vous êtes d'accord @jusabatier @pierrejego @landryb  je ferme ce ticket et j'en ouvre un autre spécifique dans le dépôt geOrchestra en demande d'évolution.

**Comment by MaelREBOUX** [comment]
Pour info : on a beau mettre ça en page d'accueil, tant que l'utilisateur se prend pas un message en modal-qui-bloque-tout...

![image](https://user-images.githubusercontent.com/6370443/38246111-f6d925bc-3740-11e8-9d81-9007dbb80212.png)

**Comment by landryb** [comment]
> Si vous êtes d'accord @jusabatier @pierrejego @landryb je ferme ce ticket et j'en ouvre un autre spécifique dans le dépôt geOrchestra en demande d'évolution.

Je ne suis pas d'accord. Autant ces navigateurs sont de la m*****, autant IE 11 est toujours censé être supporté par microsoft, donc plutot que le bannir, il faudrait le supporter correctement au moins dans cadastrapp.. a ma connaissance mfapp marche avec IE11.

**Comment by pierrejego** [comment]
Bonjour,
je viens d'installer IE11 sous Windows 10. Et je n'ai aucun problème à utiliser l'addons cadastrapp, pas de message sur le namespace. Quelques warnings dans la console sur des paranthèses attendues, mais tout fonctionne.

Je vais essayer sur un windows 7. 

Vous pourriez me donner une des confs complète ou cela ne marche pas ? C'est bien à l'ouverture de mapfishapp que ça bug ? le module cadastrapp est pré-chargé ?

**Comment by MaelREBOUX** [comment]
Oui : Mapfishapp fonctionne correctement avec IE11.
De mémoire Cadastrapp fonctionne correctement également.
On a un blocage sur un autre add-on et du coup on l'a banni. Sinon on s'en sort pas en terme de support.

Sur le fond : on a déjà eu ce message mais me souviens plus du contexte dans lequel ça apparaît. De mémoire ne concerne que IE 11 et que comme on dit qu'on le supporte pas...

**Comment by pwernert** [comment]
Pour poursuivre la discussion du ticket [#413](https://github.com/georchestra/cadastrapp/issues/413)

Avec https://www.geograndest.fr/mapfishapp/?debug=1 sous IE j'obtiens :

![image](https://user-images.githubusercontent.com/37657174/45828581-28ab6580-bcf9-11e8-9122-6f56b5d97ddf.png)

**Comment by landryb** [comment]
Merci beaucoup, on progresse!

Pour la première erreur [ici](https://github.com/georchestra/cadastrapp/blob/master/addons/cadastrapp/js/printRelevePropriete.js#L21) j'ai l'impression que IE n'aime pas qu'une valeur par défaut soit donnée à un paramètre d'une fonction, cf [la doc mozilla](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Fonctions/Valeurs_par_d%C3%A9faut_des_arguments#Compatibilit%C3%A9_des_navigateurs) . - Facile a corriger.

Pour la deuxième erreur la syntaxe [ici](https://github.com/georchestra/cadastrapp/blob/master/addons/cadastrapp/js/resultParcelle.js#L14) ne semble pas plaire a IE (et pareil sur les lignes suivantes):
```
{
            text:OpenLayers.i18n("cadastrapp.result.csv.button.parcelles"),
            showSeparator:false,
            handler(){
                return GEOR.Addons.Cadastre.exportPlotSelectionAsCSV();
            },scope:this
}
```
ca ne me surprend pas plus que ca, car pour `handler` il n'y a pas d'assignation à une variable. @pierrejego - facile a corriger celui la, mais je ne sais pas quelle est sensée être le nom de la variable.

**Comment by landryb** [comment]
Ah, le paramètre doit juste s'appeler `handler`. @pwernert si jamais tu as moyen de tester avec landryb/cadastrapp@619a7cbe .. ca permettra de savoir si le pbm est corrigé. C'est un fix rapide pas vraiment testé, mais ca peut pas être pire.

**Comment by pierrejego** [comment]
Merci pour le boulot,
je reproduis toujours pas, je ne peux donc pas tester ta correction, mais je vais au moins tester qu'il n'y a pas d'effet de bord sur l'existant :)

**Comment by gryckelynck** [comment]
Bonjour Pierre,
Je reproduis bien l'erreur (pas encore testé le correctif de Landry, Pauline voit ça avec Camtocamp).
Voici ma configuration:
- IE 11.483.15063.0 / Version des mises à jour: 11.0.44
- Windows 10 Professionnel / Version 1703 / 15063.483
L'URL testée: https://www.geograndest.fr/mapfishapp/

**Comment by pwernert** [comment]
Bonjour, le correctif n'a pas été intégré dans le code de cadastrapp, serait-il possible que l’équipe en charge de cadastrapp intègre le correctif dans master et la backporte vers les versions 1.5 et 1.6 ?

**Comment by landryb** [comment]
Pour moi, ce n'est pas comme ca que ca marche.. d'abord, vous le testez pour s'assurer qu'il corrige bien le problème pour vous, et si c'est le cas il est intégré dans master. Il n'y a actuellement pas de branches de maintenance dans tous les cas.

**Comment by fvanderbiest** [comment]
Salut Landry, je me permets d'intervenir ici :-)
Ton patch est correct, tu peux le merger à mon avis.
Du coup, il faudra que nous déployions cadastrapp master pour GeoGrandEst.

**Comment by MaelREBOUX** [comment]
Bonjour : pour le coup je suis d'accord avec Landry. Je propose que GéoGrandEst teste manuellement le patch https://github.com/landryb/cadastrapp/commit/619a7cbe 

Si c'et OK : on merge immédiatement. OK @gryckelynck  et @pwernert ?

**Comment by fvanderbiest** [comment]
Le test du patch sur https://www.geograndest.fr/mapfishapp/ est concluant.
Merci à Landry pour ses investigations sur le problème !

**Comment by landryb** [comment]
#421 mergée
