### ISSUE TITLE
Modification du style de sélection par un utilisateur

### ISSUE THREAD

**Issue by pierrejego** [georchestra/cadastrapp#388]
Laisse à l'utilisateur la possibilité de choisir le style des sélections et des sélections actives.

Ce choix se fera par un nouvelle entrée dans le menu principal de l'application, il sera possible de choisir : 
- la couleur de remplissage
- la couleur du contour
- l'épaisseur du contour
- l'opacité générale du style

Une fois ce choix fait, il sera sauvegardé dans le localstorage pour être réutilisé à chaque fois.
Ce style sera visible dans le navigateur ainsi que dans les exportes (BP et UF)

**Comment by pierrejego** [comment]
Actuellement, il y a trois types de couleur : 
- parcelle dans la liste
- parcelle sélectionné
- parcelle dont une fenêtre d'information cadastrale est ouverte

Vu avec @jusabatier  et @MaelREBOUX ce dernier type de sélection sera supprimé car non utilisé.

Il ne restera que les deux sélections (dans la liste et active)

**Comment by landryb** [comment]
Pourquoi non utilisé ? Il avait bien été demandé a un instant...

Et je peux comprendre le besoin de la personne ayant X parcelles selectionnées, et 2 fenetre d'infos ouvertes, pour retrouver a quelles parcelle ca correspond et faire la distinction.

**Comment by jusabatier** [comment]
Actuellement, la troisième option n'a pas un comportement pertinent : 

Si on ouvre un première fiche d'info, alors la parcelle correspondante passe en vert.
Si on en ouvre une deuxième la parcelle de la première repasse en jaune et celle de la deuxième passe en vert.

Aussi généralement les utilisateurs ouvrent la fiche d'info au besoin et ne la garde pas de coté pour consultation ulterieure, ce qui dans la pratique implique que seule la parcelle consultée soit sélectionnée (soit via double clic, soit pour bouton ouvrir fiche d'info).

La consultation de plusieurs fiches d'info en simultané me semble difficile vu la place sur l'écran occupé par celles-ci, si on en a deux d'ouvertes on ne voit plus la carte, donc aucun interet a avoir une couleur de sélection en plus à mon avis.

Enfin cela compliquerait l'option de definition des styles en cours de développement pour un résultat au final très peu utile en pratique.

**Comment by landryb** [comment]
Avec la justification, c'est bien plus clair, merci :) Ok pour moi. Je demande la justification, parce qu'il faut que la doc suive..
