### ISSUE TITLE
[UF] Problème table sous QGis

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#389]
Je viens d'installer une version issue de master avec les UF sur un serveur de dev.

En essayant d'interroger une UF, j'ai ce message : 

> Une erreur est survenue.
> Le serveur a renvoyé une exception.
> Illegal property name: shape for feature type pci:geo_unite_fonciere 

Ma couche pci:geo_unite_fonciere est basée sur la couche du modèle QGis qui a le même nom.

**Comment by pierrejego** [comment]
Je pense qu'il faut que tu changes la configuration dans le manifest.json et mettre geom au lieu de shape dans
  "UFWFSLayerSetting":{  
            "request":"getfeature",
            "version":"1.0.0",
            "service":"wfs",
            "outputFormat":"application/json",
            "geometryField":"geom"
        },

Dis moi si c'est bien ça le problème.

**Comment by jusabatier** [comment]
Ce problème là est bien résolu.
