### ISSUE TITLE
[AddOn 005.008] Recherche par adresse cadastrale:type de la voie

### ISSUE THREAD

**Issue by catmorales** [georchestra/cadastrapp#39]
- Absence de type de voies : rues, allée,...Si on tape LAE (pour LAENNEC) on doit avoir dans la liste **BD** RENE LAENNEC et non pas RENE LAENNEC,
- la taille dans le formulaire du cadre d'adresse sera du coup trop petite,
- pas d'auto complétion sur les lieux-dits.

**Comment by pierrejego** [comment]
@catmorales  Nous avons compris que vous souhaitez ajouter le type de voie dans l'affichage du nom de voie.

C'est bien ça ?

**Comment by landryb** [comment]
Ie dans le cas ou il y'a 3 lieux avec le meme nom (place machin, rue machin et bvd machin) que ca permette de les distinguer plutot qu'afficher 3 fois 'machin' dans la liste de selection ?

**Comment by MaelREBOUX** [comment]
Exactement : 
![screenshot020](https://cloud.githubusercontent.com/assets/6370443/11148408/e708e65a-8a1c-11e5-8029-9a7cc5b3f99b.png)

C'est plus que "enhancement" ici.
Il y a une zone grise dans le bas de la fenêtre qui vient manger l'exemple. A raffiner.
cf #45 également

**Comment by MaelREBOUX** [comment]
@catmorales changer le titre en "Recherche par adresse cadastrale : type de la voie"

**Comment by MaelREBOUX** [comment]
@pierrejego : changer le titre en "Recherche par adresse cadastrale : type de la voie"

Ticket tjs valide.
Penser également à changer le label "N de voirie et type:" par "n° / complément".

Tant qu'on y est : passer cette ligne en dernier dans le formulaire pour avoir une recherche en entonnoir :  commune > voie > adresse

**Comment by catmorales** [comment]
ticket toujours d'actualité je ne le ferme pas
