### ISSUE TITLE
[UF] Problème ouverture fiche

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#391]
Lorsque j'active l'outil Unite Foncière, en cliquant sur une unité foncière, j'ai un nouvel onglet qui s'ouvre sur l'URL : /mapfishapp/ws/addons/cadastrapp/html/ficheUniteFonciere.html

Cette page s'affiche en html (non interprété), c'est à dire que je vois réellement le code.
Testé sous Firefox 52.

Deplus dans le html qui s'affiche, on a aucune info sur l'UF cliquée, et aucun parametre n'est fourni ni en GET, ni en POST.

**Comment by pierrejego** [comment]
Bonjour,
normalement ça n'arrive que si tu n'as pas ce commit dans la partie mapfishapp https://github.com/pierrejego/georchestra/commit/3298d2f949926245e1c417969b16c3f3e6563f81

Est-ce que tu as bien mis à jour mapfishapp pour que l'addon puisse ouvrir des pages html ?

**Comment by jusabatier** [comment]
En effet, lorsque j'avais compilé mon mapfishapp le commit n'avait pas encore été appliqué sur 17.12

Maintenant ça marche très bien, juste une interrogation, est-ce voulu de voir le curseur de sélection dans l'image générée sur la fiche UF ?

**Comment by pierrejego** [comment]
Non le curseur devrait être effacé c'est étrange, je ne l'ai pas chez moi.

**Comment by MaelREBOUX** [comment]
Je ne l'ai pas non plus. Peut-on fermer ce ticket @jusabatier  ?

**Comment by jusabatier** [comment]
Oui problème résolu, ça venait en effet du commit qui manquait.
