### ISSUE TITLE
[UF] Retours sur fiche UF et export CSV

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#392]
Voivi mes retours après test de la fonctionalité de fiche UF : 

- On ne voit pas apparaitre de mention de la date de l'extraction du cadastre utilisée comme sur les BP/RP, ni de mentions légales concernant la DGFiP (copyrigth)

- Seule la surface est détaillée, on a pas le detail de la surface batie

Pour l'export CSV : 

- Certains champs adresse devraient subir un TRIM afin de supprimer les espaces superflus

- Au niveau de l'export RP-Batie, j'ai constaté une erreur d'encodage : "D?pendance commerciale", j'ai ouvert le fichier en UTF8

**Comment by jusabatier** [comment]
Il nous a également été signalé qu'il serait interessant d'avoir le pourcentage de bati par rapport à la surface totale.

**Comment by pierrejego** [comment]
Ok pour les exports CSV je vais regarder, j'ai rajouté des TRIMS pour Arcopole dans la base, mais j'avais pas vu d'espace dans la partie QGIS. Tu pourras me donner les entêtes dans les csv pour que je puisse aller faire la modification en base ?

Je vais revérifier la partie encodage demain, j'ai peut être oublié quelques choses.

Pour la partie UF, je dois pouvoir rajouter le pourcentage bati et surface totale.

Par contre, pour les mentions légales et les surfaces détailleées il faudra qu'on en reparle, ce n'était pas dans la demande initiale et il va falloir que je fasse un nouvel appel voir un nouveau service côté serveur pour récupérer les informations. A moins qu'on rajoute les informations dans le manifest, ou dans le service de configuration .

**Comment by jusabatier** [comment]
Pour les trim : 

- Batie / Non Batie : dvoilib
- Propriétaire : adresse

Pour les surfaces détaillées, c'était juste une piste, je ne sais pas si c'est utile en pratique.

Pour les mentions légales, il me semble qu'elles sont obligatoires vu qu'on utilise la donnée cadastrale.
Par contre elle peuvent être codées en dur je pense, sauf l'année du cadastre.

**Comment by MaelREBOUX** [comment]
Doublon avec #243

La demande de complément de pied de page a été prise en compte dans #243 

Je ferme @jusabatier . Tu me dis si j'ai oublié un truc. Merci

**Comment by pierrejego** [comment]
Je n'ai pas encore faire les trim dans les scripts Qgis;

Est-ce qu'on rajoute le pourcentage de la surface batie ?

@MaelREBOUX est-ce que tu as des problèmes d'encodages dans les exports, ici je n'en ai pas, mais j'aimerai bien reproduire pour être sur.

**Comment by MaelREBOUX** [comment]
OK. désolé pour les trims.

Non je n'ai aucune erreur d'encodage sur les prop bâtis. Ni en PDF ni en CSV.

**Comment by pierrejego** [comment]
Les trims ont été fait avec ce commit https://github.com/georchestra/cadastrapp/commit/9ca14ebf1a0d7ebab0901b39d017290209e98b7f#diff-3205c0ded576131ea255ad2bd38b0fb2

**Comment by MaelREBOUX** [comment]
> Pour la partie UF, je dois pouvoir rajouter le pourcentage bâti et surface totale.

Je valide également suite à consultation des instructeurs. Cela leur permet de comparer l'existant par rapport à ce qu'ils ont dans les dossiers ADS et ce qu'ils en ont calculé pour voir si c'est conforme.

Attention : on croise la surface bâti calculée (SIG) avec la contenance DGFiP. C'est étrange mais c'est ainsi -> à documenter.

**Comment by MaelREBOUX** [comment]
Je ferme ici car globalement c'est OK sauf levé de 2 petits bogues mineurs : #395 et #396
