### ISSUE TITLE
[lots] Tri alpha et pas numérique sur les numéros de lots

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#393]
Suite de #371 

Travail conséquent : pour faire propre il faut remonter aux modèles de données d'origine.
Chantier à ouvrir.

**Comment by MaelREBOUX** [comment]
A discuter car en lien avec redescendre vers le modèle de données plugin QGIS.

**Comment by pierrejego** [comment]
@MaelREBOUX je fais les modifications sur le modèle Qgis dans les scripts. Mais j'ai un gros doute, et je ne trouve pas d'information sur internet pour me valider ma question.

Es-tu bien sur que le dnulot c'est forcément un nombre ?

J'ai trouvé que pour du non bati c'est pas forcément le cas. Donc ça OK, de toute façon on ne le changeait pas.
> Numéro du lot - Le lot de BND se présente sous la forme 00Axxxx - 

mais pour le bati, je suis pas sur du tout finalement.
Et si je fais une requête pour vérifier en base sur la table lotslocaux
select distinct dnulot from cadastre.lotslocaux where dnulot NOT SIMILAR TO '[0-9]*'
Je tombe sur quelques lots avec des caractères

Et pareil sur la table lot
select dnulot from cadastre.lots where dnulot NOT SIMILAR TO '[0-9]*'

La ou j'ai un doute, c'est que dans des dnulot je trouve PUY EN, ou encore RUZ  et pas du tout des nombres. ça je pense que c'est des erreurs d'import Majic.

A côté de ça j'ai aussi des dnulots remplis d'espace ou des dnulots en 000000A. 

J'essaye de t'appeler demain matin pour faire un point.

@landryb et @jusabatier , si vous pouviez lancer cette requête chez vous dans la base cadastrapp, ça permettrait d'être un peu plus sur que je vais pas tout casser. 
select distinct dnulot from cadastre.lotslocaux where dnulot NOT SIMILAR TO '[0-9]*'

Merci

**Comment by landryb** [comment]
Y'a un peu de tout:
```
 dnulot  
---------
        
 000000A
 000000B
 000000C
...
 0LCOMMB
 0LOCCOM
 0LOCXCO
 0LOGCOM
 0NOUV.R
 0SOCIAL
 0TRANSF
 141.141
 A000001
 A000002
 A999998
 A999999
 ABANIER
...
 ZOEN   
 ZOIRES
 ZON
 ZONNES 
 ZOUX
(5187 rows)
```

**Comment by pierrejego** [comment]
Merci, du coup les derniers lignes des lots, je pense que c'est des erreurs d'import, comme si il y avait une décalage dans le fichier Majic. Mais les premières lignes confirme bien ce que je pensais, il n'y a pas que des nombres.

**Comment by EtienneRouvin** [comment]
De notre côté :
000001A
000001B
000003P
...
 CHAPEL
 JACQUE
 RHEU
 VERGER
ANTEPIE
...
(70 rows)

**Comment by MaelREBOUX** [comment]
Du coup qu'est-ce qu'on fait pour cette histoire de tri ?

Dans l'absolu je vois ça comme ça :

1. on balance la requête qui récupère toutes les données sur les lots demandés
2. on fait un test IsNumeric sur les valeurs dnulots 
3. en fonction du résultat
** si True -> on peut trier en numérique croissant
** si False -> ???

pour le cas où ça remonte justement du numéric et du text, dans l'absolu il faudrait séparer en 2 :
* prendre les enregistrements avec les valeurs numériques pour les trier et les afficher en premier
* prend le reste des enregistrements et trier en alpha et les afficher après

Bonjour l'usine à gaz.
Une chose sûre pour moi : pas possible à faire en SQL ce serait au code de gérer ça.

Qu'en penses-tu @pierrejego

**Comment by pierrejego** [comment]
On va voir si on ne peut pas faire un tri personnalisé côté client du coup. Vu que côté modèle c'est pas possible et côté serveur ça ferait une grosse verrue

**Comment by pierrejego** [comment]
Alors en fait, le tri côté client ne sert pas du tout, vu qu'on affiche pas les numéros de lot à l'IHM, je viens de faire le tour des écrans et je n'ai pas trouvé de notion de lots (uniquement présent dans les exports) .....

Pour la partie serveur, j'ai peut être trouvé une solution en ajoutant une extension de tri naturel https://github.com/Zeleo/pg_natural_sort_order à postgresql, mais ce n'est pas une extension officielle. Et plusieurs questions se posent, la licence MIT est-elle compatible, et qu'est-ce qu'on fait si l'extension n'est pas maintenu dans les futures versions de postgresql.

@MaelREBOUX qu'en penses tu ?

**Comment by landryb** [comment]
Avoir une dépendance sur une extension postgresql non présente de base, c'est non :)

**Comment by pierrejego** [comment]
Ok, alors je vais essayer de le faire le tri naturel dans le code java, après récupération des données en base. 
L'ordre de tri c'est bien uniquement sur le numlot, ou on fait invar + numlot ?

**Comment by MaelREBOUX** [comment]
> Avoir une dépendance sur une extension postgresql non présente de base, c'est non :)

je demande même pas l'avis de @catmorales, même si dans un avenir proche on fera ce qu'on veut sur la base de données : ce truc c'est un sacré fil à la patte.

Le tri se fait uniquement sur `numlot`, d'où nos difficultés...

**Comment by pierrejego** [comment]
Merci, j'essaye d'implémenter le tri par ordre 'naturel' côté java du coup.

**Comment by pierrejego** [comment]
Encore mieux. On est bien d'accord, Cadastrapp c'est java1.8 minimum, donc je peux utiliser ça : 
https://docs.oracle.com/javase/8/docs/api/java/util/Comparator.html#naturalOrder--

**Comment by pierrejego** [comment]
Ah non pas sur que ça soit dans l'openjdk, c'est peut être juste dans la version Oracle.. A tester

**Comment by pierrejego** [comment]
La fonction existe bien, mais le comportement reste le même.

Voilà le code essayé, mais qui laisse dans le tri les 10 avant les 2....
``
// Natural Order sort
		Collections.sort(proprietesBatiesLots, new Comparator<Map<String, Object>> () {
		    @Override
		    public int compare(Map<String, Object> m1, Map<String, Object> m2) {
		    	
		    	Comparator<String> naturalComparator = Comparator.<String> naturalOrder();	    	
		    	return naturalComparator.compare((String)m1.get("dnulot"), (String)m2.get("dnulot"));
		    }
		});
``
@MaelREBOUX je suis à court d'idée, si quelqu'un en a une je suis preneur

**Comment by MaelREBOUX** [comment]
Si ça veut pas... On fait un point tel cet a-m.

**Comment by pierrejego** [comment]
@MaelREBOUX j'ai fait la modification qu'on avait prévu lors de notre conversation de ce midi. J'ai beau avoir des dnulots avec des lettres dans le modèle Qgis, je n'en ai pas une fois passée dans le modèle cadastrapp.  
Pour tester j'ai rajouté des lots avec des caractères, au début, au milieu, à la fin. Mais je n'ai pas de cas réel

**Comment by MaelREBOUX** [comment]
Vu le résultat des investigation je me suis résolu à ouvrir un ticket spécifique --> https://github.com/georchestra/cadastrapp/issues/475

En résumé :  les lots avec un dnulot contenant autre chose que des chiffres ne sont pas présents dans la base cadastrapp mais on les trouve dans la base QGIS.

**Comment by MaelREBOUX** [comment]
Sur chaque PDF que j'ouvre je vois les lots bien triés comme attendu.
