### ISSUE TITLE
[RP] Export CSV propriétaires : adresse et nom de voie collés sur les adresses à suffixe

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#395]
Exemple : ``` 10BRUE GAUDRINE  35170 BRUZ```
Mais je ne l'ai pas ici :  ``` 4 SQ  DU CHATELIER  35170 BRUZ``` 

Je crois que ça concerne toutes les adresses en B T Q etc...

**Comment by pierrejego** [comment]
Dans ce cas, c'est la concaténation des champs dlign3, dlign4, dlign5 et dlign6 qui donne l'adresse. 
En vérifiant dans la base c'est le contenu du dlign4 qui semble ne pas être bon lorsqu'il y a un suffixe.
En remontant d'un niveau, on voit que c'est dans la base Arcopole qui semble y avoir une erreur. 
Le même problème existe d'ailleurs aussi sur la base QGis.  Ce problème doit donc venir encore des données du niveau au dessus.

**Comment by MaelREBOUX** [comment]
Je confirme que c'est comme ça dans les données MAJIC III à la source :   ```0010BRUE GAUDRINE ```

Du coup : rien n'à faire...
