### ISSUE TITLE
[RP] Export CSV propriété bâtie et non bâtie : dnvoirie et dindic sont vides

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#396]
```sql
select dnvoiri, dindic, dvoilib
from cadastrapp_arcopole.proprietebatie
where invar = '3500470397566'
```
==> '10';'B';'RUE GAUDRINE'

Dans le CSV :
```
dnvoiri | dindic | dvoilib
  |   | RUE GAUDRINE
```

**Comment by pierrejego** [comment]
C'est aussi valable pour les RP en PDF, le dindic et dnvoirie n'apparaît pas

![image](https://user-images.githubusercontent.com/11499415/39428897-5b3063a6-4c89-11e8-8958-63df3b8a86df.png)

**Comment by pierrejego** [comment]
Modification effectuée avec ce commit : 
https://github.com/georchestra/cadastrapp/commit/4a2f85cbc21b03bffad2d4fec9ab390b0e892bcf

**Comment by MaelREBOUX** [comment]
OK.
