### ISSUE TITLE
[UF] Bogue sur redimensionnement de la fenêtre du navigateur

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#397]
* clic avec l'outil UF sur une parcelle
* ouverture d'une nouvelle fenêtre avec la carte et la liste des parcelles composant l'UF
* redimensionner la fenêtre du navigateur ou la passer sur un autre écran

On obtient ça :

![image](https://user-images.githubusercontent.com/6370443/39240668-c525bd00-4884-11e8-9a0b-b15dad48b97f.png)

Plus on multiplie les manipulations plus on obtient de polygones de sélection.

![image](https://user-images.githubusercontent.com/6370443/39240705-e83032d0-4884-11e8-96bc-cf2f2081f2dd.png)

@pierrejego milestone 1.6 ou 1.7 ?

**Comment by pierrejego** [comment]
OK vu, je reproduis, j'avais le même problème avec le zoom, les entités avant le redraw restait affichée.

**Comment by MaelREBOUX** [comment]
Vu au tel : on laisse en l'état pour ne pas retarder la release de la v1.6.

A corriger en 1.7 si possible.

**Comment by Gaetanbrl** [comment]
La couche ne se redessine pas, les méthode de rafraîchissement forcées n'ont pas d'effet sur la représentation dégradée des parcelle dans la fiche UF au mouvement de la fenêtre. 

Observation : Un ajout et suppression des features d'une couche permet de redessiner cette couche (force).

**Comment by MaelREBOUX** [comment]
testé et approuvé
