### ISSUE TITLE
Délais de génération BP

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#398]
Je ne sais pas si c'est du au passage à georchestra 17.12 (GS 2.12) ou aux nouveaux traitements de l'image pour le BP, mais leur temps de génération à pas mal augmenté (~1 min) alors qu'avant c'était quasi instantanné.

**Comment by jusabatier** [comment]
En fait l'erreur doit venir de ça : 
`16-May-2018 10:58:06.917 INFOS [http-nio-8280-exec-10] org.geotools.data.wfs.internal.Loggers.log Sending DFT request to http://opendata.agglo-lepuyenvelay.fr:80/geoserver/wfs?REQUEST=DescribeFeatureType&VERSION=1.0.0&SERVICE=WFS`

Une URL http est appelée alors que je force le https donc 301

**Comment by landryb** [comment]
1mn ca sent le timeout nginx dans un des reverse proxies..

**Comment by jusabatier** [comment]
Dans ce cas, le BP ne se génererais pas si ?

**Comment by landryb** [comment]
Pas forcément, ca dépend de comment geotools gère les 502 timeout.. il peut très bien te renvoyer un code d'erreur ou une image blanche, et après ca dépend comment le code de cadastrapp gère le code de retour de l'appel à geotools...

**Comment by jusabatier** [comment]
Oui mais là pour le coup le BP est généré correctement avec une image.

**Comment by pierrejego** [comment]
Je vais vérifier en faisant des tests de génération sur les deux versions. Cette partie a effectivement été modifié en 1.6. Pour une meilleur qualité d'image et pour éviter toutes déformations, c'est maintenant côté serveur carto que la subrillance est faite. 
Je pense faire les tests pour début septembre je vous tiens au courant

**Comment by jusabatier** [comment]
Les délais sont meilleurs avec 1.7

Des améliorations ont-elles été apportées dans ce sens ?
Sinon ça venait peut-être de notre réseau interne.

Dans tous les cas je me demmande si il ne serait pas judicieux d'afficher un spinner de chargement en attendant que les PDF soient générés, cela permettrait à l'utilisateur de voir que le document est en cours de création.

**Comment by pierrejego** [comment]
Oui il y a eut des quelques changements mais rien qui expliquerai un gros changement.
On est passé de FOP 1.1 à FOP 2.3, mais pour le reste il n'y a que la prise en compte de ta PR et des préférences utilisateurs.

**Comment by MaelREBOUX** [comment]
rien noté ici sur mes tests sur master

**Comment by MaelREBOUX** [comment]
@jusabatier  peut-on fermer cette issue ?

**Comment by jusabatier** [comment]
Quid de l'ajout d'un spinner pendant la génération de documents ?

**Comment by pierrejego** [comment]
On n'arrive pas à fermer le spinner correctement dans tous les cas et tous les navigateurs (en partie à cause de l'utilisation de l'iframe) 
Je pense que le mieux c'est de fermer cette anomalie et de faire un ticket général sur les spinners dans l'ensemble de l'application

**Comment by MaelREBOUX** [comment]
Je ne me sens pas capable d'écrire une telle issue.

@jusabatier  ?

**Comment by MaelREBOUX** [comment]
Merci @jusabatier
