### ISSUE TITLE
Utilisation de la classe charToByteConverterClass lors de l'impression (classe dépréciée en java8)

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#399]
J'essaie de migrer mes tomcat8 vers java8, pour cadastrapp 1.5, et a chaque impression de BP j'ai ce message de warning dans le catalina.out (meme pas le log tomcat, directement sur stderr)
```
Warning: Could not get charToByteConverterClass!
```
Il n'apparait pas avec java7, donc j'imagine qu'une des dépendances de cadastrapp lors de l'impression (FOP ?) doit etre mise a jour pour ne plus trigger ce warning... l'impression PDF se passe bien qd meme.

Au passage, dans le meme catalina.out il y'a un bout de XML dumpé pour chaque impression de BP
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<bordereauParcellaire>
    <dateDeValiditeEdigeo>01/01/2017</dateDeValiditeEdigeo>
    <dateDeValiditeMajic>01/01/2017</dateDeValiditeMajic>
    <empty>false</empty>
    <parcelles>
        <parcelle adresseCadastrale="           L ETANG" codeFantoir="xxxxx" libelleCommune="SAINT PAL DE CHALENCON" parcelle="xxxx" parcelleId="2017xxxxx" section="C" surfaceCadastrale="1978">
            <proprietaires>
                <proprietaire adresse="xxxx" nom="xxxxx"/>
            </proprietaires>
        </parcelle>
    </parcelles>
    <service>Un service du CRAIG</service>
    <serviceUrl>http://localhost:8180/cadastrapp/services/</serviceUrl>
```
je ne suis pas certain que ce soit lié au logging cadastrapp en soi vu que ca arrive sur stderr.. ci dessous la config de logging:
```
        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
                <encoder>
                        <pattern>%d %-5level %logger{36} - %msg%n</pattern>
                </encoder>
        </appender>

        <logger name="org.georchestra.cadastrapp" level="DEBUG" />
        <logger name="org.springframework" level="INFO" />
```
et rien n'envoie vers l'appender STDOUT.

**Comment by pierrejego** [comment]
A faire en même temps que la #370

**Comment by MaelREBOUX** [comment]
Vu que #370 fermée : on ferme ?

**Comment by landryb** [comment]
Pas sur, plutot lié a #417?

**Comment by pierrejego** [comment]
Non il ne faut pas la fermer. Je n'ai pas encore de solution complète pour supprimer ce warning. Ce n'est pas le passage en 1.8 qui va permettre de l'enlever mais plutôt un passage de FOP 1.1 à FOP 2.x
Mais je n'ai pas encore pu vérifier l'impact, sur le papier ça n'a pas l'air trop compliqué, mais j'ai peur des effets de bords avec nos xsl.

**Comment by pierrejego** [comment]
Je viens de faire la modification de version de FOP. On passe de la version 1.1 à la version 2.3. 
Plus de trace du warning dans le catalina.out ni ailleurs d'ailleurs.

Par contre, je sais pas si c'est pareil chez vous, j'ai tous les échanges geotools qui sont loggés dans le catalina.out.

**Comment by landryb** [comment]
> Par contre, je sais pas si c'est pareil chez vous, j'ai tous les échanges geotools qui sont loggés dans le catalina.out.

c'est pas lié a #417 ? sinon on utilise aussi une version super vieille de geotools, c'est ptete lié à ca... idéalement, rien ne devrait aller sur stderr/catalina.out :)
