### ISSUE TITLE
Multi instance de la fenêtre demande d'informations foncières

### ISSUE THREAD

**Issue by sdhem** [georchestra/cadastrapp#4]
Si on clique plusieurs fois sur le bouton "Demande" la fenêtre est instanciée plusieurs fois alors q"elle devrait être instanciée qu'une seule fois.

**Comment by pierrejego** [comment]
La partie serveur de la demande d'information est en cours de réalisation, la modification pourra être effectuée en même temps. Mais ne peut-il pas y avoir plusieurs fenêtre de Demande au même moment ?

**Comment by MaelREBOUX** [comment]
Non :  ce n'est pas souhaitable. On traite plusieurs demandes à se suivre.

Pour rappel : le système doit pouvoir dire si le demandeur a atteint ou non son quota de demande mensuel / hebdomadaire.
Un système d'auto-complétion sur les champs nom, prénom, etc serait un gros bénéfice.

**Comment by pierrejego** [comment]
Modification effectuée avec la nouvelle gestion des PDFS
