### ISSUE TITLE
{AddOn 005.14] Recherche par adresse cadastrale

### ISSUE THREAD

**Issue by catmorales** [georchestra/cadastrapp#40]
Pas de réponse à la requête si on rentre une adresse+voie  mais  fonctionne sur une voie seule (les autres champs ne sont pas renseignés).
La requête renvoie une liste de parcelles mais lors du clic sur une parcelle /adresse , on a un erreur HTTP 500.

**Comment by pierrejego** [comment]
@catmorales pouvez vous vérifier si le problème est toujours présent, je ne reproduis pas. Et fermer l'anomalie le cas échéant

**Comment by MaelREBOUX** [comment]
Le pb décrit ci-dessus n'est pas reproduit.
Fermer ce ticket.
