### ISSUE TITLE
Pas de parcelle en surbrillance sur BP

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#403]
Après maj en 1.6, les images générées pour intégration dans le BP ont bien le fond de plan, la couche cadastre, mais *pas* la parcelle actuellement sélectionnée.

Le log semble bien faire chacune des étapes:
```
14:07:54,266 - - - Create buffer
14:07:54,266 - - - Perimeter : 156.87986152846685
14:07:54,266 - - - Max visible distance in meter before buffer : 29
14:07:54,266 - - - Current Scale : 1.4500000000000002
14:07:54,266 - - - Min Scale : 20
14:07:54,267 - - - Bounding box length : 322 meters
14:07:54,267 - - - Call WMS for plot
14:07:54,267 - - - WMS URL : https://tiles.dev.craig.fr/pci/service?VERSION=1.1.1&Request=GetCapabilities&Service=WMS
14:07:54,288 - - - Create background plots image
14:07:54,497 - - - Create feature image from WMS
14:07:54,498 - - - Generated SLD : <?xml version="1.0" encoding="UTF-8"?>
xmlns="http://www.opengis.net/sld" version="1.0.0">
     <sld:Name>Default Styler</sld:Name>
     <sld:Title/>
     <sld:FeatureTypeStyle>
         <sld:Name>name</sld:Name>
         <sld:Rule>
             <sld:Name>BP</sld:Name>
             <sld:Title>Borderau Parcellaire rule</sld:Title>
             <ogc:Filter>
                 <ogc:PropertyIsLike wildCard="*" singleChar="." escape="!">
                     <ogc:PropertyName>geo_parcelle</ogc:PropertyName>
                     <ogc:Literal>*20184301250000G0728*</ogc:Literal>
                 </ogc:PropertyIsLike>
             </ogc:Filter>
             <sld:PolygonSymbolizer>
                 <sld:Fill>
                     <sld:CssParameter name="fill">#1446DE</sld:CssParameter>
                     <sld:CssParameter name="fill-opacity">0.5</sld:CssParameter>
                 </sld:Fill>
                 <sld:Stroke>
                     <sld:CssParameter name="stroke">#10259E</sld:CssParameter>
                     <sld:CssParameter name="stroke-width">2</sld:CssParameter>
                 </sld:Stroke>
             </sld:PolygonSymbolizer>
         </sld:Rule>
     </sld:FeatureTypeStyle>
</sld:StyledLayerDescriptor>
14:07:54,672 - - - Create final picture
14:07:54,673 - - - WMS call for basemap with URL : http://tiles.dev.craig.fr/ortho/service?VERSION=1.1.1&Request=GetCapabilities&Service=WMS
14:07:54,813 - - - Create basemap picture
14:07:54,830 - - - Add Image to final picture
14:07:54,836 - - - Add compass
14:07:54,837 - - - Add scale
14:07:54,837 - - - Pixels size :  0.42649006622516555
14:07:54,837 - - - Image width : 755.0
14:07:54,837 - - - Visible distance : 322
14:07:55,015 /getImageBordereau nouser -o.g.c.providers.PreReponseFilter - Sending response
```

mais dans l'image png générée dans `/tmp/cadastrapp/` on ne voit pas la parcelle, alors qu'en 1.5 évidemment aucun soucis.

C'est lié à 18e98d387 qui appelle le service déclaré dans `cadastre.wms.url` (chez moi, mapproxy) avec un param SLD_BODY, ce dernier n'étant pas envoyé à geoserver qui fait le stylage - mapproxy à déja l'image en cache donc il répond avec cette dernière, sans faire le stylage.

Ca marche j'imagine pour tous les autres qui utilisent geowebcache qui doit laisser passer les requètes si il voit SLD_BODY.. et ca n'a probablement été testé que dans ce cas.

Evidemment, je pourrais mettre l'url de mon geoserver dans `cadastre.wms.url` mais dans ce cas je perds complètement l'avantage du cache.

**Comment by landryb** [comment]
De mon analyse, 2 requetes wms sont faites sur `cadastre.wms.url`, une première pour le 'plot' (c'est sensé vouloir dire quoi ?) sur la zone d'impression, sans aucun paramètre bizarre, on a bien les parcelles/sections/batiments (celle la est servie sans pbm par le cache de mapproxy)

![foo](https://user-images.githubusercontent.com/3421760/43643719-8e464696-972c-11e8-985c-cead2b876e2b.png)

 et une 2e avec le SLD_BODY (qui, si j'envoie la requete direct a geoserver en bypassant mapproxy, renvoie aussi section/batiments/etc) donc l'empilage des images va faire des doublons.

![foo2](https://user-images.githubusercontent.com/3421760/43643729-9680386c-972c-11e8-871e-f8b87ec47051.png)

D'ailleurs (et probablement à cause des niveaux max d'affichage) il n'y a pas les parcelles sur cette dernière image.

Ce qui est dommage, c'est qu'on à déja la géometrie coté serveur... vu qu'on vient de faire un GetFeature WFS juste avant (ici: https://github.com/georchestra/cadastrapp/blob/master/cadastrapp/src/main/java/org/georchestra/cadastrapp/service/ImageParcelleController.java#L169). Ca serait bien plus simple d'appliquer directement le SLD à l'objet géographique coté serveur, plutot que rappeler une fois de plus le WMS.. c'est plus ou moins ce qu'on faisait avant, non ?

**Comment by landryb** [comment]
Je peux évidemment faire une pirouette crado en utilisant `cadastre.wfs.url` ici https://github.com/georchestra/cadastrapp/blob/master/cadastrapp/src/main/java/org/georchestra/cadastrapp/service/ImageParcelleController.java#L258 mais c'est relativement moche.. et ca implique d'avoir le même nom de couche dans geoserver et mapproxy.

Il serait peut-être plus logique de refondre tous ces paramêtres en:
* fond de carte pour la visionneuse et l'impression (actuellement `baseMap`)
* fond cadastre pour l'affichage dans le viewer (actuellement `cadastre.wms`, tuilé/caché, potentiellement geowebcache ou mapproxy ou..)
* fond cadastre pour l'impression (doit supporter SLD_BODY, donc geoserver ou mapserver)
* service WFS utilisé pour la recherche de parcelles (ou d'unité foncière)

**Comment by landryb** [comment]
Je viens de comprendre pourquoi il n'y avait pas les parcelles sur la 2e image.. c'est à cause du sld envoyé qui n'affiche *que* la parcelle nous intéressant.

**Comment by landryb** [comment]
Au passage, il vaut mieux utiliser un POST plutôt qu'un GET quand on envoie un SLD_BODY inline.. ca peut poser des problèmes de taille de buffers avec des proxies intermédiaires.

**Comment by pierrejego** [comment]
On en reparle ensemble début septembre, on a fait le changement pour gagner en qualité et éviter toutes déformations. On doit surement pouvoir améliorer encore cette partie

**Comment by jusabatier** [comment]
Chez nous non plus, pas de parcelle en surbrillance sur les BP

**Comment by aureliesouvignet** [comment]
Bonjour,
Avez-vous avancé sur la sélection de la parcelle lors de l’édition du bordereau ? 
Merci

**Comment by jusabatier** [comment]
Bonjour,

J'ai réussi à corriger le problème chez nous : 

On avait défini en cadastre.wms.url une couche composite du cadastre issue de GWC

Pour corriger le souci, j'ai été obligé de remettre geo_parcelle en cadastre.wms.url et de passer notre couche cadastre composite en baseMap.

En revanche nous n'avons par conséquent plus de fond OSM sur les BP.

**Comment by landryb** [comment]
Oui, c'est une solution.. mais c'est pour ca qu'il faut revoir la définition des couches/services utilisées (et a quel moment, cf  https://github.com/georchestra/cadastrapp/issues/403#issuecomment-410252501) plutot que faire des pirouettes autour de l'existant.

**Comment by jusabatier** [comment]
Bon ben en fait ce n'est pas une solution du tout, car en utilisant cette methode, c'est la couche geo_parcelle qui est chargée par l'addon cadastrapp à l'ouverture donc ça ne va pas...

Retour à l'ancienne configuration avec pas de selection de parcelle dans le BP :/

**Comment by pierrejego** [comment]
Je vais vous appeler pour des éclaircissements, chez moi ça fonctionne très bien, mais je ne dois pas utiliser la même configuration que vous.
@MaelREBOUX chez vous aussi vous avez des problèmes de sélections ?

**Comment by pierrejego** [comment]
Ok, j'ai compris en relisant la PR.

**Comment by pierrejego** [comment]
Oui pour le POST à la place du GET, enfin je m'avance, il faut que je regarde la lib pour l'appel serveur mais normalement oui

**Comment by pierrejego** [comment]
Fermer avec la PR #425
