### ISSUE TITLE
Les couches cachées ne sont pas supprimées lors qu'on désactive l'addon

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#404]
cadastrapp crée 2 couches cachées `__georchestra_cadastrapp` et `__georchestra_cadastrapp_plots` (en plus de la couche cadastre non affichée dans le layertree) qui ne sont pas supprimées de la liste des couches (`GeoExt.MapPanel.guess().map.layers`) lorsqu'on désactive l'addon (via le bouton cadastre/fermer la barre d'outils), et que ce dernier prend en charge l'ajout/suppression de la couche parcellaire.

Si un utilisateur avec l'addon actif sélectionne une parcelle, la sélection va apparaitre 'par dessus' la couche parcellaire (cas normal, comportement attendu).

![dessus](https://user-images.githubusercontent.com/3421760/43707201-c5da82a6-9967-11e8-8617-88385b2ba46c.png)

Ensuite, s'il désactive et réactive l'addon (via le bouton dans la toolbar), la couche parcellaire est supprimée/réajoutée *par dessus* la couches temporaire de sélection, et si l'utilisateur fait une sélection elle va apparaitre *en dessous* de la couche cadastre.
![dessous](https://user-images.githubusercontent.com/3421760/43707190-c1797dc0-9967-11e8-98f6-3cecbb6c4eee.png)

Le problème n'est pas présent quand la couche parcellaire est chargée via le contexte cartographique, car l'addon ne s'occupe pas de la charger/décharger.

Il faut vraiment que cadastrapp fasse mieux le ménage quand il est désactivé...

**Comment by landryb** [comment]
I know there's code that's supposed to do it in https://github.com/georchestra/cadastrapp/blob/master/addons/cadastrapp/js/menu.js#L516 but for some reason the `cadastrapps_plots` layer is not removed.

**Comment by landryb** [comment]
ok je comprends un peu mieux. `destroy()` n'est appelé que lorsqu'on *supprime* l'addon, non lorsqu'on le désactive.

De plus, lorsque la couche parcellaire est déja présente (via le contexte), la couche `__georchestra_cadastrapps` a été ajoutée quand même (elle est présente dans la liste des couches), mais `GEOR.Addons.Cadastre.isWMSLayerAdded` est faux, donc cette dernière n'est pas supprimée non plus.

Il faut donc à mon avis:
* que la couche `__georchestra_cadastrapps` ne soit effectivement ajoutée *que* si une couche équivalente (avec la meme url/proto/nom) n'est pas déja présente
* que la suppression de la couche `__georchestra_cadastrapps_plots` se fasse lorsqu'on désactive/ferme l'addon, non lorsqu'on le supprime/détruit.

**Comment by landryb** [comment]
Je suis un peu perdu entre les 2 ou 3 couches gérées par cadastrapp (a quoi sert la couche `__georchestra_cadastrapps` si ce n'est pas la couche 'parcellaire' ?), mais je pense que la suppression de la couche `__georchestra_cadastrapps_plots` devrait se faire ici: https://github.com/georchestra/cadastrapp/blob/master/addons/cadastrapp/js/main.js#L133

au passage, c'est toujours avec mapfishapp 15.12 donc je ne pense pas avoir le support pour les evenements `aftercontextrestore` et `aftercontextcleared` qui je crois ont été ajoutés en 16.12.

**Comment by landryb** [comment]
J'ai l'impression que la couche `__georchestra_cadastrapps` n'a jamais d'objets affichés, qu'elle sert juste de support pour les controles de selection, qui vont ajouter les objets a la couche `__georchestra_cadastrapps_plots` - dans ce cas, pour cette derniere il faut juste la destroy lors de la destruction de l'addon, il n'y a pas forcément qqch à faire lors de show/hide. @pierrejego je veux bien une confirmation...

**Comment by landryb** [comment]
Peut être que https://github.com/georchestra/cadastrapp/blob/master/addons/cadastrapp/js/selectFeature.js#L47 est sensé mettre la couche WFS *au dessus* de toutes les autres mais il semble que ce n'est pas le cas en pratique..

**Comment by MaelREBOUX** [comment]
Si [PR 405](https://github.com/georchestra/cadastrapp/pull/405) mergée on peut fermer ce ticket non ? @pierrejego @landryb
