### ISSUE TITLE
doublons dans les vues matérialisées parcelle/parcelledetails après #323

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#408]
Entre 1.5 et 1.6 j'ai constaté une belle augmentation de la taille des 2 vues:
```
[db:5432] cadastrapp@cadastrapp=> \dmv+ cad201*.parcelle
                                List of relations
   Schema    |   Name   |       Type        |   Owner    |  Size   | Description
-------------+----------+-------------------+------------+---------+-------------
 cad2017aura | parcelle | materialized view | cadastrapp | 1307 MB |
 cad2018     | parcelle | materialized view | cadastrapp | 1742 MB |
[db:5432] cadastrapp@cadastrapp=> \dmv+ cad201*.parcelledetails
                                   List of relations
   Schema    |      Name       |       Type        |   Owner    |  Size   | Description
-------------+-----------------+-------------------+------------+---------+-------------
 cad2017aura | parcelledetails | materialized view | cadastrapp | 2880 MB |
 cad2018     | parcelledetails | materialized view | cadastrapp | 3759 MB |
```
il y'a maintenant des doublons:
```
[db:5432] cadastrapp@cadastrapp=>
 select p.parcelle from cad2018.parcelle p where parcelle similar to '20186303800000E(0005|0406|0006|1156|0448|0405|1147)';
      parcelle
---------------------
 20186303800000E0005
 20186303800000E0005
 20186303800000E0006
 20186303800000E0006
 20186303800000E0405
 20186303800000E0405
 20186303800000E0406
 20186303800000E0406
 20186303800000E0448
 20186303800000E0448
 20186303800000E1147
 20186303800000E1147
 20186303800000E1156
 20186303800000E1156
(14 rows)

[db:5432] cadastrapp@cadastrapp=> select count(parcelle), count(distinct(parcelle)) from cad2018.parcelle where cgocommune='630380';
 count | count
-------+-------
 13328 |  8968
```
et ca se voit quand on demande le BP sur ces parcelles, la page est en double. Ie si je fais un BP sur 20186303800000E0005 j'ai 2 pages, et si je fais une demande d'infos utilisateur sur le compte communal correspondant (201863380+00175) j'ai 14 pages...

@jusabatier tu dois aussi le voir sur le puy:
```
[db:5432] cadastrapp@cadastrapp=> select count(parcelle), count(distinct(parcelle)) from cad2018.parcelle where cgocommune='430157';
 count | count
-------+-------
 10483 |  9301

[db:5432] cadastrapp@cadastrapp=> select count(parcelle), count(distinct(parcelle)) from cad2017aura.parcelle where cgocommune='430157';
 count | count
-------+-------
  9265 |  9265
```
J'imagine que le FULL OUTER JOIN se prend les pieds dans le tapis qqpart...

Encore un bug trouvé par @stous :)

**Comment by landryb** [comment]
Pbm causé par https://github.com/georchestra/cadastrapp/pull/323, en particulier a2953241

**Comment by jusabatier** [comment]
T'es sur que c'est pas plutôt une erreur lors de ton import car moi je n'ai pas de soucis de doublons.

J'ai intégré la version 2018 des MAJIC et EDIGEO la semaine dernière en utilisant les scripts SQL de master et avec ta requête, je n'ai pas de doublons : 
`select count(parcelle), count(distinct(parcelle)) from cadastrapp_2018.parcelle where cgocommune='430157'`

 count | count
-------+-------
9301 | 9301

**Comment by landryb** [comment]
Il y'a même des parcelles en triple. Je fais des essais sur mauzun (630216) qui a 320 parcelles, 2 sont en triple (20186302160000A0484 et 20186302160000A0386) et 33 sont en double, ce qui donne 357 enregistrements dans la table parcelle.

```
[db:5432] cadastrapp@cadastrapp=> select count(parcelle), count(distinct(parcelle)) from cad2018.parcelle where cgocommune='630216';
 count | count
-------+-------
   357 |   320
```

Tu as fait l'import avec quelle version du modèle qadastre, et quelle version du modèle cadastrapp ?

**Comment by jusabatier** [comment]
J'ai fais mon import avec la dernière version du module cadastre QGis (format 2017 il me semble).
Pour cadastrapp, avec les scripts de master.

**Comment by landryb** [comment]
dernière version, 1.5.0, 1.5.1 ou 1.5.2 ? Pour 1.5.2 il faut #401...

Dans la base qgis, j'ai 320 parcelles pour 630216 dans la table `parcelle`, et 357 dans la table `geo_parcelle`, avec des doublons dans cette dernière. 

Pour le puy, j'ai 9295 dans `parcelle` et 10478 dans `geo_parcelle`.. donc ca sent le pbm d'import edigeo.

**Comment by jusabatier** [comment]
Alors c'est peut être pas la dernière version : Cadastre version 1.4.1 dans QGis

**Comment by landryb** [comment]
Effectivement, cette version du plugin date de février 2017..

**Comment by landryb** [comment]
Cf https://github.com/3liz/QgisCadastrePlugin/pull/144

**Comment by pierrejego** [comment]
Je suis pas sur d'avoir bien tout compris.
Si je résume
1-  il y a un soucis de doublons sur les données 2018 dans le plugin Qgis,  j'ai vu https://github.com/3liz/QgisCadastrePlugin/issues/143.
2 - Une fois ces doublons supprimés, il y a d'autres doublons suite à l'import dans cadastrapp ?

 c'est bien ça  ?

**Comment by landryb** [comment]
C'est à voir mais je pense pas, je suis en train de virer les doublons dans `geo_parcelle` et il faudra juste que je REFRESH MATERIALIZED VIEW après sur `parcelle` et `parcelledetails`. Mais idéalement il faut je pense reprendre tous les imports depuis le début, j'ai juste pas envie d'attendre 3 jours.

**Comment by landryb** [comment]
En fait c'est un problème que tu vas voir:
- si tu importes les données dans le modèle qgis avec une version du plugin ayant 3liz/QgisCadastrePlugin@549a1a36 (pas certain du commit, mais une version > 1.5.1 je pense)
- si tu crées les vues de cadastrapp avec une version de cadastrapp ayant a295324 (donc 1.6)

Si le bug est corrigé à la source lors de l'import d'EDIGEO dans le modèle QGIS (ou que tu importes les données avec une version plus ancienne du plugin cadastre) et qu'il n'y a pas/plus de doublons dans la base qadastre, il ne devrait pas y'avoir de doublons dans les vues matérialisées de la base cadastrapp.

**Comment by landryb** [comment]
Le fix n'a été mergé que dans la branche `master_2` du plugin Cadastre, donc les versions 1.6 et supérieures l'ont. Pour les versions 1.5 (pour qgis2?) le problème peut toujours se poser.
