### ISSUE TITLE
[AddOn 006] Recherche Propriétaire par nom

### ISSUE THREAD

**Issue by catmorales** [georchestra/cadastrapp#41]
- Pas d'autocomplétion sur le prénom - fonctionnement peu pratique - on pense plus pratique d'avoir NOM et Prénom complets ensemble . cela permettrait en outre de trouver facilement les différents propriétaires ayant le même nom et de ne pas avoir de doublon dans la liste obtenue par complétion du nom
- Prendre également en compte les noms d'usage et de naissance . en fait la recherche par nom doit taper sur les champs: ddenom, (nom de la personne physique), dnomlp (nom d'usage), drnlp (prénom usage), dnomcp (nom de naissance) et dprncp (prénom de naissance),
- le résultat de la requête ne doit pas être une parcelle mais une liste de propriétaires, un clic sur le propriétaire de la liste doit donner les parcelles de ce propriétaire .
  Exemple sur réseau carto:
  ![image](https://cloud.githubusercontent.com/assets/4659829/9193041/a5a64050-4010-11e5-958c-a8929a8de54e.png)

**Comment by MaelREBOUX** [comment]
Pour mémoire, le modèle de données CadBAS (utilisé par notre application actuelle) concatène tout dans un attribut unique. Cela facilite la recherche.

**Comment by MaelREBOUX** [comment]
Lier à #46

**Comment by landryb** [comment]
Après discussion, tout le monde est ok pour grouper les champs nom et prénom dans la recherche et dans la base, ca réglera d'un coup ce ticket et le #46, et probablement ferait disparaitre les 'champs tronqués' - de plus l'autocomplétion sera plus souple.

L'idée en mergeant les 2 champs étant de matcher sur nom + prénom en 'fuzzy', ie si je cherche 'dupont' ca me renvoie toutes les entrées commencant par dupont ('dupont%'), si je cherche 'dupont jean' ca cherche 'dupont%jean%' me renvoie 'dupont-dubord jean' et 'dupont alexandre jean'.

A voir si on veut aussi que ca matche intégralement, je ne suis pas sur que ce soit pertinent de chercher '%alexandre%' et d'avoir tout les alexandre de la commune quel que soit le nom..

**Comment by catmorales** [comment]
Ca résoudra aussi ce genre de problème; exemple pour la recherche des propriétés de la commune de Rennes (on ne penserait pas à rechercher dans le nom "DERENNES"):

![image](https://cloud.githubusercontent.com/assets/4659829/10068466/e69cdd4c-62a4-11e5-9323-7d3a58e88dfe.png)

**Comment by pierrejego** [comment]
Modification effectuée et disponible sur https://cadastrapp-qualif.asogfi.fr/mapfishapp/
