### ISSUE TITLE
[RP] Somme des surfaces est vide sur le PDF (surface totale vide) prop non bâtie

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#410]
Pas de souci en 1.5, en 1.6 le champ 'Surface totale' dans le pdf du RP est vide (affiche juste 'CA') alors que les propriétés du RP ont bien une valeur dans le champ contenance.

**Comment by landryb** [comment]
Je ne comprends pas bien ou est le souci car les surfaces semblent bien accumulées ici: https://github.com/georchestra/cadastrapp/blob/master/cadastrapp/src/main/java/org/georchestra/cadastrapp/helper/ProprieteHelper.java#L391

**Comment by jusabatier** [comment]
Constaté également chez nous

**Comment by jusabatier** [comment]
Le MAJ POS est également vide, il semblerait que les champs définis dans : 
https://github.com/georchestra/cadastrapp/blob/master/cadastrapp/src/main/java/org/georchestra/cadastrapp/model/pdf/ImpositionNonBatie.java
ne soient pas reportés sur le PDF généré.

**Comment by jusabatier** [comment]
Ne faudrait-il pas que l'attribut défini ici : https://github.com/georchestra/cadastrapp/blob/master/cadastrapp/src/main/java/org/georchestra/cadastrapp/model/pdf/ProprietesNonBaties.java
Soit de type ImpositionNonBatie, afin de pouvoir remonter les champs "surface" et "majorationTerraion" ?

**Comment by pierrejego** [comment]
A reproduire pour analyse et correction

**Comment by MaelREBOUX** [comment]
Bonjour,

Je confirme le pb est visible également chez nous.

![image](https://user-images.githubusercontent.com/6370443/48339887-77c2a680-e669-11e8-8efa-ac07b0083c7f.png)

**Comment by pierrejego** [comment]
En vérifiant le XML avant génération du PDF on voit que les attributs ne sont pas remplis, mais qu'ils le sont bien dans l'objet en amont. Cela vient donc du mapping.

Effectivement @jusabatier le type n'est pas le bon, il faut
@XmlElement(name="imposition",     type=ImpositionNonBatie.class, nillable = true)
Et non
@XmlElement(name="imposition",     type=Imposition.class, nillable = true)

Je fais la modification toute suite.
