### ISSUE TITLE
[model] Jointure à revoir sur la vue deschabitation

### ISSUE THREAD

**Issue by EtienneRouvin** [georchestra/cadastrapp#411]
La jointure à corriger est ici : https://github.com/georchestra/cadastrapp/blob/master/script/qgis/views/qgisHabitationDetails.sql#L50-L51
Il suffit d'inverser les tables pev et pevprincipale, comme c'est le cas pour descproffessionnel

**Comment by landryb** [comment]
Peux tu expliquer un peu mieux quel est le problème ?

**Comment by EtienneRouvin** [comment]
Lorsque la jointure est fait dans ce sens : **from #DBSchema_qgis.pev
			left join #DBSchema_qgis.pevprincipale pevp on pev.pev=pevp.pev**,
toutes les pev sont sélectionnées et pas uniquement les pevhabitation (on retrouve les pev professionnelles et les dépendances).
Or, si on inverse la left join comme suit : **from #DBSchema_qgis.pevprincipale pevp
			left join #DBSchema_qgis.pev on pevp.pev=pev.pev**, on a uniquement les parties principales d'habitation.

**Comment by MaelREBOUX** [comment]
Bonjour @landryb 

@EtienneRouvin est notre nouveau collègue dataminer
J'ai vérifié avec lui et il a raison : la jointure est faite à l'envers. Mais comme c'est pas visible / non bloquant dans cadastrapp on n'a jamais remarqué.

Chez nous la vue deschabitation retourne le même nb d'enregistrements que la table pev d'origine alors qu'elle devrait ramener que les enregistrements de PEV concernés par une description d'habitation.

L'amélioration devrait te plaire car ici on estime qu'on gaspille 30 % d'enregistrements qui servent à rien dans la base.

**Comment by pierrejego** [comment]
Bonjour tout le monde, me voilà de retour. 
Merci pour cette analyse, je rajoute ça dans mes corrections à faire.

Bonne journée
