### ISSUE TITLE
migration des limitations par emprise vers l'en-tête sec-org

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#412]
Depuis 16.12 (cf https://github.com/georchestra/georchestra/tree/master/migrations/16.12#ldap) les groupes LDAP correspondant aux organismes sont dans la branche ou=orgs et plus dans la branche ou=roles.

Par conséquent, le security-proxy envoie un nouveau header `sec-org` (cf https://github.com/georchestra/georchestra/tree/master/migrations/16.12#others) contenant le nom du groupe LDAP correspondant à l'organisme auquel l'utilisateur appartient - il faudrait donc adapter le code de https://github.com/georchestra/cadastrapp/blob/master/cadastrapp/src/main/java/org/georchestra/cadastrapp/service/CadController.java#L141 pour qu'il inspecte cet en-tête afin de retrouver le groupe avec lequel faire la recherche dans la table `groupe_autorisation`.

De plus, se pose la question du comportement par défaut. Si aucune entrée n'est trouvée dans la table des autorisations, actuellement aucun filtrage n'est fait. Serait-il plus pertinent d'avoir un mode (configurable?) ou par défaut, aucune donnée n'est renvoyée si aucune entrée n'est trouvée ? Ca dépend évidemment des utilisations des différentes PF, qui utilisent ou pas la fonctionalité de filtrage par emprise. Nous avons déja `user.search.are.filtered=1` pour la complétion des utilisateurs/communes, est-ce que ca ferait sens d'aussi enforcer le filtrage des recherches si cette option est active ?

Concernant le support des anciennes versions, les organismes dans `ou=roles` datent de georchestra 15.12 qui n'est plus supporté, on n'a donc à mon avis plus vraiment besoin de supporter les deux configurations (`ou=orgs` **et** `ou=roles`)

Discuté en amont avec @pierrejego @pmauduit

**Comment by landryb** [comment]
Actuellement, le filtrage en fonction de `user.search.are.filtered` se fait dans 3 cas, cf https://github.com/georchestra/cadastrapp/search?q=issearchfiltered&unscoped_q=issearchfiltered

* complétion d'une commune
* complétion d'une section
* infobulle d'une unité foncière

**Comment by pierrejego** [comment]
Dans le commit que tu as fait, tu considère qu'une personne ne peut appartenir qu'a une seule organisation, c'est bien le cas ? Je croyais qu'on avait des personnes qui travaillaient sur plusieurs communes voir d'autres départements ?

**Comment by landryb** [comment]
C'est une des choses qui sont imposées par la console lorsqu'on gère les organismes, oui. On en a discuté un bon moment avec @fvanderbiest sur un ticket georchestra mais je ne retrouve plus la référence.. mais un compte ne peut être lié qu'a *un seul* organisme dans le LDAP.

Si des personnes bossent dans plusieurs structures, elles ont plusieurs comptes.

**Comment by pierrejego** [comment]
pour un seul organisme dans le LDAP, c'est ok, c'est pour l'emprise de cette organisme ou on pourrait être faire quelques choses, voir le commentaire de @jusabatier dans la PR https://github.com/georchestra/cadastrapp/pull/415

**Comment by pierrejego** [comment]
Suite à un point aujourd'hui avec @MaelREBOUX, @landryb, @jusabatier et moi @pierrejego , voila l'orientation à prendre pour cette anomalie.

Deux fonctionnements seront possible : 
 - De la manière actuelle 
 - En utilisant la notion de zone de compétence de l'organisation de l'utilsateur (trouvé dans le header sec-org)

Dans le cas de l'utilisation de la zone de compétence de l'organisation, les informations seront récupérées grâce à un appel serveur<->serveur vers la console qui peuplera les informations de zone de compétence de l'organisation dans la table de données. 
La table contenant les informations aura un champ datedimportation permettant de connaître l'ancienneté de l'import. Par défaut les informations de plus 8 heures seront mise à jour, lors du chargement du module cadastrapp.
Cette notion de temps doit être configurable dans un fichier.
Une API accessible uniquement à un administrateur (dont le role georchestra sera configurable dans le fichier de configuration cadastrapp.properties) pourra lancer la commande de mise à jour pour un organisme donnée.

Une fonctionnalité n'est pas disponible actuellement dans la console, c'est la notion de compétence départementale (a approfondir).  Il serait intéressant soit d'avoir ce type d'information dans la console, soit de faire un algorithme côté cadastrapp avec des fichiers de données, permettant de vérifier si un organisme a un accès départemental en vérifiant la liste de ces communes. Ce fonctionnement doit lui aussi être un option activable dans le fichier de properties cadastrapp.properties.

**Comment by fvanderbiest** [comment]
> Dans le cas de l'utilisation de la zone de compétence de l'organisation, les informations seront récupérées grâce à un appel serveur<->serveur vers la console qui peuplera les informations de zone de compétence de l'organisation dans la table de données.

Pourquoi pas de connection directe au LDAP ?

**Comment by landryb** [comment]
Tant que le ldap n'est pas interrogé a chaque requète, c'est aussi une solution satisfaisante..

**Comment by pierrejego** [comment]
Oui c'est possible aussi. La connexion à la console semblait plus simple pas besoin de lib supplémentaire.
Mais c'est à étudier effectivement

**Comment by landryb** [comment]
sera fixé par #571 qui étend ce que j'avais en local.

**Comment by landryb** [comment]
#571 mergée
