### ISSUE TITLE
Erreur IE : GEOR.Addons.Cadastrapp namespace should be defined !

### ISSUE THREAD

**Issue by pwernert** [georchestra/cadastrapp#413]
Erreur constatée lorsqu'on accède au visualiseur sous IE (version 11.0.9600.19129) :
![image](https://user-images.githubusercontent.com/37657174/45810974-3b5b7580-bccc-11e8-83a6-765f6e9ac31e.png)
Ci-dessous la copie d'écran suivante de l'outil de dev de IE. C'est peut-être la dernière erreur qui est concerne le problème :
![image](https://user-images.githubusercontent.com/37657174/45811009-55955380-bccc-11e8-9aaa-deb6253ce6c5.png)

**Comment by landryb** [comment]
probablement, mais cadastrapp.js est la version 'minifiée' de l'application. As-tu une erreur différente si tu ajoutes `&debug=1` dans l'url d'appel ? Ca permettrait de savoir sur quel fichier l'erreur est..

en attendant, c'est un doublon de #387 - donc je ferme ce ticket..

**Comment by MaelREBOUX** [comment]
Doublon de #387 : je ferme donc.
