### ISSUE TITLE
[RP] [BP] [lots copro] muscler et homogénéiser les mentions de diffusion

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#414]
Je fais le point sur les documents dans le cadre d'une formation et je nous trouve léger sur le relevé de propriété.
Là où le BP indique  
"_Les informations transmises ce jour le sont pour votre usage strictement personnel. Vous ne pouvez pas les communiquer à des tiers (art 13 loi Informatique et Libertés de 1978 modifiée 2004)._" 

On a un limité "_Ce document est donné à titre indicatif - Il n'a pas de valeur légale_".

Faudrait homogénéiser tout ça. Je propose donc :

**Les informations transmises ce jour n'ont aucune valeur légale et le sont pour votre usage strictement personnel. Vous ne pouvez pas les communiquer à des tiers (art 13 de la Loi Informatique et Libertés de 1978 modifiée 2004).**

Il n'y a rien actuellement dans le relevé des lots de copro -> rajouter.

@landryb @jusabatier  ?

**Comment by pierrejego** [comment]
@landryb @jusabatier @stous @aureliesouvignet Quelqu'un peu faire un retour sur ses attentes. Juste pour savoir si je fais la modification ou non ?

**Comment by landryb** [comment]
faut que je demande à notre avocat

**Comment by landryb** [comment]
(c'était une blague, hein)

**Comment by pierrejego** [comment]
:) et sans avocat tu as quand même un avis ?

**Comment by landryb** [comment]
pour ce genre de questions, absolument aucun :)

**Comment by MaelREBOUX** [comment]
Alors ça m'a pris un peu plus de temps que prévu pcq avec le RGPD je m'aperçois que des choses bougent donc il a fallu que je vérifie plus de choses que prévu.

Pour les BP et les RP je propose :  

**Les informations contenues dans ce document sont réservées à l'usage personnel du demandeur (art L107 B du livre des procédures fiscales). Vous ne pouvez pas communiquer d'informations à caractère personnel à des tiers sans accord express des personnes concernées par ces données (chap II art 13 loi Informatique et Libertés de 1978 modifiée 2004).
Les informations contenues dans ce document sont les plus à jour dans la mesure des capacités des responsables du logiciel à les maintenir à jour.**

Pour les listes des lots de copros :

**Ce document ne peut pas être diffusé à un administré et est destiné à l'usage exclusif des services de la collectivité (art L107 B du livre des procédures fiscales).
Les informations contenues dans ce document sont les plus à jour dans la mesure des capacités des responsables du logiciel à les maintenir à jour.**

En effet si qqn veut du détail sur un lot -> on fait un RP sur le seul lot / parcelle concernée.

**Comment by MaelREBOUX** [comment]
poke @landryb @jusabatier @stous @aureliesouvignet

**Comment by landryb** [comment]
c'est toi le spécialiste..

**Comment by MaelREBOUX** [comment]
En complément il aussi indiquer "Un service fourni par " + pdf.organisme de cadastrapp.properties

**Comment by pierrejego** [comment]
> En complément il aussi indiquer "Un service fourni par " + pdf.organisme de cadastrapp.properties

C'est normalement toute la phrase que tu veux que tu mets dans pdf.organisme de cadastrapp.properties, mais on peut changer si vous voulez.

**Comment by pierrejego** [comment]
Vu avec @MaelREBOUX changé la police en 8pt pour le BP
