### ISSUE TITLE
dont print debug info to stdout

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#417]
because it kills unicorns and uselessly fills catalina.out.
5 occurences in https://github.com/georchestra/cadastrapp/search?q=%22system.out%22&unscoped_q=%22system.out%22

those should use instead a stringwriter, and log the given string - https://stackoverflow.com/a/26140934 has a good example.

**Comment by pierrejego** [comment]
Hello,
Yes that's why it was only in debug condition 
if (logger.isDebugEnabled()) {

but that's true the proposition is good.
