### ISSUE TITLE
[AddOn.007] Recherche propriétaire par compte

### ISSUE THREAD

**Issue by catmorales** [georchestra/cadastrapp#42]
la recherche rend un résultat vide.
la requête qui passe est la suivante:
https://cadastrapp-qualif.asogfi.fr/cadastrapp/services/getParcelle?_dc=1439280987883&comptecommunal=

**Comment by catmorales** [comment]
Complément 
testé avec les droits CNIL_2 sur compte de la commune de chantepie +00413 et sur un compte personnel (Mxxxx)

**Comment by MaelREBOUX** [comment]
On confirme : passe pas sur PF GFI avec données RM arcOpole mais fonctionne sur PF Craig

**Comment by landryb** [comment]
Mettre un exemple d'identifiant de compte en dessous du champ - de plus vu que le champ est obligatoire, mettre une valeur dans un champ de la liste puis le vider remet la valeur précédente -> on ne peut pas enlever une valeur en cas d'erreur.

**Comment by MaelREBOUX** [comment]
Ex : rechercher compte proprio 350139G00219

**Comment by pierrejego** [comment]
La fenêtre Compte propriétaire prend pour l'instant des dnupro et non des id de comptecommunaux.

Je peux modifier la fenêtre pour prendre plutôt un comptecommunal, mais dans ce cas, la recherche de la commune en amont n'est plus nécessaire, le compte communal contient la notion de commune

**Comment by catmorales** [comment]
Attention!i peut y avoir des propriétés d'une commune dans une autre commune (cas déjà vu): 
ex: Rennes à des propriétés dans Cesson...

**Comment by MaelREBOUX** [comment]
_la recherche de la commune en amont n'est plus nécessaire, le compte communal contient la notion de commune_

Je n'en serais pas si sûr : on a trouvé des parcelles dont le proprio est "M LE MAIRE".
Si tu fais référence à l'attribut CCOGRM (Code groupe de personne morale : 4 = commune) : celui-ci n'est pas fiable d'après notre service Foncier. Lui-même maintient une cartographie des parcelles des grands proprios foncier en s'appuyant sur les noms des organismes (ex : "mairie" / "commune"...).
Bref : ce n'est pas fiable.

**Comment by pierrejego** [comment]
Est-ce que cette anomalie peut être fermée ?  
Ce qui est fait -> 
Dans l'onglet Compte, on met la commune puis le dnupro
et dans l'onglet lot on met un fichier contenant uniquement le ou les  comptes communaux

**Comment by landryb** [comment]
@MaelREBOUX @catmorales c'est bon pour vous ?

**Comment by MaelREBOUX** [comment]
Oui très bien !
Sauf que, à l'instar de ce qu'on a pour la fiche info parcelle il manque un bouton pour obtenir le relevé de propriété.
C'est logique qu'il soit là.

![screenshot030](https://cloud.githubusercontent.com/assets/6370443/11149732/9793d168-8a24-11e5-91f1-f9ba7a8e077f.png)

**Comment by pierrejego** [comment]
Je viens d'ajouter le bouton, la modification sera visible sur la pf de qualif demain matin.

**Comment by MaelREBOUX** [comment]
peut pas vérifier : cf #102

**Comment by MaelREBOUX** [comment]
pour afficher cette fenêtre il faut avoir plusieurs proprios possible.
Le bouton est bien présent.

Ticket à  fermer.
