### ISSUE TITLE
WFS should use POST when getting UF/parcelle info

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#420]
When clicking on 'Fiche unité foncière' on a given parcelle, i sometimes get 400 codes from the webserver, because cadastrapp does a GET on the wfs via a GetFeature, passing the parcelle polygon encoded in the URL, and thus the request headers are 8k and hit default server limits.

Sure, i can bump limits here and there in the various proxies in the chain between the client and the webapp, but in that case it would be much simpler to use POST, which is made for this usecase....

**Comment by landryb** [comment]
Even after bumping the buffer sizes in the nginx proxies (ie set `large_client_header_buffers 4 16k;`), it still fails, and it seems it also hits a limit in the s-p tomcat, which logs:
```
24-Oct-2018 11:12:31.700 INFOS [http-nio-8180-exec-1] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
 java.lang.IllegalArgumentException: L'entête de requête est trop important
```

**Comment by MaelREBOUX** [comment]
Tiens ? Je croyais qu'on avait tout passé en POST il y a qqs temps déjà. Ma mémoire failli. @pierrejego  ?

**Comment by pierrejego** [comment]
Non on avait pas tout passé en POST. Je modifie les services qui évolue pour les mettre en POST au fur et à mesure. Il en reste encore en GET.

**Comment by Gaetanbrl** [comment]
Passage GET vers POST pour [cette requête GetFeature](https://github.com/jdev-org/cadastrapp/blob/29d6f1f92d5cfaa337d3828f86566e6fbf260864/addons/cadastrapp/js/selectFeature.js#L280-L294).

**Comment by landryb** [comment]
Nice !
