### ISSUE TITLE
Mise à jour de Spring

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#422]
@pierrejego On a une alerte sur Spring : https://github.com/georchestra/cadastrapp/network/alerts

je rajoute ça au mileston...

**Comment by pierrejego** [comment]
Ok, je vais faire une montée de version et vérifier si tout est ok.

**Comment by pierrejego** [comment]
Closed with this commit 
https://github.com/georchestra/cadastrapp/commit/26db144117f4b1cfa996d4874d8a10a14071f497
