### ISSUE TITLE
Le chargement de l'addon cadastrapp perturbe le fonctionnement de l'addon extracteur

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/cadastrapp#426]
Vu sur https://www.geograndest.fr/mapfishapp/ : si les 2 addons sont chargés simultanément, le cadre d'extraction n'est pas déplacable.

L'addon cadastrapp ajoute 2 couches vectorielles à l'objet map au chargement, et pour une raison que j'ignore, l'un d'entre elles doit intercepter tous les événements souris.

**Comment by landryb** [comment]
peut-etre corrigé par georchestra/cadastrapp#404 .. ou pas.

**Comment by pierrejego** [comment]
Il pertube aussi l'impression de façon occasionnel. A priori comme pour l'extracteur le cadre d'impression n'est plus déplaçable.

**Comment by fvanderbiest** [comment]
Oui, constaté sur une version 1.5 de cadastrapp.
C'est https://github.com/georchestra/cadastrapp/blob/Cadastrapp-v1.5/addons/cadastrapp/js/selectFeature.js#L24 qui pose problème.

Peut etre que la couche de sélection ne devrait être affichée que lorsqu'elle est nécessaire ?

**Comment by pierrejego** [comment]
Les modifications ont été faites pour la version 1.7. C'est sur le master en ce moment et la release devrait  bientôt être disponible
Je ne peux pas reporter en 1.5, ni 1.6 car le modèle de données à changé avec le changement de millésime.

J'ai aussi vu ce point 
https://github.com/georchestra/cadastrapp/blob/master/addons/cadastrapp/js/selectFeature.js#L61
je sais qu'on en avait déjà parlé avec @Gaetanbrl , il faut que je retrouve le bon event de mapfishapp pour faire la modif

**Comment by fvanderbiest** [comment]
Quel est le commit qui corrige ça ?
Pour GrandEst nous préfèrerions backporter le fix plutot que de tout upgrader, au moins à court terme.
Merci !

**Comment by pierrejego** [comment]
Bonjour, pardon je n'avais pas vu ton post.
malheureusement on ne sais pas trop, vu qu'on ne pouvait pas reproduire à chaque fois.
Je pense que c'est le mix de plusieurs commit, mais qui vont être compliqué à backporter.

https://github.com/landryb/cadastrapp/commit/4d0d399ba81d2daec74d2a9963555176599321ec
https://github.com/landryb/cadastrapp/commit/676d9680a0ec1d088f1cbf1c8b55ff3096881c55
https://github.com/landryb/cadastrapp/commit/b97c37b38aa449ac288fde15724db4b67eae69fe
https://github.com/landryb/cadastrapp/commit/e9afee31f2991c0de7bee37ef3fb06a734373436

et
https://github.com/georchestra/cadastrapp/commit/a7e42a3024cee727436fc5a05c64a61f41492444

Mais encore une fois, je ne suis pas sur, j'ai aussi fait pas mal de changement sur l'utilisation de la couche vectoriel qui sélectionne les parcelles (pour #430]  qui pourrait avoir un lien.

**Comment by fvanderbiest** [comment]
OK, merci de ton retour.
Je laisse tomber l'idée de backporter alors.
On verra avec GrandEst pour un upgrade complet.
