### ISSUE TITLE
Bugs sur fiche unite foncière

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#428]
J'ai constaté quelques bugs avec la fonction d'unité foncière : 

1er bug : 

On essaye de récupérer la fiche d'UF d'une parcelle et l'aperçu généré correspond bien à la parcelle, mais les infos remontées (propriétaires, contenance, ...) correspondent à une autre UF.

=> Sélection de la parcelle AT0145 :
![cpt_fiche_uf_bug](https://user-images.githubusercontent.com/8310116/49153109-165f3080-f315-11e8-89d5-28671b36dcca.png)

A noter que ce bug ne se produit que si on passe par le bouton "fiche UF" de la sélection de parcelle.

2e bug : 

Les infos de contenance UF de la popup qui apparait sur la parcelle ne correspondent pas à celle de la fiche UF : 

![cpt_fiche_uf_bug2_popup](https://user-images.githubusercontent.com/8310116/49153364-cd5bac00-f315-11e8-97a0-69b54673b28f.png)

![cpt_fiche_uf_bug2_fiche](https://user-images.githubusercontent.com/8310116/49153475-2297bd80-f316-11e8-8107-10a12f71888d.png)

**Comment by pierrejego** [comment]
En passsant en pas à pas, j'ai remarqué qu'il y avait deux services avec le même nom getInfoUniteFonciere. Je n'ai gardé que celui ou la surface calculée est bonne, dans le service supprimé il manquait une jointure.

Par contre ça n'explique pas le fait d'avoir des parcelles qui n'appartiennent pas à l'UF

Pour l'instant je ne reproduis pas ce deuxième point ici, je continue de tester.

**Comment by jusabatier** [comment]
Je viens de MaJ cadastrapp en 1.7 (master) (BDD+addon+app), et j'ai une variante du bug encore plus étrange :/

Je sélectionne ma parcelle : 
![bug_uf_1](https://user-images.githubusercontent.com/8310116/49285619-3b2fe100-f498-11e8-967f-d5cc1dd6a3a0.png)

Je clique sur "Fiche unité foncière" : 
![bug_uf_2](https://user-images.githubusercontent.com/8310116/49285760-ab3e6700-f498-11e8-9690-efd6477e0857.png)
A présent l'image n'est pas centrée sur la bonne parcelle, mais la bonne parcelles est en gris sur la gauche.
En revanche les infos textuelles sont bien sur les bonnes parcelles.
Et dans mapfishapp j'ai la parcelle sur laquelle est centrée l'image qui devient sélectionnée sans raison : 
![bug_uf_3](https://user-images.githubusercontent.com/8310116/49285937-31f34400-f499-11e8-9dc6-70d3d1744f3b.png)

PS : @pierrejego Si besoin, je peux te faire parvenir nos données cadastrales pour que tu puisses tester après avoir établi une convention.

**Comment by jusabatier** [comment]
Et je viens de voir qu'il manque la ref d'une parcelle sur la fiche d'info :/

**Comment by jusabatier** [comment]
Voici ce que j'obtiens de plus correcte en utilisant le bouton "Unit. Fonc." du menu cadastrapp et en cliquant directement sur la parcelle (carte) : 
![bug_uf_4](https://user-images.githubusercontent.com/8310116/49286304-03c23400-f49a-11e8-83f0-6beb7ab8e6ea.png)

C'est bien mieux, mais il manque toujours la reference de la parcelle AT160.

**Comment by pierrejego** [comment]
Ok je reproduis, j'avais mal compris le bouton unité foncière.

L'unique différence entre les deux cas, c'est : 
Quand on clique sur UF dans le menu puis sur la carte, on envoie une recherche côté geoserver avec un intersect avec le point du click
Quand on sélectionne, une parcelle puis on clique sur "Fiche Unité foncière" alors on envoie la même requête mais avec un multipolygon de la parcelle au lieu du point comme intersect.
A partir de ce moment la, les données sont erronées. Les parcelles renvoyées sont celle d'une UF coller à notre parcelle et non celle de la parcelle.
Je pense que c'est cette partie là qui n'est pas bonne 
https://github.com/georchestra/cadastrapp/blob/master/addons/cadastrapp/js/selectFeature.js#L254

**Comment by pierrejego** [comment]
@jusabatier J'ai fait la correction pour avoir les bonnes informations lors du cliques sur "Fiche Unité foncière". 

Par contre, il reste à reproduire le cas ou il manquait une parcelle. Pour l'instant je ne l'ai pas reproduis mais j'attends les données.

**Comment by pierrejego** [comment]
@jusabatier je viens de faire le test avec tes données, l'information de la parcelle s'affiche bien chez moi 
![image](https://user-images.githubusercontent.com/11499415/49382115-d1246f80-f715-11e8-9db7-b2503748fada.png)
 
Et je n'ai pas de problème d'affichage de parcelles supplémentaires. La correction apportée ici https://github.com/georchestra/cadastrapp/commit/5fef098e8d01e8c8901dbda22dd89c1542f1b270 a surement corrigé le problème.

**Comment by jusabatier** [comment]
J'ai integré les modifications, mais j'ai toujours le bug avec la parcelle en surbrillance qui n'est pas la bonne sur l'image lorsque je passe par le bouton "Fiche unité foncière".

**Comment by jusabatier** [comment]
Le cas ou il manquait une parcelle est également toujours présent, mais il ne se produit pas à chaque fois. 

Y a-t-il un appel à WFS qui est fait ? Car ce comportement me fait penser à un GeoServer du LB qui ne repondrait pas correctement.

**Comment by pierrejego** [comment]
Je te rappel demain, car je ne vois pas d'ou cela peut venir, on va essayer de faire du debug pour voir.
Oui il y a bien un appel WFS voir deux en cas d'utilisation du bouton "UF" du menu principal, mais si il y avait un problème, elle ne devrait pas apparaître du tout.... pas juste sa contenance.

**Comment by jusabatier** [comment]
Le bouton UF de la barre de menu fonctionne parfaitement.

Le bug est lorsque j'utilise celui de la liste de selection.
En cliquant sur celui-ci, je vois passer une requête WFS : 

```
filter | <Filter xmlns:gml="http://www.opengis.net/gml"><Intersects><PropertyName>geom</PropertyName><gml:MultiPolygon><gml:polygonMember><gml:Polygon><gml:outerBoundaryIs><gml:LinearRing><gml:coordinates>769551.54,6437597.34  769551.54,6437597.34 769535.28,6437611.18 769539.62,6437615.43  769548.49,6437624.08 769559.31,6437634.45 769568.13,6437642.91  769574.92,6437649.48 769581.22,6437655.56 769587.38,6437661.41  769596.69,6437670.05 769604.56,6437677.55 769607.9,6437680.73  769629.74,6437662.62 769631.72,6437660.98 769630.61,6437659.64  769610.63,6437635.51 769590.04,6437610.67 769577.33,6437595.31  769567.67,6437583.66 769565.64,6437585.4 769558.43,6437591.58  769551.54,6437597.34</gml:coordinates></gml:LinearRing></gml:outerBoundaryIs></gml:Polygon></gml:polygonMember></gml:MultiPolygon></Intersects></Filter>
-- | --
outputFormat | application/json
request | getfeature
service | wfs
typename | pci:geo_unite_fonciere
version | 1.0.0
```

**Comment by pierrejego** [comment]
Après test ce matin, une des différences entre nos deux plateformes c'est la projection. Ici je suis en 3857 et toi en 2154. 
Je passe tout en 2154 pour voir si je reproduis l'erreur

**Comment by pierrejego** [comment]
@jusabatier je suis passé en 2154 (merci pour le WMC) et je reproduis ton erreur. Je vais maintenant essayer de comprendre d'ou cela vient

**Comment by MaelREBOUX** [comment]
> Le bouton UF de la barre de menu fonctionne parfaitement.

je confirme : aucun pb ici

> Le bug est lorsque j'utilise le bouton de la liste de selection

je confirme : c'est n'importe quoi qui apparaît dans la carte. Enfin presque : ça a sélectionné une parcelle à côté. Les informations textuelles sont elles OK.

![screenshot113](https://user-images.githubusercontent.com/6370443/49509042-9725ab80-f884-11e8-8167-defac8d3ecf3.png)

**Comment by MaelREBOUX** [comment]
@jusabatier : est-ce qu'on ne supprimerait pas simplement ce bouton ?

**Comment by jusabatier** [comment]
Je ne suis pas d'accord pour le supprimer.

SI j'ai pu constater ce bug, c'est parce qu'en formation des utilisateurs sont passés par là plutôt que par celui de la barre cadastrapp. C'est donc qu'il est plus intuitif pour certains de passer par là.

**Comment by pierrejego** [comment]
Pour plus d'explication, 
en fait ici nous avons un "multipolygon", il suffit qu'une des lignes intersects avec une UF et celle-ci est renvoyé par le geoserver.
On peut alors se retrouver avec plusieurs résultats, et je ne sais pas lequel prendre. 
A l'origine je ne pensais ne pouvoir avoir qu'un seul résultat et je prenais donc que le premier. Or dans notre cas, le premier est l'uf d'a côté....
Je n'ai pas de moyen de savoir laquelle prendre, mais maintenant que j'ai décorrelé en deux étapes l'appel WFS, je peux utiliser Contains au lieu de Intersects dans notre cas
Les premiers tests sont bons, mais je me rappel avoir déjà essayé en début de semaine et être tombé sur des erreurs.  Je finalise donc les tests avant de commiter.

**Comment by MaelREBOUX** [comment]
Résolu ici. Tout semble cohérent.

![image](https://user-images.githubusercontent.com/6370443/54031611-88b29d00-41af-11e9-8060-84af53edf4fa.png)
