### ISSUE TITLE
geoserver-workspaces partagent les mêmes identifiants

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/cadastrapp#429]
Actuellement les 2 workspaces proposés par https://github.com/georchestra/cadastrapp/tree/master/geoserver-workspace partagent les mêmes identifiants geoserver.

Il faudrait donc au choix:
 * préciser que les deux sont mutuellement exclusifs (j'ai testé pour vous)
 * ou modifier les identifiants d'un des deux

Je propose la solution 2.

**Comment by pierrejego** [comment]
lié à la #297

**Comment by MaelREBOUX** [comment]
En quoi ça pose un problème ? On doit choisir 1 seul style pour publier les couches cadastre.

**Comment by fvanderbiest** [comment]
Je voulais tester les 2 pour me faire une idée, mais c'est peut être pas la bonne approche ?

**Comment by MaelREBOUX** [comment]
je ne sais pas. je n'ai jamais essayer de récupérer tout un workspace.

**Comment by MaelREBOUX** [comment]
lié à #297

**Comment by MaelREBOUX** [comment]
@fvanderbiest tu pourrais nous faire une PR pour corriger ce qu'il te semble pas ok ?
Sinon on ferme ?

**Comment by fvanderbiest** [comment]
Lazy me 
f62a07deaba8d1290550d648ea2228da8fc1459b

**Comment by MaelREBOUX** [comment]
lol
