### ISSUE TITLE
[AddOn.010] Sélection manuelle de parcelle

### ISSUE THREAD

**Issue by catmorales** [georchestra/cadastrapp#43]
-   [01] La sélection  manuelle directe de parcelle fonctionne avec un simple clic pas double clic,
-   [03] la sélection  manuelle  par point lance l'ouverture de la fenêtre parcelle en plus de celle de sélection,
-  [05, 07] la sélection  manuelle  par ligne et polygone lancent l'ouverture de x fenêtres parcelles en plus de la fenêtre de sélection,
- [10, 11, 12] ajout d'un onglet vide --> ne fonctionne pas.

**Comment by pierrejego** [comment]
Bonjour,
l'ensemble des points ont été corrigé, avec le passage à trois état et la fenêtre de selection de parcelles
