### ISSUE TITLE
Champ InspireId manquant

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/cadastrapp#432]
L'insertion de [qgisParcelle.sql](https://github.com/georchestra/cadastrapp/blob/master/script/qgis/) échoue sur une version 2018 du cadastre Corse (absence du champ `inspireid` dans les données source de la vue).

**Comment by pierrejego** [comment]
Bonjour @fvanderbiest , il faut lancer le script SQL, pour rajouter l'inspireID dans le modèle (même si personne ne s'en sert) https://github.com/georchestra/cadastrapp/blob/master/script/qgis/changeOnQGISModel/alterQGISParcelle.sql

**Comment by fvanderbiest** [comment]
Oh bien vu, merci !
J'avais modifié le script pour mettre `null` à la place du champ ... si personne ne s'en sert, ça me conforte dans mon choix ;-)

**Comment by pierrejego** [comment]
lié à la #363
