### ISSUE TITLE
Multiples sélections de parcelles : la sélection d'un autre onglet reste affichée sur la carte

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#438]
Sans doute introduit par #388 

Quand on veut gérer une multi-sélection on le fait par le biais des onglets. Avant : les parcelles de la sélection 1 n'apparaissent pas quand on active l'onglet 2.

![screenshot110](https://user-images.githubusercontent.com/6370443/49508522-3b0e5780-f883-11e8-99c4-0e3be7eda631.png)

![screenshot111](https://user-images.githubusercontent.com/6370443/49508529-3ea1de80-f883-11e8-97b5-ccac68ec255f.png)

or là : c'est mélangé :

![screenshot112](https://user-images.githubusercontent.com/6370443/49508585-5f6a3400-f883-11e8-9b90-57f958722541.png)

**Comment by pierrejego** [comment]
OK je reproduis

**Comment by pierrejego** [comment]
Si je passe pas une fenêtre de recherche de parcelle, les onglets sont bien nettoyés. Par contre avec une sélection par clic, le style 'default' reste actif entre les onglets.

**Comment by pierrejego** [comment]
J'ai trouvé un autre comportement étrange en analysant cette anomalie. L'event beforeOnChangeTab se lance deux fois...

**Comment by pierrejego** [comment]
Lors de la sélection par click, deux mêmes features sont ajoutées à la couche et non pas une seule.
![image](https://user-images.githubusercontent.com/11499415/49589724-6ae45a80-f96a-11e8-879a-e9cc3d40a107.png)
Ce qui explique aussi l'anomalie #431 car en fait une feature reste toujours à l'état list en dessous.

**Comment by MaelREBOUX** [comment]
Résolu.
