### ISSUE TITLE
[AddOn.11] Recherche par identifiant cadastral

### ISSUE THREAD

**Issue by catmorales** [georchestra/cadastrapp#44]
- [12,13,14,15] lancer la recherche ouvre la fenêtre de sélection mais ne donne aucun résultat

**Comment by pierrejego** [comment]
Est-ce que vous pouvez me fournir l'id de parcelle utilisée, je ne suis pas sur que le plan de test fourni soit à jour par rapport aux données

**Comment by catmorales** [comment]
En fait je tapais le mauvais identifiant (j'avais oublié un caractère pour la section) .
Avec 350001000AE0412 ça marche!
Je trouve que l'exemple montré n'est pas parlant:
![image](https://cloud.githubusercontent.com/assets/4659829/9218306/990553ce-40d1-11e5-8d28-a7ea1e8ad069.png)

**Comment by pierrejego** [comment]
OK, le champ d'exemple est paramétrable vous pouvez changer la valeur dans le manifest.json
cadastrapp.parcelle.ident.exemple

Par contre j'ai du faire une regression hier, j'ai du rajouter un validator sur le champ à 19 caractères et je vois que l'id de parcelle d'Arcopole bien que 19 en taille en base n'est que sur 15. Je refais la modification toute suite.

**Comment by catmorales** [comment]
Ah oui c'est vrai , en effet sur le modèle QGIS, il y a l'année en plus !

**Comment by MaelREBOUX** [comment]
vu :https://github.com/GFI-Informatique/addons/commit/609e9064174751636ccb3fc455d597f6ca63431f

Le label : changer en "Identifiant(s)" ou "Identifiant / Liste d'identifiants" pour laisser penser à l'utilisateur que on peut en mettre plus de un.

Il faut placer en -dessous un très court texte explicatif :
"Copier-coller ici un ou plusieurs identifiants de parcelles pour les sélectionner dans une limite de 50 parcelles.
Le format doit être le même que les données cadastrales fournies ici à savoir : 
- code commune sur 5 caractères : 35238
- code section sur 5 caractères :  000AB
- code de parcelle sur 4 caractères :  0023
  "
  Remplacer le contrôle textbox par un texarea. Le copier-coller typique sera d'un tableur vers ce contrôle. Les valeurs auront donc un retour à la ligne.
