### ISSUE TITLE
[BP] Vignettes pour illustrer le choix du fond de plan

### ISSUE THREAD

**Issue by pierrejego** [georchestra/cadastrapp#441]
vu avec @jusabatier  suite à l'évolution #436 il serait intéressant d'avoir des vignettes des fonds de plan.
J'ai fait quelques tests, mais l'affichage en ExtjS 3.4 étaient vraiment moche, il faut trouver un beau template de combobox je pense.

Par contre ça force les administrateurs à préparer des images png d'un format prédéfini.

**Comment by Gaetanbrl** [comment]
Pour bien saisir la demande, il s'agit bien de cette liste de choix du fond de plan qui s'affiche après le clic sur le bouton de demande du bordereau ? 
![image](https://user-images.githubusercontent.com/16317988/56146486-9295a000-5fa6-11e9-9e3a-18638d558c71.png)

**Comment by Gaetanbrl** [comment]
Si c'est bien le cas, ce type de représentation peux t-il convenir ? 
![image](https://user-images.githubusercontent.com/16317988/56189233-bb11ae80-6027-11e9-9611-3bea03ebd92a.png)

**Comment by Gaetanbrl** [comment]
vu avec @jusabatier : 
- on affiche une image par défaut si aucune image n'est indiquée
- placement des images dans le datadir

**Comment by Gaetanbrl** [comment]
Après réflexion, le placement des images dans le datadir nécessite de réaliser un service spécifique pour être appelées par le template (règle CSS) de la combo box de sélection d'un fond de plan. Ce n'est pas la solution la plus simple.

Placer les images dans le dossier "addons/cadastrapp/img" nécessite de pouvoir avoir accès à cette ressource et de maintenir les images lors des mises à jour. Ce qui n'est peut être pas une meilleure solution.

Ce qui fonctionne actuellement et simplement, c'est de passer une URL permettant de pointer vers une ressource interne/externe.
Voici un exemple d'URL passées dans le fichier cadastrapp.properties :
`pdf.baseMap.0.title.preview=http://kartenn.region-bretagne.fr/kartoviz/img/basemap/osm.png`

Cette solution peut-elle convenir ?

**Comment by jusabatier** [comment]
Voici un exemple de servlet permettant de rediriger une sous URL vers un dossier defini par la configuration disponible de l'application (fichier properties ou parametre tomcat/JAVA) : 

https://gitlab.agglo-lepuyenvelay.fr/snippets/3

A adapter pour l'application : 

- Stocker les vignettes dans un dossier "vignettes" du datadir cadastrapp
- Si une URL est renseignée, alors la vignette est chargé depuis l'URL
- Si seulement le nom du fichier est renseigné, alors on charge celui-ci via l'URL : 

/cadastrapp/config/vignettes/<nom_fichier>

Qui renvoie le fichier correspondant du dossier "vignettes" du datadir.

**Comment by pierrejego** [comment]
ça me semble plus pratique pour l'administrateur de déposer, ou d'utiliser des images qu'il aura déposer sur un serveur statique comme Apache, plutôt que de les mettre dans la webapp. Ou alors dans les datadir de cadastrapp avec le reste de la conf, mais dans ces cas là il faut utiliser le service de mapfishapp qui récupère les élements dans le datadir

appel http /mapfishapp/ws/addons/cadastrapp/repertoire avec les images ( a tester, je ne sais pas si les images peuvent passer, si ce n'est pas juste js et css)

**Comment by jusabatier** [comment]
Je ne suis pas d'accord, la configuration des vignettes se faisant dans le cadastrapp.properties, il me semble plus logique que les images correspondant soient stockées dans ce même datadir (cadastrapp)

**Comment by landryb** [comment]
> Je ne suis pas d'accord, la configuration des vignettes se faisant dans le cadastrapp.properties, il me semble plus logique que les images correspondant soient stockées dans ce même datadir (cadastrapp)

+1, mfapp a déja le code pour shipper des fichiers depuis le datadir (cf ce qui a été fait pour le css/js des UF, et je crois que les vignettes des wmc passent par le meme canal car elles sont dans `datadir/mapfishapp/contexts/images`), donc autant utiliser ca, plutot que d'avoir "une autre procédure" pour foutre des images qqpart dans un middleware.

**Comment by pierrejego** [comment]
@landryb, en fait le code du mapfishapp fonctionne uniquement pour le répertoire mapfishapp du datadir, mais il ne peux pas aller un niveau en dessous, et il ne peut donc pas aller dans le répertoire cadastrapp du datadir.

Donc si on ne veut pas mettre les images dans l'addons (qui est dans ce répetoire mapfishapp du datadir) mais dans le répertoire /etc/georchestra/cadastrapp/ il faut faire un nouveau service pour ça.

De mon côté ça me semblait pas déconnant de mettre les images côtés addons, vu que ce n'est que pour l'addons, mais je comprends aussi, que c'est plus logique de tout mettre au même endroit pour faciliter l'administration.

Donc on part, sur la mise en place des images dans le datadir cadastrapp, avec la création d'un nouveau service côté cadastrapp, qui va récupérer les vignettes. 

ça va à tout le monde ? @Gaetanbrl @MaelREBOUX @jusabatier @landryb

**Comment by jusabatier** [comment]
Pourquoi le service de mapfishapp si c'est dans le datadir cadastrapp ?

Je vous ait donné un exemple plus haut de comment faire le même service en quelques lignes avec les annotations Spring.

**Comment by pierrejego** [comment]
Non justement on utilisera pas le service mapfishapp. On va en faire un nouveau pour cadastrapp sûrement basé sur ton exemple.


Pierre Jégo

JDev

+33 6 79 83 82 71<tel:+33%206%2079%2083%2082%2071>


---- Julien Sabatier a écrit ----


Pourquoi le service de mapfishapp si c'est dans le datadir cadastrapp ?

Je vous ait donné un exemple plus haut de comment faire le même service en quelques lignes avec les annotations Spring.

**Comment by MaelREBOUX** [comment]
Nous a pris l'habitude de publier tout ce type de ressources sur notre serveur public. Et de les atteindre par une url.
Simple, efficace.

Pcq attendre / dépendre d'un redéploiement serveur de toute une appli c'est juste pas possible.

**Comment by landryb** [comment]
C'est assez horrible de faire comme ca.. vous n'avez peut-etre pas le choix car vous etres contraints par vos prestataires, et donc vous contournez le problème de cette manière, mais ce n'est pas la bonne solution imo.

Autant que possible, une appli doit etre self-contained, et n'avoir que des dépendances connues et clairement établies. Le jour ou ton serveur public migre vers autre chose (parce que c'est qqn d'autre qui gere cette partie dans ta collectivité, etc), et que tu as oublié que t'avais mis ces 3 vignettes dessus, bon courage... :)

**Comment by catmorales** [comment]
>Autant que possible, une appli doit etre self-contained

Oui je suis assez d'accord si on peut c'est mieux car là on touche à des vignettes "applicatives"

**Comment by MaelREBOUX** [comment]
Vu que vous êtes tous contre moi : je m'incline  ;-)

Au moins le pb est réglé.
Et je suis d'accord sur le fond.

**Comment by jusabatier** [comment]
Après j'avais proposé un peu plus de souplesse sur ce parametrage : 

- chemin de la vignette commence par http/https => Chargement depuis une URL externe (celle renseignée)

- sinon c'est que la vignette est stockée par cadastrapp et on la charge depuis une sous-URL de l'application

**Comment by pierrejego** [comment]
Développement terminé, mais il manque un peu d'explication dans le cadastrapp.properties pour expliquer les deux cas (http et stockage dans datadir)
https://github.com/jdev-org/cadastrapp/tree/issue-441-rest en attente de merge

**Comment by MaelREBOUX** [comment]
testé et approuvé
