### ISSUE TITLE
[lots] Renommer la colonne "Numéro Invariant"

### ISSUE THREAD

**Issue by EtienneRouvin** [georchestra/cadastrapp#444]
Lors de la sortie PDF et CSV, la 1ère colonne "Numéro Invariant" correspond en réalité au numéro du local

**Comment by pierrejego** [comment]
Il faut que je regarde dans le code ou se situe l'erreur exactement, je crois me rappeler qu'il y avait une différence Arcopole et Qgis sur ce champ. 
Du coup, on change le nom du champ ( de colonne) , ou on change la valeur pour le invar dans les exports ?

**Comment by MaelREBOUX** [comment]
On change juste le nom de la colonne. On garde les valeurs actuelles. Qui pour nous sont mieux pcq comporte le code de commune et se comportent donc comme un identifiant ou en tout cas une valeur unique. On préfère.

**Comment by Gaetanbrl** [comment]
> Lors de la sortie PDF et CSV, la 1ère colonne "Numéro Invariant" correspond en réalité au numéro du local

 Le nouveau nom "numero_local" conviendrai donc pour renommer cette colonne **à l'export des lots** en csv ? 
![image](https://user-images.githubusercontent.com/16317988/56221428-870bad00-606a-11e9-8c5a-65fa9d98652b.png)

**Comment by MaelREBOUX** [comment]
ok
