### ISSUE TITLE
url non normalisées avec le sec-proxy de 18.12

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#445]
Cadastrapp 1.7 avec georchestra 18.12, certaines URL des services de cadastrapp explosent en vol:
```
org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL was not normalized.
	org.springframework.security.web.firewall.StrictHttpFirewall.getFirewalledRequest(StrictHttpFirewall.java:248)
	org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:193)
	org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
	org.georchestra.security.UTF8Filter.doFilter(UTF8Filter.java:33)
```
Potentiellement lié a des maj spring ? @pmauduit une idée ?
a priori ce sont toutes les requetes qui font `cadastrapp/services//*`, si j'enlève le double / ca passe.

vu sur `cadastrapp/services//getProprietairesByParcelles?parcelles=20186300590000C0996`

A priori 3 occurences a corriger:
```
[28/03 16:58] root@ids.thruxton:/etc/georchestra/mapfishapp/addons/cadastrapp/js $git grep cadastrappWebappUrl *.js|grep "'/"
detailUniteCadastrale.js:            url : GEOR.Addons.Cadastre.cadastrappWebappUrl + '/getProprietairesByParcelles?parcelles=' + parcelleId,
searchCoPropriete.js:                            url : GEOR.Addons.Cadastre.cadastrappWebappUrl + '/getCoProprietaireList',
searchUtils.js:            url: GEOR.Addons.Cadastre.cadastrappWebappUrl + '/getDnuplaList',
```

**Comment by pierrejego** [comment]
OK, je vais faire le changement.
En plus je voulais externaliser les urls d'appels au service, comme ça je vais faire les deux en même temps.

**Comment by MaelREBOUX** [comment]
J'avais repéré il y a qqs mois ces doubles /  mais jusqu'à présent c'était sans conséquence.
Bien vu Landry. Merci.

**Comment by landryb** [comment]
A priori, il y'en a d'autres dans le code java. Si j'essaie de générer un BP, j'ai que du vide, et dans les logs:
```
Image not found. URI: http://localhost:8180/cadastrapp/services//getImageBordereau?parcelle=20186300590000B0007&fillcolor=81BEF7&fillopacity=0.6&strokecolor=111111&strokewidth=4&basemapindex=0. (No context info available)
```
(avec le beau double slash.. et *aucune* gestion d'erreur, alors que le SP renvoie un code 500)

si je supprime le double slash, ca semble mieux, l'appel direct me renvoie bien une image. A priori, pour cette instance il faut corriger les 2 urls sur https://github.com/georchestra/cadastrapp/blob/master/cadastrapp/src/main/resources/xsl/bordereauParcellaire.xsl#L103

**Comment by pierrejego** [comment]
En plus des modification de Landry, il faudrait externaliser dans des variables tous les noms des services pour ne plus avec d'appel du style GEOR.Addons.Cadastre.cadastrappWebappUrl + 'getConfiguration'
mais que getConfiguration soit dans une autre variable dans le fichier de configuration de l'addon côté client.

**Comment by MaelREBOUX** [comment]
Je pense que c'est bon alors je ferme. OK @landryb
