### ISSUE TITLE
[UF] On affiche des informations erronnées pour le %age de surface bâtie

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#446]
On découvre un problème avec les infos affichées dans la fiche UF.

**1. correction du calcul du pourcentage**
Actuellement le pourcentage est calculé en faisant : surfaces bâti SIG / contenance DGFiP parcelle. Ce qui est aberrant : il faudrait faire le calcul uniquement sur la surface SIG. Soit : surfaces bâti SIG / surface parcelle SIG. Question de cohérence. Sachant que le plan est arrangé par les géomètres du cadastre pour que les proportions restent fidèles à la réalité.

On arrive pas à savoir pourquoi / comment on aurait laissé passer ça mais nos négociateurs fonciers viennent de mettre le nez dessus.

**2. texte somme des surfaces**
Le texte affiche : "La somme des surfaces DGFiP est égale à 366 m²."
C'est faux : ce n'est pas une info DGFiP. Le texte devrait être "La somme des surfaces parcellaires calculée est égale à 366 m²."
On pourrait éventuellement rajouter un texte avec une autre information : "La somme des surfaces DGFiP est égale à 372 m²."

poke @landryb @jusabatier

**Comment by landryb** [comment]
C'est pas vous les spécialistes qui avez spécifié cette fiche UF ? :)

**Comment by MaelREBOUX** [comment]
Ben oui justement... On vieillit parfois...

Si ça défrise personne : tant mieux.

**Comment by MaelREBOUX** [comment]
Ça va éviter de produire ce genre de chose :

```
Contenance DGFIP de l'UF : 78 m²
Surface calculée : 79 m²
Surface bâtie calculée : 79 m²
Pourcentage surface bâtie calculée : 101.3 %
```

**Comment by MaelREBOUX** [comment]
testé et approuvé
