### ISSUE TITLE
Préférences des styles de sélection : difficile de réappliquer le style par défaut

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#447]
Je suis en train de tester la v1.7.1 et je rencontre un bogue mineur.

Je change mes préférences de styles (cf #388).
Je ferme la fenêtre.
Je fais des sélections.
Je rouvre la fenêtre de préférence pour remettre le style par défaut.
Là le clic sur le bouton est inopérant.

Pour pouvoir revenir sur les réglages par défaut :
ctrl + F5
fenêtre de préférences
clic sur le bouton

**Comment by Gaetanbrl** [comment]
Le bogue est reproductible sans avoir à réaliser de sélection.
La configuration par défaut `GEOR.Addon.Cadastre.defaultStyle` est modifiée après la modification d'un paramètre de style. C'est la dernière configuration de style éditée dans la fenêtre qui est reprise comme dernier style par défaut.

**Comment by MaelREBOUX** [comment]
testé et approuvé
