### ISSUE TITLE
[AddOn] Organisation de la fenêtre de recherche de parcelle 

### ISSUE THREAD

**Issue by catmorales** [georchestra/cadastrapp#45]
En utilisant l'interface et selon notre usage actuel de ce genre de fonctionnalités,  nous trouvons qu'il serait plus pratique de faire évoluer cette interface de la façon suivante:
- onglet "par référence" à découper en 2 blocs visibles dans la même fenêtre:
  - bloc "recherche assistée" qui contiendrait toute la partie actuelle "par référence" sans le chargement de fichier csv
  - bloc "recherche directe" qui contiendrait le contenu de l'onglet "Identifiant cadastral"
- onglet par adresse cadastrale, idem pas de changement,
- nouvel onglet "par lot" qui contiendrait le chargement du  fichier csv.

Nous attendons bien sûr un retour de tous sur cette évolution des spécifications.

**Comment by MaelREBOUX** [comment]
Vu #44 il serait peut-être souhaitable que le résultat du chargement du CSV remplisse le textarea de la recherche par identifiant.
Le copier-coller de valeur étant également une recherche par lot.
Donc déplacer les contrôles de chargement d'un fichier dans la recherche par lot ?

Des avis ?

**Comment by pierrejego** [comment]
Pouvez vous faire un petit dessin des fenêtres que vous envisagez pour que je puisse vous dire si c'est faisable facilement ?

**Comment by MaelREBOUX** [comment]
On reformule :
- onglet référence : on supprime le chargement du fichier
- onglet adresse : inchangé
- onglet identifiant : ne permet de copier-coller ou saisir UNE SEULE référence cadastrale
- nouvel onglet "par lot" :
  - une zone comprenant un textarea permettant de copier-coller une longue liste de références
  - une zone permettant d'aller charger un fichier text / csv contenant une liste de référence cadastrale (pensez à explication en ligne / tooltip).

Pour rester en cohérence, rajouter une entrée de menu dans la barre d'outils.

[rajouter dessin]

**Comment by landryb** [comment]
Précision sur l'onglet identifiant: changer le tooltip / aide contextuelle pour rappeler que le champ ne prend qu'un seul ID.
Pour le menu recherche avancee->parcelle ca rajoute une entree 'Par Lot' ouvrant la fenetre sur l'onglet correspondant, comme les autres entrees

**Comment by landryb** [comment]
Et du coup enlever le 'ou charger fichier csv' de l'onglet référence

**Comment by pierrejego** [comment]
Il me semble que l'ensemble des modifications souhaitées ont été effectuée, pouvez vous vérifier si le comportement correspond à vos attentes sur : https://cadastrapp-qualif.asogfi.fr/mapfishapp/

**Comment by landryb** [comment]
@catmorales @MaelREBOUX  c'est bon pour vous ?

**Comment by MaelREBOUX** [comment]
Bien fonctionnellement mais il y a cette zone grise qui ne contient aucun contrôle qui n'est pas assez haute.
Si on ajoute plus de 5 références de parcelle : on a vite l'ascenceur.

![screenshot023](https://cloud.githubusercontent.com/assets/6370443/11148645/300bc9e8-8a1e-11e5-85c6-023ce295c30b.png)

**Comment by landryb** [comment]
> Bien fonctionnellement mais il y a cette zone grise qui ne contient aucun contrôle qui n'est pas assez haute.

C'est le ticket #48. Ce ticket-ci peut être fermé.
