### ISSUE TITLE
Problème de recherche par propriétaire, dnupro

### ISSUE THREAD

**Issue by pierrejego** [georchestra/cadastrapp#455]
En réalisant les tests de la #380, il s'avère que la recherche par dnupro ne fonctionne que pour un seul dnupro.
Il faut modifier la partie serveur pour prendre en compte une liste de dnupro et non pas seulement un seul dnupro.

Pour moi cette fonctionnalité fonctionnait au début, je ne sais pas d'ou vient cette régression, je n'ai rien trouvé dans l'historique du code qui pourrait l'expliquer

**Comment by MaelREBOUX** [comment]
Et boum ! sur la v 1.7.1 récemment mise en prod.

![capture_018](https://user-images.githubusercontent.com/6370443/56961613-7b34e600-6b54-11e9-9861-e6da25a597cb.png)

Je n'utilise pas cette fonction souvent et personne n'a signalé de régression avant.

Si cette issue est fermée c'est que cette régression est soldée  @pierrejego  ?

**Comment by pierrejego** [comment]
A priori c'est autre chose, je n'avais pas le message d'erreur. Juste les réponses correspondant à un dnupro mais pas aux autres dans la liste. Tu peux faire une autre anomalie et si tu peux mettre les traces javascript et cadastrapp.log ?

**Comment by MaelREBOUX** [comment]
Laisse tomber : encore notre F5...

<html><head><title>Request Rejected</title></head><body>The requested URL was rejected. Please consult with your administrator.<br><br>Your support ID is: 12137756330811563348</body></html>
