### ISSUE TITLE
Prénom coupé dans la consultation des informations du propriétaire

### ISSUE THREAD

**Issue by stous** [georchestra/cadastrapp#46]
Sur le Puy en Velay  parcelle AE 0207 (Lon = 3.88719, Lat = 45.04334), les informations sur le prénom du propriétaire semblent coupées : "ROLLAND JEAN AL"  idem dans l'onglet bâtiment (alors que la dénomination dans le même onglet bâtiment fait apparaitre "BADIOU/ROLLAND JEAN ALBERT"

**Comment by MaelREBOUX** [comment]
Probablement pcq il n'y a qu'un attribut d'utilisé pour ça. Je dis ça sans accès à la base pour confirmer.

A lier à #41 pour la résolution.

**Comment by pierrejego** [comment]
Les données viennent de champs différents en base, le "BADIOU/ROLLAND JEAN ALBERT" correspond à un champ ddenom, le prénom lui vient du champ dprnlp qui est limité à 15 caractères dans la base de données à l'origine. Nous ne l'avons pas coupé.  
On peut ne garder que le champ ddenom et les nom complémentaires si vous voulez ?

**Comment by pierrejego** [comment]
Je viens de faire les modifications pour la recherche par nom de propriétaires. Les champs sont bien tronqué à 15 caractère à part le ddenom mais qui ne contient pas forcément les informations.

Les prénoms étant tronqués dans les données d'origine, je ne peux pas les recréer. Seul le champ ddenom (dénomination) est de 60 char et donc non tronqué.

**Comment by MaelREBOUX** [comment]
Oui : on a toujours utilisé l'attribut DDENOM qui vient directement de MAJIC 3.

Dans le modèle ImaCAD :

SELECT IDPROP, DDENOM, NOMA, NOMB FROM proprio
WHERE CODCOMM = '350047' AND LENGTH( DDENOM ) >50

![screenshot072](https://cloud.githubusercontent.com/assets/6370443/10188372/1c05e1e0-675f-11e5-959f-75e233dfc052.png)

phpmyadmin tronque à l'affichage mais les données sont bien là.

@pierrejego de quels autres attributs tu parles ? dnomlp ?

**Comment by MaelREBOUX** [comment]
Pour info, on révérifiera après tes modifs, mais on ne trouve aucun syndicat, commune, HLM, etc, etc.
On dirait qu'il n'y a que des personnes physiques. Merci de vérifier.

**Comment by pierrejego** [comment]
Je parles des attributs dnomlp, dprnlp, dnomcp et dprncp. Les données affichées dans l'IHM viennent de ces champs là. Qui viennent des tables proprietaires de QGIS et Arcopole. Tous les deux ont limités les champs à 15 chars.
Le ddenom lui est bien sur 60 char, mais il ne contient pas que le nom et prénom (comme tu le montres dans la copie d'écran) ça me semble compliqué de le coupé en morceau ne contenant que le nom prénom.

**Comment by MaelREBOUX** [comment]
Pas compris car j'ai pas accès aux bases arcOpole ou QGIS pour regarder. Tu peux faire une capture d'écran basée sur la même requête STP ?

Qu'est-ce qui est gênant à n'utiliser que le ddenom ? On s'en sert depuis 10 ans comme ça ici.

**Comment by pierrejego** [comment]
Effectivement pour les personnes physique, dans l'affichage de la recherche, je met le nom, prénom et pas la dénomination, on je voit donc apparaître que les personnes physique.
Je change l'affichage de la recherche pour mettre le ddenom et nom les champs nom prénom.

Dans la capture d'écran que tu as fait, on voyait d'autres choses que le dénomination dans DDENOM, dans  Arcopole on trouve ça, il n'y a effectivement que les bonnes informations dans ddenom, même si je n'ai pas de cas avec le dnomcp
![image](https://cloud.githubusercontent.com/assets/11499415/10188791/725c736c-6762-11e5-8167-d7855a853ec8.png)

Dans la base Qgis on trouve ça
![image](https://cloud.githubusercontent.com/assets/11499415/10189279/ab8f94ea-6765-11e5-9351-3284d8a666c9.png)
On voit que les informations pour la ligne 6 par exemple, ne sont pas complète dans le ddenom

Par contre l'avantage c'est bien que le prénom n'est pas coupé, mais en cherchant PINEL je ne trouverais pas LaCROIX/CLAUDETTE

J'espère que c'est plus clair :)

**Comment by MaelREBOUX** [comment]
Je remet ci-dessous un extrait de la notice du MAJIC III

DDENOM | Dénomination de personne physique ou morale
DQUALP | Qualité abrégée
DNOMLP | Nom d’usage
DPRNLP | Prénoms associés au nom d’usage
DNOMCP | Nom complément
DPRNCP | Prénoms associés au complément
EPXNEE | Mention du complément NEE si complément

SELECT IDPROP, DDENOM, DNOMLP, DPRNLP, DNOMCP, DPRNCP, EPXNEE
FROM proprio
WHERE CODCOMM = '350363'
AND IDPROP = 'Z00002'

**Les cas que tu décris sont des erreurs de saisie ou des problèmes d'homogénéiésation des saisies dans le temps.** C'est la DGFiP la responsable.

Exemple avec :
SELECT IDPROP, DDENOM, DNOMLP, DPRNLP, DNOMCP, DPRNCP, EPXNEE
FROM proprio
WHERE CODCOMM = '350363'
AND IDPROP = 'Z00002'

![screenshot076](https://cloud.githubusercontent.com/assets/6370443/10190444/f67966b4-676c-11e5-8a2b-1de98afdd508.png)

Pour ce compte proprio (2 personnes), on a 1 monsieur Philippe ZATORSKY marié à une Magdalène ZATORSKY née Magdalène DUSASAN. Et inversement.
**Sauf que les gens de la DGFiP a mis le nom du mari ("Philippe ZATORSKY") de la dame comme nom d'usage au lieu de "Magdalène ZATORSKY". Tout ça à cause des histoire de Monsieur / Madame / Mariage et que l'identité du mari passe toujours d'abord !!!**

Ta ligne 1 QGIS avec LANGLOIS vs BRUYERE-PIROT c'est exactement pareil.

C'est donc pas logique et **c'est donc pour ça qu'il ne faut chercher QUE dans DDENOM**. Le monsieur et la dame sont en indivision donc ont une ligne chacun donc on les retrouve individuellement.

En cherchant PINEL tu vas bien trouver "Bertrand PINEL". Claudette LACROIX c'est sa femme donc c'est normal que tu ne la remonte pas. Tu la retrouveras en consultant de le relevé de propriété de leur compte proprio commun.
A noter que qqn peut avoir la même dénomination sur une commune et posséder plusieurs comptes de proprio pour des indivisions différentes.

OK ?

Note : le "/" qui sépare le nom du reste dans DDENOM est qqch qu'il faudrait traiter dans la vue pour le remplacer par un espace. A moins de traiter ça dans les scripts d'intégration des données.

**Comment by pierrejego** [comment]
Oui :) cette fois je pense qu'on se comprend.

Je modifie la recherche pour chercher uniquement dans le ddenom. 
Pour l'affichage des tableaux de résultat, je laisse pour l'instant le dnomlp, mais je vais regarder pour ne garder que le ddenom dans l'ensemble de l'application.

**Comment by catmorales** [comment]
tu peux aussi tester sur mon cas à Acigné nom MORALES .qui a la même "erreur" de saisie.. un peu de mysoginie  ...;)

**Comment by MaelREBOUX** [comment]
@pierrejego  oui : il faut utiliser uniquement DDENOM. C'est le relevé de propriété qui contient le plus d'infos détaillées. Il sert à ça.

Penser à supprimer les références trop précises aux personnes nommées plus haut : les tickets sont publics.
A faire après fermeture de ce ticket.

**Comment by pierrejego** [comment]
Modification effectuée, la recherche se fait sur le DDENOM et le nom affiché vient du ddenom.
