### ISSUE TITLE
Spinner lors de la génération de documents

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#462]
Pour faire suite à #398 je pense qu'il serait important d'ajouter des spinners lors de la génération de documents (RP, BP, exports, ...).

Ceci permettrait à l'utilisateur de voir qu'un traitement est en cours et ainsi eviter qu'un utilisateur impatient clique plusieurs fois.

**Comment by MaelREBOUX** [comment]
Julien,

Je me permet de fermer ce ticket car ce spinner est maintenant présent dans mapstore2-cadastrapp :  
![image](https://user-images.githubusercontent.com/6370443/148551736-d76a0737-9d64-4c31-89e9-9b53abba61b8.png)
