### ISSUE TITLE
Barre d'outil : rajouter bouton recherche rapide proprio

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#47]
Il faut rajouter un bouton de recherche rapide "Proprio" permettant d'ouvrir la fenêtre de recherche par propriétaire (https://github.com/GFI-Informatique/addons/blob/dev/cadastrapp/js/searchParcelleByOwner.js)

**Comment by pierrejego** [comment]
Ajout d'un bouton d'accès rapide propriétaire qui ouvre sur Nom Usage ou Naissance, visible uniquement en CNIL_1 ou CNIL_2

**Comment by pierrejego** [comment]
Le bouton vient d'étre ajouter, disponible demain sur la machine de qualification

**Comment by pierrejego** [comment]
commit c2b9cb86955f83e916f8120ebf5937e98e7cabd2

**Comment by landryb** [comment]
GFI-Informatique/addons@c463a2d330964e421b8a986131496afa33cfe472
GFI-Informatique/addons@c2b9cb86955f83e916f8120ebf5937e98e7cabd2

**Comment by MaelREBOUX** [comment]
ok : vu
