### ISSUE TITLE
[ Build ] Montée de version de JAVA

### ISSUE THREAD

**Issue by pierrejego** [georchestra/cadastrapp#471]
Pour améliorer la partie serveur, il serait intéressant de changer de version de tomcat et de java.

Le minimum supporté pour la version 1.8 de cadastrapp est le jdk 1.7 et tomcat6.

Pour la version 1.9, il serait intéressant de passer en jdk 11 et tomcat 9. 
Mais au minimum java 1.8 et tomcat 8

**Comment by landryb** [comment]
ok pour java 1.8..
