### ISSUE TITLE
évolutions majic 2019 ?

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#478]
Les donnéees 2019 commencent a arriver, donc @MaelREBOUX, @pierrejego et @mdouchin je vous laisse voir s'il y'a des adaptations à faire dans les modèles de données de cadastrapp et du plugin qgis.. je vais probablement mouliner tout ça d'ici peu, donc probablement essuyer les platres :

* PROP:

> Mise à jour 2019
> Création du code droit bail réel solidaire (code Z) et modification du code droit bail réel B( cf. §2.3).
> Nouvelles valeurs (cf. § 2.9) pour les champs DFORME « forme juridique » et DFORMJUR « forme juridique abrégée ».

* NBAT:

> Mise à jour 2019
> Dans l’article 10, descriptif de la parcelle, création d’un code trésorerie (CCPPER).
> Dans  l’article  30,  descriptif  des  exonérations,  éclatement  du  code  collectivité  « TC » (toutes collectivités) par les codes « C » (commune), « A » (taxe additionnelle), « TS » (taxe spéciale d'équipement) et « GC » (groupement de communes).

* BATI:

> Mise à jour 2019
> - Au  sein  de  l’article  00,  descriptif  du  local,  création  du  champ  CCPPER,  code  de  la trésorerie gestionnaire.
> - Au sein de l’article 10, descriptif du local, le champ FBURX peut prendre une nouvelle valeur (4 : local passible de la TSBCS et/ou de la TSS mais non saisi dans l’application de gestion des données cadastrales).
> - Au sein de l’article 30, descriptif des exonérations des PEV s’appliquant sur la base imposable, la donnée GNEXTL peut prendre les valeurs « AM » (addition de construction – Ville de Paris), « NM » (construction nouvelle – Ville de Paris) et « MB » (boutique et magasins situés hors d’un ensemble commercial dont la surface principale est inférieure à 400 m²). Création d’un article 31, décrivant les exonérations liées au local s’appliquant sur la base imposée avec le même dessin d’enregistrement que l’article 30.

* PDLL et LLOC: RAS

**Comment by landryb** [comment]
[DESCRIPT.zip](https://github.com/georchestra/cadastrapp/files/3397123/DESCRIPT.zip)

Si besoin, les PDF de description des fichiers

**Comment by landryb** [comment]
Pour info, avec la v1.6.2 du plugin qadastre j'ai pu faire un premier test d'import de la commune 03159, avec le pci vecteur de https://cadastre.data.gouv.fr/data/dgfip-pci-vecteur/latest/edigeo/feuilles/03/03159/ et en spéficiant dans le plugin qadastre que les données étaient de 2018 (même si elles sont de 2019) - et a priori l'import dans une base spatialite locale en 1mn s'est bien passé. J'ai aussi pu charger les données dans le plugin, et faire qqs requêtes, donc a priori il n'y a pas de trucs 'bloquants' dans l'immédiat pour des données majic 2019.

J'attends qu'etalab ait sorti le millésime juillet 2019 pour le PCI, et je tente l'import de mes 12 départements dans la base cadastrapp. En attendant je vais refaire un test sur un EPCI avec la version 1.7.1 du plugin, et rebaser ma branche import_cli pour pouvoir scripter les imports.

**Comment by pierrejego** [comment]
A vérifier mais la modification du NBAT risque d'impacter le calcul fait dans le relevé de propriété, il va surement être erronée avec cette nouvelle version (https://github.com/georchestra/cadastrapp/blob/d3c94084fc8f2df580081a1e80a85c063f8a4962/cadastrapp/src/main/java/org/georchestra/cadastrapp/helper/ProprieteHelper.java#L327)

Pour le prop, je pense qu'il va y avoir la table de correlation à mettre à jour, mais pas d'impact direct

Et voir si on souhaite voir apparaître l'article 31....

**Comment by MaelREBOUX** [comment]
Salut @landryb 

Je suis rentré de congés et on m'a signalé ce matin qu'il y avait des évolutions.
Merci pour le pointage.

Je vais ouvrir un ticket sur https://github.com/3liz/QgisCadastrePlugin/issues  pour suivre ça.
Avec @EtienneRouvin on s'y collera la semaine prochaine, normalement.

**Comment by MaelREBOUX** [comment]
Ticket de suivi -> https://github.com/3liz/QgisCadastrePlugin/issues/192

**Comment by landryb** [comment]
Pour info, depuis ce midi cadastrapp 1.8 avec les données de 2019 est prod chez nous sur https://cadastre.craig.fr

**Comment by MaelREBOUX** [comment]
En prod chez nous depuis mercredi dernier également. RAS de ce côté là pour le moment.

Du coup : y a quoi à faire ? Selon moi :
- [ ] rebrancher les requêtes utilisant pevexoneration par pevexoneration_imposable
- [X] identifiant parcellaire QGIS ne contient plus l'année : https://github.com/georchestra/cadastrapp/pull/484

Et rien d'autre. @pierrejego : je vois pas de quelle modif tu parles dans nbat un peu plus haut.

**Comment by MaelREBOUX** [comment]
Ma proposition de modif pour clore ce millésime.
