### ISSUE TITLE
Redimensionnement intelligent des grids/textarea pour s'adapter aux tailles de fenetres

### ISSUE THREAD

**Issue by pigma** [georchestra/cadastrapp#48]
La fenêtre peut être redimensionnée mais les controles à l'intérieur ne s'adaptent pas à la nouvelle taille

**Comment by MaelREBOUX** [comment]
+1

**Comment by pierrejego** [comment]
Bonjour,
est-ce que je peux avoir un peu plus de détails ? Quel comportement souhaitez vous  et quelles sont les contrôles qui ne s'adaptent pas ?

**Comment by pierrejego** [comment]
On vient de faire la point avec @landryb, vous souhaitez que le grid Section Parcelle s'agrandisse, ainsi que le textArea dans l'onglet Lot ?

**Comment by landryb** [comment]
Et pareil pour l'onglet "compte propriétaire" de la fenetre 'recherche propriétaire', que le grid section s'adapte a la taille de la fenetre parente ?

**Comment by MaelREBOUX** [comment]
> vous souhaitez que le grid Section Parcelle s'agrandisse, ainsi que le textArea dans l'onglet Lot ?

Oui

**Comment by landryb** [comment]
Le bug est présent pour toutes les fenêtres: fiche d'information parcellaire, fenetre de résultat de recherche, fenetre d'information foncière, fenetres de recherche (parcelle et propriétaire) .. cf http://i.imgur.com/UVxJxOX.png

J'ai renommé le ticket pour être plus clair.

Quand la fenetre est agrandie en bas ou a droite, le composant extjs correspondant devrait suivre la taille de sa fenetre parente...

**Comment by landryb** [comment]
Pour le redimensionnement en largeur, essayer la propriété 'anchor' des Ext.form (cf https://github.com/georchestra/georchestra/blob/15.06/mapfishapp/src/main/webapp/app/js/GEOR_LayerBrowser.js#L73) - merci @fvanderbiest pour le hint :)

http://docs.sencha.com/extjs/4.2.3/extjs-build/examples/resizer/basic.html a quelques autres exemples du composant 'resizable' .. dans mes souvenirs, l'attribut 'layout' de la fenetre parente pouvait avoir une influence sur les composant fils.

**Comment by pierrejego** [comment]
Merci je vais essayer, en espérant que le fonctionnement 4.2.3 et 3.4.0 sont les mêmes

**Comment by fvanderbiest** [comment]
Quoi, l'addon charge ExtJS 4.2.3 ?

**Comment by pierrejego** [comment]
:) non non pas du tout, c'est bien du 3.4.0 c''est l'exemple donnée qui est en 4.2.3

**Comment by fvanderbiest** [comment]
Ha, ouf, merci pour la clarification :-)

**Comment by landryb** [comment]
Au passage, dans la fenetre de resultat de recherche, je vois que la scrollbar est sur la fenetre - imo elle devrait etre sur le contenu de l'onglet, car dans l'état si on ne redimensionne pas la fenetre et qu'on scrolle tout en bas... le bandeau des onglets a disparu :)

**Comment by pierrejego** [comment]
Modification effectuée pour les fenêtres de recherches, mais pas encore pour les autres..
Il y a un problème sur la fenêtre avec la liste des sélections qui ne met pas de scrollbar si je l'insère dans les onglet au lieu de la fenêtre

https://github.com/GFI-Informatique/addons/commit/12dae137fc33a8729b5d6c77bc0c17165821821a#diff-7a571e55b8ab6ef19c25dd6b9fd20485

**Comment by pierrejego** [comment]
J'ai fait l'ensemble des modifications.

Il reste un comportement que je n'arrive pas à améliorer. J'aurais souhaité que la hauteur de la fenêtre de sélection s'adapte à la hauteur de l'onglet à l'intérieur, mais lorsque j'arrive a avoir ce comportement, je perds la possibilité de mettre une scroll bar... et donc potentiellement la possibilité de voir l'ensemble des éléments. Je laisse donc comme c'est, c'est à dire une fenêtre de taille fixe au démarrage qui peut être agrandi par les utilisateurs.

https://github.com/GFI-Informatique/addons/commit/68d74fc54424c90d193fe3710459aab18f3fc301#diff-5dc43d4ee93a8605f9955571a8911c03
https://github.com/GFI-Informatique/addons/commit/7651652702895190a5ac828547c6c93ce8e4cd7a#diff-7a571e55b8ab6ef19c25dd6b9fd20485
https://github.com/GFI-Informatique/addons/commit/1112c78a60512db4a2473c69dcaeac33f36dcb57#diff-7a571e55b8ab6ef19c25dd6b9fd20485
https://github.com/GFI-Informatique/addons/commit/f55d1ce0760df33760ab5b069596d6a9bed89748#diff-7a571e55b8ab6ef19c25dd6b9fd20485
https://github.com/GFI-Informatique/addons/commit/68d74fc54424c90d193fe3710459aab18f3fc301#diff-7a571e55b8ab6ef19c25dd6b9fd20485
https://github.com/GFI-

**Comment by pierrejego** [comment]
@landryb je te laisse vérifier si le nouveau comportement te va et fermer cette anomalie si c'est bon

**Comment by landryb** [comment]
Comportement ok pour:
- apparition de la scrollbar quand on rentre + de 3 références sur l'onglet réference de la recherche de parcelles. Si on redimensionne la fenetre la scrollbar disparait
- apparition de la scrollbar quand on rentre + de 2 propriétaires sur l'onglet 'compte propriétaire' de la recherche de propriétaires. Par contre, cette recherche ne renvoie rien... commune le puy en velay, recherche 'DURAND' ou 'DURAND/' alors qu'il y'a des résultats avec la complétion sur l'onglet 'nom usage ou naissance'.. ou alors c'est moi qui ne maitrise pas la différence entre propriétaire ou compte propriétaire/compte communal? Mettre un exemple pour l'onglet compte propriétaire ?
- fenetre de résultat de selection -> appartion de la scrollbar ok si trop de resultats pour la taille de la fenetre
- fenetre de résultat de selection -> le bouton fermer n'apparait presque pas http://i.imgur.com/LYBduBB.png (firefox 44)

**Comment by pierrejego** [comment]
Ok je rajoute une description sous le tableau pour les compte propriétaire (c'est le compte communal qu'il faut entrer) 
pour le bouton, ça vient de ta police de caractère, je vais agrandir la fenêtre, chez moi ça passe tout juste 
![image](https://cloud.githubusercontent.com/assets/11499415/12086305/0f311a1a-b2c9-11e5-978b-6ca92dd472a6.png)

**Comment by pierrejego** [comment]
https://github.com/GFI-Informatique/addons/commit/730ac8aec8ab827a010f01a7fb5ac8f4d9776b45#diff-7a571e55b8ab6ef19c25dd6b9fd20485
