### ISSUE TITLE
Documentation pour lecture RP

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#482]
Bonjour,

Existe-t-il déjà une documentation pour aider les utilisateurs à lire les relevés de propriété générés par l'addon ?

**Comment by MaelREBOUX** [comment]
Pas que je sache.

Ca manque aussi pour cadastrapp...
J'espérais pouvoir bosser un peu dessus en août...

**Comment by MaelREBOUX** [comment]
Oups : je croyais que tu postais sur QGISPlugin.

En fait : je voudrais qu'on fasse une doc en MD pour sphinx / readthedocs.
Donc un dépôt github à part dans georchestra. 

Genre :
- georchestra/doc_mapfishapp
- georchestra/doc_cadastrapp
- georchestra/doc_console

etc

**Comment by pierrejego** [comment]
lié à #279  je pense

**Comment by MaelREBOUX** [comment]
Sandrine + Louise : si on pouvait traiter ce ticket pour la doc en cours d'écriture ce serait super !

**Comment by MaelREBOUX** [comment]
@stous + @LouiseBAILLET : si on pouvait traiter ce ticket pour la doc en cours d'écriture ce serait super !

**Comment by stous** [comment]
Documentation utilisateur en cours de rédaction pour Cadastrapp

**Comment by MaelREBOUX** [comment]
Doublon avec #279
