### ISSUE TITLE
[AddOn 005.14] Recherche par Adresse cadastrale - lieudit

### ISSUE THREAD

**Issue by pigma** [georchestra/cadastrapp#49]
La recherche par lieudit en utilisant le champ dédié ne donne aucun résultat (ex: LE BARRAIL sur la commune de Léognan en Gironde), par contre si l'on saisit le nom du lieudit dans le champ d'adresse, l'auto-complétion fonctionne et la recherche renvoie bien une liste de parcelles.

![pb_recherche_lieudit_1](https://cloud.githubusercontent.com/assets/3725336/9272211/84472b00-4280-11e5-84fc-1d3dd46e2f1d.png)

![pb_recherche_lieudit_2](https://cloud.githubusercontent.com/assets/3725336/9272214/89cae742-4280-11e5-811d-79703e01065d.png)

**Comment by MaelREBOUX** [comment]
Je vous propose de regrouper la recherche par voie et lieu-dit au sein de la même interface.
Des avis ?
@pierrejego : ça vous fait bcp de changement en salle des machines ?

**Comment by pigma** [comment]
Effectivement on peut envisager d'utiliser le même champ pour le nom de la voie ou le lieudit si ça apparaît clairement dans l'interface.

**Comment by pierrejego** [comment]
Non cela ne fait pas trop de changement, on peut regrouper dans un même champ.

**Comment by MaelREBOUX** [comment]
Super. Personne contre ?

**Comment by landryb** [comment]
Après discussion, tout le monde est ok pour 'regrouper' nom de voie et lieudit dans le meme champ et faire l'autocomplétion sur les 2 champs en base.

**Comment by pigma** [comment]
Proposition d'interface :

![recherche_adresse_cadastrale](https://cloud.githubusercontent.com/assets/3725336/10051307/4112b1cc-6221-11e5-8df5-640436d6275d.png)

**Comment by pierrejego** [comment]
Modification effectuée
