### ISSUE TITLE
Audit Cadastrapp

### ISSUE THREAD

**Issue by Gaetanbrl** [georchestra/cadastrapp#491]
Cette issue concerne un audit (back-end) :  
* des scripts SQL de génération du modèle Cadastrapp (hors arcOpole)
* des services / appels du modèle Cadastrapp dans le code du module
* des remarques d'ordre général relatifs aux deux points précédents de prés comme de loin

Cette issue ne concerne pas un audit de Cadastrapp au sein de Mapfishapp (front-end). 

N'hésitez-pas si vous avez des idées, des remarques ou des points à intégrer.

**Comment by Gaetanbrl** [comment]
Optimisations à réaliser en lien avec les co-propriétaires comme remonté dans #485.

**Comment by Gaetanbrl** [comment]
![image](https://user-images.githubusercontent.com/16317988/67693265-b8fab600-f9a1-11e9-8079-92a7d047dbae.png)

@jusabatier @MaelREBOUX 
Ce petit schéma serait-il intéressant à mettre dans la doc / [README ](https://github.com/georchestra/cadastrapp/tree/master/script)des scripts ?

Est-il correct ?

**Comment by landryb** [comment]
Il est correct, et je me demande si il ne faudrait pas rajouter geoserver qui tape dans la BD Qgis pour fournir les flux utilisés par la visionneuse... mais ca risquerait de compliquer le schéma

**Comment by Gaetanbrl** [comment]
quelque chose comme cela ? @landryb  
![image](https://user-images.githubusercontent.com/16317988/67749377-53eca200-fa2d-11e9-8955-9c76cf795f75.png)

**Comment by MaelREBOUX** [comment]
Je pense qu'on peut enlever la base SQLite car personne ne s'en sert.
La flèche bleue qui part de la base vers la carte me gêne aussi. En fait : la carte dans QGIS ça me gêne pcq c'est pas notre périmètre.

Si on doit faire figurer des usages carto bureautique, perso je les mettrais à droite des BD.
A droite : usage carto.
Milieu : les BD.
A gauche : usage geOrchestra

Mais je pense que usage bureautique = pas notre périmètre.

**Comment by pierrejego** [comment]
C'est pas faux, juste enlever la flêche bleue remontante de la bdd vers qgis.

**Comment by Gaetanbrl** [comment]
Je résume : 
- pas de flèche bleu, 
- pas de "moniteur" dans le cadre Qgis (usages carto bureautique). Je laisse la grande carte pour montrer que la base de données Qgis comporte des données spatiales chargeables via le plugins Qgis.
- pas de SQLite

**Comment by Gaetanbrl** [comment]
![image](https://user-images.githubusercontent.com/16317988/67751689-dbd4ab00-fa31-11e9-9066-d7e7f9fe4904.png)

**Comment by MaelREBOUX** [comment]
En fait : la flèche bleue = pas possible car la base cadastrapp ne contient pas de données géo.
Et le GeoServer lui est branché sur la BD verte.

Donc je mettrai une progression gauche -> droite
fichiers Majic / EDIGEO  -> BD QGIS -> BD cadastrapp
et en-dessous ce qui est relatif à GeoServer et cadastrap
et encore en-dessous les clients

PS : merci pour le boulot @Gaetanbrl

**Comment by landryb** [comment]
geoserver se connecte a la base QGIS, pas la base cadastrapp..

**Comment by MaelREBOUX** [comment]
> geoserver se connecte a la base QGIS, pas la base cadastrapp..

Pauvre @Gaetanbrl  : on s'acharne (emoji rieur + clin d'œil)

**Comment by Gaetanbrl** [comment]
> mais ca risquerait de compliquer le schéma

D'où l'emplacement de mon GeoServer sans liens directs avec les bases @landryb.

> Pauvre @Gaetanbrl : on s'acharne (emoji rieur + clin d'œil)

Pas de problème 😉 l'objectif c'est qu'à la fin le schéma corresponde et que tout le monde soit d'accord (à peu près).

**Comment by Gaetanbrl** [comment]
En suivant vos recommandations @MaelREBOUX @landryb 
![image](https://user-images.githubusercontent.com/16317988/67756376-2f4af700-fa3a-11e9-90cc-ce373bbebccd.png)

**Comment by pierrejego** [comment]
Il y a aussi un lien entre cadastrapp serveur en bleu et le geoserver pour la partie impression ;)  
Création de l'image pour les bordereaux avec fond de plan et plan cadastral

**Comment by Gaetanbrl** [comment]
> un lien entre cadastrapp serveur en bleu et le geoserver pour la partie impression ;)

Chose faite, merci.

**Comment by MaelREBOUX** [comment]
Mieuuxxxxx ! Bravo.

Est-ce qu'on met un petit cadre "geOrchestra" autour de GeoServer et Cadastrapp ?
Avec un bô logo ?

**Comment by Gaetanbrl** [comment]
> Est-ce qu'on met un petit cadre "geOrchestra" autour de GeoServer et Cadastrapp

Oui c'est possible, donc je viens de rajouter le logo et le cadre.

**Comment by pierrejego** [comment]
@Gaetanbrl  est-ce que tu pourrais mettre ce schéma sur la page d'accueil du Wiki s'il te plaît ?  ( Juste avant "Ce wiki comporte deux parties :"

**Comment by Gaetanbrl** [comment]
@pierrejego c'est fait.

**Comment by MaelREBOUX** [comment]
nickel.

je vais m'utiliser pour faire de la pub pour la v1.9
