### ISSUE TITLE
Fenêtre de recherche : le bouton "Rechercher" doit être grisé

### ISSUE THREAD

**Issue by sdhem** [georchestra/cadastrapp#5]
Le bouton "Rechercher" doit être grisé tant qu'une commune n'est pas sélectionnée.
Le bouton reste grisé après avoir sélectionner une commune.

**Comment by pierrejego** [comment]
Modification effectuée, le bouton Rechercher est grisé à part lors d'une rechercher par Lot qui ne nécessite pas de connaître la commune.
