### ISSUE TITLE
Recherche de parcelles par "Adresse cadastrale" ou "Identifiant cadastral"

### ISSUE THREAD

**Issue by pigma** [georchestra/cadastrapp#50]
Lorsque l'on fait une rechercher de parcelles en utilisant l'onglet "Référence" les parcelles sélectionnées sont mises en surbrillance, par contre pas de surbrillance si les parcelles sont sélectionnées à partir des onglets "Adresse cadastrale" ou "Identifiant Cadastral"

![pb_surbrillance_parcelles_selectionnees_1](https://cloud.githubusercontent.com/assets/3725336/9275002/73ed28f8-429a-11e5-80da-36cad2621e71.png)

![pb_surbrillance_parcelles_selectionnees_2](https://cloud.githubusercontent.com/assets/3725336/9275010/7c4efb48-429a-11e5-87cc-c5f3fd415bfc.png)

![pb_surbrillance_parcelles_selectionnees_3](https://cloud.githubusercontent.com/assets/3725336/9275016/81ba024e-429a-11e5-92d3-05a5c8a3ec05.png)

**Comment by pigma** [comment]
Idem pour les recherches de propriétaires (Par nom ou compte de propriété)

**Comment by MaelREBOUX** [comment]
lier à #37

**Comment by pigma** [comment]
Même propblème avec la Recherche des parcelles par Lot :
![pd_recherche_par_lot](https://cloud.githubusercontent.com/assets/3725336/10581319/4d992050-7682-11e5-8a9f-5c285712071e.png)

**Comment by pierrejego** [comment]
Corrigé en même temps que l'anomalie #74
