### ISSUE TITLE
Traduction incomplète de l'interface

### ISSUE THREAD

**Issue by pigma** [georchestra/cadastrapp#51]
Fenêtre "Recherche de parcelles" et "Recherche de propriétaires" : Close
Fonctions avancées : Owner, By name

**Comment by MaelREBOUX** [comment]
lié à #32

**Comment by landryb** [comment]
Habituellement les clefs de traduction sont en anglais - ici les clefs de traduction sont en francais, et il y'a tres peu de traductions pour l'anglais, donc si mapfishapp est en anglais 90% de l'interface de cadastrapp est en francais. Il y'a peu de chances d'avoir un besoin pour cadastrapp en anglais, mais il faut penser aux anglophones qui visitent nos plateformes...

**Comment by landryb** [comment]
Les traductions anglaises sont a ajouter dans https://github.com/GFI-Informatique/addons/blob/dev/cadastrapp/manifest.json#L30 - si quelqu'un se sent, cela peut se faire facilement directement dans l'interface de github en faisant un fork, une edition locale et une pull request :)

**Comment by pierrejego** [comment]
Modification effectué pour les champs internationalisés, le fichier manifest est maintenant à jour.

Tous les champs (surtout dans les headers de tableau) ne sont pas forcément internationalisé et donc non présent dans le manifest.
