### ISSUE TITLE
problème limitation géographique avec infos de debug

### ISSUE THREAD

**Issue by vfabry** [georchestra/cadastrapp#514]
Bonjour,
J'ai rempli la table  cadastrapp_qgis.groupe_autorisation comme ça :
![image](https://user-images.githubusercontent.com/15424976/78231348-f3c5c480-74d2-11ea-93d6-f7c9bc773ef7.png)

Je ne devrais donc pas voir les noms de propriétaire pour d'autres communes que la 800001. Or je les vois.
Les logs d'erreur à la consultation :

> 02/04/2020 10:48:082020-04-02 08:48:08,246 INFO o.g.c.providers.PreRequestFilter - Incoming request
> 02/04/2020 10:48:082020-04-02 08:48:08,248 DEBUG o.g.c.providers.PreRequestFilter - Parameter list : {_dc=[1585817288166]}
> 02/04/2020 10:48:082020-04-02 08:48:08,252 INFO o.g.c.providers.PreReponseFilter - Sending response
> 02/04/2020 10:48:552020-04-02 08:48:55,361 INFO o.g.c.providers.PreRequestFilter - Incoming request
> 02/04/2020 10:48:552020-04-02 08:48:55,361 DEBUG o.g.c.providers.PreRequestFilter - Parameter list : 
> {parcelle=[800021000CD0172], _dc=[1585817335231]} 
> 02/04/2020 10:48:552020-04-02 08:48:55,362 DEBUG o.g.cadastrapp.service.CadController - Mandatory parameters to check : 800021000CD0172
> 02/04/2020 10:48:552020-04-02 08:48:55,362 DEBUG o.g.cadastrapp.service.CadController - Mandatory parameter is ok
> 02/04/2020 10:48:562020-04-02 08:48:56,542 DEBUG o.g.cadastrapp.service.CadController - Check user CNIL Level
> 02/04/2020 10:48:562020-04-02 08:48:56,543 DEBUG o.g.cadastrapp.service.CadController - Get user roles informations : ROLE_EL_PNR_BDS;ROLE_GT_DRAAF;ROLE_REFERENT;ROLE_GT_EFF_ENER_BAT;ROLE_CADASTRE_CNIL1;ROLE_CADASTRE_CNIL2;ROLE_USER;ROLE_GT_AGENCE;ROLE_GT_RESEAU_DE_DONNEES_SUR_L_ENVIRONNEMENT;ROLE_GT_TU_CAPTES;ROLE_GT_INGENIERIE_FONCIERE;ROLE_GT_TU_CAPTES_REDACTEUR
> 02/04/2020 10:48:562020-04-02 08:48:56,543 DEBUG o.g.cadastrapp.service.CadController - Check user CNIL Level : 2
> 02/04/2020 10:48:562020-04-02 08:48:56,543 DEBUG o.g.cadastrapp.service.CadController - Check user geographical limitation
> 02/04/2020 10:48:562020-04-02 08:48:56,543 DEBUG o.g.cadastrapp.service.CadController - user roleList : ROLE_EL_PNR_BDS;ROLE_GT_DRAAF;ROLE_REFERENT;ROLE_GT_EFF_ENER_BAT;ROLE_CADASTRE_CNIL1;ROLE_CADASTRE_CNIL2;ROLE_USER;ROLE_GT_AGENCE;ROLE_GT_RESEAU_DE_DONNEES_SUR_L_ENVIRONNEMENT;ROLE_GT_TU_CAPTES;ROLE_GT_INGENIERIE_FONCIERE;ROLE_GT_TU_CAPTES_REDACTEUR
> 02/04/2020 10:48:562020-04-02 08:48:56,543 DEBUG o.g.cadastrapp.service.CadController - List to String : WHERE idgroup IN (?,?,?,?,?,?,?,?,?,?,?,?)
> 02/04/2020 10:48:562020-04-02 08:48:56,960 DEBUG o.g.c.service.InfoBulleController - List des informations avec proprietaire : {parcelle=800021000CD0172, cgocommune=800021, dnupla=172, ccopre=, ccosec=CD, surfc=6364.0, libcom=AMIENS, dcntpa=6361, dnvoiri= , dindic= , cconvo=SEN, dvoilib=DE L EPOUSEE, proprietaires=[
> {app_nom_usage=MME xxxxxxx xxxxxx} 
> ]}
> 02/04/2020 10:48:562020-04-02 08:48:56,960 DEBUG o.g.cadastrapp.service.CadController - Mandatory parameters to check : 800021000CD0172
> 02/04/2020 10:48:562020-04-02 08:48:56,960 DEBUG o.g.cadastrapp.service.CadController - Mandatory parameter is ok
> 02/04/2020 10:48:562020-04-02 08:48:56,960 DEBUG o.g.cadastrapp.service.CadController - Check user geographical limitation
> 02/04/2020 10:48:562020-04-02 08:48:56,960 DEBUG o.g.cadastrapp.service.CadController - user roleList : ROLE_EL_PNR_BDS;ROLE_GT_DRAAF;ROLE_REFERENT;ROLE_GT_EFF_ENER_BAT;ROLE_CADASTRE_CNIL1;ROLE_CADASTRE_CNIL2;ROLE_USER;ROLE_GT_AGENCE;ROLE_GT_RESEAU_DE_DONNEES_SUR_L_ENVIRONNEMENT;ROLE_GT_TU_CAPTES;ROLE_GT_INGENIERIE_FONCIERE;ROLE_GT_TU_CAPTES_REDACTEUR
> 02/04/2020 10:48:562020-04-02 08:48:56,960 DEBUG o.g.cadastrapp.service.CadController - List to String : WHERE idgroup IN (?,?,?,?,?,?,?,?,?,?,?,?)
> 02/04/2020 10:48:572020-04-02 08:48:57,306 DEBUG o.g.c.service.InfoBulleController - User does not have enough right to see information about parcelle
> 02/04/2020 10:48:57org.springframework.dao.EmptyResultDataAccessException: Incorrect result size: expected 1, actual 0
> 02/04/2020 10:48:57 at org.springframework.dao.support.DataAccessUtils.requiredSingleResult(DataAccessUtils.java:69)
> 02/04/2020 10:48:57 at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:799)
> 02/04/2020 10:48:57 at org.springframework.jdbc.core.JdbcTemplate.queryForMap(JdbcTemplate.java:832)
> 02/04/2020 10:48:57 at org.georchestra.cadastrapp.service.InfoBulleController.getInfoBulleUniteFonciere(InfoBulleController.java:173)
> 02/04/2020 10:48:57 at org.georchestra.cadastrapp.service.InfoBulleController.getInfoBulle(InfoBulleController.java:59)
> 02/04/2020 10:48:57 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 02/04/2020 10:48:57 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 02/04/2020 10:48:57 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 02/04/2020 10:48:57 at java.lang.reflect.Method.invoke(Method.java:498)
> 02/04/2020 10:48:57 at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:181)
> 02/04/2020 10:48:57 at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:97)
> 02/04/2020 10:48:57 at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:200)
> 02/04/2020 10:48:57 at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)
> 02/04/2020 10:48:57 at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
> 02/04/2020 10:48:57 at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
> 02/04/2020 10:48:57 at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
> 02/04/2020 10:48:57 at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
> 02/04/2020 10:48:57 at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:251)
> 02/04/2020 10:48:57 at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
> 02/04/2020 10:48:57 at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
> 02/04/2020 10:48:57 at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
> 02/04/2020 10:48:57 at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)
> 02/04/2020 10:48:57 at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:293)
> 02/04/2020 10:48:57 at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:217)
> 02/04/2020 10:48:57 at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
> 02/04/2020 10:48:57 at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:268)
> 02/04/2020 10:48:57 at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
> 02/04/2020 10:48:57 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
> 02/04/2020 10:48:57 at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214)
> 02/04/2020 10:48:57 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
> 02/04/2020 10:48:57 at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
> 02/04/2020 10:48:57 at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
> 02/04/2020 10:48:57 at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
> 02/04/2020 10:48:57 at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
> 02/04/2020 10:48:57 at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
> 02/04/2020 10:48:57 at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
> 02/04/2020 10:48:57 at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
> 02/04/2020 10:48:57 at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
> 02/04/2020 10:48:57 at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
> 02/04/2020 10:48:57 at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
> 02/04/2020 10:48:57 at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
> 02/04/2020 10:48:57 at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
> 02/04/2020 10:48:57 at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
> 02/04/2020 10:48:57 at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
> 02/04/2020 10:48:57 at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
> 02/04/2020 10:48:57 at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:152)
> 02/04/2020 10:48:57 at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
> 02/04/2020 10:48:57 at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
> 02/04/2020 10:48:57 at org.eclipse.jetty.server.Server.handle(Server.java:505)
> 02/04/2020 10:48:57 at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
> 02/04/2020 10:48:57 at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
> 02/04/2020 10:48:57 at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
> 02/04/2020 10:48:57 at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
> 02/04/2020 10:48:57 at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
> 02/04/2020 10:48:57 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
> 02/04/2020 10:48:57 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
> 02/04/2020 10:48:57 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
> 02/04/2020 10:48:57 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
> 02/04/2020 10:48:57 at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
> 02/04/2020 10:48:57 at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
> 02/04/2020 10:48:57 at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
> 02/04/2020 10:48:57 at java.lang.Thread.run(Thread.java:748)
> 02/04/2020 10:48:572020-04-02 08:48:57,308 INFO o.g.c.providers.PreReponseFilter - Sending response
> 

Vincent

**Comment by pierrejego** [comment]
Pour information, il y a avait le même type d'erreur dans les issues #129 #344 et #287.
Est-ce que je peux avoir les données sur cette commune pour faire un test ?

**Comment by MaelREBOUX** [comment]
@vfabry  est-ce que ton problème est toujours d'actualité ?

**Comment by vfabry** [comment]
je ferme.

**Comment by MaelREBOUX** [comment]
MERCI
