### ISSUE TITLE
Amélioration du script de build js

### ISSUE THREAD

**Issue by RemiDesgrange** [georchestra/cadastrapp#515]
Bonjour,

Le script de build du js (https://github.com/georchestra/cadastrapp/blob/master/cadastrapp/jsbuild/jsbuild.sh) fait appelle a "python" sans spécifer la version or sur de nombreuse distribution linux la version de python par défaut est la 3.X. 

Je vais proposer une PR pour faire en sorte de spécifier l'appel a python2. Et également être sur d'appeler la version "virtualenv"

**Comment by landryb** [comment]
Fwiw this broke the build for github actions , cf https://github.com/georchestra/cadastrapp/actions

**Comment by landryb** [comment]
ah, sorry, hadnt understood https://github.com/georchestra/cadastrapp/pull/516#issuecomment-624601554 was about it. Coffee didnt hit yet.

**Comment by RemiDesgrange** [comment]
FYI, I base the script on what I've done in [mapfishapp](https://github.com/georchestra/georchestra/blob/20.0.x/mapfishapp/jsbuild/build.sh)
