### ISSUE TITLE
Changer le message

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#517]
![image](https://user-images.githubusercontent.com/6370443/82811270-a2153700-9e90-11ea-9f5a-7a229367fffc.png)

Ce message est trop technique : un administrateur le comprend tout de suite mais pas un utilisateur. Donc, demande de support pour pas grand chose.

Trouver un message plus orienté utilisateur.

**Comment by MaelREBOUX** [comment]
Heu : comme c'est côté client : à faire également pour MapStore2 ?

**Comment by pierrejego** [comment]
Mais quoi comme message ?

**Comment by jusabatier** [comment]
Peut-être un truc du genre : 

> La parcelle demandée n'a pas pu être localisée sur la carte, probablement suite à la prise en compte encore partielle d'une mutation (division, fusion, ...). Vous pouvez essayer de retrouver une parcelle fille où mère si vous connaissez ses références, ou en la localisant manuellement sur le plan.

Ca correspond plus où moins à ce que j'explique par téléphone aux utilisateurs qui m'appellent.

**Comment by MaelREBOUX** [comment]
Je clos. éventuellement à reporter sur mapstore2-georchestra.
