### ISSUE TITLE
Zoom sur la sélection

### ISSUE THREAD

**Issue by pigma** [georchestra/cadastrapp#52]
Le bouton de recentrage sur la sélection ne fonctionne pas lorsque les parcelles ont été sélectionnées par "Adresse cadastrale", "Identifiant cadastral", "Nom de propriétaire", "Compte de propriétaire".

Lié au #50 (pas de sélection graphique)

**Comment by pierrejego** [comment]
La modification de la fenêtre d'affichage des resultats de parcelle semble avoir corrigé ce problème. Pouvez-vous me le confirmer.

Pour information, le bouton zoom dans la barre de menu zoom sur l'ensemble des entitées de tous les onglets. Puis sur chaque onglet, il y a deux boutons zoom, un pour la liste complète et l'autre pour la selection.

**Comment by pigma** [comment]
Effectivement la nouvelle fenêtre "Sélection de parcelles" corrige le problème
