### ISSUE TITLE
Fix github actions (boundless/packages.georchestra.org repo broken ?)

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#523]
github actions are broken since #516, apparently because now it hits the dead boundless repo, or packages.georchestra.org maven repo has an expired https cert...

 cf https://github.com/georchestra/georchestra/pull/3095 for ideas

**Comment by pierrejego** [comment]
link to #523 
done

**Comment by landryb** [comment]
https://github.com/georchestra/cadastrapp/actions/runs/199195879 is green whooo \o/
