### ISSUE TITLE
[UI] Mémoriser les recherches de parcelles/propriétaires

### ISSUE THREAD

**Issue by pigma** [georchestra/cadastrapp#53]
Il serait intéressant de conserver en mémoire les critères de la dernière recherche pour les fenêtres "Recherche de parcelles" et "Recherche de propriétaires" (actuellement tout est effacé à chaque fermeture de la fenêtre) et d'ajouter un bouton "Effacer tous les critères".

**Comment by landryb** [comment]
Ca doit pouvoir se faire en utilisant l'api localstorage, qui est encapsulée par GEOR.ls

**Comment by jusabatier** [comment]
Nous avons la même demande d'un élu qui voudrait que la commune précédemment sélectionnée soit gardée en mémoire et pré-remplie. Il est vrai que cela serait plus pratique pour les secrétaire de commune qui vont toujours traiter la même commune de ne pas avoir à la sélectionner à chaque fois.

Est-il prévu de mettre en place cette évolution ?

**Comment by MaelREBOUX** [comment]
ça l'air ok : on peut fermer @jusabatier

**Comment by landryb** [comment]
La demande initiale de @pigma était plus vaste, pas uniquement sur le champ 'nom de commune'... ca reste a mon avis une évolution intéressante.

**Comment by jusabatier** [comment]
Pour moi autant garder en mémoire le nom de commune est d'une très grande utilité pour les secrétaires de mairie qui consultent toujours la même commune, en revanche je doute de la pertinence de garder le nom d'un propriétaire qui va être a mon avis spécifique à une recherche et changer à la prochaine.
Cela alourdirait l'utilisation du module.

**Comment by MaelREBOUX** [comment]
Moi je suis pas opposé à cette évolution : à garder de côté et en rediscuter ultérieurement (avant fin 2016).
PS : je veux mettre des labels !

**Comment by MaelREBOUX** [comment]
@landry : change au moins le titre pour [évolution] mémoire des recherches en cours

**Comment by MaelREBOUX** [comment]
Après échanges entre Rennes et Le Puy : aucun utilisateur n'a remonté ce besoin après plusieurs mois de mise en service de l'outil.
A rouvrir si nécessaire.
