### ISSUE TITLE
Données lots / locaux incomplètes à cause des données DGFiP

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#531]
Bonjour tous,

Des utilisateurs nous ont remonté des soucis avec le contenu des lots de copropriétés. Si on tente d'imprimer un bordereau de lots de copro : celui-ci est soit vide soit incomplet. Le problème a été identifié et provient des données fournies cette année par la DGFiP qui diffèrent largement sur le dénominateur du lot (attribut  `lotslocaux.ddenql` ).

En fait : toutes les données sont bine là dans la base cadastre_qgis mais il manque des données lots dans la vue matérialisée de cadastrapp nommée `lot`
C'est donc la requête de la vue matérialisée qui est en cause :

https://github.com/georchestra/cadastrapp/blob/7fc33b68c78a0c49a3ba23bdf696fbf3ba656935/script/qgis/views/qgisLot.sql#L9-L14

**Le pb vient spécifiquement de la clause where `where ddenql not like '0000000'`.  La requête exclut tous les lots avec ce dénominateur donc cette année on perd 25 % des infos !**

Bon. Même si clairement il y a une régression des données DGFiP, **est-ce qu'on peut sereinement enlever cette clause WHERE ?**

ping @landryb @jusabatier @pierrejego

**Comment by MaelREBOUX** [comment]
On va remonter les donnée de 2019 fraîchement remplacées pour compter le nb de lots avec `ddenql = '0000000' ` et voir le différentiel.

**Comment by MaelREBOUX** [comment]
En 2019 : 81 000 lots non affichés sur 304 000 soit 26 %.
La situation n'est donc pas récente :(

**Comment by MaelREBOUX** [comment]
Sur 2 parcelles tests on est allé voir et le nb de locaux / lots varie selon les années à cause de travaux mais en comparant avec VisuDGFiP on confirme que on n'est pas bon.

Donc je pousse une PR.

**Comment by MaelREBOUX** [comment]
On a patché notre test et prod et ça donne ça 

![image](https://user-images.githubusercontent.com/6370443/95870199-84c40500-0d6c-11eb-9c8f-66e34068efb9.png)


ci-joint un patch pour ceux que ça intéresse, en attendant une release 1.9.1


[patch.zip](https://github.com/georchestra/cadastrapp/files/5371800/patch.zip)

**Comment by landryb** [comment]
je comprends que ca fait disparaitre des données, mais est-ce qu'on pourrait comprendre tout d'abord pourquoi ce `where ddenql not like '0000000'` était la a l'origine/d'ou il venait ? @pierrejego ? :)

**Comment by MaelREBOUX** [comment]
Je pense que c'estr sa collègue GFi de l'époque qui a été prescriptrice. En tout cas dans VisuDGFiP on a toutes celles qui manque. Mais VisuDGFip ne montre pas les tantièmes (en tout cas je les ai pas vu).

**Comment by pierrejego** [comment]
Pardon, ce message est passé à travers les mailles. 
C'est effectivement bien ancien, j'ai donc ressorti mes anciennes notes. C'était voulu, lors des tests nous avions remarqué que certaines valeurs étaient remplies avec des 0. Ce qui n'a aucun sens pour un dénominateur. 
D'ailleurs je pense toujours que ça n'a pas de sens et qu'il faut peut être aller voir côté importation Qgis pour vérifier si c'est bien volontaire.

**Comment by MaelREBOUX** [comment]
Il me semble qu'on a vérifié avec @EtienneROUVIN à l'époque et les zéros sont dans les fichiers DGFiP.

Faut re-vérifier du coup...

**Comment by MaelREBOUX** [comment]
On a vérifié et les données sont ainsi 

![image](https://user-images.githubusercontent.com/6370443/114519588-d7f61200-9c40-11eb-81ec-1b3071df0530.png)

Donc : go pour la PR SVP.
