### ISSUE TITLE
[AddOn.004.13] Recherche de parcelles: doublons dans liste des résultats

### ISSUE THREAD

**Issue by pigma** [georchestra/cadastrapp#54]
Sur l'onglet "Référence" si l'on clique plusieurs fois sur "Rechercher" sans fermer la fenêtre "Sélection de parcelles" on obtient plusieurs lignes avec la même parcelle (cf copies d'écran).

![pb_boublon_liste_parcelle](https://cloud.githubusercontent.com/assets/3725336/9738252/f269191c-564a-11e5-9f26-893b6d938b05.png)

**Comment by pierrejego** [comment]
Un bug dans la gestion des ongles empêchait l'ouverture d'un nouvel onglet.

Le comportement qui était attendu, était l'ouverture d'un nouvel onglet à chaque fois que l'on clique sur le bouton recherche qui à avoir deux fois le même tableau. Ce comportement permet de rajoute en cliquant sur la carte d'autres parcelles, et d'avoir des selections différentes en partant de la même recherche.

Est-ce que ce comportement vous va, ou faut-il le modifier ?

**Comment by landryb** [comment]
J'arrive encore a avoir des doublons sur la PF de qualif GFI si sur un onglet/resultat de recherche avec une ligne interesectant 2 parcelles, je fais une nouvelle ligne interesectant 3 parcelles (dont une déja selectionnée par la ligne précédente) - au lieu d'avoir 4 parcelles j'en ai 5 avec un doublon sur celle interesectée par les 2 lignes. 

Mais sinon oui, on veut bien un nouvel onglet a chaque fois qu'on fait une recherche textuelle, meme si les params n'ont pas changé.

**Comment by pierrejego** [comment]
Je n'ai pas encore retouché à la sélection par la carte, je vérifierais les doublons à ce moment là. Normalement ici je n'ai corrigé que les doublons lors d'une recherche par les formulaires.

**Comment by pierrejego** [comment]
Les modifications apportées lors des changements d'état de la sélection par cliques on corrige ce comportement
