### ISSUE TITLE
Nom de naissance - utilisation de dnomlp à la place de ddenom

### ISSUE THREAD

**Issue by Gaetanbrl** [georchestra/cadastrapp#545]
Vu avec @MaelREBOUX .

Pour la recherche par nom de naissance dans le plugin Qgis Cadastre, c'est le champ `dnomlp `qui sera utilisé à la place du champ `ddenom`.

https://github.com/3liz/QgisCadastrePlugin/issues/119

Est-ce qu'on utiliserait pas également le champ `dnomlp` pour la composition du nom de naissance dans la vue `proprietaire ` à la place de `ddenom ` ? Ceci pour s'aligner avec Qgis (quand la PR sera validée). 

https://github.com/georchestra/cadastrapp/blob/46de8d0b19cc68637f7ea5d251f05d74860145f7/script/qgis/views/qgisProprietaire.sql#L114-L120

**Comment by MaelREBOUX** [comment]
Je vote pour aligner avec la ligne 115 et virer ddenom

**Comment by MaelREBOUX** [comment]
Pour faciliter la compréhension du truc : 

```sql
SELECT
  ccocom, comptecommunal, ddenom,
  CASE
      WHEN gtoper = '1' THEN COALESCE(rtrim(dqualp),'')||' '||COALESCE(rtrim(dnomus),'')||' '||COALESCE(rtrim(dprnus),'')
      WHEN gtoper = '2' THEN trim(ddenom)
  END AS nom_usage,
  CASE
      WHEN gtoper = '1' THEN COALESCE(rtrim(dqualp),'')||' '||COALESCE(rtrim(dnomlp),'')||' '||COALESCE(rtrim(dprnlp),'')
      WHEN gtoper = '2' THEN trim(ddenom)
  END AS app_nom_naissance
FROM cadastre_qgis.proprietaire
```

**Comment by MaelREBOUX** [comment]
Pour être raccord avec https://github.com/3liz/QgisCadastrePlugin/pull/274
