### ISSUE TITLE
Ne pas inclure/utiliser de fichiers provenant de ext/examples

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#55]
ext/examples n'est plus inclus dans mapfishapp dans georchestra 15.06, or 4 fichiers sont inclus dans le manifest.json (cf https://github.com/GFI-Informatique/addons/blob/dev/cadastrapp/manifest.json#L18) - il faudrait en importer une copie dans cadastrapp si c'est nécessaire.

Cf https://github.com/georchestra/georchestra/issues/965 et https://github.com/georchestra/georchestra/issues/966

**Comment by pierrejego** [comment]
https://github.com/GFI-Informatique/addons/commit/ffbde64a1df39ec0c89ad9e76e6979a27b41cb47

Modification effectuée, suppression de deux JS non utilisé et déplacement de la lib FileUpload dans l'addon
