### ISSUE TITLE
fix CI when docker is not in use

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#550]
#510 added `build-docker` target, which is run inconditionally by the CI.

it doesnt check if what's necessary for the docker crap is present, so all jobs globally fail now, even if `build-deb-package` succeeds. ex https://github.com/landryb/cadastrapp/actions/runs/527764075 fails with ` Error: Input required and not supplied: username `.

please add what's necessary to this yaml whack-a-mole so that the task is skipped if what it expects isnt present :)

**Comment by fvanderbiest** [comment]
Credentials should already be provided by organization-wide secrets, as per https://github.com/georchestra/cadastrapp/blob/master/.github/workflows/cadastrapp.yml#L82-L86

Puzzled ...

@pmauduit - any hints ?

**Comment by landryb** [comment]
well, if i want to do a PR on the main repo, i push a branch to my fork, and by default  apparently the CI runs on my fork/repo, which doesnt have any kind of secret. so the CI fails ?

And what if someone else not in the org wants to do a PR, and is said 'your PR failed' just because said someone doesnt have any docker account ?

**Comment by fvanderbiest** [comment]
OK, didn't notice it runs on your fork.
If this is the case, the docker push steps should be skipped if not running in the org repo.

**Comment by fvanderbiest** [comment]
like in https://github.com/georchestra/georchestra/blob/2ff8266ca2134864e444ceb718840c03c1cb1e3f/.github/workflows/cas.yml#L58
