### ISSUE TITLE
Peut-on se passer de dblink pour la source des données cadastre QGIS ?

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/cadastrapp#553]
Je rapporte ici un questionnement de @pmauduit : "Je me demande à quoi sert le dblink, maintenant que le modèle arcopole n'est plus supporté. On devrait pouvoir mettre les vues matérialisées dans la même base ?"

**Comment by landryb** [comment]
on en a causé sur IRC, pour moi il n'a plus lieu d'etre, ca peut tres bien etre 2 schemas distincts dans la meme base.

par contre, il faudra bien penser a tout ce qui est migration, changements de doc, etc, etc... mais a terme, ca *pourrait* rendre le calcul des vues matérialisées plus rapide (3h ici pour 12 départements..)

**Comment by MaelREBOUX** [comment]
Heu : ici ça n'est pas dans la même base ni sur la même machine. Pour ça que le dblink a été retenu. C'est un arbitrage imposé par les architectures.
ouais ok : surtout la notre qui est compliquée mais c'est la réalité.

Donc je propose le statut quo.
Car sinon ça va impliquer de maintenir le code SQL en vue et en dblink...

A moins que les _foreign tables_ soit une piste ?

**Comment by sigrmed** [comment]
Nous avons clairement séparé les bases "applicatives " des bases référentielles SIG. 
Sigrmed c'est catherine ....

**Comment by landryb** [comment]
perso ca ne m'impacte pas (avec ou sans separation), la seule chose a y gagner serait sur le temps de calcul des MV.

**Comment by MaelREBOUX** [comment]
En fait vu notre archi actuelle il me semble qu'on pourrait se passer de la base applicative cadastrapp qui est sur un serveur geOrchestra. Car après tout : tout le reste des données est déjà dans la BD principale. Et que si ça tombe de tte façon plus rien ne marcherait alors l'intérêt d'avoir un cadastrapp qui répond tt seul est limité.

Donc, sous couvert de @catmorales oui on pourrait maintenant se simplifier la vie en ayant :
* 1 schéma cadastre_qgis
* 1 schéma cadastrapp
dans la même base de données.

PS : c'est pas vues matérialisées VS dblink, actuellement c'est dblink + vues matérialisées.

**Comment by landryb** [comment]
j'ai pas dit que c'était l'un VS l'autre, c'est juste que la construction des MV prend un certain temps, et je pense qu'une partie de ce temps est due a l'utilisation de dblink, même si c'est sur localhost y'a un overhead...

Après, si on fait sauter dblink, on peut *aussi* faire sauter les MV, vu qu'elles ont été ajoutées à cause de dblink.. ainsi on ne pourrait plus avoir que des vues 'simples' dans le schéma cadastrapp, ce qui permettrait au passage de diminuer sa taille.. actuellement ma db cadastrapp de production pour un millésime fait 36Go, et la db qadastre 92Go.

ah, et aussi, nommer les schémas par millésime c'est pas mal :)
- `cad2020`
- `qad2020`

**Comment by pierrejego** [comment]
Hello, je vous rejoins c'était bien l'objectif a terme en arrêtant Arcopole. Et en plus le modèle intermédiaire de cadastrapp n'est peut être plus non plus nécessaire. Avec quelques modifications, il y a surement possibilité d'appeler directement la db qgis cadastre.
Il faudrait regarder de plus prêt.

**Comment by jusabatier** [comment]
Le modèle intermédiaire de cadastrapp reste bien pratique lorsqu'on souhaite extraire de la donnée du cadastre car il est plus human friendly que les données brutes du cadastre.

Il permet d'avoir plus rapidement des extractions de données un peu plus complexe pour les services.

**Comment by MaelREBOUX** [comment]
Le sujet était plutôt de réinternaliser vers cadastre_qgis ce qui pourrait l'être. C'est-à-dire les vues, à défaut qu'elles soient matérialisées.
Mais comme @jusabatier  je pense qu'on va drastiquement perdre de la perf si on vire les vues matérialisées. N'est-ce pas @EtienneRouvin ? Je vote contre. mais je comprend le pb de gain de place de @landryb 

Donc je propose :
1. qu'on parte du postulat qu'on travaille dorénavant dans la même BD
2. que le script de création des données donne le choix de travailler avec des vue simples ou des vues matérialisées

Pour la question des schémas avec le nom des millésimes @landryb : il n'y aura pas de consensus. Ton besoin est lié à ton archi, ta façon de maj les données, etc. Et c'est pour moi plus une question du registre du plugin QGIS.

**Comment by pierrejego** [comment]
Hello, 
La vue matérialisée c'était pour des problèmes de performance. On peut revoir la structure du modèle pour se rapprocher le plus de celui que QGis, et pourquoi pas utiliser en grande partie directement la base de données Qgis.

Mais je pense que le DBlink peut être nécessaire dans certains cas, qu'il faut le rendre optionnel en modifiant cette partie des requêtes SQI.

https://github.com/georchestra/cadastrapp/blob/72baae52ae41f2cdd07e6e64dd6e2e9b2ea1242c/script/qgis/views/qgisCoProprieteParcelle.sql#L7

Et au lancement du Shell il n'y aura plus qu'a choisir DBLink ou pas (ou pourrait même l'automatiser si les deux hosts sont les mêmes)

Première étape le DBLink, et dans le futur regarder comment simplifier la base de données. Par exemple la partie commun ce n'est que de la recopie de données de référence Qgis

**Comment by MaelREBOUX** [comment]
Work in progress comme disent les auvergats : https://github.com/georchestra/cadastrapp/tree/issue_553/database

Je vais sortir la partie initialisation de la BD et des schémas pour mettre ça uniquement dans la doc car on a tous nos contraintes et au final les BD et schémas sont tjs existants. Ce qui nous intéresse c'est : purge puis chargement.
Idem avec les tables des demandes d'informations foncières : une fois créées : on n'y touche plus.

**Comment by MaelREBOUX** [comment]
bon. comme je m'y attendais un peu @pierrejego on va pas pouvoir faire un truc dynamique pour les vues mat avec / sans dblink.

Syntaxe avec dblink

```sql
DROP MATERIALIZED VIEW  IF EXISTS cadastrapp.commune ;
CREATE MATERIALIZED VIEW cadastrapp.commune AS 
	SELECT commune.cgocommune, -- Code commune INSEE
			commune.annee, -- Annee
			commune.clerivili, -- Zone alphabétique MAJIC2 - not use
			commune.libcom, -- Nom de commune
			commune.libcom_maj, -- Nom de commune majuscule
			commune.libcom_min, -- Nom de commune minuscule
			commune.typcom -- Différencie commune recensées de rurales - not use
		FROM dblink('host=localhost port=5432 dbname=bdu user=cadastre_qgis_user password=cadastre_qgis_mdp'::text,
			'select 
				communeqgis.ccodep|| communeqgis.ccodir|| communeqgis.ccocom as cgocommune,
				communeqgis.annee,
				communeqgis.clerivili,
				rtrim(communeqgis.libcom),
				rtrim(upper(communeqgis.libcom) )as libcom_maj,
				rtrim(initcap(lower(communeqgis.libcom))) as libcom_min,
				typcom 
			from cadastre_qgis.commune communeqgis where typcom is not null'::text)
	commune(
		cgocommune character varying(6),
		annee character varying(4), 
		clerivili character varying(1), 
		libcom character varying(30), 
		libcom_maj character varying(30), 
		libcom_min character varying(30), 
		typcom character varying(1));
```

Syntaxe avec 2 schémas dans la même BD

```sql
DROP MATERIALIZED VIEW  IF EXISTS cadastrapp.commune ;
CREATE MATERIALIZED VIEW cadastrapp.commune AS 
	SELECT commune.cgocommune, -- Code commune INSEE
			commune.annee, -- Annee
			commune.clerivili, -- Zone alphabétique MAJIC2 - not use
			commune.libcom, -- Nom de commune
			commune.libcom_maj, -- Nom de commune majuscule
			commune.libcom_min, -- Nom de commune minuscule
			commune.typcom -- Différencie commune recensées de rurales - not use
	FROM 
(
SELECT 
	communeqgis.ccodep|| communeqgis.ccodir|| communeqgis.ccocom as cgocommune,
	communeqgis.annee,
	communeqgis.clerivili,
	rtrim(communeqgis.libcom) as libcom,
	rtrim(upper(communeqgis.libcom) )as libcom_maj,
	rtrim(initcap(lower(communeqgis.libcom))) as libcom_min,
	typcom 
from cadastre_qgis.commune communeqgis where typcom is not null
) as commune
```

Le pb est qu'il y a plus que la clause FROM à modifier car PG réclame, par ex un alias à la fin du SELECT source.
Donc à ce stade je pense que c'est plus rapide et plus simple de gérer de façon séparée la création des vues matérialisées dlink / pas dblink.
Pour résumer : le dblink réclame des choses supplémentaires (typiquement les datatypes).

**Comment by MaelREBOUX** [comment]
et on a d'autres détails de ce genre à régler / adapter  : ```sql ERROR:  column commune.libcom does not exist ```

**Comment by MaelREBOUX** [comment]
Bon. J'ai fini.

Saut que j'ai pas de cadastrapp sous la main pour tester cette nouvelle façon de créer les données.

Ce qu'il resterait à faire pour optimiser le truc :
- [ ]  minuteur pour les temps d'exécution
- [ ]  créer le script de contrôle des droits définis dans le fichier de configuration
- [ ]  créer un script qui mettent bien les droits sur les données cadastre_qgis (on a ça ne python à rennes)
- [ ]  créer un script bilan / de contrôle pour compter le nb d'enregistrements dans certaines tables clés pour voir si on se plante pas

**Comment by MaelREBOUX** [comment]
oups @pierrejego faudra modifier la doc pour indiquer le fonctionnement du nouveau script **AVANT** de faire une release

https://docs.georchestra.org/cadastrapp/latest/guide_installation/donnees.html#donnees-cadastrales-pour-cadastrapp

**Comment by MaelREBOUX** [comment]
Oups : nous avons un conflit avec https://github.com/georchestra/cadastrapp/pull/567
