### ISSUE TITLE
Mettre à jour les liens vers la documentation des Readme

### ISSUE THREAD

**Issue by pierrejego** [georchestra/cadastrapp#557]
Remplacement des liens des wikis vers la nouvelle doc : 
https://docs.georchestra.org/cadastrapp/

**Comment by pierrejego** [comment]
Et ici aussi 
https://github.com/georchestra/mapstore2-cadastrapp/tree/master#local-config

**Comment by MaelREBOUX** [comment]
README du plugin MS2 fait.

et je savais bien que j'avais déjà changé ça dans le code : https://github.com/georchestra/mapstore2-cadastrapp/blob/master/localConfig.json#L285
