### ISSUE TITLE
Problème de prénom de naissance tronqués

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#569]
Avec ce commit : https://github.com/georchestra/cadastrapp/commit/228edaf33fec1878d34c60deef5007e3ed97f2ff#diff-4051bb42719272c8e9ac84b6d0e8b75e6bf93497b8af19a6af93bd4dd02ce339

On voit apparaitre un problème avec les prénoms de naissance qui sont à présent tronqués à 15 caractères.

Dans le modèle généré par QGis, dprnlp est tronqué à 15 caractères
Cependant ddenom affiche bien la totalité du nom et prenom.

La restriction de dprnlp à 15 caractères vient de MAJIC3.

La seule solution pour avoir l'integralité du prénom semble de revenir à l'utilisation de ddenom.

**Comment by landryb** [comment]
https://github.com/georchestra/cadastrapp/pull/570/commits/6d9ff3cb704e69c9ce18bc56109448ae3cbceb2e est plus ou moins le revert de https://github.com/georchestra/cadastrapp/commit/228edaf33fec1878d34c60deef5007e3ed97f2ff#diff-4051bb42719272c8e9ac84b6d0e8b75e6bf93497b8af19a6af93bd4dd02ce339 ? si oui ca me semble le bon choix.

**Comment by jusabatier** [comment]
@landryb Oui c'est un revert de ce commit, j'admet que l'utilisation de `dnomlp` et `dprnlp` serait plus logique, malheureusement cela entraîne un tronquage au niveau des prénoms de plus de 15 caractères

**Comment by landryb** [comment]
c'est vous les experts majic :) mais j'admets que c'est dommage de présenter des infos tronquées..

**Comment by MaelREBOUX** [comment]
Réparé avec 5b6d8d3e72f70f3b5d6baa9d0aa677e3e7fcc72d

note : ouf c'est OK dans cadastre QGIS : https://github.com/3liz/QgisCadastrePlugin/blob/master/cadastre/cadastre_dialogs.py#L1557
