### ISSUE TITLE
support du millésime majic 2021

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#572]
cf #528 pour la précédente itération

[BATI_21.pdf](https://github.com/georchestra/cadastrapp/files/6838863/BATI_21.pdf)
[LLOC_21.pdf](https://github.com/georchestra/cadastrapp/files/6838864/LLOC_21.pdf)
[NBAT_21.pdf](https://github.com/georchestra/cadastrapp/files/6838865/NBAT_21.pdf)
[PDLL_21.pdf](https://github.com/georchestra/cadastrapp/files/6838867/PDLL_21.pdf)
[PROP_21.pdf](https://github.com/georchestra/cadastrapp/files/6838868/PROP_21.pdf)

**Comment by landryb** [comment]
LLOC/NBAT/PDLL: pas de changement

**Comment by landryb** [comment]
BATI
```
DATE DESCRIPTION FICHIER FONCIER STANDARD PAGE
10/02/2021 DE FICHIER PROPRIÉTÉS BÂTIES 8
1.6. Évolutions du fichier
Mise à jour 2021
Au sein des articles 30 et 31, descriptif des exonérations des PEV, la donnée GNEXTL peut prendre les
valeurs  «  AQ » (addition de construction exonération de 2 ans droits acquis),  « NQ»   (construction
nouvelle exonération de 2 ans droits acquis), « CV » (entreprises situées dans les zones ZRVC), « RR»  
(commerces en milieu rural) et « MU » (abattement sur les modèles U).
Les anciennes significations des codes   AQ (Exonération de 15 ans pour addition de construction
antérieure au 01/01/1973) et NQ (Exonération de 15 ans pour construction nouvelle antérieure au
01/01/1973) sont désormais obsolètes.
Les valeurs « CM » et « DM » de la donnée GNEXPL (exonération permanente) sont supprimées
```

PROP:
```
Mise à jour 2021 ( cf. §2.3)
Création du code droit réel Z (gestionnaire d’un bien de l’État)
Suppression du code droit bail réel solidaire (ancien code Z) 
Création, suppression et modifications de valeurs (cf. § 2.9) pour les champs DFORME « forme 
juridique »
```

**Comment by landryb** [comment]
import des données d'une commune dans le plugin qgis cadastre 1.12.1 a priori ok

**Comment by MaelREBOUX** [comment]
Ticket cadastre QGIS --> https://github.com/3liz/QgisCadastrePlugin/issues/306

**Comment by MaelREBOUX** [comment]
@landry : je te propose de clore ce ticket car la prise en compte du millésime 2021 sera transparente dans cadastrapp dès qu'on aura mouliné les données cadastre QGIS.

Je te laisse clore si tu es d'accord.
