### ISSUE TITLE
Barre d'outil : supprimer entrée Traitement sélection > import liste parcelle.csv

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#58]
Enlever cette entrée de menu car en cohérence avec le ticket #45

**Comment by landryb** [comment]
La logique etant que le menu s'appelle "traitement selection", et faire un import depuis un CSV n'est pas vraiment appliquer un traitement sur une selection - tous les autres items de ce sous-menu sont des exports csv/pdf depuis la selection existante.

**Comment by pierrejego** [comment]
Modification effectuée voir commit
