### ISSUE TITLE
Fenêtre sélection des parcelles: comportement au simple clic

### ISSUE THREAD

**Issue by pigma** [georchestra/cadastrapp#59]
Dans une liste de parcelles sélectionnées (apparence graphique jaune), un clic sur une ligne permet d'identifier graphiquement la parcelle correspondante (apparence différente).

**Comment by landryb** [comment]
Cf le ticket #37 - auparavant, la logique était "parcelle en jaune" = "parcelle selectionnée via une recherche par attribut/geographique" + "parcelle en bleu" = la meme chose + "la fenetre d'informations sur cette parcelle est ouverte/affichée".

Vu que dans le ticket #37 on est parti sur la logique de pouvoir faire une sous-selection (par simple-clic) dans notre résultat de recherche, on garde "jaune" = "parcelle résultant d'une recherche" et la surbrillance en bleu devient "cette/ces parcelle(s) est/sont selectionnée(s) parmi l'ensemble des résultats de recherche"

**Comment by pierrejego** [comment]
Modification apporté, en complément, le point est maintenant l'outils par default. La selection par clique n'ouvre plus les fenêtres de détails, cela ajoute à la liste de parcelles et selectionne dans cette liste dans un deuxième temps 
Jaune -> dans la liste
Bleu -> selectionné dans la liste

pour information la couleur verte est mise lorsqu'un fenêtre de détails est ouverte via le fenêtre de selection
