### ISSUE TITLE
[3.12.2] Fonction d'export CSV de la liste des parcelles 

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#60]
Point 3.12.2 page 73 dus spécifications (version 1.1)

La fonction d'export d'une liste de parcelles / d'une sélection de parcelles n'est pas implémentée.

Lié à #37 pour l'ergonomie.

**Comment by pierrejego** [comment]
La fonctionnalité d'import et export de parcelle par CSV a été implémenté. Il n'y a pas de contrôle sur la taille du fichier pour l'instant. Peut-être faut-il plutôt envisager un contrôle sur le nombre de parcelle pouvant être importé et exportée.

**Comment by MaelREBOUX** [comment]
La liste est une suite de valeurs séparées par un point-virgule.
Un import dans un tableur ne correspond pas au résultat attendu.

Ce n'est pas un CSV "standard".
Il faut une valeur par ligne.
Le séparateur vient séparer les attributs, pas les enregistrements.

A corriger SVP.

**Comment by MaelREBOUX** [comment]
Ne fonctionne plus ce jour. Génération d'un fichier fantôme de 64 ko qui n'est pas traité par le navigateur (FF)

![screenshot044](https://cloud.githubusercontent.com/assets/6370443/11247255/873bc564-8e1b-11e5-9c9d-df4b8c665157.png)

**Comment by pierrejego** [comment]
@MaelREBOUX  Je viens de faire un export sans soucis sur le serveur de qualif, peux tu me détailler la manipulation que tu as réalisés ?

**Comment by MaelREBOUX** [comment]
Rien de spécial. Ce matin ça fonctionne parfaitement.
