### ISSUE TITLE
Fenêtre de sélection de parcelles : onglets

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#61]
On ne veut pas de gestion multi-onglets des sélections de parcelles.
C'est une bonne idée mais pas demandé et ne permet pas de rester dans le planning + non prioritaire.

DONC : enlever le bouton "+" et faire disparaître l'onglet qui contient le nom de la commune.

**Comment by MaelREBOUX** [comment]
lié à #37

**Comment by landryb** [comment]
Pour synthétiser: 
l'idée de départ est bonne, c'est un + ergonomique de pouvoir travailler sur plusieurs sélections indépendantes, mais ca fait un peu doublon avec l'import/export de listes de parcelles, et ca impliquerait j'imagine pas mal de changements d'architecture dans le code:
- gérer plusieurs sous-ensembles d'objets spatiaux dans la couche selection
- n'afficher que ceux correspondants a l'onglet selectionné
- comment nommer de manière pertinente l'onglet pour s'y retrouver entre ses différentes selections
  
  Donc sauf si 90% est fait et qu'il faut juste réactiver cette possibilité (et la tester de manière intensive) pour pouvoir en bénéficier, on le veut bien, sinon ce n'est pas prioritaire pour la livraison à venir.

**Comment by pierrejego** [comment]
La gestion par onglet était déjà réalisé, un bug sur le numéro courant de l'onglet empêchait l'ouverture de nouveaux onglets. C'est corrigé depuis hier et déployé sur la plateforme.

https://cadastrapp-qualif.asogfi.fr/mapfishapp/

Le nom des onglets dépendents de la manière dont la recherche à été faite (par nom, identifiants, lots ou selection sur le carte)

Vous pouvez faire un test et me dire ce que vous en pensez.

Le plus permet d'ouvrir un nouvel onglet pour faire une nouvelle selection sur la carte

**Comment by landryb** [comment]
@MaelREBOUX des tests de votre coté ? J'essaie de mettre a jour la pf chez moi ajd ou vendredi pour bénéficier aussi de la gestion des onglets.

**Comment by catmorales** [comment]
Je viens de tester en faisant une recherche par nom de propriétaire, puis une recherche par clic sur la carte. Il n'y a plus de doublon dans le résultat. Par contre, les résultats sont affichés à la queue leu leu  et pas dans des onglets différents et il n' y a pas de recentrage sur la carte.
![recherches successives](https://cloud.githubusercontent.com/assets/4659829/10188436/9917b94c-675f-11e5-84c0-96b168f91c4a.png)

**Comment by catmorales** [comment]
A priori ça marche dans un sens mais pas dans l'autre à savoir:
-  recherche par clic puis recherche par nom de proprio --> OK
-  recherche par nom de proprio puis recherche par clic --> NOK

**Comment by pierrejego** [comment]
Oui le comportement que nous avions prévu est le suivant et correspond à ce que vous venez d'écrire 

3 cas : 
 1- recherche par un formulaire à chaque fois un nouvel onglet est ouvert (même si il existe déjà)
si on clique sur la carte on ajoute à la selection courante

2- On commence par sélectionner sur la carte, la fenêtre s'ouvre et un nouvel onglet selection apparaît. Si on fait une recherche pas un formulaire un nouvel onglet s'affiche. si on reclique sur la carte, la parcelle selectionnée s'affiche dans l'onglet courant

3 - Création d'une nouvelle sélection cartographique via le bouton +.  Si on veut faire une nouvelle selection à partir de la carte on clique sur + puis sur les parcelles qui nous intéressent.

**Comment by pierrejego** [comment]
Pouvez vous fermer cette issue si le comportement actuel vous convient ? 
Merci

**Comment by landryb** [comment]
@MaelREBOUX si c'est ok pour toi le comportement actuel tu fermes le ticket ?

**Comment by MaelREBOUX** [comment]
ok
