### ISSUE TITLE
Ajout de logs lors de la géneration de documents

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#613]
Comme évoqué précédemment, il semble intéressant d'avoir des logs concernant les documents générés par l'application : 

- Bordereau parcellaires
- Relevé de propriété
- Demandes d'infos
- Exports

Ceci permettrait d'une part de garder une trace des infos qui sortent de l'appli, et d'autre part de récupérer des métriques d'utilisation de l'outil.

**Comment by landryb** [comment]
pi je viens de faire une metrique arbitraire en greppant mes logs, depuis septembre 2020 environ 7000 BP et 12000 RP.

**Comment by MaelREBOUX** [comment]
Je rêve de retrouver ce genre de stats

**Comment by MaelREBOUX** [comment]
tu partages ton grep @landryb  ?

**Comment by landryb** [comment]
```
nbp=0
nrp=0
for f in /srv/log/tomcat/cadastrapp*gz ; do

date=$(basename $f .log.gz)
# utilisateurs authentifiés par jour
zgrep ROLE $f  | cut -d ' ' -f7 | sort -u > /tmp/cadalog/users-$date
zgrep -c -e /createBordereauParcellaire.*response $f > /tmp/cadalog/bp-$date
nbp=$(( $nbp + $(cat /tmp/cadalog/bp-$date) ))
zgrep -c -e /createRelevePropriete.*response $f > /tmp/cadalog/rp-$date
nrp=$(( $nrp + $(cat /tmp/cadalog/rp-$date) ))
done
echo bp:$nbp
echo rp:$nrp
```

**Comment by pierrejego** [comment]
@landryb @MaelREBOUX @catmorales  vous en pensez quoi. 

Pour moi c'est un gros plus, je reteste et je vérifie si ça s'installe bien (activé/desactivé)

Côte RGPD vous êtes bien tous d'accord.

Je propose d'en reparler ensemble et de l'intégrer dans la prochaine release.

**Comment by MaelREBOUX** [comment]
La PR est #612

**Comment by landryb** [comment]
perso j'ai jamais été fan des logs en DB

**Comment by jusabatier** [comment]
Ça n'a rien d'obligatoire, ça permet juste à ceux que ça intéresse de les mettre en place.

Le principe c'est juste de passer à log4j2 (plus récent que l'actuel logback), et ajouter des fonctions de log de niveau INFO.
De plus, le namespace de log utilisé est `org.georchestra.cadastrapp.loggers.documents` ce qui permet de le désactiver en le passant en WARN.

Enfin j'ai fourni en commentaire un exemple de config pour log dans BDD, afin de guider ceux qui voudraient le mettre en place.

**Comment by MaelREBOUX** [comment]
Mergé donc on ferme
