### ISSUE TITLE
[Cadastrapp-Mapstore] les fichiers pdf sont entourés de "_"

### ISSUE THREAD

**Issue by catmorales** [georchestra/cadastrapp#615]
### Environnement
Cadastrapp testé dans Mapstore (v1.2.x)
Après redéploiement du backend cadastrapp sur la branche master + CTRL F5 dans Mapstore
Chrome Version 96.0.4664.45 (Build officiel) (64 bits)

### Test 
La création du bordereau parcellaire créé un fichier entouré de "_" --> conséquence le pdf ne s'ouvre pas automatiquement
Idem avec le relevé de propriété.

![image](https://user-images.githubusercontent.com/4659829/144013049-8aa24f15-1fe1-4d3e-ab90-6a2fea2b4c93.png)

 On n'a pas ce problème sur Mapfishapp.

**Comment by MaelREBOUX** [comment]
Je ne comprend pas : je n'ai pas ce problème. Je récupère bien des PDF sans pb sous FireFox.

(en plus si c'est mapstore : il faut poster dans https://github.com/georchestra/mapstore2-cadastrapp/issues ;) )

**Comment by catmorales** [comment]
Oui mais c'est lié à la dernière version, je n'avais pas ce problème avant.

**Comment by jusabatier** [comment]
Je constate le même souci ici.

Sous Firefox, ça fonctionne correctement.

Sous chromium, on a des '_' autour du nom de fichier.

**Comment by MaelREBOUX** [comment]
Alors sous Chrome j'ai pas de pb non plus MAIS je note que sous FireFox les BP se nomment "BP-xxxxxx.pdf" et sous chrome c'est "BPxxxxx.pdf".

**Comment by catmorales** [comment]
Et de mon côté sous firefox 78.11.0esr (32 bits), ça fait un ficher nommé BP-1638263996917.pdf.pdf
Je vais mettre à jour mon firefox.
Mise à jour de Firefox vers 91.3.0esr (32 bits)
Je n'ai plus le problème.

**Comment by MaelREBOUX** [comment]
Ma config :
- FireFox 91.3.0esr
- Chrome 96.0.4664.45

**Comment by catmorales** [comment]
Le file name dans l'entête de réponse est bon :/
![image](https://user-images.githubusercontent.com/4659829/144021758-bfaf1ec9-ca1d-4e1e-bc8f-ae824b84a3e3.png)

**Comment by MaelREBOUX** [comment]
Moi sous FF j'ai ça dans le header de réponse `content-disposition`  (BP ou RP depuis la fiche info parcelle)
` attachment; filename="BP-1638264618741.pdf"`

Sous Chrome :
`attachment; filename=RP1638263875045.pdf`


BP ou RP c'est pareil : avec un tiret sous FF et sans tiret dans Chrome. C'est déroutant.

Ha : l'un est entouré de quote, l'autre non.

**Comment by landryb** [comment]
regression de #598 probablement ?

**Comment by Gaetanbrl** [comment]
> La création du bordereau parcellaire créé un fichier entouré de "_"

Pour ms-cadastrapp, idem avec l'export CSV d'une sélection (dernière version)

`https://gis.jdev.fr/cadastrapp/services/exportParcellesAsCSV
`
Retourne le fichier :

`_export-1639141004080.csv_`

**Comment by pierrejego** [comment]
Après vérification, la nouvelle version de cadastrapp utilisé avec l'addons Mapfishapp ou via le Swagger retourne bien les bons noms de fichiers sans _
En appelant les mêmes services avec les mêmes données  mais avec mapstore le comportement est différent. 

La documentation de Spring remonte que les quotes sont bien le comportement attendu par la RFC
```
[ContentDisposition.Builder](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/ContentDisposition.Builder.html) filename([String](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html?is-external=true) filename)
Set the value of the filename parameter. The given filename will be formatted as quoted-string, as defined in RFC 2616, section 2.2, and any quote characters within the filename value will be escaped with a backslash, e.g. "foo\"bar.txt" becomes "foo\\\"bar.txt".
```

En faisant des tests avec Chrome et un petit script en php, on voit que Chrome remplace les " par des _

Je ne sais pas encore si le soucis vient de la partie serveur, de la partie front mapstore ou juste de Chrome. 
Côté serveur le filename est un string, il n'y a pas que quote supplémentaires, je ne peux donc pas les enlevé.

J'ai aussi essayé en remplaçant : 
```
ContentDisposition contentDisposition = ContentDisposition.builder("attachment")
					.filename(filename)
					.build();
HttpHeaders headers = new HttpHeaders();
headers.setContentDisposition(contentDisposition);
```
par 
```
 HttpHeaders headers = new HttpHeaders();
    headers.setContentType(MediaType.APPLICATION_OCTET_STREAM);
    response.setHeader("Content-Disposition", "attachment; filename=" + filename);
```

Mais j'ai le même comportement, je me demande si ça vient bien de la partie serveur ou si la mise à jour de la version de cadastrapp backend ne correspondrait pas avec la montée de version de Chrome.

Je continue à chercher demain

**Comment by MaelREBOUX** [comment]
ok. tiens-nous au courant.

**Comment by MaelREBOUX** [comment]
Au fait : pour nous le pb touche également FireFox.

**Comment by landryb** [comment]
@pierrejego vous avez pensé a regarder le code axios dans ms2-cadastrapp appelant le service ? Il peut aussi faire un traitement en fct des headers recus avant de proposer le pdf au browser...

**Comment by jusabatier** [comment]
https://github.com/georchestra/mapstore2-cadastrapp/issues/143 ?

**Comment by landryb** [comment]
@jusabatier ca me paraitrait une hypothèse plus forte, si ca marche dans mfapp et pas dans ms2-cadastrapp...

**Comment by jusabatier** [comment]
Le code cité est tiré de ms2-cadastrapp, donc a priori logique qu'il ne provoque le bug que dans ms2-cadastrapp

Où alors je comprends mal ce que tu veux dire ?

**Comment by landryb** [comment]
ce que je veux dire c'est que si le bug n'est vu que dans ms2-cadastrapp, alors il est probable que le bug soit dans la manière dont le code de ms2-cadastrapp gère la réponse du service web (comme tu montres dans le code cité) avant de proposer le fichier au navigateur.. bref, je pense qu'il faut regarder de ce coté la plutot que coté serveur - ok il y'a p-e eu un changement coté backend mais s'il n'affecte pas la version mfapp...

**Comment by pierrejego** [comment]
Je teste la modif justement lié à https://github.com/georchestra/mapstore2-cadastrapp/issues/143 je pense aussi que c'est ça mais je voulais en être sur avant de proposer une PR.

**Comment by pierrejego** [comment]
Je teste la modif justement lié à https://github.com/georchestra/mapstore2-cadastrapp/issues/143 je pense aussi que c'est ça mais je voulais en être sur avant de proposer une PR.

**Comment by pierrejego** [comment]
C'était bien une erreur dans le code de l'addon mapstore. Merci @jusabatier d'avoir pointé l'endroit :) PR faite

**Comment by catmorales** [comment]
Use case : files with "_" at the end and the beginning of the filename

**Context:** https://portail-test.sig.rennesmetropole.fr/mapstore/#/context/master-urba-foncier
**Chrome** Version: 99.0.4844.82 (Build officiel) (64 bits)

**cadastrapp Backend**: [Tag V2.0](https://github.com/georchestra/cadastrapp/tree/Cadastrapp-V2.0)
**mapstore2-geOrchestra:** [2021.02.xx](https://hub.docker.com/layers/geosolutionsit/mapstore2-georchestra/2021.02.xx)
**mapstore2-cadastrapp :** [RC18](https://github.com/georchestra/mapstore2-cadastrapp/releases/tag/1.0.0-rc18)

![chrome_undescore](https://user-images.githubusercontent.com/4659829/159297828-8e2a3ffd-d32e-477b-aed8-e63e924a4b85.gif)

**Comment by pierrejego** [comment]
It can not be correct in backend, it have to be done in frontend with this PR 
https://github.com/georchestra/mapstore2-cadastrapp/pull/152

**Comment by catmorales** [comment]
Corrected with [rc20 tag ](https://github.com/georchestra/mapstore2-cadastrapp/releases/tag/1.0.0-rc20) of mapstore2-cadastrapp
