### ISSUE TITLE
Problème compilation webapp sous Ubuntu

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#617]
Sur ma Ubuntu en voulant compiler ce matin, j'ai eu une erreur au niveau de la webapp.

Il semble que le paquet `python-virtualenv` n'existe plus dans les dernière Ubuntu.
J'ai donc du installer les paquets necessaires manuellement : 

```
sudo apt install python2
sudo apt install python-setuptools
```

Je poste ça ici au cas où d'autres auraient le même problème.

**Comment by pierrejego** [comment]
Bonjour,
oui on l'a vu aussi passé sur mapfishapp. Je voudrais modifier les fichiers maven. 
Mettre le build et l'assembly de toutes les applications enfants dans le parent et ne laisser que les builds enfants dans chaque pom. ça permettra de ne builder le plugins mapfishapp que si nécessaire.

**Comment by jusabatier** [comment]
Je ferme car MFapp plus supporté.
