### ISSUE TITLE
Recherche par proprio : parcelles dupliquées 

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#62]
Lors de la recherche d'un propriétaire, la liste de parcelles résultante affiche plusieurs fois la même parcelle:
![screenshot059](https://cloud.githubusercontent.com/assets/6370443/10042574/3a1a20f6-61ec-11e5-93c0-7d41312f20eb.png)

Pour info : compte proprio avec 2 indivisions.

**Comment by pierrejego** [comment]
Modification apporté et déployé sur la plateforme https://cadastrapp-qualif.asogfi.fr/mapfishapp/
Il manquait un distinct sur la requête de selection des parcelles
