### ISSUE TITLE
changer la recherche sur le nom de commune pour "contient" au lieu de "commence par"

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#621]
actuellement la recherche des communes se fait sur "commence par" (ie `motif%`), cf https://github.com/georchestra/cadastrapp/blob/master/cadastrapp/src/main/java/org/georchestra/cadastrapp/service/CommuneController.java#L65 - une évolution possible serait de la faire sur "contient" (ie `%motif%`) qui remonterait plus d'occurences et éviterait les embrouilles sur les noms de communes avec ou sans tiret, avec ou sans préfixe, etc...

@jusabatier @MaelREBOUX @catmorales ?

**Comment by MaelREBOUX** [comment]
Pas d'opposition.
