### ISSUE TITLE
Largeur infobulle insuffisante

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#63]
Il faut que la largeur de l'infobulle soit plus grande que actuelle
![screenshot060](https://cloud.githubusercontent.com/assets/6370443/10042916/112d3a22-61ef-11e5-9fd1-6b360d227e35.png)
ment à cause des noms de proprios.

**Comment by pierrejego** [comment]
Largeur augmenté a 300 au lieu de 200
