### ISSUE TITLE
Où mettre la liste des lots de copropriété

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#64]
Pour suivi.

**Comment by pierrejego** [comment]
Il manque la fenêtre pour lancer la recherche, on pense rajouter un onglet co-propriétaire dans la fenêtre propriétaire

**Comment by landryb** [comment]
@MaelREBOUX plutot une nouvelle fenetre indépendante (c'est ce qui est dans le CCTP) avec une fenetre de resultats distincts de celle des propriétaires, ou un onglet ?

**Comment by MaelREBOUX** [comment]
Vu l'experience utilisateur offerte par le module je ne suis pas chaud pour rajouter une nouvelle fenêtre.
Rajouter un onglet dans la fenêtre d'infos parcelles est cohérent car l'entrée se fait forcément par la parcelle.
Dans le cas d'un pavillon il conviendrait d'afficher "Aucune copro" ou de laisser blanc.
Dans le cas d'un immeuble l'onglet proprio afficherait (par ex) "LES COPRO IMMEUBLE...." et l'onglet copro listerait tous les locaux et leur proprios.

Ca me semble logique.
Prévoir une pagination ?

**Comment by pierrejego** [comment]
@MaelREBOUX je viens de rajouter l'onglet dans la fiche d'information cadastrale, il faut encore que je teste avec de gros volume de données pour mieux gérer la pagination. 

Par contre j'avais aussi commencer à développer une fenêtre de recherche de co-proprietaire, comme indiqué dans le CCTP. 

![image](https://cloud.githubusercontent.com/assets/11499415/11277798/5870aad8-8ee8-11e5-92d2-d17a7ebc059d.png)

Mais j'ai du mal à voir l’enchaînement possible derrière, on peut déjà rechercher les copropriétaires depuis les autres pages de recherches, j'ai donc l'impression de développer un doublon. Peux-tu m'appeler demain matin pour faire le point ?
