### ISSUE TITLE
Affichage des couches selection et geo_parcelle dans le layerswitcher

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#65]
Lié au ticket #56 - le fait d'avoir 2 couches spécifiques au module cadastrapp présentes dans l'arbre des couches peut perdre les utilisateurs - a plus forte raison s'ils décident de décocher ou supprimer la couche 'selection' et/ou la couche 'geo_parcelle'.

la couche 'selection' (ainsi que le controleur gérant le click sur la carte) _doivent_ etre présentes tant que l'addon est actif, donc il serait bien mieux lors de l'ajout/création de cette couche de setter displayInLayerSwitcher a false pour "cacher" cette couche a l'utilisateur. Et la supprimer (ainsi que le controleur) lors qu'on désactive/destroy l'addon

pour la couche WMS geo_parcelle, c'est un peu plus complexe - en fonction des plateformes, certains vont utiliser la meme couche pour les requetes WFS (paramétrée dans WFSLayerSetting) et les requetes WMS (paramétrée dans WMSLayer) et l'utiliser comme une couche "classique" de mapfishapp (apparaissant donc dans la liste des couches) alors que d'autres vont utiliser une autre couche composite/cachée pour le fond cadastre, et ne vont pas forcément vouloir la faire apparaitre dans la liste des couches (dans tout les cas, elle devra etre ajoutée a l'objet map lors de l'activation de l'addon et supprimée lors de sa désactivation).

La proposition est de n'afficher la couche WMS 'geo_parcelle' dans le layerswitcher que si 'layerNameInPanel' est non-vide - si ce parametre est explicitement vide (ie layerNameInPanel: '' dans la config) alors setter displayInLayerSwitcher a false dans https://github.com/GFI-Informatique/addons/blob/dev/cadastrapp/js/selectFeature.js#L713.

La cerise sur le gateau serait de pouvoir interdire la suppression de cette couche dans le layerswitcher - et si ce n'est pas possible (je ne crois pas en regardant le code de GEOR_managerlayers a la création du GeoExt.tree.LayerContainer!), s'assurer (a chaque requète? lourd...) que la couche est présente dans la map tant que l'addon est actif.

**Comment by pierrejego** [comment]
OK, 
du coup les deux Layers sont en variables globales pour pouvoir être supprimer à la fin, même si le layer WMS n'a pas de nom.

Ajout de la couche WMS et WFS au démarrage. Uniquement la couche WMS est visible et ce uniquement si la variable layerNameInPanel n'est pas vide. (Il faut qu'elle soit présente)

Suppression des deux couches WMS et WFS lors de la desactivation de l'addons.
