### ISSUE TITLE
Gestion des droits géographiques : doc incomplète + lien hs

### ISSUE THREAD

**Issue by Doctor-Who** [georchestra/cadastrapp#650]
Bonjour,

Sur la gestion du filtrage géographique, la doc est encore incomplète. (https://docs.georchestra.org/cadastrapp/latest/guide_administrateur/configuration_webapp.html#gestion-des-droits-geographiques)

De plus, sur cette même page, le lien est HS : https://github.com/georchestra/cadastrapp/blob/master/script/commun/user/README.md

Merci de votre aide. Besoin de pouvoir limiter la recherche sur un département pour un organisme.

**Comment by jusabatier** [comment]
Bonjour,

En effet pour la doc il semble y avoir un trou.

Depuis cette PR : https://github.com/georchestra/cadastrapp/pull/571
Il est possible, en activant la fonction (https://github.com/georchestra/cadastrapp/tree/master/database#si-on-souhaite-remonter-les-autorisations-geographiques-depuis-les-groupes-georchestra) de configurer le filtrage geographique via la zone de compétence de l'organisation depuis la console georchestra.

Sinon, il me semble qu'en ajoutant une ligne dans la table `groupe_autorisation` il est possible de configurer l'accès à une commune ou un département pour un role/organisation donné.

Exemple : 

INSERT INTO cadastrapp.groupe_autorisation(idgroup,ccodep) VALUES ('ROLE_EXEMPLE','043');

ou eventuellement

INSERT INTO cadastrapp.groupe_autorisation(idgroup,ccodep) VALUES ('ORGSHORTNAME','043');

**Comment by MaelREBOUX** [comment]
Bonjour,

Vous pouvez pousser une PR sur la doc ?
Au pire : mettre ici le complément de doc et je me chargerai de modifier la doc.

Merci d'avance.

**Comment by jusabatier** [comment]
Sue quelle doc en fait ?

J'ai jamais compris laquelle était "officielle"

**Comment by landryb** [comment]
celle dans le repo (https://github.com/georchestra/cadastrapp/tree/master/docs/guide_administrateur) est celle qui est maintenue et publiée sur https://docs.georchestra.org/cadastrapp/latest/guide_administrateur/

**Comment by jusabatier** [comment]
Du coup on peut clôturer ?

**Comment by landryb** [comment]
bien vu, merci pour le rappel :)
