### ISSUE TITLE
Désactiver l'addon devrait fermer les fenetres cadastre ouvertes

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#67]
Désactiver l'addon supprimer effectivement les couches cadastre et ferme la barre d'outils, mais il peut rester a l'écran des fenetres de résultats de recherche ou d'information parcellaire. Pareil pour les fenetres de recherche de proprio ou de demande d'information foncieres (bref, toutes les fenetres specifiques a l'addon)

Au passage, si je ferme manuellement la fenetre de résultats après avoir désactivé l'addon, j'ai une exception JS (logique..) a la ligne 468 de selectParcelle.js

```
TypeError: GEOR.Addons.Cadastre.result is null
GEOR.Addons.Cadastre.result.tabs.activeTab.featuresList = [];
```

**Comment by landryb** [comment]
Après MAJ, si je desactive l'outil cadastre, a l'écran il me reste une fenetre 'selection de parcelle', une fenetre 'information parcellaire' et la fenetre de details d'informations foncieres.

**Comment by pierrejego** [comment]
Je viens de faire le test, toutes les fenêtres se ferme bien chez moi. Est-ce que tu peux rester et me dire si il y a des traces javascript ? 
Ou me donner la manip exacte que tu fais pour que je reproduise ?

**Comment by landryb** [comment]
Sur la PF GFI, j'ouvre : 
- la toolbar cadastrapp
- la fenetre de recherche de parcelles
- la fenetre de demande d'IF
- avec l'outil point je selectionne une parcelle
- j'ouvre la fiche d'IF de cette parcelle -> j'ai la toolbar et 4 fenetres a l'ecran

menu outils, gerer les outils, deselectionner 'cadastre', valider par clic sur 'aucun outil'

la toolbar cadastrapp, la fiche d'IF, la fenetre de resultat de selections sont fermées. il reste la fenetre de recherche de parcelle et de demande d'IF a l'ecran, et le bouton cadastrapp est toujours dans la toolbar mfapp.

Dans firebug: TypeError: feature is undefined (sur selectFeature.js (ligne 406, col. 5))

je reactive l'outil cadastre -> un 2e bouton est ajouté dans la toolbar mfapp.

**Comment by MaelREBOUX** [comment]
je viens de faire le test sur la PF Gfi à l'état de ce matin.
Toutes les fenêtres se sont fermées sont celles des demandes d'informations cadastrales.

**Comment by pierrejego** [comment]
Je viens de reproduire, merci pour les détails.  Les fenêtres ne se fermaient pas toutes à cause d'une mauvaise gestion d'un feature.
Je viens de corriger.
Le comportement était différent qu'on soit sous IE ou Chrome.

**Comment by pierrejego** [comment]
Il me reste encore une correction à apporté lorsque plusieurs onglets sont ouverts, suite à la modification pour l'anomalie #74

**Comment by MaelREBOUX** [comment]
ici je n'ai pas noté de pb.

**Comment by pierrejego** [comment]
Anomalie corrigée avec le commit 43d652ec6b0a93a1895e0c2bbe19f87ecee97f7b
@landryb tu peux confirmer sur ton serveur ?

**Comment by landryb** [comment]
J'ai toujours un warning dans firebug lors de la desactivation de l'addon:

```
TypeError: a.el.dom is undefined
```

Mais tout est bien fermé... sauf dans un cas : j'ai fait 2 selections distinctes, une par ligne et une par point, et j'ai ouvert une fiche d'info parcelle pour un des resultats dans chacune des selections (j'ai donc 2 fenetres affichant des infos sur des parcelles provenant de 2 selections). A la desactivation de l'addon, une des 2 fenetres n'est pas fermée.

**Comment by landryb** [comment]
Et au 2e essai, je reproduis mais c'est plus subtil que je pensais... en fait j'ai l'impression qu'il faut: faire une recherche, ouvrir la fiche d'info, ouvrir un 2e onglet de recherche, cliquer sur une parcelle, ouvrir sa fiche d'info, et switcher sur le premier onglet de recherche avant de desactiver l'outil -> la fiche d'info pour le 2e onglet n'es pas fermée.

**Comment by MaelREBOUX** [comment]
ce jour je constate le pb : la fermeture de la Toolbar ne ferme plus rien du tout.

**Comment by pierrejego** [comment]
Il y avait un effet de bord avec l'anomalie  #74
Lorsque qu'on supprimait un onglet, les fenêtres de cet onglet n'était pas supprimé, mais uniquement les fenêtres de l'onglet précédent.

Pourrais-tu rester ta manipulation sur la qualif, et si jamais tu reproduis encore, me la décrire en détails.

Merci

**Comment by MaelREBOUX** [comment]
Rien de spécial : fenêtre de recherche de parcelle ouverte, fenêtre de résultats avec plusieurs onglets.
Si je ferme la barre d'outil par clic sur X en haut à droite -> la barre d'outil disparaît mais les fenêtres restent affichées.

**Comment by landryb** [comment]
Ce ticket etait pour fermer les fenetres et la toolbar quand on _désactive_ l'addon dans le menu outils. Pas quand on 'ferme la toolbar' ...

**Comment by pierrejego** [comment]
Ah oui, je comprend mieux :) ça c'est normal. Enfin pour moi, quand on parle de désactiver l'addon, on parle d'aller dans outils->gérér les outls, et enlever cadastrapp.

Fermer la fenêtre ne desactive pas l'addon.

Donc la question, est-ce que fermer la fenêtre doit desactiver l'addon ?

**Comment by MaelREBOUX** [comment]
OK : j'avais pas saisi la nuance.
La désactivation de l'add-on via le gestionnaire d'outil Mapfishapp fonctionne.

> Donc la question, est-ce que fermer la fenêtre doit désactiver l'addon ?

Bonne question. 
Je pense que non sinon l'icone dans la barre d'outil Mapfishapp va disparaître ?
Mais si on peut fermer toutes les fenêtre ce serait un comportement logique.
Après si c'est trop compliqué : c'est pas la mer à boire.

**Comment by landryb** [comment]
Autre détail: si on laisse la couche geo_parcelle affichée dans le layertree, ca veut dire qu'on laisse la possibilité a l'utilisateur de la supprimer - et a partir de ce moment l'addon peut avoir un comportement incohérent.
- soit regarder s'il est possible d'empecher la suppression d'une couche du layertree dans mapfishapp (je doute)
- soit prendre en compte ce cas et verifier que la couche est la avant de l'interroger

Au passage, si la couche a été supprimée par l'utilisateur et qu'on essaie de désactiver l'addon, une erreur survient(NotFoundError: Node was not found) et l'addon ne peut plus etre désactivé.

**Comment by pierrejego** [comment]
Je viens d'ajouter la fermeture des fenêtres lors du cliques sur la croix de la toolbar.

Je regarde ce que je peux faire pour l'autre cas

**Comment by MaelREBOUX** [comment]
Je vous avoue que j'ai remarqué la persistance de la couche support des parcelles. Même quand il n'y a plus rien dans la table des matières.
Ca milite pour un rapprochement avec un contexte de carte spécifique cadastre.
il se passe quoi si on charge un autre contexte ?

**Comment by landryb** [comment]
Un utilisateur doit pouvoir charger un contexte puis activer l'addon - ici l'addon est sensé activer/désactiver ses couches support de manière indépendante.

**Comment by landryb** [comment]
Si l'addon est chargé et qu'on charge un WMC, les couches support disparaissent - l'addon doit vraiment vérifier que les couches sont présentes à chaque opération, ou pouvoir être désactivé proprement - dans le cas ou ses couches support sont absentes, désactiver l'addon produit toujours un message d'erreur dans firebug (NotFoundError: Node was not found).

**Comment by pierrejego** [comment]
Ok, je vois comment ça peut être réalisé.
L'idée que j'ai pour l'instant c'est de faire une vérification si les couches sont présentes dans les layers avant chaque requête et avant la fermeture de l'addons.

En cas de fermeture de l'addon, pas de soucis je corrige pour pas enlever quelques choses de déjà enlever.

Et pour le deuxième cas, je vous propose une fenêtre de warn et une desactivation de l'addons.

**Comment by landryb** [comment]
au passage, si on ferme la barre d'outil les fenetres sont bien fermées mais l'outil de selection par point est toujours actif - il faut le toggler

**Comment by pierrejego** [comment]
Je viens de refaire les tests sur les trois plateformes avec Chrome, IE et Firefox. Les outils de sélections point, ligne et polygon ne sont plus actif.
Dans le code menu.js à la ligne 514, il y a bien de deactivate sur chacun des boutons de la toolbar du cadastrapp.

On se retrouve avec l'action par défaut de mapfishapp qui est le drag, sans pour autant que celui ci soit séleectionné.

Je pense qu'il doit y avoir une autre erreur dans les logs, qui fait que le destroy() ne se passe pas bien. Si tu arrives à reproduire est-ce que tu peux me dire si tu as une erreur dans les logs, c'est peut être quelques choses que j'ai corrigé depuis.

je rajoute un commentaire dans le code, pour pouvoir lier à cette anomalie

https://github.com/GFI-Informatique/addons/commit/a912471b61841ed59b3da743c54b9a3a1e8b320c#diff-bb3ccd78b5f6f4c4bb3d896f6969738f

**Comment by landryb** [comment]
Le problème est toujours présent. J'active l'addon, je selectionne l'outil point, je clique sur une parcelle, je ferme la barre d'outil -> les fenetres sont bien fermées, la couche est supprimée, mais l'outil actif est toujours la selection par point (j'ai le rond bleu qui suit la souris). Firefox 44beta.

Si je réactive l'addon, l'outil point est toujours actif.

**Comment by pierrejego** [comment]
Je ne reproduis pas sur Chrome, je réessaye sur Firefox

**Comment by pierrejego** [comment]
Ah ok, j'ai compris la subtilité :) fermer la toolbar et non desactiver l'addons dans Outils.

**Comment by pierrejego** [comment]
https://github.com/GFI-Informatique/addons/commit/04929e18829e49f86bc16193f33228ea825f375e#diff-94302db2d40845274f961ee984d13d57

**Comment by landryb** [comment]
Ok, la c'est bon, si je ferme la toolbar ca revient bien à l'outil déplacer. Merci!
