### ISSUE TITLE
Problème génération des documents via les demandes

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#675]
Un utilisateur vient de me faire remonter un bug avec la génération des documents lorsqu'il passe par la demande d'info.

Sous Firefox, lorsque le premier document (pdf demande) est téléchargé, la barre de chargement ne se ferme pas, ce qui bloque complètement mapfishapp.

**Comment by MaelREBOUX** [comment]
Est-ce que l'on supporte toujours Mapfishapp ?

Nous venons de décider de décommissionner / désactiver tous les outils déjà porté sous MapStore pour le 01/01/2023.

**Comment by jusabatier** [comment]
Sans parler de le supporter, j'ai signalé un bug bloquant et proposé une correction.
Est-il possible de merger la PR ? C'est une correction mineure.

Chez nous, nous n'avons pas encore effectué la migration, donc je serais pour supporter MFapp pendant encore 1 an au moins. Aussi, je pense que nous ne sommes pas les euls dans ce cas.

Après, je pense que cette discussion devrait être faite dans sa propre issue, ou même sur le google groups afin d'être sur d'avoir les retours de tous les utilisateurs.

**Comment by landryb** [comment]
+1 pour merger, ca ne fait pas de mal.

**Comment by jusabatier** [comment]
Je ferme comme MFapp n'est plus supporté.
