### ISSUE TITLE
Sélection des parcelles: Exporter la liste

### ISSUE THREAD

**Issue by pigma** [georchestra/cadastrapp#68]
Actuellement, le bouton "Exporter la liste" exporte la sélection et non l'ensemble des items la liste, en fonction de l'objectif attendu il faut soit renommer le bouton, soit modifier le comportement (ce qui me semble le plus adapté).
![pb_exporter_la_liste](https://cloud.githubusercontent.com/assets/3725336/10581916/640acca0-7685-11e5-9288-4a1461104c32.png)

**Comment by pierrejego** [comment]
Modification du label effectuée
