### ISSUE TITLE
Outil de sélection point activé par défaut au chargement du module

### ISSUE THREAD

**Issue by pigma** [georchestra/cadastrapp#69]
Actuellement au chargement du module, l'outil de sélection point est activé par défaut même si la fenêtre "Outils cadastre" n'est par ouverte, aussi on ne peut plus déplacer la carte avec l'outil de déplacement. Ce comportement est perturbant, il serait préférable de laisser l'outil de sélection point désactivé par défaut ou d'ouvrir la fenêtre "Outils cadastre" au chargement du module (l'utilisateur verra ainsi qu'un outil est activé).

![pb_outil_selection_point](https://cloud.githubusercontent.com/assets/3725336/10582021/fb236b9c-7685-11e5-9432-3f986ab5f536.png)

**Comment by landryb** [comment]
https://github.com/GFI-Informatique/addons/commit/39912c7d0d2519c4300e72c4277bddcc040dbf31 should fix it - upgrading geor.demo.craig this afternoon/tmrw.

**Comment by pigma** [comment]
résolu
