### ISSUE TITLE
Suppression de l'add-on cadastrapp-mapfishapp (ne builde plus)

### ISSUE THREAD

**Issue by pierrejego** [georchestra/cadastrapp#695]
Le jsbuild ne passe plus dans les github action.

L'application cadastrapp mapfishapp n'est plus maintenu.
Je propose de supprimer l'addon front et de modifier le github action en cohérence

Votre avis ?

**Comment by landryb** [comment]
:+1: pour supprimer :)

**Comment by fvanderbiest** [comment]
makes sense

**Comment by pierrejego** [comment]
Suppression de l'addon mapfishapp dans la prochaine version

**Comment by MaelREBOUX** [comment]
+1 également
