### ISSUE TITLE
regroupement des pages "guide utilisateur" par famille d'outils

### ISSUE THREAD

**Issue by mvadin** [georchestra/cadastrapp#697]
la présentation est très détaillée et longue => un regroupement par famille est nécessaire

**Comment by mvadin** [comment]
voici un fichier Excel contenant une proposition de réorganisation du volet utilisateur de la documentation :
[reorganistion_doc_utilisateur_cadastrapp.xlsx](https://github.com/georchestra/cadastrapp/files/10719933/reorganistion_doc_utilisateur_cadastrapp.xlsx)

**Comment by mvadin** [comment]
mettre à part demande.md

**Comment by MaelREBOUX** [comment]
Pour moi c'est fait.
