### ISSUE TITLE
Problème d'affichage de parcelles sélectionnées

### ISSUE THREAD

**Issue by pigma** [georchestra/cadastrapp#70]
J'ai observé à plusieurs reprises (mais ce n'est pas systématique) des problèmes d'affichage des parcelles sélectionnées sur le référentiel cadastral lors de changements d'échelles de la carte.
cf copies d'écran ci dessous:

![pb_affichage_selection_2](https://cloud.githubusercontent.com/assets/3725336/10583027/0692773e-768b-11e5-9321-76f1661df7af.png)

![pb_affichage_selection_1](https://cloud.githubusercontent.com/assets/3725336/10583035/0c56d8fe-768b-11e5-8497-2a8021704320.png)

![pb_affichage_selection_3](https://cloud.githubusercontent.com/assets/3725336/10583038/13aeb4dc-768b-11e5-9eb8-002bb526105c.png)

**Comment by landryb** [comment]
J'ai aussi eu ce bug, mais uniquement sur une parcelle d'une selection de 3 parcelles - les 2 autres étant correctement rendues, cf http://i.imgur.com/AnbmuYb.png - la parcelle 'mal' rendue est la 608

Pour reproduire - selection par ligne, une nouvelle selection, selection par point, zoomer sur la liste, revenir sur l'onglet avec la selection par ligne, zoomer sur la liste.

A ce stade, si je clique sur la ligne de la parcelle 608 dans ma liste de resultats, elle est rendue en bleu 'au bon endroit'.

**Comment by landryb** [comment]
Et si par dessus, je selectionne la parcelle 607 et je 'zoom sur la selection', ca donne http://i.imgur.com/ctW17P8.png - ca zoome bien sur la 607, mais la 608 n'est pas re-rendue. un pbm sur la gestion de la liste des features ?

**Comment by landryb** [comment]
Au passage, aucun msg d'erreur dans la console de firebug.

**Comment by pierrejego** [comment]
Lié avec la #74, je fais des tests demain matin sur la qualification pour vérifier que tout est bien corrigé

**Comment by MaelREBOUX** [comment]
Nous n'avons pas rencontré ce pb ici jusqu'à présent.
Veut pas dire que ça arrivera pas si j'ai suivi.

**Comment by pigma** [comment]
Effectivement ça semble corrigé.
