### ISSUE TITLE
Problème recherche propriétaire par compte

### ISSUE THREAD

**Issue by pigma** [georchestra/cadastrapp#71]
La recherche de propriétaire par compte ne fonctionne pas (La recherche par nom / prénom fonctionne correctement).
- Aucun résultat avec le DNUPRO (Compte communal)
  ![pb_recherche_compte_communal_1](https://cloud.githubusercontent.com/assets/3725336/10602071/7ed0ce18-7716-11e5-9ee9-477359ddd0de.png)
- Aucun résultat avec le DNUPER (Numéro de personne MAJIC)
  ![pb_recherche_compte_communal_2](https://cloud.githubusercontent.com/assets/3725336/10602065/7796cfc6-7716-11e5-9071-d749a7ba9d78.png)

**Comment by pierrejego** [comment]
Correction apporté, une erreur javascript empêchait de lancer la recherche.

Pour information le champ utilisé pour la recherche est le dnupro et non le dnuper

**Comment by pierrejego** [comment]
Pouvez-vous vérifier si le comportement est OK pour vous ?

**Comment by landryb** [comment]
@pigma tu peux confirmer sébastien ?

**Comment by MaelREBOUX** [comment]
ok pour moi : à fermer.
