### ISSUE TITLE
Mise à jour de java 

### ISSUE THREAD

**Issue by pierrejego** [georchestra/cadastrapp#713]
Actuellement l'application est buildée est java 8. Il faudrait à minima passer en java 11

**Comment by landryb** [comment]
fait partiellement en #739 pour builder le profil debian avec java17, puis la gh action a été updatée pour builder en java17 avec d43ea1987c7, et changé sur le buildbot communautaire pour passer a java17 a l'instant.

il reste un commit a faire pour que le profil `docker` builde avec la bonne version du plugin war comme fait en #739

**Comment by landryb** [comment]
profil `docker` corrigé en 8bc60f338, testé ok avec https://github.com/georchestra/cadastrapp/actions/runs/10245982888
