### ISSUE TITLE
Edition du relevé de propriété

### ISSUE THREAD

**Issue by pigma** [georchestra/cadastrapp#72]
L'édition du relevé de propriété PDF ne donne aucun résultat

**Comment by landryb** [comment]
Sur quelle plateforme ? Sur quelle commune ? Sur quelle parcelle ? Avec quels droits ? En cliquant ou ?

**Comment by landryb** [comment]
Effectivement, ca echoue chez nous avec un code 500:
500 Internal Server Error - cadastrapp/services/createRelevePropriete?compteCommunal=201443045M00085"

```
ERROR /createRelevePropriete - testadmin - ROLE_MOD_LDAPADMIN,ROLE_SV_ADMIN,ROLE_ADMINISTRATOR,ROLE_MOD_ANALYTICS,ROLE_EL_CAD_CNIL1,ROLE_EL_DEP_33,ROLE_EL_DEP_67,ROLE_EL_DEP_43,ROLE_EL_CAD_CNIL2,ROLE_MOD_EXTRACTORAPP -o.a.c.i.AbstractFaultChainInitiatorObserver - Error occurred during error handling, give up!
org.apache.cxf.interceptor.Fault: java.sql.Date cannot be cast to java.lang.String

Caused by: java.lang.ClassCastException: java.sql.Date cannot be cast to java.lang.String
        at org.georchestra.cadastrapp.service.pdf.ReleveProprieteController.getReleveProprieteInformation(ReleveProprieteController.java:242) ~[ReleveProprieteController.class:na]
        at org.georchestra.cadastrapp.service.pdf.ReleveProprieteController.createRelevePDFPropriete(ReleveProprieteController.java:107) ~[ReleveProprieteController.class:na]

```

**Comment by pigma** [comment]
C'est sur la plateforme http://georchestra.demo.craig.fr/mapfishapp/

Je fais mes tests sur la commune de Leognan (33238) en Gironde

Le compte utilisateur utilisé est dans les groupes suivants:
![_groupes_tests_module_cadastre](https://cloud.githubusercontent.com/assets/3725336/10603459/683ef500-771e-11e5-9112-9557c19b8ee1.png)

Pour lancer l'édition du relevé de propriété j'utilise le bouton de l'onglet Propriétaire:
![_pb_edition_releves_propriete](https://cloud.githubusercontent.com/assets/3725336/10603502/9b0e7712-771e-11e5-90ac-1c111cde612c.png)

**Comment by pierrejego** [comment]
Bonjour, après vérification, je pense que ça vient d'un problème de mise à jour de votre base.

le commit cdc7aea38ecf1c3e48cd1aba85b85f8199a3bbb4 change justement ce type date en String.

J'appel Landry demain pour vérifier

**Comment by landryb** [comment]
effectivement, dans la base chez nous jdatnss est toujours de type date. ca sera probablement résolu a la prochaine MAJ ou je forcerais une reinitialisation des tables de bdd..

**Comment by landryb** [comment]
Après MAJ ce bug est à priori corrigé chez nous, peux-tu me le confirmer sébastien ?

**Comment by pigma** [comment]
Effectivement le relevé de propriété est maintenant édité, merci pour le correctif. Je vais vérifier le contenu du relevé.

**Comment by landryb** [comment]
Ce ticket peut etre fermé :)
