### ISSUE TITLE
Suppression de parcelles dans une selection quand présente dans plusieurs selections

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#74]
(on en a déja parlé au telephone, c'est juste pour le suivi)

Si une parcelle se retrouve dans 2 selections, et qu'une des 2 selections est supprimée/l'onglet est fermé, alors la parcelle ne sera plus affichée sur la carte alors que toujours présente dans l'autre résultat de selection.

**Comment by pierrejego** [comment]
Modification effectuée disponible sur la qualif demain matin, teste à faire sur les zooms

**Comment by MaelREBOUX** [comment]
marche pas ici. et impossible de rezzomer sur la parcelle en double.

**Comment by pierrejego** [comment]
@MaelREBOUX est-ce que tu peux m'expliquer un peu plus ce qui ne marche pas pour toi ?

**Comment by MaelREBOUX** [comment]
1. sélection de 6 parcelles
   ![screenshot033](https://cloud.githubusercontent.com/assets/6370443/11242172/605aca32-8e00-11e5-9c3a-484cc696db27.png)
2. ajout d'un nouvel onglet (onglet 2)
3. sélection de 1 parcelle déjà sélectionnée dans l'onglet 1
   ![screenshot034](https://cloud.githubusercontent.com/assets/6370443/11242184/70e9edc4-8e00-11e5-999e-a847a3270794.png)
4. fermeture de l'onglet 2
   la parcelle "en double" disparaît également de la sélection de l'onglet 1, sur la carte mais pas dans la liste
   ![screenshot035](https://cloud.githubusercontent.com/assets/6370443/11242213/9d54767c-8e00-11e5-9c60-e09e5d5ff457.png)
5. zoom
   possible sur toutes les parcelles encore en jaune.
   impossible sur la parcelle "en double" car pas présente sur la carte.

**Comment by pierrejego** [comment]
Merci pour la description, j'ai pu reproduire et je viens de le corriger, dispo demain matin sur la pf de qualification.

**Comment by MaelREBOUX** [comment]
Vu : c'est résolu et ça marche bien.

@landryb  ticket à fermer pour moi.

**Comment by landryb** [comment]
Ok pour moi aussi
