### ISSUE TITLE
création d'index dans les BDD

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#79]
Les scripts SQL devraient fournir des exemples de creation d'index pour la production, ou les créer par défaut.. je viens de créer la table uf_parcelle sur la région auvergne entière, et sans aucun index avec 3.2M d'enregistrements, j'ai peur pour les performances...

**Comment by pierrejego** [comment]
Les indexes viennet d'être créés, il faut aussi que je modifie la création de certaines vues pour en limiter la taille

**Comment by landryb** [comment]
Index crées par b9fdc15db89dd63f3b924d56de73ca5573451ef0 - a voir si il faut créer l'index dans le schéma correspondant.

**Comment by landryb** [comment]
Pour info le script de creation des index les colle tout seul dans le bon schéma (celui ou les tables sont)
