### ISSUE TITLE
Dans le menu Outils, absence de l'outil cadastrapp

### ISSUE THREAD

**Issue by sdhem** [georchestra/cadastrapp#8]
près avoir ajouter l'outil Cadastrapp. Un item dans le menu Outils doit être créer. L'item n'existe pas.

**Comment by MaelREBOUX** [comment]
On confirme : bug sur plate-forme GFi et CRAIG.

**Comment by catmorales** [comment]
Pourtant il est bien sélectionné dans les outils
![manque add on dans menu outils](https://cloud.githubusercontent.com/assets/4659829/9171385/57e1f666-3f6b-11e5-8d89-a277a5183f13.png)

**Comment by laurentcornic** [comment]
Modification effectuée voir commit
