### ISSUE TITLE
table de correspondance des communes en base

### ISSUE THREAD

**Issue by jpklipfel** [georchestra/cadastrapp#80]
Je souhaiterais tester qu'un user ait bien accès uniquement aux données des communes qui le concerne.
Comment faire?

**Comment by pierrejego** [comment]
Bonjour, 
la manipulation est indiqué dans le readme
https://github.com/GFI-Informatique/cadastrapp/tree/master/script/commun/user/README.md

N'hésitez pas à m'envoyer un mail si vous rencontrez un problème

**Comment by jpklipfel** [comment]
Merci, je ne pense pas avoir accès en écriture aux bases de test GFI ou CRAIG
Si quelqu'un l'a déjà testé c'est bon pour moi ou alors je serais intéressé à ce que l'on importe ce sql dans la base de test CRAIG

``` sql
INSERT INTO cadastreapp_qgis.groupe_autorisation (idgroup, cgocommune) VALUES ('EL_CO_67301', '670301');
```

**Comment by pierrejego** [comment]
Landry, je n'ai pas accès a ta base non plus :) tu peux faire l'import ?

**Comment by landryb** [comment]
Ajouté. Pour mémoire, voici ce que contient la table actuellement:

```
cadastrapp_qgis=> select * from groupe_autorisation;
 id |   idgroup   | cgocommune | ccodep 
----+-------------+------------+--------
  1 | EL_DEP_33   |            | 33
  2 | EL_DEP_43   |            | 43
  3 | EL_DEP_67   |            | 67
  4 | EL_CC_33    | 330023     | 
  5 | EL_CC_33    | 330037     | 
  6 | EL_CC_33    | 330077     | 
  7 | EL_CC_33    | 330080     | 
  8 | EL_CC_33    | 330109     | 
  9 | EL_CC_33    | 330206     | 
 10 | EL_CC_33    | 330213     | 
 11 | EL_CC_33    | 330238     | 
 12 | EL_CC_33    | 330274     | 
 13 | EL_CC_33    | 330448     | 
 14 | EL_CC_33    | 330454     | 
 15 | EL_CC_33    | 330474     | 
 16 | EL_CC_33    | 330501     | 
 17 | EL_CAPEV    | 430002     | 
 18 | EL_CAPEV    | 430018     | 
 19 | EL_CAPEV    | 430039     | 
 20 | EL_CAPEV    | 430045     | 
 21 | EL_CAPEV    | 430061     | 
 22 | EL_CAPEV    | 430078     | 
 23 | EL_CAPEV    | 430089     | 
 24 | EL_CAPEV    | 430152     | 
 25 | EL_CAPEV    | 430174     | 
 26 | EL_CAPEV    | 430197     | 
 27 | EL_CAPEV    | 430229     | 
 28 | EL_CAPEV    | 430241     | 
 29 | EL_CAPEV    | 430254     | 
 30 | EL_CAPEV    | 430260     | 
 31 | EL_CAPEV    | 430010     | 
 32 | EL_CAPEV    | 430032     | 
 33 | EL_CAPEV    | 430041     | 
 34 | EL_CAPEV    | 430046     | 
 35 | EL_CAPEV    | 430062     | 
 36 | EL_CAPEV    | 430084     | 
 37 | EL_CAPEV    | 430124     | 
 38 | EL_CAPEV    | 430157     | 
 39 | EL_CAPEV    | 430190     | 
 40 | EL_CAPEV    | 430221     | 
 41 | EL_CAPEV    | 430233     | 
 42 | EL_CAPEV    | 430251     | 
 43 | EL_CAPEV    | 430257     | 
 44 | EL_CC_67    | 670033     | 
 45 | EL_CC_67    | 670039     | 
 46 | EL_CC_67    | 670067     | 
 47 | EL_CC_67    | 670100     | 
 48 | EL_CC_67    | 670249     | 
 49 | EL_CC_67    | 670250     | 
 50 | EL_CC_67    | 670298     | 
 51 | EL_CC_67    | 670301     | 
 52 | EL_CC_67    | 670361     | 
 53 | EL_CC_67    | 670417     | 
 54 | EL_DEP_33   |            | 33
 55 | EL_DEP_43   |            | 43
 56 | EL_DEP_67   |            | 67
 57 | EL_CO_67301 | 670301     | 

```

**Comment by jpklipfel** [comment]
Merci Landry
J'ai testé en me mettant uniquement dans ce groupe EL_CO_67301 et pourtant je peux consulter des info propriétaire sur Brumath (67067)
![image 2](https://cloud.githubusercontent.com/assets/5012040/10934005/23c98c9e-82dd-11e5-8e85-f117902555eb.png)

**Comment by landryb** [comment]
Effectivement, je pense qu'on a un probleme d'accès, car dans le log j'ai vu passer ta requete avec uniquement le bon role:

```
DEBUG /getFIC - jpklipfel - ROLE_SV_USER,ROLE_EL_CAD_CNIL1,ROLE_EL_CO_67301,ROLE_EL_CAD_CNIL2
```

@pierrejego , une idée ? la version de l'addon déployée est https://github.com/GFI-Informatique/addons/commit/273b8a9ad0250d3e17c4b4c47871374633389dd6 et https://github.com/GFI-Informatique/cadastrapp/commit/92e1c9f10f2a66cc0192a0fc17e37162dcf41ffc pour la webapp

(ca peut aussi etre du au probleme des doublons dans la bdd en fonction des lots d'import etc.. je peux tester une requete sql dans la BDD si tu as besoin)

**Comment by pierrejego** [comment]
Je regarde ça en début d'après midi. Il y a  peut être une anomalie sur le filtre côté serveur

**Comment by pierrejego** [comment]
Je viens de vérifier, il manquait effectivement le filtre dans le requête, je viens de faire les modifications. Je teste et push dès que j'ai fini de tester

**Comment by MaelREBOUX** [comment]
@pierrejego je vais tester le dispositif pour C2C en limitant à une commune.
Je fournis qqch de ce genre ?

 id |   idgroup   | cgocommune | ccodep

**Comment by pierrejego** [comment]
Comme indiqué ici, il faut juste l'idgroupe de l'utilisateur et soit le cgocommune soit le ccodep.

Il faut que je passe une requête de cette forme là :+1:

`INSERT INTO cadastreapp_qgis.groupe_autorisation (idgroup, ccodep) VALUES ('EL_DEP', '63');`
 ou uniquement pour une commune
`INSERT INTO cadastreapp_qgis.groupe_autorisation (idgroup, cgocommune) VALUES ('EL_COMMUNES', '630001');`

**Comment by pierrejego** [comment]
Je viens de refaire des tests, c'est bon maintenant.
J'ai une question au niveau du comportement,
lorsque l'on filtre un user, il ne dispose plus que de cette commune dans les fenêtres de recherche, il a donc accès à moins d'information qu'un user lambda. 
Je souhaiterais donc modifié légèrement le comportement pour qu'il puisse faire des recherches ou il veut, mais que le filtre géographique ne se mette en place que lorsqu'il essaye d'accéder à des données CNIL1 ou CNIL2.
Est-ce que ce comportement vous va ?

**Comment by landryb** [comment]
@MaelREBOUX dans mes souvenirs c'etait bien le comportement attendu (qu'une personne connectée avec un role ayant une emprise donnée ne voit que des resultats de recherche sur cette zone), tu peux confirmer ?

**Comment by landryb** [comment]
@pierrejego dans mes souvenirs, on s'était mis d'accord pour que le champ idgroup corresponde au nom du groupe dans le ldap LDAP (donc sans le prefixe ROLE_ qui est ajouté par le sec-proxy) - dans le commit 75f68a7 tu rajoute le prefixe ROLE_ dans l'exemple, ca ne serait pas plutot mieux de (dans le code java faisant la comparaison/controle d'acces: https://github.com/GFI-Informatique/cadastrapp/blob/92c2af52f63c8239c7b05916849520e961984b27/cadastrapp/src/main/java/org/georchestra/cadastrapp/service/CadController.java#L207) _supprimer_ le prefixe ROLE_ des headers reçus avant de comparer avec la valeur d'idgroup ?

Peu importe l'un ou l'autre, mais que ce soit bien documenté.. de plus idgroup est limité a 30 chars ce qui me parait peu - surtout si on rajoute ROLE_ a chacune des valeurs. Penser au cas ROLE_EL_RM_SERVICE1_SOUSSERVICE2 ou ROLE_EL_COMCOM_PAYS_MACHIN_TRUC_ET_BIDULE qui vont coincer.. donc au moins augmenter la taille d'idgroup a 50 :)

**Comment by pierrejego** [comment]
@landryb  justement j'ai mis à jour car dans mon souvenir tu m'avais demandé de faire l'inverse :)
 Dans le cadastrapp.properties tu m'as fait remettre le ROLE_ devant les propriétés CNIL alors que je les avaient ajoutés dans le code Java
Je te propose donc de laisser le ROLE_ pour être cohérent avec le cadastrapp.properties et les ROLE Cnil.

Par contre, c'est noté je passe la colonne idgroup à 50

**Comment by landryb** [comment]
Mise a jour faite chez nous @jpklipfel si tu peux tester que tu as le bon comportement maintenant...

(j'ai aussi mis a jour groupe_autorisation en rajoutant ROLE_ temporairement pour que ca corresponde bien)

**Comment by jpklipfel** [comment]
C'est bon pour moi!
(L'utilisateur se voit retourner une fenêtre vide d'information sur une commune qui ne lui correspond pas)

**Comment by MaelREBOUX** [comment]
je n'ai pas encore testé ce cas et pas le temps d'ici ce soir :(

j'ai créé un compte pour test @pierrejego merci de rajouter cette correspondance : 

EL_COM_VERN | 350353

**Comment by pierrejego** [comment]
@MaelREBOUX je viens de faire l'insert dans la base

**Comment by landryb** [comment]
A priori tests ok - @MaelREBOUX tu confirmes que ca marche pour toi ?

**Comment by MaelREBOUX** [comment]
Il me reste à tester le cas avec utilisateur sur n communes.
- ref #112

**Comment by landryb** [comment]
A priori celui la est ok :)
