### ISSUE TITLE
[Demandes d'infos] liste type demandeur

### ISSUE THREAD

**Issue by aureliesouvignet** [georchestra/cadastrapp#81]
Revoir les listes de choix : lorsqu'on selectionne un élement de la liste déroulante on ne peut pas le modifier. 

Explication détaillée:
Lorsqu'on selectionne un type de demandeur ( Adminsitration,Particulier....) ou qu'on selectionne un objet de la demande (compte communal, référence parcellaires), on ne peut pas changer  notre choix.

**Comment by pierrejego** [comment]
Bonjour,
je viens de faire les modifications. Elles seront déployées pour demain matin sur la plateforme https://cadastrapp-qualif.asogfi.fr/mapfishapp/

L'ensemble de la demande d'information vient d'être finalisée.

**Comment by MaelREBOUX** [comment]
pour moi c'est réglé. @aureliesouvignet tu fermes ?
@pierrejego merci de renommer le ticket en [Demandes d'infos] liste type demandeur
