### ISSUE TITLE
page web sur /cadastrapp/ cassée

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#82]
dans https://github.com/GFI-Informatique/cadastrapp/commit/5ca2e4e28da715056b2f7aa5590c04af8af4bb2c j'ai cassé la page web renvoyée par la servlet - cf http://georchestra.demo.craig.fr/cadastrapp/

```
org.apache.jasper.JasperException: Unable to compile class for JSP: 

An error occurred at line: [65] in the generated java file: [/srv/tomcat/georchestra/work/Catalina/localhost/cadastrapp/org/apache/jsp/index_jsp.java]
The method getDispatcherType() is undefined for the type HttpServletRequest

Stacktrace:
    org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:103)
    org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:199)
    org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:450)
    org.apache.jasper.compiler.Compiler.compile(Compiler.java:361)
    org.apache.jasper.compiler.Compiler.compile(Compiler.java:336)
    org.apache.jasper.compiler.Compiler.compile(Compiler.java:323)
    org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:564)
    org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:357)
    org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
    org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
    org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
```

d'après @pmauduit c'est le fait de dépendre de servlet-api 2.4 qui pose pbm, il faudrait dépendre de la v3 au moins. je tente un fix.

**Comment by pmauduit** [comment]
> d'après [3]@pmauduit c'est le fait de dépendre de servlet-api 2.4 qui pose pbm,
> il faudrait dépendre de la v3 au moins. je tente un fix.

Par ailleurs ce n'est pas le role des webapps de fournir servlet-api, mais du
serveur applicatif. tomcat blackliste les classes de la servlet api, donc ce
n'est pas dramatique si c'est en dépendance et que cela fini dans le war, mais
ce n'est pas nécessaire, d'où l'utilisation de <scope>provided</scope>
généralement sur cette dépendance (ou de l'exclusion si dépendance par
transivité).

-- Pierre
