### ISSUE TITLE
[Demandes d'infos] PDF récapitulatif

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#83]
@pierrejego voici mes demandes de modifs :
- qqs coquilles
- de la mise en forme de texte
- un peu d'espacement
- passer les bordures à 0

Un seul pb fonctionnel : je demande une parcelle et ça affiche "proprio"
je t'envoie le PDF annoté par courriel

**Comment by aureliesouvignet** [comment]
Un autre petit point : dans le recapitulatif, le numéro CNI n'est pas repris.

**Comment by pierrejego** [comment]
Bonjour,
effecitvement il n'est pas repris, il n'était pas dans le formulaire de Mael.
Ou est-ce que je rajoute le numéro CNI ? Est-ce que je met un label devant ?

@MaelREBOUX  je regarde tes remarques. Quand tu dis bordures à 0 ça veut dire plus de tableau ?

**Comment by pierrejego** [comment]
Je viens de faire les modifications, la plateforme se déploie automatiquement à 14h vous, pourrez vérifier mes modifications. Je n'ai pas enlever les bordures partout, mais je peux le faire.

**Comment by MaelREBOUX** [comment]
bordure = 0 : oui : on ne fait pas apparaître le tableau. Je l'avais laissé volontairement dans le ODT pour te faciliter la transposition XSLT.

Pour le n° CNI : c'est un oubli. Je laisse Aurélie trancher s'il faut l'avoir ou pas sur le formulaire papier. Ce serait plus logique que oui. Cependant.

**Comment by aureliesouvignet** [comment]
Re, pour le numéro CNI, je pense que ce serait plus opportun pour permettre aux signataires de vérifier toutes les informations avant signature.

**Comment by pierrejego** [comment]
Pas de problème, je peux le rajouter, pouvez juste me dire comment ?

Je vous propose de rajouter 
CNI : (valeur de la cni)

Entre le type de démandeur et le nom. ça vous va ?

**Comment by MaelREBOUX** [comment]
oui : nickel

**Comment by pierrejego** [comment]
Modification effecutée, disponible demain matin sur la pf de qualif

**Comment by MaelREBOUX** [comment]
Je crois que c'est pas mal pour une v1.

Dans le PDF : supprimer le tiret entre le code postal et le nom de la commune.

**Comment by pierrejego** [comment]
Modification effectuée disponible demain sur la pf de qualif
