### ISSUE TITLE
Plusieurs onglets pour une seule recherche avec plusieurs parcelles

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#86]
Cf http://i.imgur.com/5NDk57V.png - si je fais une recherche sur 2 refs de  parcelles, la fenetre de resultat me les presente dans 2 onglets distincts avec une entrée chacun au lieu de mettre les 2 dans le meme nouvel onglet.

**Comment by pierrejego** [comment]
Corrigé et déployé sur la qualification le test a été fait ce matin

@landryb je te laisse fermer l'anomalie quand tu auras pu vérifier

**Comment by MaelREBOUX** [comment]
@landryb  on peut fermer ce ticket je pense.

**Comment by landryb** [comment]
Problème toujours présent (ou alors c'est un _autre_ problème), si j'ai 2 refs de parcelle dans ma recherche un onglet est ouvert mais avec uniquement les infos d'une parcelle, c'est comme s'il n'y avait pas d'infos pour la 2e.

2 requetes getparcelles sont faites, la 2e ne renvoie rien alors.. que la parcelle devrait remonter.

http://georchestra.demo.craig.fr/cadastrapp/services/getParcelle?cgocommune=430045&dnupla=11&ccopre=%20%20%20%20&ccosec=AC -> rien
http://georchestra.demo.craig.fr/cadastrapp/services/getParcelle?cgocommune=430045&dnupla=7&ccopre=&ccosec=AC -> ok

problème sur le champ ccopre envoyé dans la requete ?

Un getinfobulle sur la parcelle 11 remonte bien des infos pourtant..
http://georchestra.demo.craig.fr/cadastrapp/services/getInfoBulle?parcelle=2014430045000AC0011

**Comment by landryb** [comment]
Une recherche par lot sur 3 identifiants m'ouvre bien un seul onglet de recherche avec les 3 résultats.

**Comment by landryb** [comment]
Pour référence (et après discussion au telephone), le pbm avec %20%20%20%20 ne se produit que sur le modele qgis, il faut enlever les espaces en début de ces champs comme les zeros ont été enlevés sur le modele arcopole.

**Comment by pierrejego** [comment]
Correction éffectuée avec le commit https://github.com/GFI-Informatique/cadastrapp/commit/2d98ebf0fa6a3d981a22376255209d25b6c1f109#diff-3205c0ded576131ea255ad2bd38b0fb2

**Comment by landryb** [comment]
Euh.. c'etait pas le commit qui fixait #103 plutot ?

**Comment by landryb** [comment]
Ca devait plutot etre https://github.com/GFI-Informatique/cadastrapp/commit/fd413676544019c90d947762312aa4e1af678e66 je pense :)

**Comment by pierrejego** [comment]
Oui effectivement le copié-coller du commit était pas bon....

**Comment by landryb** [comment]
pbm sur le ccopre=%20%20%20%20 bien corrigé sur le modele qgis.
