### ISSUE TITLE
hibernate.default_schema prend le pas sur schema.name ?

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#88]
Je dois encore regarder les détails, mais sur ma pf de pré-prod le démarrage de la webapp cherche le schéma de BDD dans le schéma 'cadastrapp_qgis' (tel que specifié comme hibernate.default_schema dans WEB-INF/beans.xml) alors que schema.name est a 'cad2015' dans /etc/georchestra/cadastrapp/cadastrapp.properties _et_ WEB-INF/classes/cadastrapp.properties. - du coup hibernate échoue. Est-ce que les parametres sont déja lu quand hibernate valide le schéma ?

Au passage, ca serait utile d'avoir un message de log au démarrage pour savoir dans quel fichier cadastrapp.properties la classe CadController va chercher ses parametres...

**Comment by landryb** [comment]
Je ne m'étais pas rendu compte de ce pbm auparavant car sur ma pf de qualif/tests le schéma est resté cadastrapp_qgis par défaut...

**Comment by pierrejego** [comment]
Oui, il me semblait te l'avoir dit, le beans.xml ne va pas lire le cadastrapp.properties, du coup il y a une référence au schéma dedans. 
Il faut que je vois comment lire le cadastrapp.properties en amont du beans.xml pour peuplé avec la valeur du schéma

**Comment by landryb** [comment]
L'idée, c'est que ca marche dans les deux cas (avec et sans georchestra.datadir dans l'env) _sans_ avoir a modifier les fichiers de la webapp, et donc pas avoir a changer beans.xml......

**Comment by pierrejego** [comment]
Ok, oui je suis d'accord, la ça corrige que le fait que ça lise la valeur dans le cadastrapp.properties de la webapp sans avoir à modifier le beans.xml.
Il faut que j'ajoute la gestion d'erreur sur l'absence de l'env georchestra.datadir
