### ISSUE TITLE
Fenêtre non redimensionnable

### ISSUE THREAD

**Issue by sdhem** [georchestra/cadastrapp#9]
Les fenêtres de recherche, de résultat doivent être redimensionnable
La taille des fenêtres est redimensionnable mais il y a des problèmes d'affichage avec la barre de scroll horizontale (pas toujours visible, parfois dupliqué)

**Comment by pierrejego** [comment]
Modification apportée, il reste uniquement le cas de l'ouverture d'une recherche avec plus de 20 parcelles. Lors de l'ouverture la fenêtre dépasse la taille maximum de la fenêtre sans scroll, mais lorsqu'on la déplace celle ci se redimmensionne et la scroll apparaît

**Comment by landryb** [comment]
Il y'aura forcément des recherchers avec plus de 20 parcelles en résultat, la scrollbar _doit_ apparaitre automatiquement dans ce cas sans avoir besoin de la deplacer/redimensionner.
