### ISSUE TITLE
Export CSV pas standard

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#90]
Le fichier généré contient une suite de valeurs séparées par un point-virgule. Tout est sur une seule ligne.
Un import dans un tableur ne correspond pas au résultat attendu.

Ce n'est pas un CSV "standard".
Il faut une valeur par ligne.
Le séparateur vient séparer les attributs, pas les enregistrements.

A corriger SVP.

Sinon le copier-coller d'une liste (1 enr par ligne) ou le chargement d'un fichier fonctionne très bien.
Cool.

**Comment by pierrejego** [comment]
Modification du délimiteur a effectuer, retour à la ligne au lieu de ;
