### ISSUE TITLE
Taille / format de la fenêtre d'infos parcelle

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#91]
Elle est très / trop large : 800 x 300
A chaque fois je la redimensionne quand j'en ouvre une.
Passer à 470 x 300.

**Comment by landryb** [comment]
Si tu est connecté et que tu vas sur l'onglet batiment, il y'a deja une scrollbar horizontale.. ok ptete que la fenetre fait 'grande' si tu as uniquement l'information de parcelle, mais la taille est pas mal pour les champs de l'onglet propriétaire a mon avis..

d'ailleurs sur l'onglet propriétaire, ca serait bien que le champ 'nom' soit plus large, qu'on n'ait pas a le redimensionner pour voir l'information. Pareil pour le champ 'compte' sur les onglets propriétaire et batiment.

pas facile d'avoir une taille par défaut qui satisfasse tout les cas..

**Comment by pierrejego** [comment]
Alors je fais quoi ? :)
Je viens déjà d'augmenter la taille des champs nom et compte.

**Comment by MaelREBOUX** [comment]
La remarque de @landryb est juste.

C'est hyper choquant pour le premier onglet mais normal pour les autres.
On laisse comme ça.

Je découvre les fonctionnalités riches des colonnes :D
![screenshot041](https://cloud.githubusercontent.com/assets/6370443/11245304/59fa0c2c-8e12-11e5-9ee4-cf73d9e6aa4d.png)
