### ISSUE TITLE
taille de la fenêtre de liste de parcelles

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#92]
Elle est juste pas assez large et vient manger le bouton "Fermer" à droite.

![screenshot021](https://cloud.githubusercontent.com/assets/6370443/11148591/d58dc28c-8a1d-11e5-8098-ce26345510d3.png)

**Comment by pierrejego** [comment]
Je viens de faire la modification, elle sera déployée demain matin sur le serveur de qualification

**Comment by MaelREBOUX** [comment]
vu : ok
