### ISSUE TITLE
Supprimer les "000" dans les listes des sections dans le code ou en base ?

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#93]
Dans les listes et les formulaires il faut supprimer les triples 0 qui servent à padder le code de section.

Ca nuit à l'autocomplétion et ce n'est pas dans les habitudes des utilisateurs qui ne voient jamais ce format. On va se faire lyncher si on laisse comme ça.

![screenshot025](https://cloud.githubusercontent.com/assets/6370443/11148744/e3dc3fde-8a1e-11e5-93b4-875cc2926819.png)

![screenshot024](https://cloud.githubusercontent.com/assets/6370443/11148726/ce45769a-8a1e-11e5-809c-bf728aa53987.png)

**Comment by MaelREBOUX** [comment]
Dans la fenêtre de sélection de parcelles, dans le champ Section il reste un zéro pour les sections à une seule lettre.
![screenshot029](https://cloud.githubusercontent.com/assets/6370443/11149662/472096c6-8a24-11e5-9142-2284c8f583b4.png)
Ici on "0A" on attend juste "A".

**Comment by pierrejego** [comment]
Les données sont avec les 0 en base, la modification n'est pas simple a effectuer. Soit dans la vue en base je supprime les 0. Soit je rajoute une "véru" dans le code, qui supprime les zéros en début et les rajoutes lors de l'appel, mais il faut que je vois si ça marche pour les deux modèles Qgis et Arcopole.

**Comment by MaelREBOUX** [comment]
Si on me demande mon avis je pense qu'il faut traiter ça au niveau des vues, pas du code.
En fait il y a 2 choses différentes : le code de section utilisée comme identifiant (sur 5 caractères) et le libellé utilisé par les humains. Et comme je ne connais pas la machinerie, je ne mesure pas l'impact.

Un autre avis ? @catmorales @landryb ?

**Comment by MaelREBOUX** [comment]
NICKEL !!

**Comment by landryb** [comment]
Je ne sais pas si c'est un effet de bord de ce changement, mais dans une liste de selection avec les numéros de parcelle, l'ordre est ... 'non naturel'

ie 1 10 100 ... 109 11 110 ... 119 12 ... 199 2 20 200 201 ...

**Comment by MaelREBOUX** [comment]
Dans cette fenêtre j'ai remarqué qu'il n'y a jamais vraiment eu de tri.
Mais pb car tri inopérant cf #107

**Comment by landryb** [comment]
Je reouvre cf mon commentaire précédent.

**Comment by pierrejego** [comment]
Il faut revoir le sort par défaut, qui prend les éléments comme du texte et non comme un nombre

**Comment by pierrejego** [comment]
Modification effectuée
https://github.com/GFI-Informatique/addons/commit/f2002af0b6a3d673b4604f7f8f709a18fab362e6

**Comment by landryb** [comment]
Le tri sur les numéros de parcelles est bien correct maintenant.
