### ISSUE TITLE
Fiche info parcelle : secteur urbain / parcelle bâtie

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#94]
![screenshot026](https://cloud.githubusercontent.com/assets/6370443/11148793/40fd2048-8a1f-11e5-99f2-3d2396127c99.png)

Il faut afficher "oui" ou "non" pas 1 / [vide]

sur la PF du CRAIG j'ai 1 / \* ?!

**Comment by pierrejego** [comment]
Je viens de faire la modification par contre @MaelREBOUX  je ne vois pas les  / \* ?! tu peux me faire une copie d'écran
