### ISSUE TITLE
Bordereau parcellaire : infos et mise en forme

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#95]
**cartouche : 2e bloc**
les infos sont trop espacées : on perd de la place/
il manque l'info sur le millésime des données Edigéo. A Rennes, cette info est dans un cartouche sur la carte mais elle peut prendre place ici.

**cartouche : bloc 3 4 et 5**
si la mise en forme utilise un tableau (cause XSL je présume) il ne faut pas qu'il apparaisse.
supprimer "(FANTOIR)" qui est à la ligne et qui casse toute la mise en forme.

**cartouche : bloc 6**
il contient la liste des proprio. Ce bloc doit être d'une hauteur fixe afin de renvoyer vers le bas le dernier bloc qui contient "Un service du...."
aligner les infos à gauche (centré actuellement) avec une marge gauche pour pas coller au tableau.

**mentions**
il manque des mentions légales. Je propose de les alléger et de les mettre dans le bloc 2 après les infos sur les dates.
"Fond de plan origine DGFiP - Reproduction interdite - Mesures données à titre indicatif"

**échelle**
il manque une échelle graphique.

**carte**
elle est bcp trop centrée sur la parcelle en question. Il faut donner de l'air pour voir l'environnement immédiat. Comment faire ? Une zone tampon de 20 m mini ? Une échelle max ?

![screenshot028](https://cloud.githubusercontent.com/assets/6370443/11149457/260564ae-8a23-11e5-89ba-36cce7c97b87.png)

@pierrejego je t'envoie par mail le XSL de notre bordereau parcellaire actuel.

**Comment by MaelREBOUX** [comment]
@pierrejego je viens de t'envoyer mes demandes de modifs sur le BP.
Essentiellement de la mise en forme.

**Comment by pierrejego** [comment]
Modification effecutée

commit https://github.com/GFI-Informatique/cadastrapp/commit/b7ed5f24a4bcb6b2ad458506024c23466651610d#diff-2b3585f41e1ddc13ea80de2ba0acde9e

**Comment by MaelREBOUX** [comment]
Pour moi c'est impeccable sauf une coquille : "Données fonçières"  ->  foncières  sans ç
