### ISSUE TITLE
Traitement de la sélection > Parcelles > Export par lot de bordereaux

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#96]
x parcelles sélectionnées dans la fenêtre de sélection de parcelles.

barre outil > Avancées > traitement sélection > Parcelles > bordereaux

rien ne se pas. pas de mail.
on doit recevoir un mail avec un lien de téléchargement je crois ?
mais là rien aucun message.

**Comment by pierrejego** [comment]
Il y a un bug si plus d'une parcelle a été sélectionnée, la liste de parcelle est transformé en une seul chaîne de caractères. 
Correction à apporter côté client.

@MaelREBOUX pour information, il n'y pas de lien de téléchargement, c'est directement le pdf avec l'ensemble des parcelles qui vient en téléchargement.

**Comment by MaelREBOUX** [comment]
vu : récupération d'un PDF multipages.
