### ISSUE TITLE
Toolbar : renommer case "Foncier" en "UF"

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#97]
Tout est dans le titre ;)

**Comment by landryb** [comment]
Je ne suis pas d'accord... peut-être que dans votre applicatif actuel c'est "UF" et que vos utilisateurs sont habitués à ca, mais je doute fortement que "UF" parle aux "autres" utilisateurs potentiels... si "foncier" n'est pas parlant je veux bien un autre terme, mais qu'il soit clair au moins. Dans les deux cas il y'a le tooltip pour éclairer l'utilisateur, mais le titre doit donner une idée de la fonctionalité.

**Comment by MaelREBOUX** [comment]
"Unit. Fonc." ?
Foncier ça veut rien dire : c'est trop global. Amha qqn qui fait du droit du sol va s'attendre à qqch en rapport avec la note de renseignement d'urbanisme.

Un autre avis ?

**Comment by landryb** [comment]
Pour info la chaine de caracteres vient de https://github.com/GFI-Informatique/addons/blob/dev/cadastrapp/manifest.json#L44 donc ca peut toujours être une modification locale.

**Comment by MaelREBOUX** [comment]
OK. à noter.
Mais on n'a rien réglé. "Foncier" ça correspond pas à la fonctionnalité. Ici ça convient à personne.
Merci de changer pour mettre "UF" ou  "Unit. Fonc."

**Comment by pierrejego** [comment]
J'ai remplacé dans le manifest.json Foncier en Unit. Fonc.

Chaque intégration pourra changer le label comme il le souhaite dans le manifest.json.

**Comment by MaelREBOUX** [comment]
vu : ok.
