### ISSUE TITLE
Fenêtre recherche proprio par nom : pb de recherche

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#99]
![screenshot031](https://cloud.githubusercontent.com/assets/6370443/11150949/e50dcd58-8a2a-11e5-8dfb-9c145872e303.png)

je n'arrive pas à trouver "gerard françoise" alors qu'elle est bien proprio ?!

**Comment by MaelREBOUX** [comment]
j'ai trouvé : 
![screenshot032](https://cloud.githubusercontent.com/assets/6370443/11151013/1b5ef77e-8a2b-11e5-9601-9874b3d46af8.png)

c'est dû aux données sauce arcOpole je pense.
Qqn peut confirmer avant de fermer ?

**Comment by MaelREBOUX** [comment]
Je constate le même problème sur la PF du CRAIG. Donc c'est pas au niveau des données ?

Sinon je constate un problème qui est peut-être lié et qui entrave la recherche par un prénom / partie de nom.

chercher "francois"

la requête qui est envoyée ne contient que "fra" soit 4 caractères
cgocommune=350139
ddenom=fra

la liste JSON renvoyée comporte 25 enregistrements
l'add-on en affiche 8

En base la requête utilsiée sur notre appli actuelle

```
SELECT *
FROM proprio
WHERE CODCOMM = '350139'
AND DDENOM REGEXP ("FRANCOIS")
GROUP BY DDENOM
```

me donne 202 enregistrements.

Donc je suis un peu perdu pour retrouver mes petits et qualifier si c'est correct ou pas.
J'ai noté également un comportement asynchrone qui est assez perturbant.

C'est compliqué à décrire ici. @pierrejego est-ce qu'on peut voir ça au tel ?

**Comment by pierrejego** [comment]
Bonjour,
pour l'autocomplétion on limite à 25 le nombre de résultat, plus tu mets de lettre plus la réponse est fine. 

C'est donc normal qu'avec uniquement fra tu n'es que 25 caractères. Par contre si tu as tapé Francois tu devrais avoir francois dans le ddenom de la requête.

**Comment by MaelREBOUX** [comment]
ce qui est fait est plus "tordu" car en fonction de ce qu'on tape ça ne reformule pas forcément une requête vers l'API.
Et donc j'arrive à prendre en défaut la fenêtre de recherche qui ne répond pas à ce que je cherche.

fran -> 1 requête
francois -> pas de requête = utilisation de la première liste renvoyée ? Sauf que si limité à 25 ça ne marche pas. si ?

ensuite : effacement par touche eff arrière + saisie "alexandra"
ça affiche 3 résultats alors que j'en ai 6 en base ?!
(marge d'erreur 1 car millésime des données différent ??)

**Comment by MaelREBOUX** [comment]
vu avec @pierrejego 
un bogue + une aide contextuelle pour accompagner l'utilisation.
A retester après correction.

**Comment by pierrejego** [comment]
@MaelREBOUX  c'est corrigé et dispo sur la qualif, peux-tu vérifier si le comportement te va ?

**Comment by MaelREBOUX** [comment]
Ha ben oui : c'est très bien là.
MERCI !
